### ISSUE TITLE
[IME] Firefox/macOS: composition is invisible if it occurs at a block's start

### ISSUE THREAD

**Issue by danburzo** [ianstormtaylor/slate#1008]
#### Do you want to request a *feature* or report a *bug*?

Reporting a *bug* with IME behavior in Firefox/macOS. I am using the _Hiragana_ input method ([see here](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md#testing-input-methods) on how to install it).

1. Go to [any example](http://slatejs.org) and clear the text inside the editor
2. With an empty editor, type _sensei_ in the field and press Enter

#### What's the current behavior?

Composition is invisible until pressing the Enter key to stop composing. This reproduces when beginning any new block:

<img src='http://g.recordit.co/Qg2eHhEyRL.gif'/>

#### What's the expected behavior?

Composition is visible regardless of where you're introducing text.

#### Additional notes

* Safari/Chrome exhibit [a different problem](https://github.com/ianstormtaylor/slate/issues/939).
* The composition UI in Firefox seems to be located somewhere at the bottom left corner of the browser window, and is barely visible.
* Composition in Draft.js works as expected on FF/macOS

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
