### ISSUE TITLE
Consider dropping -webkit-user-modify: read-write-plaintext-only as default

### ISSUE THREAD

**Issue by danburzo** [ianstormtaylor/slate#1022]
I propose we drop this non-standard CSS property and embrace the rich-text world.

1. It causes Chrome to behave in a [poorly documented way](https://www.chromestatus.com/feature/5743696054059008)
2. It doesn't seem like this behavior [is going to be revisited](https://bugs.chromium.org/p/chromium/issues/detail?id=755509) — re: thread, I'm not convinced this is expected behavior.
3. We'd probably shave off a few unpredictable but similar bugs
4. We can revert [the fix I pushed earlier](https://github.com/ianstormtaylor/slate/pull/994)

The COMPAT note suggests it has been introduced as a reaction to the IOS rich-text formatting bar introducing potential inconsistencies in the DOM:

https://github.com/ianstormtaylor/slate/blob/74d697b4b8d00a9afb5bff037bdc23bddaed7ab3/src/components/content.js#L843-L846

However, at least from Safari 10.1 we get a nice beforeinput event with a`inputType=format{FormatType}` property, that we can:

1. ignore them onbeforeinput in the core plugin
2. allow them to be caught, and possibly acted upon, by other plugins.

I also intuit that when more platforms start implementing Input Events Level 2 more thoroughly, we're going to see these kinds of control pop up on other platforms.

One piece of information I'm missing right now is what the behavior is for Safari < 10.1 on devices that will show their RTE toolbar (iOS/macOS with Touch Bar). Since Touch Bar was launched post Safari 10.1 I doubt there's an easy way to get Safari < 10.1. And on iOS I think they were already emitting these inputTypes by the time they introduced the RTE toolbar. It's hard to check (on Browserstack I can get either iOS 9 with no RTE, or iOS 10.3 with RTE) but I think there's only a very thin slice of potentially problematic OS. Not sure about the situation on Android.

P.S. COMPAT notes are 💯!

**Comment by ianstormtaylor** [comment]
@danburzo really good research!

Here's another bit of information for us:

- https://github.com/facebook/draft-js/issues/214
- https://bugs.webkit.org/show_bug.cgi?id=147406

My last remaining question would be if there's another way to hide that menu without the negative effects. Because it seems like it's impossible still to remove B/U/I formatting options for editors that don't want those. And that it's also impossible to get rid of the menu if you end up having a menu of your own to display instead.

So I guess that compat note should have mentioned both the out-of-sync-ness, and the need in some cases to not have the menu show because there's another menu to show.

What do you think?

**Comment by danburzo** [comment]
(Just to clear the air, I meant the COMPAT thing as compliment, as it helped me figure out why the CSS property was needed :D) 

So it seems that indeedio iOS Safari had implemented the B/U/I _long before_ they had any mechanism to allow authors to figure out what has happened (we just get an input event, no useful data), so there's no way to catch those formatting commands prior to iOS 10 👎 

As for removing the BUI from the UI, it seems that there's currently no way around webkit-user-modify. And it's entirely impossible to remove the menu altogether if you implement your own — the CSS property will only hide the BUI buttons from that menu 👎

**Comment by ianstormtaylor** [comment]
> (Just to clear the air, I meant the COMPAT thing as compliment, as it helped me figure out why the CSS property was needed :D)

Ah no worries! I interpreted it that way and was happy to hear that they paid off! 😄 

1. iOS 10 support only is slightly unfortunate, although it's not the worst because the upgrading is so fast. Probably like ~90% of people are on iOS 10 nowadays, especially for savvier audiences. So although this isn't the best, it's actually not the worst either. Given a few more months it'll be even better.

2. Ah very true, I hadn't remembered that the menu wasn't actually hidden completely, and that it just removed those options from it instead. (The `COMPAT` note was correct after all!) The only slight difference is that I think the <kbd>B/U/I</kbd> buttons are the only ones that are truly schema-dependent. The others are all copy/cut/paste/replace which don't really tie into the schema, although you could argue that in certain more edge-editor-cases those are schema dependent too, so it's not totally true.

3. Not exactly sure what you mean here, let me know.

What's your overall take do you think? Or are you still a bit too early in the research to say for sure what we should do?

**Comment by steida** [comment]
Should not be WebkitUserModify added for iOS only?

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
