### ISSUE TITLE
nodeProperties function returns pseudo-symbol type identifier

### ISSUE THREAD

**Issue by YurkaninRyan** [ianstormtaylor/slate#1025]
Below I have this situation, two Paragraph blocks, one containing an inline void Image, and another containing only text.  Here is what happens when I attempt to drag and drop it.

![screen shot 2017-08-24 at 11 01 53 am](https://user-images.githubusercontent.com/8742831/29673095-269a442c-88bc-11e7-9286-2a25c13952b4.png)
---

Dragging it causes the onDrop to fire, which will have a `data.type` of Node, and contain the inline void image node in `data.node`.  This will cause `onDropNode` to fire which will then go on to `insertBlock`

![screen shot 2017-08-24 at 11 02 18 am](https://user-images.githubusercontent.com/8742831/29673173-693e7e24-88bc-11e7-9012-f10c8dc9e206.png)
---

The `insertBlock` transform will then call `normalize` on the node being passed in.

![screen shot 2017-08-24 at 11 02 49 am](https://user-images.githubusercontent.com/8742831/29673218-8c0cda4a-88bc-11e7-9982-2d548c84ea1f.png)
---

In the normalize, this node will fail the `Block` check, because it's an `Inline`.  Falling through, we pass it through `nodeProperties`, and then shove it into `Block.create`

![screen shot 2017-08-24 at 11 03 03 am](https://user-images.githubusercontent.com/8742831/29673276-bc2713b2-88bc-11e7-924c-aa684c867eef.png)
---

It seems as though `nodeProperties`,  creates an object that has the  pseudo-symbols from not just us, but also immutableJS

![screen shot 2017-08-24 at 11 10 45 am](https://user-images.githubusercontent.com/8742831/29673348-f51e3420-88bc-11e7-829b-5aab35d05b55.png)
---

This causes some crazy stuff to happen.  Now we are at a point, where the` Block.create` function is tricked into thinking what it has is an `Inline` node, however what it actually has is just some properties.  It quietly returns the properties, and then all hell breaks loose

![screen shot 2017-08-24 at 11 04 08 am](https://user-images.githubusercontent.com/8742831/29673394-13976f3e-88bd-11e7-961d-f340f6af9cca.png)
---

It manages to make it's way from `insertBlock` all the way to `insertNode`.  When it gets there, it attempts to `mapDescendants`.  Unfortunately, we aren't an `Inline` that has a `nodes` property.
  So we just actually die here.

![screen shot 2017-08-24 at 11 12 42 am](https://user-images.githubusercontent.com/8742831/29673473-485edc84-88bd-11e7-8ce6-7e494d09bad3.png)
---

@ianstormtaylor I see a couple of spots where this should be fixed, but in my opinion the true source of pain is `nodeProperties`.  Should we be white listing what properties we let through?

**Comment by ianstormtaylor** [comment]
@YurkaninRyan great writeup, makes the problems super clear.

- [x] On the #836 branch I've actually got all of the `Model.create` methods using white listing the properties that the models are aware of. I realize this doesn't help as soon as possible, but I'm hoping to merge this branch in soon and do a bump.

It sounds like we've also got at least:

- [ ] The `onDrop` handler should be smart enough to use `insertBlock` or `insertInline`.

- [ ] The `Normalize.block/inline/text` functions should throw an error if their working with one of the other kinds of nodes, instead of doing crazy stuff. 

Maybe some others that you're aware of too. Let me know! I'd love PR's that help to address any of these pieces. Thank you!

**Comment by YurkaninRyan** [comment]
You got it,  I'll tackle this one, and get those two other items in there!

**Comment by ianstormtaylor** [comment]
@YurkaninRyan I just ran into something like this on another branch, except with weird zombie `Mark` objects instead of `Inline` objects after being passed through `Normalize.mark`. Do you know why those were being created? I'm about to dig in, but figured you may have already figured it out. Thanks!

**Comment by YurkaninRyan** [comment]
@ianstormtaylor I do not :(, but i'll probably end up encountering this soon because I plan on spending the next few days hunting these inconsistencies down

**Comment by ianstormtaylor** [comment]
@YurkaninRyan going to close this since the root issue was solved. If we notice that weird behavior happening again we can open a new issue to solve whatever it was.
