### ISSUE TITLE
Can't delete blocks at first line

### ISSUE THREAD

**Issue by ezakto** [ianstormtaylor/slate#1031]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

Can't delete block nodes in first line.

1. Go to http://slatejs.org/#/rich-text
2. Add a list or a blockquote
3. Remove the previous content so the block is in the first line
4. Press backspace like crazy

![slatelist](https://user-images.githubusercontent.com/778104/29727082-dbf937be-89a8-11e7-9c36-0e2f50ff9c77.gif)

![slatequote](https://user-images.githubusercontent.com/778104/29727089-e0dd66ce-89a8-11e7-885e-ff6a1f3fbc18.gif)

#### What's the expected behavior?

It should remove the block (probably defaulting to paragraph?)

**Comment by ianstormtaylor** [comment]
Hey @ezakto thanks for this. The `rich-text` example is just an example of what's possible, in your editor you can choose how you want to handle backspacing at the beginning of a document like this, but it's not something core will handle for it, since it doesn't make assumptions about your schema.

**Comment by ezakto** [comment]
@ianstormtaylor that seems odd as it assumes you want to delete block nodes in other lines?

**Comment by ianstormtaylor** [comment]
@ezakto in other cases it's not forced to come up with the node type you want to insert by itself because it's actually just collapsing the content into the previous node, whatever its type may be. In the case of deleting at the start of a single quote block, it would actually need to create a new node (or change the node's `type`), and that is a schema-specific decision.
