### ISSUE TITLE
try to change isNative to exist only in the component layer

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1070]
Right now it lives in the `State` model, and is checked in the component layer. It would be awesome if this could be eliminated from the model layer entirely and live only in the components. I haven't dug in to see if this is possible yet, but if so it would be nice.

**Comment by AlbertHilb** [comment]
I think it's really simple.

1. `isNative` flag is set by the core `onBeforeInput` handler. Change the handler so to add the flag to the `data` object it receive as parameter instead of the returned state.

2. After all `onBeforeInput` handlers have been executed, check `data` object: if `isNative` flag is present, set `isNative` in the `Content` `tmp` object and store the `state`returned by the handler chain in `tmp.pendingState`

3. When a new `state` is passed to the `Content` components, check if `tmp.isNative` is set. If so compare `state` with `tmp.pendingState`, if they are equals skip rendering and reset `isNative` and `pendingState`.

**Comment by ianstormtaylor** [comment]
Actually no need now, since it's gone!
