### ISSUE TITLE
onKeyDown can not prevent keys like `enter`, `delete` 

### ISSUE THREAD

**Issue by eromoe** [ianstormtaylor/slate#1179]
Hi,
I am build a annotator tools,  I need a  editable switcher, which means :

1. if this.state.editable === false,  only can add `marks` (by predefined shortcut ) and `ctrl-z` to rollback. But can not edit original text by other keys.

2. if this.state.editable === true,  can add marks and also can edit the text .

I copy the example and write code like below

```
onKeyDown = (event, data, change) => {
    if (!this.state.editable)
      event.preventDefault()

    if (!event.altKey) return
    ....
  }
```

But I found  `event.preventDefault()` donot prevent  keys like `enter`, `delete` `backspace`  ?

**Comment by YurkaninRyan** [comment]
Would it be easier to just call undo yourself, and set readOnly to `true`?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
