### ISSUE TITLE
if the editor becomes `readOnly`, blur it

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1207]
This is a bit controversial maybe.

I think if `props.readOnly` becomes true, then we should blur the editor, because it shouldn't be able to be "selected" in that sense. Otherwise custom logic needs to always account for "is it focused but in a read only state" which is counter-intuitive.

**Comment by dmitrizzle** [comment]
Would the content still be selectable as plain HTML? I'd imagine most of the time read only mode is used to parse the JSON content without having to deal with HTML in the database.

**Comment by oyeanuj** [comment]
@ianstormtaylor How would this affect users selecting text in the editor (for example, to focus on parts they are reading, or copying)?

**Comment by zkwentz** [comment]
I agree with this one. Reason being I am showing two editors on one page, an Editing Slate Editor and a Preview Slate Editor.

The Preview Slate Editor is in `readOnly={true}` mode. I push the value of the Editing Slate Editor over to the Preview Slate Editor `onChange` of the Editing Slate Editor, e.g.:

```
  <>
    <EditingSlateEditor onChange={() => this.setState({value})}/>
    <PreviewSlateEditor readOnly={true} value={value} />
  </>
```

Because the Value contains selection logic, the PreviewSlateEditor tries to steal focus, and then both editors end up losing focus.

**Comment by ianstormtaylor** [comment]
I realized that this is not a great idea since it's a common practice to make editors read-only if the connection drops out, and quickly make the read-write again when it returns. And keeping the selection in place there is key to the user experience... so it seems like this should be done in userland instead.
