### ISSUE TITLE
Bug with inserting void nodes & text

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#1249]
https://jsfiddle.net/7ut8eo72/

Select some text and hit Cmd + M. Note that only one inline void node is inserted.
Expected behavior: on line 43, we are actually inserting a void node, followed by text, followed by another void node.

OS X 10.12.6, Chrome, Slate 0.27.2

**Comment by doodlewind** [comment]
You can just firstly call `Document.create` to generate a fragment, then `insertFragment` for once, instead of continuously calling `insertInline` and `insertText`. See how Slate handles pasted HTML in `onPaste` as an example.

Slate is updated, new JSFiddle here: https://jsfiddle.net/doodlewind/7ut8eo72/3/

@ianstormtaylor can we close this since it looks like a question more than a bug?

**Comment by ianstormtaylor** [comment]
Hey @AlexeiAndreev I believe this is happening because the `insertText/insertInline` pieces are being called once the first void inline has already been inserted. And when a void node is focused, you can't insert text without moving the selection after it.

The solution would be to move the cursor after inserting it. Although I'd be open to discussing removing this limitation if someone wants to make a PR.
