### ISSUE TITLE
Plugin dependencies

### ISSUE THREAD

**Issue by marijnh** [ianstormtaylor/slate#129]
*(This is an unasked-for open-ended discussion issue that I'm opening here in the hope of starting a discussion with someone who's working on problems that I'm also working on. If that's not something you have time for, definitely feel free to simply close.)*

Slate currently represents a set of plugins as a raw (user-provided) array of plugin objects. One thing I've ran into in other plugin-supporting systems, such as [Tern](http://ternjs.net/), is that once the ecosystem gets bigger, you start to have plugins that depend on other plugins.

Do you have any vision of whether and how you want to support this in Slate? I did (for ProseMirror) some sketches where plugins could declaratively list their dependencies, and there'd be a wrapping object that resolves the set of plugins it is given by flattening it out so that all dependencies are present, once, in the resulting array of plugins. This adds the need for being able to recognize plugins by identity (to know when the same dependency is being pulled in multiple times) and to resolve when and how variously configured instances of a plugin may be merged.

Which adds a bunch of awkward new concepts to the way plugins are defined and used, and feels like it's quickly veering towards overcomplication again. But I've also not been able to convince myself that this isn't a feature that's going to be needed—a system for modularity that requires users to manually collect and list (recursive) dependencies just feels primitive.

**Comment by ianstormtaylor** [comment]
Interesting! Definitely down to discuss this kind of stuff. I could imagine a few cases where plugins might need to depend on others. Do you have any concrete examples you're thinking about?

My gut feeling is that it's going to be slightly more edge case that plugins have dependencies on other plugins, so it probably wouldn't be worth the complication of trying to manage those dependencies for people automatically. Might just be easiest in the end to go with a mention in the plugin's readme or similar.

One complication of trying to identify plugins, is that I've imagined re-using the same plugin as a pretty valid use case for an easy way to configure multiple behaviors. For example you might use a text replacing plugin a few times:

```js
const plugins = [
  Replace('(c)', '©', [
    ignoreIn: ['code']
  ]),
  Replace('fn ', 'function () {\n  ', [
    onlyIn: ['code']
  ])
]
```

So it might get more complex figuring out plugin identities. Although that might not matter.

This is slightly unrelated, but I was recently thinking about it: another reason "fingerprinting" plugins and their config would be useful is to know whether "a plugin has changed since the last render", for Slate's case, where it's stateless with React. Since otherwise, you have to enforce that users define plugins outside of their `render` method, or else it will be new each time and constantly reset state. But I've just gone with a "up to userland" for that right now as well.

**Comment by marijnh** [comment]
(Do I see correctly that plugins that keep state aren't something that Slate does right now?)

I am aiming to represent various pieces of functionality, such as in-document or on-scrollbar annotations and decorations, as plugins. These are the kind of utilities that other plugins will build on. Maybe that's not part of your plan for Slate.

**Comment by ianstormtaylor** [comment]
What do you mean by keeping state? A plugin can definitely closure over some state if it wants to cache things for example. However, it's up to the user to ensure that they aren't reinitializing the plugin on every render of the editor (which would destroy that long-lived state).

**Comment by marijnh** [comment]
> What do you mean by keeping state?

State in the sense of the editor state -- something that's not randomly mutated, but rather that's updated in lockstep with the rest of the editor state, such as you would need for history and other types of change tracking.

**Comment by ianstormtaylor** [comment]
Yup, they totally can. They can just listen `onChange` and store the current editor state inside their own closure, so that other handlers/operations can make use of it if needed!

**Comment by ianstormtaylor** [comment]
(Btw, going to close this just for my own issue-handling OCD, but keep chatting and I'll see the notifications and respond!)
