### ISSUE TITLE
Distributing Slate as a bundle

### ISSUE THREAD

**Issue by N1kto** [ianstormtaylor/slate#130]
Hi. Pretty much impressed with work you've done. Especially with designed API (which is kind of a candy after hacking [Draft.js](https://github.com/facebook/draft-js)) and plugins.

What I wounder about is why isn't **Slate** distributed as a single bundle? Like e.g. mentioned [Draft.js](https://github.com/facebook/draft-js)).

In our project, we are using [Brunch](http://brunch.io/) as a build tool and it's kind of 'difficult' to consume NPM packages and probably impossible to consume ones which have dependencies to other NPM modules: **Slate**'s compiled files in `/dist` folder have dependencies to NPM modules outside of `/dist` folder.

I understand that I probably can build such a bundle myself, but I wonder if is there a specific reason not to distribute **Slate** as a single bundle and therefore make it much easier to start using it in such projects like ours?

**Comment by ianstormtaylor** [comment]
Nope, no reason, just no one had asked yet! I've added a `dist/slate.js` file in the latest release. Let me know if that works for you.

Unfortunately, because of how [`cheerio`](https://github.com/cheeriojs/cheerio) manages its `lodash` dependency, the build is close to `0.5MB` bigger than it should be from that alone. But hopefully once `0.21` is released they will have solved that. If anyone else wants to investigate build size and swap out dependencies to get things smaller, I'd welcome pull requests!

**Comment by ianstormtaylor** [comment]
@N1kto slight update, due to way that `dist` is packaged in the build steps, the `dist/slate.js` file is still there, but you'll need to `npm install` the specific version you want and retrieve it from the downloaded package in `node_modules/slate/dist/slate.js`.

**Comment by N1kto** [comment]
@ianstormtaylor thanks a lot for fast reply.

Unfortunately, the bundle doesn't work well. 
The *lodash* dependency (the one from cheerio probably) has over-written `_` var in `global` with itself, and we have [underscore](http://underscorejs.org/) living there. This broke our app.

Also bundle size is `2.1 MB` which is kind of huge. Will experiment a little to see whether it can be improved. 
Also using other bundler than browserify (which seems to evaluate each module, e.g. *lodash* in `global`) can help to avoid such accidental over-writes as we I mentioned above.
