### ISSUE TITLE
How to check null state

### ISSUE THREAD

**Issue by gmchaturvedi1** [ianstormtaylor/slate#1301]
i am saving the default state as following on database when it return back how to check this is empty or not :+1: 
{
        "nodes": [
          {
            "kind": "block",
            "type": "paragraph",
            "nodes": [
              {
                "kind": "text",
                "text":""
              }
                
            ]
          }
        ]
      }
regards
gmchaturvedi

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
