### ISSUE TITLE
Initialize slate with an empty paragraph, doesn't show placeholder

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#131]
I'm using a placeholder as such:

```jsx
      <Editor
        readOnly={Boolean(readOnly)}
        renderNode={renderNode}
        placeholder="Write something..."
        onChange={change(onChange)}
        state={editorState || html.deserialize(importFromHtml)}
      />
```

However, the placeholder is only shown when the state is:

```
  editorState: Raw.deserialize({
      nodes: [{
        kind: 'block',
        type: 'placeholder',
      }]
```

When I'm using a paragraph block type, the placeholder isn't shown:
```
  editorState: Raw.deserialize({
      nodes: [{
        kind: 'block',
        type: 'paragraph ',
        nodes: [{
          kind: 'text',
          ranges: [{
            text: ''
          }]
        }]
      }]
```

The same applies if I remove all content from an editor containing paragraph nodes

**Comment by ianstormtaylor** [comment]
Hey @arekkas question for you: are you rendering a custom renderer for the `paragraph` type blocks? The docs could probably be a lot more clear here, but let me see if I can explain this in case it's the cause of the problem:

The current `placeholder*` props of the `<Editor>` affect the placeholder used in "default" blocks, AKA ones that Slate renders for you automatically. If you'd like to add placeholders to your custom blocks (ones that are renderer via `renderNode`), you can definitely do that, but you'll need to use the `<Placeholder>` component. (This might be a reason to remove the `placeholder*` attributes all together, to keep the usage simpler.)

My guess is the reason it works with the `placeholder` block type, is because you haven't defined a block renderer (via `renderNode`), so it's using the default one, which has the placeholder.

Does that make sense? Let me know if that's not the case!

**Comment by arekkas** [comment]
Ah I see, i had my own paragraph logic when messing around and forgot about that. Thanks! I disabled that now and the placeholder works fine - nice catch!
