### ISSUE TITLE
change to use explicit `return false` to "abort" the stack everywhere

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1311]
Right now, depending on the place we use different semantics to abort.

- In the HTML serializer, if you explicitly `return null`, the element will be aborted.
- In event handlers, if you return any non-null value, the event will be aborted. I've been using `return true` often, but sometimes it will also just be `return change...`

I think this is confusing, and it would be better if the way to abort was always `return false`, which somewhat matches the browser's handling of prevent default in native event handlers, since it seems like a pattern that people are used to.

Open to ideas!

**Comment by steida** [comment]
It's a little bit confusing because I had to find this issue to understand the meaning of `return true`. The good API should have the minimal surface area with single responsibilities. Therefore, I suggest using event.preventDefault method only, because it's explicit. Return boolean should not have any effect, because it would violate the single responsibility principle, and developers would have to think about which way should be used.

**Comment by steida** [comment]
For example, this is confusing https://github.com/ianstormtaylor/slate/blob/master/examples/rich-text/index.js#L232 Why there are both methods?

Btw, your work is super awesome. Nuff said.

**Comment by ianstormtaylor** [comment]
Hey @steida thanks for the ideas. I think in this case there are actually two concerns to handle though:

1. Whether to prevent the native browser behavior.
2. Whether to break out of the plugins stack.

Concern **1** is what `preventDefault` is for, and might not apply to certain events, or even at all on certain platforms. But concern **2** is what the return value is for.

**Comment by ianstormtaylor** [comment]
This is solved differently now with `next()` to continue.
