### ISSUE TITLE
handle both LTR and RTL text direction

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#134]

**Comment by SamyPesse** [comment]
That'd be awesome, I'm closely following Slate so that we can switch our [GitBook Editor](https://www.gitbook.com/editor) from Prosemirror to it (we've tested Draft as well).

RTL is one big missing feature of Prosemirror, but Prosemirror is very stable for edition and handle inline atomic entities very well (for example inline images, HR).

@ianstormtaylor Since we've built [markup-it](https://github.com/GitbookIO/markup-it), I'll be happy to contribute by creating a Markdown serializer for Slate. Should I make a PR for it or publish it as an NPM module?

**Comment by mathieudutour** [comment]
I read somewhere in the docs that the HTML serializer would probably be extracted from the core. Make sense for a markdown serializer to be an external NPM module I guess

**Comment by SamyPesse** [comment]
Yes, it makes more sense 👍

**Comment by ianstormtaylor** [comment]
That would be awesome, @SamyPesse! I think outside core makes sense yep. I'm still slightly conflicted on whether to pull the `Html` one out, but over time it will start making more and more sense as everything stabilizes I think!

I haven't really dug into what RTL entails, but if you wanted to dive in I'm happy to help with advice on pull requests. (If you need anything the Slack channel is probably fastest!)
