### ISSUE TITLE
[IME] Crashing when inputting more than a single character

### ISSUE THREAD

**Issue by blakeembrey** [ianstormtaylor/slate#1340]
#### What's the current behavior?

![](https://d26dzxoao6i3hh.cloudfront.net/items/0D072i3v3q3q3o3G0F2L/Screen%20Recording%202017-10-29%20at%2010.10%20pm.gif)

#### What's the expected behavior?

It shouldn't crash. I've been trying to debug and figure out where to start, but unfortunately the codebase is still a bit beyond me. It appears to be related to https://github.com/ianstormtaylor/slate/issues/1229 and meant to be fixed with https://github.com/ianstormtaylor/slate/pull/1322, but it seems to still be broken running from `master`.

**Comment by doodlewind** [comment]
I believe this is a common pitfall in editors based on React tech stack, since this also happens in [Draft.js](https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#browser-plugins-extensions). The direct reason is that **vDOM and DOM are out of sync**.

We've ran into several kinds of IME bugs in Slate for now:

1. Selection collapsed, cursor inside blocks, errors thrown during/after IME composition. See #1314.
2. Selection collapsed, cursor in an empty new block, errors thrown after IME composition. See #1229.
3. Selection expanded, error thrown after IME composition. See #1114.

On desktop, for 1 and 2 we've generally fixed through COMPAT code in `slate-react`'s plugin (only desktop Safari still facing case 2), but case 3 is the most difficult one, since browser **natively removes all selected blocks on IME updates, and such behavior happens before IME composition event triggers, so when Slate tries updating these nodes, React crashed**.

Seems that this issue you raised belongs to case 3. To reproduce just do as below:

1. Select multi blocks.
2. Use IME to input some texts.
3. Choose a word.

Just do this in [demo](https://draftjs.org) of Draft.js and you'll also crash them 😈 I've yet not thinking about any 'elegant' approaches handling this for now, but hope this writeup somewhat helps.

**Comment by blakeembrey** [comment]
Thanks @doodlewind, I was looking through the other PRs and issues you were opened earlier and trying to use that as a starting point for what the issue may be. Interestingly, I can't crash the Draft.js demo - can you share your replication here? When I do the same input with Draft.js, it correctly responds immediately by hiding the placeholder text and doesn't crash when inputting more than a single character from IME input.

Also, I didn't realise this part of the interactions used React virtual DOM instead of native DOM APIs. I was trying to understand it and thought it was relying on native DOM APIs.

P.S. My Chinese is terrible, I wish it was better but I haven't practiced enough. Thanks though :smile:

**Comment by doodlewind** [comment]
@blakeembrey I've recorded a [demo](http://7u2gqx.com1.z0.glb.clouddn.com/QQ20171011-144824-HD.mp4) as a replication.

For my understanding, the pain point is that during IME ops, browser may natively mutates DOM without noticing React, then when React's editor component runs `onComponentUpdate`, ReactDOM will try removing non-existing DOM nodes, for now we have to manually sync this back, and it's not unprocurable since Slate also implements its own DOM utils.

**Comment by blakeembrey** [comment]
Thanks, I see. It's a bit more of a complex case. I'll have to experiment a bit and try to understand the codebase some more to figure out if there's a better workaround. I feel like it shouldn't be impossible to fix, I just don't have a good enough grasp right now on the codebase.

**Comment by blakeembrey** [comment]
@ianstormtaylor I just noticed that this actually only occurs when it's at the beginning of the line. If it's after any single character (even a space) it works perfectly. Is there something that would account for this behaviour?

**Comment by doodlewind** [comment]
@blakeembrey you can set a `debugger` in `<Content />`'s  `updateSelection`, then see the DOM change after IME composition ends.

In safari, say this is the DOM structure before: 

``` html
<span data-key="xxx">
  <span data-slate-empty-block></span>
</span>
```
After (`<span>` removed, this demo may not accurate):

``` html
ni' hao
```

So comprehending what browser natively did when inserting chars in Safari is the point I think.

**Comment by blakeembrey** [comment]
I couldn't easily put a breakpoint because it's called way too often, but you can watch how the error occurs. I think it's because Mac OS is automatically inserting a space? E.g. you type `nihao` but the DOM is gets `ni hao`. Right before the second word appears, the DOM is:

```html

```

Right after it collapses:

```html
<div data-key="2" style="position: relative;">ni hao</div>
```

When inserting after the first character, it aligns correctly:

```html
<div data-key="2" style="position: relative;"><span data-key="3"><span data-offset-key="3:0"><span data-slate-empty-block="true">ni</span></span></span></div>
```

**Comment by blakeembrey** [comment]
Do you know if there's a way to avoid the content being placed inside `data-slate-empty-block`? I assume that's not meant to be happening?

**Comment by doodlewind** [comment]
Yeah this is not expected. Which browser are you running into this? Chrome works fine for me, is that only Safari needs a fix? If so,`preventDefault` in `slate-react/plugins/before.js` according to `IS_SAFARI` may work. To see the input events log, I'd recommend this [demo](https://optimdata.github.io/slate/#/mobile).

**Comment by chemzqm** [comment]
I have this issue with  Chrome 62.0.3202.75 on MacOS today, but I don't have this issue yesterday, might related to Chrome/Slate update.

**Comment by doodlewind** [comment]
@chemzqm if you select multi blocks and replace them with IME input, Slate crashes regardless your browser for now. This is a known issue. Could you please share your reproduction steps?

**Comment by blakeembrey** [comment]
I'm on Chrome 61 and macOS for the demo.

**Comment by chemzqm** [comment]
@doodlewind 
![2017-10-31 11_50_44](https://user-images.githubusercontent.com/251450/32206709-c9ad6fae-be31-11e7-9f32-b5dc6f799af4.gif)

Always broken when insert new text in empty block, both type `nihao1` or `nihao` and space.

**Comment by doodlewind** [comment]
I see, third party Sougou pinyin IME works fine but macOS's built-in pinyin IME fails. I'll look into this later.

**Comment by blakeembrey** [comment]
I got it working by changing the `\n` in `<span data-slate-empty-block />` to `\u200B`. If you change that, then fix the the `hasAttributes` (should be `hasAttribute`) typo it works (https://github.com/ianstormtaylor/slate/blob/97002a483523e236e42f2fd107a4aac6d24fea69/packages/slate-react/src/utils/find-dom-point.js#L47).
