### ISSUE TITLE
Restoring previous selection

### ISSUE THREAD

**Issue by ctrlplusb** [ianstormtaylor/slate#136]
Frikken loving this project!!

I have an auto save pipeline which will then result in a redux auto prop pass in, which then causes a rerender.  This works okay from a content standpoint as it is simply reloading the content I just saved, however I am having problems with restoring the selection state.

At the moment I track all changes via the `onChange` event.  Then when I receive the "persisted" state back from redux I want to try and restore the selection using the existing state that is currently on the component, but I can't seem to get this to work.  

Here is my current attempt:

```javascript
// The state from props/redux.
const editorState = Raw.deserialize(this.props.editorState);

// Any existing tracked state.
const { editorState: existingEditorState } = this.state;

let selectionProps;

if (!!existingEditorState) {
  selectionProps = {
    anchorKey: existingEditorState.anchorKey,
    anchorOffset: existingEditorState.anchorOffset,
    focusKey: existingEditorState.focusKey,
    focusOffset: existingEditorState.focusOffset,
    isFocused: existingEditorState.isFocused,
    isBackward: existingEditorState.isBackward
  };
}

this.setState({
  editorState: !!props
    // Try re-set the existing selection.
    ? editorState.transform().moveTo(selectionProps).apply()
    // First time render, use as is. 
    : editorState
});
```

Any ideas?  Have I completely misunderstood the API docs? :)

**Comment by ctrlplusb** [comment]
Ok, hmmm, I think I have a bit more insight into the issue. I see there are `anchorKey` and `focusKey` props.  But I believe these keys will be different on my nodes after I deserialize the updated state and pass it to `Editor`.

**Comment by ianstormtaylor** [comment]
Yup, that's right. The keys are randomly generated whenever you serialize/deserialize an `State` right now, so the selection won't find the same nodes anymore. It seems like the better way to go would be to have the editor not need to re-load the identical state, since this would result in a lot of extra re-rendering since the immutable objects would also all be re-created.

**Comment by ctrlplusb** [comment]
Brilliant, that is exactly what I went for in the end.  :)

**Comment by ctrlplusb** [comment]
One thing that just came to mind... 

Would this affect an SSR implementation? i.e. the unique keys create a different hash of the react content which results in the reconciler doing a full rerender?

**Comment by ianstormtaylor** [comment]
Possibly! I think it might end up reconciling because of the changes keys (although it would for changed immutable instances regardless), but it won't end up re-rendering. But just that once is probably fine. The real performance issue would be reconciling/rerendering on each content change I think. But I might be missing something there, haven't looked into it deeply yet!

**Comment by ianstormtaylor** [comment]
Going to close for now, glad that helped!
