### ISSUE TITLE
Ctrl+Z to undo on empty editor crashes the editor

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#1418]
Creating an empty editor with `html.deserialize('<p></p>')`, and then pressing `Ctrl+Z` crashes the editor.

Instead initialize with a raw value:
```
Value.fromJSON({
  document: {
    nodes: [
      {
        kind: 'block',
        type: 'paragraph',
        nodes: [
          {
            kind: 'text',
            leaves: [{ text: '' }]
          }
        ]
      }
    ]
  }
})
```

**Comment by Slapbox** [comment]
Okay nevermind that. It was working for about 2 minutes it seemed, but I'm seeing the issue again. In any event, this is an edge case.

The error is: `Uncaught Error: Invalid `key` argument! It must be a key string, but you passed: null` in `slate/lib/models/node.js on line 2229`

Using Slate 0.31.

**Comment by julienp** [comment]
This also happens when you paste text into an empty editor and then Ctrl-Z

In the fiddle https://jsfiddle.net/mh0an9ss/ paste some text, ctrl-z and it throws Error: Invalid `key` argument! It must be a key string, but you passed: null

**Comment by anewusr** [comment]
The underlying problem has been an issue since https://github.com/ianstormtaylor/slate/issues/1161.

You can't do any transformations in the SlateEditor until it has been focused, for some reason.

**Comment by conorcussell** [comment]
I may just be repeating things people already know, but here are my findings from digging into this today. 

When you create an empty editor the selection is unset, and an invalid selection is created because text is `undefined`.

https://github.com/ianstormtaylor/slate/blob/199c32a2b5f776c586e7202cfa3183e551153fe4/packages/slate/src/models/value.js#L117-L120

This also happens with copy and paste because the onPaste plugin invokes [`Plain.deserialize`](https://github.com/ianstormtaylor/slate/blob/199c32a2b5f776c586e7202cfa3183e551153fe4/packages/slate-react/src/plugins/after.js#L613) which in turn invokes [`Value.fromJSON`](https://github.com/ianstormtaylor/slate/blob/199c32a2b5f776c586e7202cfa3183e551153fe4/packages/slate-plain-serializer/src/index.js#L58)

In the [render method of slate-react's content component ](https://github.com/ianstormtaylor/slate/blob/199c32a2b5f776c586e7202cfa3183e551153fe4/packages/slate-react/src/components/content.js#L428) `getSelectionIndexes` is called with a `startKey` and `endKey` of null, which calls `getFurthestAncestor` with `null` and gives us the error.

https://github.com/ianstormtaylor/slate/blob/199c32a2b5f776c586e7202cfa3183e551153fe4/packages/slate/src/models/node.js#L1410-L1414

Simply returning `null` in `getSelectionIndexes` when `startKey` and `endKey` are null will fix this case, and copy + pasting but it will not fix the case mentioned in https://github.com/ianstormtaylor/slate/issues/1161. If the editor won't work without any nodes in it, should we ensure there is at least one node by default?

```javascript
// if we've been passed an invalid range, we can exit early
if (!startKey && !endKey) {
  return null;
}
```

**Comment by ianstormtaylor** [comment]
Hey @conorcussell thanks for the super clear writeup. I'd love a PR that fixes the `getSelectionIndexes` case.

For the empty nodes case, Slate itself shouldn't add a node, but I'd definitely be open to a PR that threw a more helpful error when that impossible case is run into. (Ideally in a single, or few places, wherever makes the most sense in that code path.)

Thank you!

**Comment by tobiasandersen** [comment]
This isn't an issue anymore (since #1443).

**Comment by Slapbox** [comment]
This is an issue again as of `0.33.4`

**Comment by Slapbox** [comment]
`editor.value.history.undos.size` seems to have a default size of `1`

Why is this?

**Comment by Slapbox** [comment]
Moving discussion to #2260
