### ISSUE TITLE
Docs versioning

### ISSUE THREAD

**Issue by stochris** [ianstormtaylor/slate#1431]
#### I want to request a *feature* ?

It would be cool to have a docs system in which the user can navigate previous versions.

**Comment by ianstormtaylor** [comment]
There is now a versioning example that shows how you might build this.

**Comment by t3db0t** [comment]
Am I crazy, or do I no longer see the versioning example? I saw it a few weeks ago but now I can't find it!

**Comment by ianstormtaylor** [comment]
Definitely closed this for the wrong reason. There was a versioning example in `0.47` but it was removed along with a few others that were too much to maintain.

As for docs versioning, which the issue was originally about. You can navigate to old versions of the docs in GitHub since everything is stored there. Unfortunately maintaining multiple versions at once is too much scope to maintain though.

**Comment by t3db0t** [comment]
Gotcha. Yeah, I was looking through the commit history for `site/examples` but for some reason it only goes for one page and "Older" is grayed out. It wasn't somehow on a different branch, right?

Do you think that versioning example would require much modification?
