### ISSUE TITLE
Way to bundle change updates, so they get undo-ed together

### ISSUE THREAD

**Issue by stochris** [ianstormtaylor/slate#1456]
#### Do you want to request a *feature* or report a *bug*?
I would to request a feature 

#### What's the current behavior?

Currently, there is no way to bundle change operation together so they get undo-ed at the same time.

#### What's the expected behavior?

It would be useful, especially when using a table, to have operation done on multiple cells be undo-ed all at the same time ( for example, when you delete text from multiple cells, undo would undo all the deletes, not just the first )

**Comment by Slapbox** [comment]
Was just asking about this. Would love a method for this.

**Comment by thesunny** [comment]
I haven't looked into the internals but just wanted to start a discussion of how the developer might bundle actions together.

In my opinion, it should work something like this:

* By default, all operations submitted at the same time get bundled together into a single undo. Usually this is a reasonable default. For example, a "delete column in table" action would be executed at once so all its operations would be grouped togehter. Can't think of too many situations where this isn't true.
* If operations need to be broken down further, use something like `change.doSomething().doSomethingElse().bundle().andDoThis().bundle().andFinallyDoThis()`. There is an implicit `bundle()` at the start and end. The in between `bundle`s separate other groups of operations.
 
I like this because by default the editor should normally just do the right thing (I think).

**Comment by ianstormtaylor** [comment]
Doesn't it merge everything right now? There's also a `merge` operation flag that might be used to get this functionality.

**Comment by thesunny** [comment]
LOL! Yeah, it does exactly that. Because of the comment earlier about deleting multiple texts, I assumed it was saying that it chunked them more granularly by default.

**Comment by stochris** [comment]
@ianstormtaylor could you provide a link to the merge flag implementation or to the docs? I couln't find anything about that

**Comment by stochris** [comment]
I'm using the `deleteAtRange` method for every cell content which in turn which calls `change.snapshotSelection()`. That creates a slight problem, since every change operation is seen as a separate action. Is there any way to add a flag that skips this ?

**Comment by maddrag0n** [comment]
@ianstormtaylor any news on this one?

**Comment by zGrav** [comment]
A workaround has been made for this, but it would still be interesting that deleteAtRange undoing would act more like removeNodeByKey undoing.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
