### ISSUE TITLE
In which version of IE can run slate?

### ISSUE THREAD

**Issue by imlgm** [ianstormtaylor/slate#146]
Because I can't have IE installed on my computer, I asked one workmate to check how slate works in IE. she gave me the feedback that slate don't work on both IE9 and IE10。
Which version of IE is in the compatible list or plan?

**Comment by arekkas** [comment]
I have had multiple React projects with issues on =< IE10 ("Symbol not defined"), that's probably why Slate doesn't work on IE10 right now. Runs better on Edge though.

**Comment by arekkas** [comment]
Also, this is a dupe - check #73

**Comment by ianstormtaylor** [comment]
My guess is that the lowest I'd personally want to go is `IE 11`. Although it might be something that needs to be contributor-driven, because I don't have an easy way to test IE, so if it's up to me it would take a while 😄

**Comment by ianstormtaylor** [comment]
Feel free to investigate and open issues / pull requests with specific fixes!

**Comment by robbertbrak** [comment]
I'd definitely vote for IE11 support, as it will be probably (have to) be supported for quite a while. I wouldn't bother with any earlier IE versions, since they are EOL anyway (https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support).

About being able to test on IE11: have you considered using the VM's offered by Microsoft (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)?
