### ISSUE TITLE
What was the last stable version of slate?

### ISSUE THREAD

**Issue by anewusr** [ianstormtaylor/slate#1496]
Last time I checked, the latest releases broke existing behavior in the examples and degraded performance across the board.

What version of slate are people while this is all getting sorted out?

**Comment by aguilera51284** [comment]
in the readme say

> Slate is currently in beta. It's useable now, but you might need to pull request a fix or two for advanced use cases.

**Comment by ianstormtaylor** [comment]
Ask this kind of thing in Slack. This library is in beta, the releases are all varying degrees of stable, but many people are using them in production. YMMV.

**Comment by anewusr** [comment]
@aguilera51284 
All the examples and even the jsFiddle to report bugs should not be considered an "advanced use case".

@ianstormtaylor 
I'm fine with breakages while the library is in Alpha, but at the very least, this OSS should indicate which versions are stable and which have been committed without testing.

**Comment by ianstormtaylor** [comment]
@anewusr every commit and every pull request is run against CI. We don't have great CI in all areas yet that's for sure, and some things are inherently very hard to test (like cross-browser event handling).

If you'd like to help by adding testing to ensure better coverage for APIs that you see are broken that would be very appreciated. Or if you'd like to submit pull requests to fix something you see that is broken, that would also be very appreciated. Or even if you just open well-written issues for the things you see that are broken, with a way to reproduce the issue so that others can help fix them, that would also be very appreciated.

What's less appreciated is opening passive aggressive issues with open-ended questions. (Doing a quick search, this seems to be the second time you've done this, with https://github.com/ianstormtaylor/slate/issues/1381 being the first.) The contributing instructions (and many past issues if you search) make clear that the Slack channel is the place for questions and discussions. Or, if you want to open a constructive issue that presents current recurring problems, and even suggests a solution for them, that works too.

Please remember that this is open-source software, not a job.

**Comment by anewusr** [comment]
I would agree with you if the bugs in question were due to user customizations or some eclectic setting.

But when the bugs are so glaring, like breaking the examples and actually preventing reproduction, a.k.a. when a version was released that broke the JSFiddle for a week, that's where I draw the line between 'Beta' and 'Alpha'.

You point out #1381 as being "passive aggressive". To who? It was neither yours nor Slate's fault that the documentation search sucks, it was GitBooks as I clearly noted in the issue. I even provided a workaround to get the right behavior I asked for. If pointing out another company's error seemed like it was attack on your self-worth, then, I apologize.

But, rather than paint me as some whiner , you can see in #558 that I've been here cheering you guys on for a while now. Outside of Github, I've recommended you to friends, promoted you on message boards.

Unfortunately, it seems to me that this project tried to do a lot once, got pulled in way too many directions, and is now buckling under the stress. 

I'm not demanding immediate fixes for all my problems; I'm not a customer. 

But I was a developer who put faith in this project.
