### ISSUE TITLE
remove the restriction that void nodes have " " as text content

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1504]
This restriction was setup a while back, but based on the discussion in https://github.com/ianstormtaylor/slate/issues/667 I think this limitation is not helpful. It would be great if void nodes could actually act on their text (programmatically), and that could be preserved when converted to/from void.

**Comment by CameronAckermanSEL** [comment]
This would be a good improvement

**Comment by tuanmng** [comment]
Hi Ian,

I don't know if this is related to the current issue, but I have the following comment and would like to hear what you think about it. I noticed that below, whitespaces become part of characters, so you have ```'A '``` and ```' of ' ``` for examples. Would it be an advantage to have spaces as a special kind, for examples ```' '``` (one), ```'  '``` (two) etc. This is because in certain kinds of editors whitespaces could be significant.  

```
{
  kind: 'text',
  ranges: [
    {
      text: 'A ',
      marks: [],
    },
    {
      text: 'line',
      marks: [{ kind: 'mark', type: 'bold', data: {}}],
    },
    {
      text: ' of ',
      marks: [],
    },
    {
      text: 'rich',
      marks: [{ kind: 'mark', type: 'bold', data: {}}],
    },
    {
      text: ' text.',
      marks: [],
    }
  ]
}
```

**Comment by ianstormtaylor** [comment]
@tuanmng I don't think it's related to the current issue, but I'm not sure what you mean. Whitespace can be significant, but I don't think that merits changing the data model?

**Comment by tuanmng** [comment]
@ianstormtaylor I was thinking about the ability to deal flexibly with spaces in any way one wants (for example counting tabs, spaces, newlines that occur around and contracting or removing them if desired).
