### ISSUE TITLE
Shift-select with the arrow keys fails when selecting toward an inline void node

### ISSUE THREAD

**Issue by bengotow** [ianstormtaylor/slate#1518]
Hey folks! This one's a bit odd. GIF below! In the GIF, I am holding down the shift key the whole time. (I haven't attached a JSFiddle because it's reproduced on http://slatejs.org/#/emojis.)

![jan-10-2018 14-18-04](https://user-images.githubusercontent.com/1037212/34798479-1bf4221e-f611-11e7-96be-f42451887560.gif)

Observations:
- Happens in both Firefox Beta and stable Chrome.
- You can shift-select with the arrow keys *away* from an inline void node. Eg: "shift right arrow" past the last void node, or "shift left arrow" before the first void node works. 
- You cannot shift-select with the arrow keys *toward* an inline void node.

**Comment by CameronAckermanSEL** [comment]
Might be similar to https://github.com/ianstormtaylor/slate/issues/1502

**Comment by ms88privat** [comment]
Also related?
https://github.com/ianstormtaylor/slate/pull/913

**Comment by conorcussell** [comment]
This is happening because [`nextText`](https://github.com/ianstormtaylor/slate/blob/44eccca60a60908c88f022b1303452fc8467fde9/packages/slate-react/src/plugins/after.js#L444) is the zero-width text node slate inserts. As a result, the condition is true and we collapse the selection forward instead of extending it. 

I've made a PR which deals with this issue, I still need to check it deals with the other cases and doesn't cause any regressions.
