### ISSUE TITLE
How to move range to the start of a `isVoid` block if the `isVoid` block is at the start of the document

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1521]
**Do you want to request a feature or report a bug?**
bug

**What's the current behavior?**

Because all ranges are inside Text Nodes, suppose we have an `isVoid === true` image block moved to the start of a document, then it seems impossible to move selection to the real start of the document (for example, users press leftArrow at the end of the image)  insert text before the image.

Thank you
Jinxuan Zhu

**Comment by zGrav** [comment]
My workaround around this was actually putting in two empty textnodes previous and after the image:D

**Comment by bengotow** [comment]
Hey @zhujinxuan — I think I've seen a related problem. If an isVoid block is the last node of the document or the last/deepest child of the last node, select-all doesn't work in the editor. I tried to hack a fix to this by ensuring that my HTML serialization inserts an empty space after the last node, but it's not a perfect fix.

**Comment by zhujinxuan** [comment]
@zGrav Consider that the user delete the text node....

I am thinking about 
```
  schema: 
      image: inline, fakeEmptyTextInline
```
And then we can then ensure `fakeEmptyTextInline` is not editable.

**Comment by ianstormtaylor** [comment]
Hey @zhujinxuan good question. 

> Because all ranges are inside Text Nodes, suppose we have an isVoid === true image block moved to the start of a document, then it seems impossible to move selection to the real start of the document (for example, users press leftArrow at the end of the image) insert text before the image.

From Slate's perspective, there is no "real start of the document" in that sense. If the first block in a document is a void image block, that's the first thing you can select. There's no way to select "before" that block because selections can only live inside blocks, and there is nothing before that block. If you need to always be able to select before an image, you can either ensure that there's always a paragraph before it, or add custom logic to ensure that pressing up/left/etc. when an image void node is selected actually inserts a paragraph before it.

@bengotow that sounds like something we should fix, feel free to open a new issue for it!

**Comment by tvrcgo** [comment]
My workaround was copied void image block to second line and deleted the first one. :(
