### ISSUE TITLE
Feature request: clear formating function 

### ISSUE THREAD

**Issue by barry800414** [ianstormtaylor/slate#1556]
#### Do you want to request a *feature* or report a *bug*?

feature

#### What's the current behavior?

I need to make a button to reset every nodes (except image, iframe) in current selection to be default node (e.g. paragraph).
 
Something like the `clear formatting` button in google doc
![2018-01-25 3 57 18](https://user-images.githubusercontent.com/3805975/35377006-7d3e866c-01e8-11e8-9c77-d12b037f548d.png)

However, it seems that there is no function to directly reset all nodes to paragraph node. Or maybe there exists but I am not pretty sure how to do it.

#### What's the expected behavior?
Hope there exists a simple api in `change`, for example `change.clearFormats()`

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
