### ISSUE TITLE
isInRange does not work when testing if a not selected node is part of the given selection

### ISSUE THREAD

**Issue by ch1ll0ut1** [ianstormtaylor/slate#1569]
#### Do you want to request a *feature* or report a *bug*?
bug
#### What's the current behavior?
I`m looping through all child nodes of the Document and trying to find a node that is part of the current selection by:
```javascript
const range = value.selection
const document = value.document

document.nodes
        .find(node => node.isInRange(range));
```

As soon as isInRange is called on a node that is **not** part of the range, it will throw a normalization warning and modifying the range: 
```javascript
Warning: The range was invalid and was reset. The range in question was: ...
```

#### What's the expected behavior?
Because of that, isInRange can not be used to find not selected nodes or filter selected from not selected nodes. Although from the name i would expect this to be possible.

Possible solution:

A) isInRange should have a option to deactivate normalization 
B) find a way to remove normalization for this use case

I would prefer B) because A) makes Slate less easy to use.

**Comment by zhujinxuan** [comment]
I do not think `isInRange` is whether a node is in the range;  Because range only stores key and offset in itself, node method can do at most whether a node is including or is overlapped by a range.

I doubt whether the annotation and the name of that function is a bug.

**Comment by ch1ll0ut1** [comment]
@zhujinxuan i looked into the code and from what i understand the method does check if the node or any childs is part of the given range

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
