### ISSUE TITLE
onSelect disables undo behavior

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1581]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?
Relates to https://github.com/ianstormtaylor/slate/issues/1494
Like the gif below, the C-z undo cannot undo further more after the `<link>a</link>`.  The reason is that, at that stage, each undo will cause a normalization back to the un-normalized cursor and then the normalization will move the cursor back.
![](http://g.recordit.co/gKnHhsHUxA.gif)

### What's expected behavior?
I am wondering whether we shall add a special mark to onChange normalization behaviors that the undo will undo further steps.

**Comment by zhujinxuan** [comment]
Or we may have something like
```
change.setOperationFlag('undoRedo', 'doNotStopHere') 
```

**Comment by DamareYoh** [comment]
I wrestled with a similar problem this week, but mine was more in "Self inflicted pain" territory. 

If you write a custom undo handler and then use the `setOperationsFlag('save', false)` feature to keep from the normalization being added to the undo stack, this will help resolve the issue. However, if the undo stack is advanced further, this will cause redos to have problems. 

It'd be nice to have a core solution to this problem because it's kinda hard to deal with

**Comment by CameronAckermanSEL** [comment]
Also for normalizations that happen as part of an undo, I wonder if it'd be useful to have them applied to the operation list on the top of the undo stack. That way, it doesn't destroy the rest of the undo/redo stack, and if the user does redo -> undo, then those normalizations are still applied

**Comment by justinweiss** [comment]
I don't know whether this is the same issue, but it seems similar:

In the current version of Slate (repros on https://www.slatejs.org/#/rich-text), in Safari:

* Select some text
* Make the text bold
* undo

The undo does not take effect.

As far as I can tell, this is because Safari prefers the cursor to be at the last position of a node rather than at the beginning of the next node.

I think this is what's happening: 

* After the splits, Slate's selection is at anchor offset 0 and focus offset 0 (of the next node)
* Safari sends a `selectionchange` event, triggering `onSelect`, with the selection at anchor offset 0 and focus offset `length`
* Slate calls `select`, setting its selection focus to focus offset `length`, adding it to the undo stack
* You hit undo, setting the focus back to offset 0 of the next node. Safari sends a `selectionchange` event, changing the focus and adding another `set_selection` to the top of the undo stack

I don't really know how to fix this in a cross-browser way, but I think it's happening more often now that marks create full-fledged text nodes. 

I think it'll be easier to handle it on the Slate side than on the browser side. Maybe we can treat "end of the preceding text node" and "beginning of the next text node" as equal when comparing selections in `select`? Maybe we can skip adding `set_selection` operations to the undo stack for some amount of time after we perform an operation? Maybe ignore `selectionchange` events that happen while we perform an operation? I don't know a lot about how the selection code works, so these are all just stabs in the dark.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
