### ISSUE TITLE
floating blocks cause placeholder to be mispositioned

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#159]
![floating](https://cloud.githubusercontent.com/assets/3372410/17055686/adb0b064-500e-11e6-834a-95dde0e59651.PNG)

```html
<div>
  <img style="float: left">
  <Slate />
</div>
```

**Comment by ianstormtaylor** [comment]
Hmm interesting! 

- What's the rest of the structure around that point look like in terms of the component that are being used in `renderNode`? 
- Is that `<div>` missing `props.attributes`?
- What's `<Slate />`? a nested editor?

You might be able to add `props.attributes` to a nested `<div>` wrapper that you put around `<Slate />` instead and have it work, since it uses the `data-key` attribute in there as the way to know what the DOM node is for a node.

**Comment by arekkas** [comment]
> What's the rest of the structure around that point look like in terms of the component that are being used in renderNode?

Per default, Slate renders a paragraph:

```
class Paragraph extends Component {
  shouldComponentUpdate(nextProps) {
    return !shallowEqual(this.props, nextProps)
  }

  render() {
    const { node, state, children, attributes } = this.props
    return (
      <p {...attributes}>
        <Placeholder
          styleName="placeholder"
          node={node}
          parent={state.document}
          state={state}
        >{placeholder}</Placeholder>
        {children}
      </p>
    )
  }
}
```

> Is that <div> missing props.attributes?

The wrapping div is not under slate control

> What's <Slate />? a nested editor?

That's the Slate editor. The image is not under Slate control.

I believe that the issue is the aboslute positioning of the placeholder. It uses the paragraph's parent to get the current offset. The parent is filling the complete space whereas the text is floating around the image.

**Comment by ianstormtaylor** [comment]
Thanks for the extra info. I'm still not quite sure what's going on. The placeholder should be using the paragraph node itself to calculate the offset it should be at. And then it's positioned absolute relative to the body. Can you investigate in the `<Placeholder>

**Comment by arekkas** [comment]
I think this gif explains it better than words can do:

![asdfa3w](https://cloud.githubusercontent.com/assets/3372410/17077035/3fa1ae5c-50c2-11e6-9ea2-84536b79481f.gif)

**Comment by ianstormtaylor** [comment]
Hmm interesting, yes it does! I'm not sure if there's a way to solve that... hmm. Since the paragraph is the block to be position relative to, and it does actually take up that space with the float. Can you think of any way to derive that?

**Comment by arekkas** [comment]
Why does the placeholder have to be positioned absolutely at all?

**Comment by arekkas** [comment]
Couldn't we use the caret's position instead?

**Comment by ianstormtaylor** [comment]
Good question! There may be some sort of `<Void>`-like hack with nesting content editable that could make it not need to be absolutely positioned. (I know way too much about browser content editable handling 😂) I can check that out soon. 

I don't think using the caret will work, at least for the general "core" case because the editor isn't always focused, and in some cases (like captions) you might want a placeholder to always show regardless of document content.

**Comment by ianstormtaylor** [comment]
Okay, good news and bad news!

Your question prompted me to deep dive into the placeholder. And turns out we don't actually need to use a `<Portal>` to render it. So I was able to simplify how it's rendered. Now it's just a child at the same level with `contentEditable={false}`.

But, it's still positioned absolutely by default, since this it the best for general cases.

But but, you should be able to pass `style={...}` to it, so you can customize it to handle your case. I believe you'll want to float it to the left, and use make it zero-width. Something like:

```js
style={{
  position: 'relative',
  float: 'left',
  width: '0px',
  marginRight: 'none',
  whiteSpace: 'nowrap'
}}
```

I think that will do it. The reason it's not on by default is that it breaks for multi-line placeholders, so you'll have to make sure your placeholder text is really short. 

That's the best I think we can do! But if anyone figures out a more bulletproof set of styles for the default let me know.

**Comment by arekkas** [comment]
ok I'll check it out, thanks!
