### ISSUE TITLE
yarn build and yarn test improvements with rollup

### ISSUE THREAD

**Issue by DamareYoh** [ianstormtaylor/slate#1593]
#### Do you want to request a *feature* or report a *bug*?

Not really sure XD

#### What's the current behavior?

The current behavior (and please correct me if I am wrong :)) is that 

`yarn build` defaults to building production data
`yarn test` tests the production build
`yarn start` attempts to open a dev example site that does not get built anymore by `yarn build`

The consequences of this are that (test) development on slate is slower because, one has to run `yarn build` to get `yarn test` to function. `yarn build` also takes a very long time because it has to do extra steps for a production build.

`yarn start` also now yields a 404 because it tries to run against the dev site, which does not get built in `yarn build`

#### What's the expected behavior?

It seems to me that `yarn build` should default to building in a development environment, and tests should be run against that for the purposes of having quicker development.

Alternatively, we should have a family of commands that run development equivalents of the aforementioned commands.

**Comment by DamareYoh** [comment]
I'd be happy to submit a PR for this, I'm just not sure what the best solution is. 

Thanks!

**Comment by schneidmaster** [comment]
`yarn build` has always defaulted to building production data, the difference now is that it also defaults to building the `examples.prod.js` whereas previously it only built the production build of each package. Similarly `yarn start` has always only started the http server, while `yarn watch` runs the http server and also starts building the packages under watch mode.

I think some improvements we could consider making here are:

1. Change the `yarn watch` command to also output the CJS for each package (not just the ES) -- then when running `yarn watch` you get auto rebuilds that you can test against

2. Define a build command for development that builds the minimum for (re)testing (the CJS variant for each package) and watches (while skipping building the examples which are expensive if you are not using them)

3. I would personally be fine with changing `yarn start` to start both the http server and the rollup watch process rather than just the http server -- seems like this would be more intuitive to get up and running as you mentioned.

**Comment by DamareYoh** [comment]
Hey cool that makes sense, thanks! 

Is there a readme I missed that talks about this stuff?

**Comment by schneidmaster** [comment]
@DamareYoh The "Running Tests" part of the [Contributing doc](https://docs.slatejs.org/general/contributing#running-tests) discusses to a lot of this. However item 1 in my list above is a regression from rollup, so the part about `yarn watch` keeping the source building such that it can be tested against won't be accurate again until #1595 is merged 🙂
