### ISSUE TITLE
Best practice suggestion: display should reflect the slate.value model under (simulated) lag

### ISSUE THREAD

**Issue by amitm02** [ianstormtaylor/slate#1596]
Please consider the following fiddle: [link](https://jsfiddle.net/vma9k6z8/)

I've set a setTimeout of 500ms to simulate a stressed computation load.
```
onChange({ value }) {
    setTimeout(() => {
    	this.setState({ value });
    }, 500);
  }
```

In the first video i've type 1-9 quickly (less than 0.5 per key). the final text in a normal stress would have been "123456789"

![kon8bnnoq1](https://user-images.githubusercontent.com/1888927/35771956-0685ed1e-093e-11e8-9b9f-c56616858fce.gif)

In the second video i've long key pressed the right arrow key, moving the cursor from the start of the sentence it its end. 
 
![axs5gz58qq](https://user-images.githubusercontent.com/1888927/35771975-4f1662ac-093e-11e8-92a0-d9596e9d6c02.gif)

#### What's the expected behavior?

Safe to say,  lagged responsiveness is expected. But the UI should only display events that are stored to state.value. 
In the first examples, digit "1" should have not been temporarily displayed as it was not stored in the final state.value.
In the second example, the cursor should have not move forward and jump back to what was stored in the state.value. It should have moved very slowly.

**Comment by schneidmaster** [comment]
Hey there! Can you explain in a bit more detail how your `setTimeout` accurately simulates computational stress? 

For example, open your fiddle and quickly press 1, 2, 3. You'll see a 500ms delay and then the input will quickly flash through 1 and 2 before ending on 3. This totally makes sense -- the value that is provided to the `onChange` is dependent on the current state of the editor modified by the input. So the `1` keypress triggers a `setState` in 500ms with new value of `"1"`, then the 2 keypress (which occurs before the 1 keypress has actually been applied to the state) queues a `setState` with a new value of `"2"`, then the 3 keypress queues a new value of `"3"`. Then, in 500ms, the 3 events quickly resolve sequentially. Because of the artificial `setTimeout` the changes in events 2 & 3 are still based on an empty editor rather than on the result of the previous operation.

It's not clear to me what else Slate is supposed to do here. At the point when you type the 2 and 3, Slate's value prop is still telling it that the editor is empty (so the newly generated values are correct). When the events are resolved, it briefly flashes the 1 & 2 because it cannot possibly know that another `setState`/rerender is just about to replace the value prop (so the display behaviour seems accurate). It seems that anything else would require Slate to predict the future of what its value prop will later contain, or else would require Slate to maintain some sort of extra internal state (like a list of `onChange`s it has triggered) which violates pure component design principles.

Also I don't think this would be reproducible in the wild without the `setTimeout`. Part of the issue here is that the `setTimeout` slows down the process of re-rendering the component wrapping Slate, but doesn't actually slow anything down in Slate itself, so it is still able to keep handling keypresses and firing off `onChange`s. Practically speaking, if your CPU was that slow, Slate's ability to handle keypresses would be substantially throttled as well, so you wouldn't be able to queue up 4 or 5 changes before a rerender happened. (And indeed, if you remove the `setTimeout`, none of this behaviour is reproducible by maxing out CPU throttling in the Chrome devtools.)

**Comment by schneidmaster** [comment]
Gotcha. So that's actually already the behaviour in Slate. Keeping with the rapid-fire 1, 2, 3 from my last comment, consider this example timeline:

| Time | Description | Current `state.value` |
| --- | --- | --- |
| 0ms | initial state | `''` |
| 5ms | `1` pressed, and queues a `setTimeout` in 500ms | `''` |
| 10ms | `2` pressed, and queues a `setTimeout` in 500ms | `''` |
| 15ms | `3` pressed, and queues a `setTimeout` in 500ms | `''` |
| 505ms | The setTimeout from `1` fires and updates the `state.value`, Slate rerenders  | `'1'` |
| 510ms | The setTimeout from `2` fires and updates the `state.value`, Slate rerenders  | `'2'` |
| 515ms | The setTimeout from `3` fires and updates the `state.value`, Slate rerenders  | `'3'` |

In essence, the flashing mirrors the amount of time between keypresses. At 505ms, Slate receives a new `value` prop saying the value is now `'1'`. Slate rerenders to match what is then the current `state.value`. It has no way of knowing that another `setTimeout` is going to resolve again in a few ms and change the state again. Indeed, the flashing happens because Slate already does exactly what you suggest (precisely render what is provided in its `value` prop).

**Comment by amitm02** [comment]
In you example, shouldn't state.value end up being '123'? (the chars are append to the string)

**Comment by schneidmaster** [comment]
No, because when the `2` and the `3` are pressed, the `1`'s `setTimeout` has not been fired so no state update has been made. Thus the value prop given to Slate is still `''`, so Slate appends the `2` to the empty string and provides that new value (`'2'`) to the `onChange` callback, and the same thing for the `3`. Then, when the `2`'s `setTimeout` fires, it's running the equivalent of `setState({ value: '2' })`, and the same again for the `3`.

**Comment by amitm02** [comment]
I get it. I missed the fact that the change via change() happens to the "value" in the slate-editor component and not to the "value" in the component wrapping/storing it. I guess no easy fix for that...

**Comment by schneidmaster** [comment]
Well, it's the same thing. The `state.value` in the wrapping component is what's given to the `value` prop so it's also the value inside the slate editor to which the change is applied. It's just that in your example, the first `state.value` update does not happen for 500ms, so any subsequent changes that happen within that 500ms will be based on the non-updated `state.value`. In other words, the fact that the `onChange` has been called does not mean that the wrapping component's state has been updated; with your `setTimeout` the wrapping component's state will not actually be updated for 500ms.

**Comment by linonetwo** [comment]
If I sync ```JSON.stringify(value.toJSON())``` to redux store the lag will cause all editing goes to the top of the editor.
And only sync ``value.toJSON()`` to redux, and ```Value.fromJSON``` in ```getDerivedStateFromProps``` it works fine.
