### ISSUE TITLE
Re-rendering of text blocks cause perfomance and flickering issues

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#160]
When text is updated in a text node, the complete inner content is being replaced - not just the delta. This causes substantial lags in large text nodes and flickering as seen in the gif below. The maximum FPS I was able to squeeze out in this gif is 40. On a 75hz display the autocorrect flickering is much more intense and frequent.

![flickering](https://cloud.githubusercontent.com/assets/3372410/17055772/5ace4f22-500f-11e6-9454-2c417f3cc92e.gif)

**Comment by ianstormtaylor** [comment]
Just published `0.6.1` which should fix this issue, but check out the [`History.md`](https://github.com/ianstormtaylor/slate/blob/master/History.md) because there's a breaking change for void nodes. (And the newly updated `images` example code will help for migrating!)

**Comment by arekkas** [comment]
Awesome! If I may ask - how did you solve this?

**Comment by ianstormtaylor** [comment]
For sure! Two things contributed:

- We used to use `data-offset-key="${key}:${start}-${end}"` as an attribute on each `<Leaf>` component in the DOM, for tying it back to the state. But since `start` and `end` are calculated via the content, when the content changes they will cascade—specifically every leaf after the one you've added text to inside a text node will have to update. So now it's `${key}-${index}` instead. This only applies to text nodes with marks applied.

- We also didn't used to render selection changes "natively", ie. without re-rendering, when possible. If a selection event happens and the native selection is between text nodes, it's good to go, so we no longer re-render the editor on those selections (the majority, since adding a character triggers a that kind of selection too). (Otherwise we re-render so that the selection is set to at the proper point in the right leaf node.)
