### ISSUE TITLE
value.endInline not returning Inline node

### ISSUE THREAD

**Issue by bewallyt** [ianstormtaylor/slate#1608]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

`value.endInline` returns undefined if its attribute `isVoid: true` even though there is an inline element in the document.

[jsfiddle example](https://jsfiddle.net/jftdst51/1/)

OS: macOS Sierra v10.12.5
Browser: Chrome 63.0.3239.132
Slate: 0.11.2

#### What's the expected behavior?

`value.endInline` should return the inline node just like `value.endBlock` is returning a block node.

**Comment by CameronAckermanSEL** [comment]
This happens only when the inline is `isVoid: true` because of the extra 0 width block at the end that actually has the selection.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
