### ISSUE TITLE
How can a plug render a Mark?

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1664]
In the [Plugins Guide](https://docs.slatejs.org/guides/plugins), there is this code --

```
RenderMark('bold', props => <BoldMark {...props} />)
```

Within this "feature plugin" -- 

```
function Bold(options) {
  return {
    changes: {
      addBoldMark,
      removeBoldMark,
      toggleBoldMark,
    },
    components: {
      BoldMark,
      BoldButton,
    },
    helpers: {
      hasBoldMark,
    },
    plugins: [
      Hotkey('cmd+b', addBoldMark),
      RenderMark('bold', props => <BoldMark {...props} />),
      RenderButton(props => <BoldButton {...props} />),
      ...
    ]
  }
}
```

But I don't see how a plugin can render a Mark, and can't find any info on how this would be possible.  The spec for a Plugin has no obvious place to render a mark --

```
  onBeforeInput: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onBlur: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onFocus: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onCopy: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onCut: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onDrop: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onKeyDown: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onKeyUp: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onPaste: (ev:Event,change:Change,editor:Editor): Change|void => { },
  onSelect: (ev:Event,change:Change,editor:Editor): Change|void => { },
  
  onChange: (change:Change): any|void => { },
  renderEditor: (props: Object, editor: Editor): Object|void => { },
  schema: { },
```

How can a plugin render a mark?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by tashburn** [comment]
I understand. I'll ask in Slack.
