### ISSUE TITLE
Collapse to end of parent block? (try add new table-row)

### ISSUE THREAD

**Issue by joehua87** [ianstormtaylor/slate#167]
I've try to add a new table-row to table but end up like this: table-row & table-cell is at same level
```
[
  {
    "kind": "block",
    "type": "table-cell",
    "nodes": [
      {
        "kind": "text",
        "ranges": [
          {
            "text": "9"
          }
        ]
      }
    ]
  },
  {
    "kind": "block",
    "type": "table-row",
    "nodes": [
      {
        "kind": "text",
        "ranges": [
          {
            "text": ""
          }
        ]
      }
    ]
  }
]
```
I've try difference ways but cannot insert new table-row as the same level
```js
    // Assume that we're focus on an tabel-cell
    // Get the first block (should be table-cell)
    const cellNode = state.blocks.first()

    // Get the Table
    const tableBlock = state.document.getClosest(cellNode, (block) => block.type == 'table')
    if(!tableBlock) return

    // Get the last row
    const lastRow = tableBlock.nodes.last()
    console.log('Last Child', lastRow.toJS()) // Show table-row here

    state = tranform
      .collapseToEndOf(tableBlock)
      // .collapseToEndOf(lastRow)
      .splitBlock()
      .setBlock('table-row')
      .apply()
```

**Comment by ianstormtaylor** [comment]
Ah shoot yup. This is because selections are always "relative to" the leaf text nodes. So that `collapseToEndOf` actually ends up setting the cursor at the end of the text node in the last table cell of the block. And then that one gets split and the newly split one changed to a row. 

You could try using `insertFragment` as a stopgap for now, but it will feel a little clunky until we can get the `insertNode` transform (and others) that operate at the node level regardless of selection. I was working in that yesterday but it'll still be a few more days at least until it's ready I think.

**Comment by bkniffler** [comment]
Hey, 
I'm trying this now with insertNodeByKey, but i can't seem to get this to work.

If I use 

```jsx
.insertNodeByKey(
    tableBlock.key,
    tableBlock.nodes.length,
    Block.create({ type: 'table-row', data: { } }) // or simply 'table-row'
)
```

I get 
```jsx
// components/node.js:347 Uncaught TypeError: Cannot read property 'kind' of undefined, node.nodes.first().kind

if (node.kind == 'block' && node.nodes.first().kind != 'block') {
      var direction = node.getTextDirection();
      if (direction == 'rtl') attributes.dir = 'rtl';
}
```

Any hints how we can rows/cells to the table? Thanks!

**Comment by ianstormtaylor** [comment]
Hey @bkniffler I think this might actually be solved by calling `.normalize()` before returning a `Block` in `Block.create`, which will ensure that it has text nodes.
