### ISSUE TITLE
Plugin schemas not combining properly

### ISSUE THREAD

**Issue by tashburn** [ianstormtaylor/slate#1671]
If I add two plugins to the same Editor with these schemas --

```
  {
    schema: {
      document: {
        nodes: [ 
          { types: [ 'paragraph' ] } 
        ],
      },
      blocks: {
        paragraph: {
          nodes: [{ objects: ['text','inline'] }],
        }
      }
    }
  }
```

```
  {
    schema: {
      document: {
        nodes: [ 
          { types: [ 'quote' ] } 
        ],
      },
      blocks: {
        quote: {
          nodes: [{ objects: ['text','inline'] }],
        }
      }
    }
  }
```

The combination should be --

```
  {
    schema: {
      document: {
        nodes: [ 
          { types: [ 'paragraph', 'quote' ] } 
        ],
      },
      blocks: {
        paragraph: {
          nodes: [{ objects: ['text','inline'] }],
        },
        quote: {
          nodes: [{ objects: ['text','inline'] }],
        }
      }
    }
  }
```

But is actually (wrongly) --

```
  {
    schema: {
      document: {
        nodes: [ 
          { types: [ 'paragraph' ] } 
        ],
      },
      blocks: {
        paragraph: {
          nodes: [{ objects: ['text','inline'] }],
        },
        quote: {
          nodes: [{ objects: ['text','inline'] }],
        }
      }
    }
  }
```

What's wrong is `schema.document.nodes.types`. It should have both block types, but it only has `paragraph`.

**Comment by CameronAckermanSEL** [comment]
There's probably a limitation where the schema plugin logic does not merge conflicting rules. I think this is probably very difficult to get right.

**Comment by CameronAckermanSEL** [comment]
One other thought. I think it might be an antipattern for a plugin to dictate where it fits in the document schema, because it creates conflicting rules where the consumer of the plugin might have a different set of expectations on where the component provided by the plugin sits within the document. To get this functionality correct, I think we'd be looking at a pattern where the plugin that provides the block basically "registers" where the block sits in the document with the document.nodes schema on top of the other encapsulated rules for the schema rules of the block. Delegating control over the block's relationship with the document and blocks to the plugin makes the plugin less flexible.

**Comment by tashburn** [comment]
In order to get this working now, I did the following to compose my plugin schemas together and feed into the `Editor` as one schema, which seems to work (in Typescript) --

```
function combineSchemas(plugins : Plugin[]) {
  let schema = {
    document: {
      nodes: [] as any[],
    },
    blocks: {},
    inlines: {},
  }
  plugins.forEach(plugin => {
    if (!plugin.schema) return
    let nodes = (plugin.schema.document && plugin.schema.document.nodes) || []
    let blocks = plugin.schema.blocks || {}
    let inlines = plugin.schema.inlines || {}
    schema.document.nodes = [ ...schema.document.nodes, ...nodes ]
    schema.blocks = { ...schema.blocks, ...blocks }
    schema.inlines = { ...schema.inlines, ...inlines }
  })
  // debug('>> schema: '+tos(schema))
  return schema
}
```
