### ISSUE TITLE
Uncaught Error: Invalid `key` argument! It must be a key string, but you passed: null

### ISSUE THREAD

**Issue by raviteja83** [ianstormtaylor/slate#1702]
#### What's the current behavior?

When value is empty the above error is thrown when updating the doc. Can you please explain how to start with an empty doc without initialValue?

#### What's the expected behavior?
The error should be handled.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions.

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help.

Thanks for understanding!
