### ISSUE TITLE
Cant't delete character which is placed just behind transformed character

### ISSUE THREAD

**Issue by e346m** [ianstormtaylor/slate#1708]
#### Do you want to request a _feature_ or report a _bug_?
bug report

#### What's the current behavior?
![can t delete character after kanji sometimes](https://user-images.githubusercontent.com/4677523/37579429-5a5b29b2-2b81-11e8-8f3a-54d408ba0041.gif)

OS: macOS High Sierra
browser: Firefox nightly v61

and

OS: OSX El Capitan
browser: Chrome v64
slate version: 0.32.2

#### What's the expected behavior?
delete works correctly

**Comment by 21-Hidetaka-Ko** [comment]
Same as me. This is a critical problem.

**Comment by bengotow** [comment]
Hey—I'm also seeing this problem with Mailspring and diatric marks. If you type `´`and then `i` back to back, sometimes (maybe based on speed?) you become unable to backspace or use the arrow keys to move the cursor /until/ you type another diatric and complete it with a vowel.

**Comment by bengotow** [comment]
I'm investigating this a bit further and I've found an interesting way to reproduce the issue. Open the Chrome inspector and put breakpoints in `slate-react/lib/plugins/before.js` at the top of `onCompositionStart` and `onCompositionEnd`. If you type a diatric it'll pause at the start breakpoint. Use the arrow at the top center of the viewport (`>`) to continue without removing focus from the web view, and when you complete the diatric by typing "e" it completes without `onCompositionEnd` ever firing.

Seems like maybe either React or something in Slate is getting confused and not matching these events 1:1?

**Comment by bengotow** [comment]
Ok... so this is an interesting one. For me, this bug is only reproducible when the editor has complex plugins - specifically, plugins that implement `onChange()` and make modifications after you type the diatric character. When they're present, the cursor sometimes jumps from after the diatric to before the diatric, and that appears to prevent the browser from ever firing `compositionend`. In my case, I had a plugin that performs some custom spellcheck, and it's onChange looked something like this:

```
function onChange(change, editor) {
  const next = //compute decorations for spellcheck

  change
    .setOperationFlag('save', false)
    .setValue({ decorations: next })
    .setOperationFlag('save', true);
}
```

When I remove this plugin, everything works fine.

As a stopgap solution, I added a check for `editor.state.isComposing`, the internal flag set by `slate-react` when composing is in progress (in those two functions in my prev. comment). If anyone could weigh in on why this is happening and what a better solution might be, that'd be great!

**Comment by 21-Hidetaka-Ko** [comment]
We can't launch by you fix this issues. Could you solve this if you can ?
