### ISSUE TITLE
Issues in IE 11

### ISSUE THREAD

**Issue by ikorgik** [ianstormtaylor/slate#1757]
Hi, we found several issues in IE 11 during slate integration:

```
Objects are not valid as a React child (found: object with keys {size, _origin, _capacity, _level, _root, _tail, ownerID, hash, __altered}). If you meant to render a collection of children, use an array instead. in span (at text.js:130)
```

```
Unable to get property 'childNodes' of undefined or null reference
```

```
Objects are not valid as a React child (found: List [ [object Object] ]). If you meant to render a collection of children, use an array instead.
```
Attached a pull request with changes that work well to me: 
https://github.com/ianstormtaylor/slate/pull/1756

**Comment by Slapbox** [comment]
I can't even load http://slatejs.org/ in IE11.

**Error:**
```
SCRIPT5009: 'Symbol' is undefined
File: main-01e8c59ea6c6fde8ea58.js, Line: 6, Column: 81245
```

**Comment by renchap** [comment]
This is because the official website is not transpiled for IE11 compat nor includes the needed polyfills (like Symbol)

**Comment by sethmcleod** [comment]
On a related note, I just opened a PR for adding the polyfills needed to support IE11 on the example site: https://github.com/ianstormtaylor/slate/pull/1782

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
