### ISSUE TITLE
undo/redo state change does not trigger an editor rerender

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#176]
Noticed this while testing undo/redo support. The [rich-text example](http://slatejs.org/#/rich-text?_k=dt4ops) shows this issue. Make some text bold, then undo. The text will still be bold.

Cmd-z and Cmd-Shift-z do correctly call `onChange` with modified state, but the editor does not show the change. Interestingly, since the `onChange` method was called the mark and block buttons change to show the new state. If you make another change to the state (add text or more marks) then the editor updates with the undo, albeit with some selection offset issues.

**Comment by ianstormtaylor** [comment]
Good catch, thanks man. Combination of problems related to the recent performance increases for plain inserting text:

- The "native" flag that prevents React re-rendering needed to be always set to `false` on undo.
- The "native" flag should account for the new "cursor marks".
- The leaf nodes should always remount when rerendering, to account for us bypassing React's internal DOM tree for "native" updates.

Fixed in `0.7.3`!
