### ISSUE TITLE
optimize `Node` methods

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#180]
**If anyone wants to help, these are great, self-contained places to start!**

A big area of performance low-hanging fruit is that many of the `Node` methods are not very optimized (I've been focused on getting the logic right, and worrying about optimization later). When working with large documents this is very often what slows things down.

Examples:
- [ ] Many methods do `assertDescendant()` at the beginning to ensure that the node in question exists, which traverses the whole tree. They might be able to be rewritten to throw only after not finding the child.
- [ ] New methods `getFirstText()`and `getLastText()` would save cycles instead of currently using `getTexts().first()` or `getTexts().last()` in lots of places, because they will avoid traversing the whole document tree.
- [ ] Many places use immutable objects for a series of updates, when using `asMutable()` and then `asImmutable()` might result in quicker operations.
- [ ] Many places use `mapDescendants` when they really could be aborting much sooner after having found the node in question.

Some of the hottest code paths to optimize first are:
- `getTexts`
- `getBlocks`
- `getDescendant`
- `getParent`
- `getClosest`
- `updateDescendant`
- `removeDescendant`
- `mapDescendants`

As I find more I'll add them to this list. 

_Note: some of these might be tricky, because we're currently memoizing return values on immutable retrieval methods, which means that the second `getText()` call might be faster than two methods that have different traversal logic._

**Comment by Soreine** [comment]
I believe having a way to measure the execution time of those functions is key to solve performance problems:

1. Measuring actually shows which operations are slow and need work first.
2. Measuring allows to validate a performance improvement after optimizing.
3. Measuring helps preventing regression when optimizing other parts (thinking of memoizing benefits).

Now on how satisfy each point:

1. Profiling would be the best way to make educated guess about performance bottlenecks (which part needs to be optimized in priority). But it's hard to do and not easily reproducible. Alternatively, simply measuring common operations or functions could highlight the most obvious places of interest.
2. Adding performance scripts to measure the execution time, on average, of common operations or functions, would allow to compare two implementations.
3. Adding performance tests (requirements on average execution time) could do the trick. But it's hard to do since it's hardware dependent.

Now on how necessary they are:

1. This could be necessary, depending on how confident you are on your analysis @ianstormtaylor. 
2. One could argue that we don't need that to improve performances, since most of the time it is obvious that reducing the computational complexity reduces the computation time. I accept that, but I think it would still be cool to have, I'm open to suggestion to implement this, and I can bootstrap a PR for that.
3. This is not critical to have.

**Comment by Soreine** [comment]
> Some of the hottest code paths to optimize first are:
> [...]

Do you mean each of these function could be re-implemented more efficiently ? Or that we could optimize the code to reduce their use ?

**Comment by ianstormtaylor** [comment]
Lots of these were solved by @Soreine in `0.15`. There are very likely still places to optimize, so if anyone is digging into performance feel free to open specific issues for specific places that could be optimized. I'm going to close this one now since it's fairly generic and less actionable
