### ISSUE TITLE
Calling preventDefault inside onKeyDown  doesn't stop `Enter`, `Backspace`

### ISSUE THREAD

**Issue by gaoxiaoliangz** [ianstormtaylor/slate#1822]
#### What's the current behavior?

I defined onKeyDown as follows

```
onKeyDown = (event, change) => {
    event.preventDefault()
}
```
I press keys, and I cannot input chars like: 'a', 'b', etc, but 'Enter', 'Backspace' still take effect.

#### What's the expected behavior?

 'Enter' or 'Backspace' should not take effect when `preventDefault` is called.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
