### ISSUE TITLE
[bug]Add Chinese text after the element

### ISSUE THREAD

**Issue by HereSinceres** [ianstormtaylor/slate#1829]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
slate v: 0.33.5
slate-react v:0.12.5
 
![1](https://user-images.githubusercontent.com/11225986/39793147-c0be4438-5376-11e8-850f-2e521340640a.gif)

#### What's the expected behavior?
slate-react v:0.12.4 is correct

**Comment by WDFS** [comment]
I found a same bug when i type korean with slate.

**Comment by yunwuxin** [comment]
@WDFS me too

**Comment by yunwuxin** [comment]
@kommen @justinweiss @rgrove

**Comment by qingxiangchayun** [comment]
+1

**Comment by WDFS** [comment]
I solved this problem using very awkward solution. Right after the user adds mark while selection is collapsed, I made the editor to put one white space at the front of the selection anchor so that white space is marked as well. After that, if user does any action except typing korean, (like select other area or type english/special characters or select other mark/block/inline tags etc...) my Editor deletes that pre-inserted white space. Doing so solves the weird behavior of editor appearing when user types korean.

**Comment by zhujinxuan** [comment]
The strange thing is: when we try to input Chinese with input method, the <a> tag disappears...

I am trying whether we shall prevent key when `event.key === null`

**Comment by yunwuxin** [comment]
@ianstormtaylor  any solutions?

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2368, if you think this is unrelated let me know and we can reconsider.
