### ISSUE TITLE
Allow multiple selections

### ISSUE THREAD

**Issue by jtadmor** [ianstormtaylor/slate#1844]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### Concept

There are some advanced use cases that are very difficult to develop without the potential for multiple selections.

These might include: 
- In a multi-column or tables setup, allow a user to select and style multiple cells / columns without grabbing all the text in between.
- Provide mutli-cursor / select-all functionality similar to some code editors, either to do some text replacement or to style all instances of a word, for example.

While these use cases are possible to accommodate right now by manually storing the psuedo-selection in `data` and calling changes on those ranges explicitly, it does not play well with the concept of plugins. If a developer writes a `bold` plugin with a hotkey or menu button, we don't want for the `select-all` plugin to need to know about it, or vice-versa.

In an ideal world, a developer for the `bold` plugin just needs to think about a hotkey bolding a selection, and the developer for the `select-all` plugin just needs to think about selecting the right ranges.

#### Downsides
This would be a pretty dramatic change to the data model, and would certainly create more code complexity and potentially some performance issues because we'd need to check if `selection` is a list or not (or always store it as a list, in which case we are constantly creating and iterating over lists, presumably a perf hit as well).

**Comment by ianstormtaylor** [comment]
I'm open to the idea, and people discussing if they can find a nice way to implement it. I think the biggest hurdle though will be that browsers don't have a way to represent multiple selections natively though? (I think Firefox is the only one that does?)

**Comment by jtadmor** [comment]
I would imagine that in the short-run, it would be on developers to add decorations that mirror the various selections, although I suppose that wouldn't help for any multi-cursor rendering.

**Comment by ianstormtaylor** [comment]
I don't think this is possible while we have the constraint that Slate maps to the DOM's selection API, since browsers (other than Firefox?) don't support multiple selections. I'm going to close this out, but if someone finds a way feel free to open a new issue.

**Comment by jordanpapaleo** [comment]
It looks like Chrome, Firefox, and Edge all support range selections now.

**Comment by NikitaIT** [comment]
### This is quite a serious hurdle.

I wanted to implement `mark` to mark quiz answers in text. 

It is not possible to use the SelectionAPI for this. Because it is impossible to remove all unwanted effects on mobile.

Luckily, I know [one of the libraries](https://simonwep.github.io/selection/) that works well on mobile devices with a minimum of customization.

<img width="480" alt="image" src="https://github.com/ianstormtaylor/slate/assets/16810067/d75f7428-3cb9-4cda-98db-2da88c68418a">

I wrapped all the words in `Range` using the decorate callback

```ts
const range: Range = {
        anchor: { path, offset: start },
        focus: { path, offset: end },
        token: true,
        meta: {
          path,
          start,
          end,
          selected: selected.has([start, end, path].flat().join("-")),
        },
};
```

But firstly, this is not a very cheap rerender.

And I found that I don't know how to apply `Transforms.wrapNodes` to multiple ranges in one "transaction":
```ts
...map(([start, end, path]) => Transforms.wrapNodes(editor, block, {
      at: {
        anchor: { path: path.map(Number).slice(0, -2), offset: +start },
        focus: { path: path.map(Number).slice(0, -2), offset: +end },
      } as Range,
      split: true,
      voids: true,
    }));
```

`Offset` obviously changes right after the previous call.

2 pre-saved offests:

<img width="165" alt="image" src="https://github.com/ianstormtaylor/slate/assets/16810067/db5a6fdb-0aa2-4ec0-ad28-ceb8a3ce324f">

after non-transactional `map(wrapNodes)` wrap:

<img width="178" alt="image" src="https://github.com/ianstormtaylor/slate/assets/16810067/b0527136-feb3-4ef2-a708-929c3d01fc80">

after transactional (one by one) wrap:

<img width="220" alt="image" src="https://github.com/ianstormtaylor/slate/assets/16810067/49c6d342-59ec-4d52-baac-9c64cac4e979">
