### ISSUE TITLE
Maintain cursor position based on remote change

### ISSUE THREAD

**Issue by bigfish24** [ianstormtaylor/slate#1873]
I have a working implementation collaboratively syncing Slate editors, however, I cannot figure out how to handle integrating an external change while maintaining the user's current cursor position. Any thoughts on how to approach this?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
