### ISSUE TITLE
el.closest not supported in IE11

### ISSUE THREAD

**Issue by jschen5** [ianstormtaylor/slate#1882]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
`el.closest` is called from `Content.isInEditor` (among a number of places). It seems like this method is not supported in IE11, and it throws an error.

#### What's the expected behavior?
The error should not occur. One possible solution (based on [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)) is just to polyfill the method.

**Comment by Dtphelan1** [comment]
N.B. that `NodeList.forEach` is not supported in IE11. This function gets used in the `cloneFragment` method used in copying and pasting.

**Comment by ianstormtaylor** [comment]
Hey folks, please bring your own polyfill for older browser support—like [polyfill.io](https://polyfill.io/v2/docs/features/).

**Comment by Dtphelan1** [comment]
Again, worth noting here that this isn't a legacy browser issue. IE11 is the most recent version of Internet Explorer. If Slate doesn't plan on supporting IE, that's fine but that should be reflected in the FAQ https://docs.slatejs.org/general/faq#what-browsers-and-devices-does-slate-support

**Comment by ianstormtaylor** [comment]
Feel free to submit a pull request mentioning that older browsers will need to use polyfills for things like `el.closest`. 

I realize that IE is the latest Internet Explorer, but seeing as it's superseded by Edge, and doesn't have tons of the functionality that is considered baseline these days, it's not something that we're going to support without polyfills. Otherwise every single library starts re-bundling the same polyfills over and over and everyone else suffers from bloat.

**Comment by Opty1712** [comment]
Two poly for IE11

`/**
 * closest
 */
(function () {
  if (!Element.prototype.closest) {
    Element.prototype.closest = function (css) {
      var node = this;

      while (node) {
        if (node.matches(css)) return node;
        else node = node.parentElement;
      }

      return null;
    };
  }
})();

/**
 * matches
 */
(function () {
  if (!Element.prototype.matches) {
    Element.prototype.matches =
      Element.prototype.matchesSelector ||
      Element.prototype.webkitMatchesSelector ||
      Element.prototype.mozMatchesSelector ||
      Element.prototype.msMatchesSelector;
  }
})();
`
