### ISSUE TITLE
Comparison of slate vs rest when considering webcomponents use

### ISSUE THREAD

**Issue by AndreasGalster** [ianstormtaylor/slate#1894]
Hi, I've been looking at some editors to use with a webcomponents app (shadow DOM) and I think majority of them don't support shadow DOM yet.

I see that this project started initially when you tried other editors. I am wondering if you can suggest if this or any other library is a good fit for webcomponents (editor within a shadow DOM) usage?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
