### ISSUE TITLE
Nested List on Paste HTML Example not working

### ISSUE THREAD

**Issue by zoebfilvo** [ianstormtaylor/slate#1911]
It's a bug or incomplete functionality

#### What's the current behavior?

on Paste of nested UL, OL it completely removes the nested list and renders only the top list text

#### What's the expected behavior?

It should render the nested list exactly.

```
<ul>
  <li>
    Text Content
    <ul>
      <li>Nested Text Content</li>
    </ul>
  </li>
</ul>
```
Above is the example of the HTML which doesn't work... However if I use this html:
```
<ul>
  <li>
    <p>Text Content</p>
    <ul>
      <li><p>Nested Text Content</p></li>
    </ul>
  </li>
</ul>
```
Then it works.

Tried playing with deserializers of list block, but with no success.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
