### ISSUE TITLE
Pass selectionPosition Prop To Nodes

### ISSUE THREAD

**Issue by travigd** [ianstormtaylor/slate#1914]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
Currently, nodes get an `isSelected` prop which is `true` if and only if the selection resides within the node. It seems that the selection for inline nodes is considered within the node if the cursor falls within `[startOfNode, endOfNode)` (i.e. if the cursor is at the right edge of the node, the selection is considered to be at the start of the next node). This makes it impossible for nodes to know if the cursor lives at their right edge (short of always updating in `shouldComponentUpdate` and checking the current value of `editor.value.selection`, which is performance prohibitive for large documents).

#### What's the expected behavior?

Something like this was considered in #1125 (the proposal was making `isSelected` an enum of sorts).

I'd like to add a prop along the same lines named `selectionPosition` (or a different name) that takes on enum values to signify where the selection lies.

```typescript
const enum SelectionPosition {
  LeftEdge,
  RightEdge,
  Within, // includes when selection is expanded but start and/or end is at edge
  Outside, // or pass prop as null
}
```

This would leave the existing behavior of `isSelected` in place.

I'd be happy to create a pull request if you think that this sounds okay. It'd be a few extra lines of code around the [`render` and `renderNode` methods of `Content`](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L465), plus `PropTypes` for `Node`.

P.S. Seems like this would only actually be useful for inline nodes since the selection is still contained within a block node when the caret is at the right-most (assuming LTR) position.

**Comment by ianstormtaylor** [comment]
Is it really `[startOfNode, endOfNode)`? I wasn't aware of that. Might be a bug somewhere, or something else going on here.

**Comment by travigd** [comment]
See [this JSFiddle](https://jsfiddle.net/0x7th53y/). I actually notice (in Chrome on Ubuntu) that the cursor is still blue because Chrome considers the cursor to still be inside the span but slate considers the selection to be in the text after the inline.

It seems to me like sensible behavior. The alternative (as far as I see) would be to give two nodes the `isSelected: true` prop which doesn't really make a lot of sense if the selection is collapsed.

Also seems very much related to #1905.

**Comment by travigd** [comment]
Actually, in that example, it seems that the focus is (to abuse interval notation...)
```
[ text ]( inline )[ text ]
```
so that having the caret on either edge of the inline results in it being not selected (according to `isSelected` prop).

`an |inline in` results in `inline` not being selected, as does `an inline| in`.

**Comment by ianstormtaylor** [comment]
@travigd interesting, I think I follow you. What's your use case for this? Just curious.

How complex would it actually be to implement as `shouldNodeComponentUpdate`?

**Comment by isubasti** [comment]
@ianstormtaylor `isSelected` condition is on this line https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L465 which is `[start, end)`. should it be changed to `[start, end]`?

**Comment by travigd** [comment]
@isubasti No, not quite.
I'm not really sure why `getIndexes` is the way it is but it's meant to return `[startIndex, endIndex + 1]`. It also doesn't consider selection within a node, it just finds which child nodes are selected (of which there's only one if the caret is collapsed). It returns
```js
{
  start: /* index of first node that has selection */,
  end: /* index of last node that has selection + 1 */,
}
```
so the check on that line is essentially already doing `[start, end]`. Sorry if that didn't make sense. tl;dr it returns indexes with semantics like Python's list slicing: `my_list[start:end]` returns `[start, start + 1, ..., end - 1]`.

You can see in the [code for `getSelectionIndexes`](https://github.com/ianstormtaylor/slate/blob/cb3a9a5528c9c17b122d4182b09cc7dc1404ad67/packages/slate/src/models/node.js#L1508), every time it sets end it does `i + 1` (or `nodes.size` which is `indexOfLast + 1` because of zero based indexing).

**Comment by ianstormtaylor** [comment]
Thanks for mocking up the idea in #1918 @travigd! I definitely want to help make this use case easier to solve. That said, I'm feeling some unease with this...

I think it might be something that is better exposed as a method (or set of methods) on the `Range` object, since it feels like trying to distill it to a single enum is going to be hard and only cater to some use cases.

I often try to base things off of equivalent native DOM methods, since I figure the browser vendors have needed to solve issues like these. For context, here are a bunch that might or might not be related:

- [`Selection.containsNode(node, partial)`](https://developer.mozilla.org/en-US/docs/Web/API/Selection/containsNode)
- [`Range.compareBoundaryPoints(how, range)`](https://developer.mozilla.org/en-US/docs/Web/API/Range/compareBoundaryPoints)
- [`Range.comparePoint(node, offset)`](https://developer.mozilla.org/en-US/docs/Web/API/Range/comparePoint)
- [`Range.intersectsNode(node)`](https://developer.mozilla.org/en-US/docs/Web/API/Range/intersectsNode)
- [`Range.isPointInRange(node, offset)`](https://developer.mozilla.org/en-US/docs/Web/API/Range/isPointInRange)

Not that one of these necessarily solves this issue exactly, but I wonder if there are a set of methods we could devise that are similar to these that would solve this issue, and other issues like it that people using Slate might have. Any ideas?

**Comment by ianstormtaylor** [comment]
This is still not possible as mentioned. But in the newest version of Slate you can use the `useSlate` hook to re-render whenever the editor changes. If used only inside rare inline elements I think it would be alright performance wise. I think that's the best we're going to do on this front, so closing this out.
