### ISSUE TITLE
On spell-check and Re-rendering

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1934]
There are issues about spell check cannot currectly occur in slate editor, while can in draft-js.  I investigate the draft-js code and find that they use the default browser input event and do not re-render if the browser input event can well handle the consistency between the slate-core and dom.

The pseudo-code of the fix looks like that:
```javascript
onBeforeInput(event) {
   const prevValue = change.value;
   change.insertText(event.target.data);
   if (IsBrowserDefaultHandle(prevValue, change.value)) return;
   
}

onInput(event) {
  // Handle the text by beforeInput
  if (change.startText.text === event.target.data) {
     return;
  }
  // Handle the text by spell correction
}

Text.shouldComponentUpdate(prevProps) {

  if (!prevProps.text.equals(text)) {
     // Do not re-render if onInput has currectly insert the characters
     if (text.text !== dom.textContent) return true
  }
}
```

I am thinking about using a plugin and a plug-able interface to fix the problem as the first step.  Because
1. Directly fixing spell-check within the slate-react is a bit too complex, includes hacking onBackspace, onInput, onChange, onBeforeInput and potentially onSelection.  I would like to start with a basic fix in the usual scenario and resolve corner cases one by one. This development is good to start in a seperate plugin packages without causing conflicts with other PRs.  
2. I would like to use snapshot test to ensure the fix, while the slate's common test styles do not support snapshot tests.
3. The plug-able interface will provides more flexibility to users.
4. The plugable interface can de-couple and simplify some logic in the slate-react.
5. Most importantly, it makes slate more pluggable.

The PR will provides an interface like the following
1. provides `preventTextComponentUpdate(reason, prevProps, nextProps)` interface.  The interface will be alike:
```javascript
Text.shouldComponentUpdate(prevProps) {
  if (!prevProps.decorations.equals(decorations)) {
     if (!Stack.find("preventTextComponentUpdate", "decorations", prevProps, this.props)) {
          return true;
     }
  }
//.....
  if (!prevProps.text.equals(text)) {
     if (!Stack.find("preventTextComponentUpdate", "text", prevProps, this.props)) {
          return true;
     }
  }

}
```

This interface will prevent re-render only with special reasons, and therefore we do not need to worry users may shoot their own feet.

The PR interface provides users a method to control re-rendering in necessary cases.

**Comment by zhujinxuan** [comment]
Spell check problem:
https://github.com/ianstormtaylor/slate/issues/1598

Input method problem:
https://github.com/ianstormtaylor/slate/issues/1879

**Comment by ianstormtaylor** [comment]
Hey @zhujinxuan, thanks for bringing this up. We actually used to do something very similar to Draft.js in terms of handling Sobel check and simple inserts. We had a property called `value.isNative` (actually `state.isNative`) that would abort rerendering if the browser could handle it instead. 

It works well for Draft.js because their editor is much more restricted in what you can do. 

But in Slate is caused issues because it means that there is this hard coded logic in core that prevents re-rendering, and often will prevent you from rendering more complex behaviors/interactions. 

That’s why we removed it a while ago. 

But there’s a chance we did this without investigating further to find a way to make it coexist with the more complex use cases that Slate allows. So research is welcome!

On the other hand, are there not other ways to solve the spell check without aborting the re-render?

**Comment by zhujinxuan** [comment]
@ianstormtaylor I will have a try that whether the spell check can be fixed by allowing onBeforeInput and onInput events without aborting the re-render.  If that method works, then we can fix it without re-render interface.

**Comment by zhujinxuan** [comment]
Close in favor of https://github.com/ianstormtaylor/slate/issues/2051
