### ISSUE TITLE
Normalise falsely surrounds non void inline nodes

### ISSUE THREAD

**Issue by RXminuS** [ianstormtaylor/slate#1948]
I'm not sure if it's a bug, but the behaviour seems to deviate from the docs. In the docs it's suggested that only inlines that have `isVoid` must be surrounded by empty text nodes, but this normalisation function surrounds all inline nodes by text nodes.

https://github.com/ianstormtaylor/slate/blob/37418643e2430058203f88d460cf55bded9a5747/packages/slate/src/constants/core-schema-rules.js#L142

I can either make a PR to fix the issue by a simple 

```js
if (child.object !== 'inline' || !child.isVoid) return list;
```
or change the docs to clarify that every inline node needs to be surrounded by text nodes.

The reason this is important is that I wrote a performance critical "serialize" function that is supposed to output a perfect tree to avoid unnecessary normalisation, and this added a full 3 seconds to the loading time.

**Comment by ianstormtaylor** [comment]
Ah yeah, all inlines are surrounded by text nodes I guess.

**Comment by adamlibusa** [comment]
> Ah yeah, all inlines are surrounded by text nodes I guess.

Why is this a thing? Is it a deliberate design decision or is it simply a consequence of the implementation?

**Comment by yonahforst** [comment]
@ianstormtaylor - I'm also curious if this is necessary for all inlines, or just void ones 😄

I have a large document with several hundred `block` nodes which I would like to convert to `inline`. All the insertions of empty text nodes causes the browser to hang.

I'm happy to submit a PR implementing what @RXminuS suggested above

**Comment by yonahforst** [comment]
I'm struggling a bit trying to apply this rule to only void inlines. Here's the schema:
https://github.com/ianstormtaylor/slate/blob/cf46e9d3d4fddae8b86fe7ae7a097d07b2baf306/packages/slate/src/plugins/core.js#L130-L155

What I can't figure out is how to tell the schema to match only when the `inline` is void.
If I add `isVoid` to the rule like so:
```js
 { 
   isVoid: true,
   match: { object: 'inline' }, 
   first: [{ object: 'block' }, { object: 'text' }], 
   ...
}
```
that seems to tell the schema that the `inline` nodes must be void, otherwise they are invalid (instead of saying `inline` nodes that are void must match the following rules)

I also tried checking inside the `normalize` function if it's void and returning early, but it looks like the unless an operation is added to the editor, the default normalizer will run and the node will be removed.

So, I'm stuck 😅. I don't want to double my node count by adding a bunch of empty text nodes, but i also don't want to add the same number of `setSelection` commands just to get the rule to pass...

Any ideas? 🙏🏽

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
