### ISSUE TITLE
Access to the editor's current selection inside a schema or normalize function

### ISSUE THREAD

**Issue by thallada** [ianstormtaylor/slate#1960]
I asked in the Slack, and it seemed like others also thought it would be useful to have access to the editor's current selection in the schema or normalize function.

The specific use case that I need this for is to be able to write a schema to remove all Inlines of type "link" that have an empty `href` data value and are not currently selected in the Editor (the user is probably still editing the link if it is selected).

**Comment by ianstormtaylor** [comment]
Hey @thallada, this has been asked before, but the issue is that the normalization of nodes is memoized for performance. We need to be able to validate a node without external information in a deterministic way. If people are allowed to take the `value` or `selection` into account this contract is broken unfortunately.
