### ISSUE TITLE
Clicking on a zero-width node and dragging does not select text

### ISSUE THREAD

**Issue by thallada** [ianstormtaylor/slate#1969]
#### What's the current behavior?

Clicking on an empty paragraph or next to a inline link (both have `data-slate-zero-width` nodes) and then dragging to select text only moves the cursor and does not select text.

![slate_bug](https://user-images.githubusercontent.com/1505923/42695277-db8bb036-8682-11e8-8e00-490369436375.gif)

#### What's the expected behavior?

I should be able to click and drag anywhere on the document to select text.

**Comment by willbryk720** [comment]
I have the same problem with the cursor. Sometimes it just doesn't highlight. It happens randomly about every 1 in 4 attempts to highlight. For me, it's not just inline nodes, it happens anywhere. It more often happens when I start highlighting from within an already highlighted section. So if I place my cursor inside a highlighted portion and try to highlight, it will not highlight.

![strangecursor](https://user-images.githubusercontent.com/16409551/43867306-c95deab4-9b36-11e8-89df-e6ddf6b34306.gif)

**Comment by zhujinxuan** [comment]
Is this problem reproducible right now?  It seems I cannot reproduce it in current demo.

**Comment by willbryk720** [comment]
Interestingly, after investigating the problem more deeply, it seems the cause of my problem was completely different from @thallada. 

I wrap my editor so that I can access its value from a parent component. The onChange function passed to the editor called a function that passed the editor value to the parent component. Every time the editor changed, it passed it to the parent component. I tested out the same editor without any passing to parent function, and the editor stopped having this problem. This bad cursor behavior then must be due to the parent component re-rendering so often.

For anyone who has a similar problem, instead of passing the value to the parent on every onChange, you can just pass the value to the parent only when you need it.

**Comment by ianstormtaylor** [comment]
@willbryk720 thank you! That is actually super helpful to figuring out the original issue too.

I think it might be the case that the original issue is caused by re-rendering too, where clicking a zero-width space happens to result in `updateSelection` being triggered, cancelling the draggability. Which means we might be able to solve it without needing to listen to `mousemove` events? cc @zhujinxuan

**Comment by zhujinxuan** [comment]
@ianstormtaylor I think the re-rendering is perhaps the reason.  We shall not have the re-rendering just after selection change.  

I will have a try whether udpateSelection in onChange and change `updateSelection` works

**Comment by zhujinxuan** [comment]
I am not sure about this part: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/node.js#L105

Why the node is always re-rendered if `isSelect` is true.

**Comment by ianstormtaylor** [comment]
@zhujinxuan it might not be specifically the re-rendering, but actually the call to `updateSelection` which changes the native DOM selection that causes the drag to fail. So I don't think we need to prevent re-rendering, but maybe use `updateSelection` less when we don't need to? Not sure.

**Comment by zhujinxuan** [comment]
@ianstormtaylor I think you are right.  I commented out the updateSelection and then the problem does not happen.

I will have a look at updateSelection

**Comment by steobrien** [comment]
I can no longer reproduce this at https://www.slatejs.org/#/links, @thallada, and think it might be fixed. Would you mind confirming?

**Comment by zhujinxuan** [comment]
@steobrien It is still producible.  You need to have a blank paragraph and move cursor around beginnings of paragraphs....

The strange thing is that it is somehow reproducible by chance; I have reproduce it by a chance about 1/3.  I am still unsure about the reason of why it happens.

**Comment by knubie** [comment]
Seems like this was fixed at some point, but the bug is back in 5.x and reproducible on all of the demos.
