### ISSUE TITLE
shouldNodeComponentUpdate is never called when defined

### ISSUE THREAD

**Issue by mvanlonden** [ianstormtaylor/slate#2005]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
When defining the static method `shouldNodeComponentUpdate` in a custom node - it is never called.

[Fiddle](https://jsfiddle.net/fj9dvhom/1546/)

macOS, chrome
"slate": "^0.34.2",
"slate-react": "^0.12.11"

#### What's the expected behavior?
Expect the static method to be called when defined.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
