### ISSUE TITLE
Plugin / Export transformations

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#209]
This issue is mostly a question about plugin conventions. I'm working on a few plugins for lists, tables and code edition.
And for example the `slate-edit-table` should provides some transformations (`insertRow`, `insertColumn`, etc).

I'm wondering that could be the best API for this:
1. Export these transformation as `transform(state: State) : State` from the module
2. Plugin extends the `Transform` class

-----

### 1. Plugin module exports these method

**Good:** avoid extending an internal object
**Bad**: we have to pass all options to all calls

```js
import EditTable from 'slate-edit-table'

const opts = { typeTable: 'table', typeRow: 'table-tr', typeCell: 'table-cell' }

const plugins = [
  EditTable(opts)
]

// Later in code:

this.onChange(
    EditTable.insertRow(this.state.state, opts)
);
```

### 2. Plugin extends the `Transform`

**Good:** same API for core transformation and plugin transformations
**Bad**: we have to extend an internal object (Slate can provides an API for plugin to do so?)

```js
import EditTable from 'slate-edit-table'

const plugins = [
  EditTable({ typeTable: 'table', typeRow: 'table-tr', typeCell: 'table-cell' })
]

// Later in code:

this.onChange(
    this.state.state
         .transform()
         .insertRow()
         .apply()
);
```

----

**Personal opinion:** I prefer the second method.

**Comment by ianstormtaylor** [comment]
Good question! I think the second method isn't something I'd recommend, at least not yet, because it gets a bit hacky with extending the transform object. But I do like the idea of providing an API for transforms, I'll open another issue for that.

In the meantime, I'd probably do something similar to the first method, but instead of taking a `state` and returning a `state`, I'd have it take a `transform`. So that you'd do things like:

```js
let transform = state
  .transform()
  .insertText('some text')

transform = EditTable.insertRow(transform)

return transform
  .insertFragment(someFragment)
  .apply()
```

Still not as nice as chaining only, but it allows you to use it the same way other transforms are used, and be part of a single `apply()` transaction.

**Comment by SamyPesse** [comment]
Yes, I'll start with this API, and change it if Slate moves to an another one.

It's clear that if Slates grows an ecosystem of plugins, it will require a API convention for plugins to expose transformations.

-- 

Since you'll open another PR, I'm closing this one.
