### ISSUE TITLE
A schema rule could not be normalized after sufficient iterations

### ISSUE THREAD

**Issue by sourcesoft** [ianstormtaylor/slate#2118]
#### What's the current behavior?

I faced a weird issue today using the latest version 0.40.0 and `slate-html-serializer` and using a simple bold deserializer rule. It only happens when getting initial value not when pasting or editing which means it occurs in deserialize rule of html-deserializer.

The problem is quite challenging. It only happens when html I have more than 5 `<strong>` (or any other marks) html tags sent as a initial value to html-serializer package which throws [this error](https://github.com/ianstormtaylor/slate/blob/4dcbe1918a30c25624ed813c9e8ff3667b5a5794/packages/slate/src/changes/with-schema.js#L184).

Reproducing the issue was easy, instead of uploading to fiddle, I forked the repo and modified one of Slate tests adding extra `<strong>e</strong>`s [here](https://github.com/ianstormtaylor/slate/compare/master...sourcesoft:bug-report-1). Run the tests and see the same error.

Error:
```
Error: A schema rule could not be normalized after sufficient iterations. This is usually due to a `rule.normalize` or `plugin.normalizeNode` function of a schema being incorrectly written, causing an infinite loop.
    at iterate (node_modules/slate/lib/slate.es.js:14838:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
    at iterate (node_modules/slate/lib/slate.es.js:14842:0)
```

repo: https://github.com/sourcesoft/slate/tree/bug-report-1

#### What's the expected behavior?

Deserialize without errors.

**Comment by sourcesoft** [comment]
Could it be related to [this refactor](https://github.com/ianstormtaylor/slate/pull/1993)? I don't remember having this issue before July. I updated Slate few weeks ago and I accidentally saw this in one pages.

**Comment by sourcesoft** [comment]
**ADDITIONAL NOTE**: The error happens when I have more than 5 `strong` tags in a single `p`.

For example if I had 15 `strong` or `em` tags in my html spread inside 4 `p` tags (each have less than 5 nested children of `strong` or `em`) it's going to be okay.

**Comment by ianstormtaylor** [comment]
Hey @sourcesoft, thanks for reporting this. I figured out, this was caused by the maximum iteration count logic being too low. When a parent has invalid children, it will iterate fixing each child one at a time. But the maximum iterations wasn't considering the number of children, so nodes with many children would exceed the max, even though the normalization was working as intended.

I've put a fix in the latest release, and maybe in the future we can figure out a more bulletproof way to calculate the max.

**Comment by yashk-coursera** [comment]
hey @ianstormtaylor, thanks for the fix! Would it be possible to publish this as part of `0.37.8`? We're using `0.37.7` in production and seeing this issue come up frequently, and the patch worked correctly in my dev environment. 

I figure upgrading to the latest slate version just for this fix would be a big effort and if there's a patch I could do in the short-term, that would be awesome!

(I've tried creating a fork and patching in the fix but there's many other dependencies errors due to different slate versions in the dependencies)
