### ISSUE TITLE
Decorations over inline boundaries highlights entire inline

### ISSUE THREAD

**Issue by RXminuS** [ianstormtaylor/slate#2138]
## Current Behaviour
When you set a decoration whose start point and end-point exist in different inlines it selects the whole block of text.

![image](https://user-images.githubusercontent.com/3949285/44840799-28f89980-ac42-11e8-956f-793f4c738e39.png)

What is being rendered is a 

```jsx
<Text key=0>
    This Intercompany Services (“
</Text>
<Inline key=1>
    Agreement
</Inline>
<Text key=2>
     ") effective
</Text>
```

where the decoration is

```json
{
   "start": {
      "key": 1,
      "offset": 1
   },
   "end": {
      "key": 2,
      "offset": 0
   }
}
```
## Expected Behaviour
Just like if the search highlight was within a single "inline" you would expect only the actual text within the range to be selected.

I did manage to find where the problem is created. In this check...
https://github.com/ianstormtaylor/slate/blob/54611b7dd74ce2024fa4523f1fd9b8ac7638b26d/packages/slate/src/models/text.js#L255

The behaviour of splitting leaves is only done if the node contains both the start and the end. Instead we probably want to do some kind of check to see if the start is before this node (and mark everything from offset 0) or if the end lies beyond this node (and mark everything up to offset `text-length`), but still making sure that the end and start positions respectively are set based on the mark.

I'm on holidays so sadly didn't have time to do a full bug report yet (including JSFiddle) so if someone has the time to make one based on that description that would be amazing, otherwise I'll get to it after my trip.

**Comment by SmilinBrian** [comment]
We're running into what I think may be the same problem with Decoration rendering, and I am pretty sure that statement should be `if (hasStart || hasEnd)` (instead of `&&`).

The Decoration list that is passed to that `getLeaves` function has already filtered the list so that only "relevant" Decorations are given. The code inside the `if (hasStart && hasEnd)` looks like it already deals with the cases where start is from "before this" or end is "after this". If the condition fails (`hasEnd` is true, but `hasStart` is false), then the Decoration's Mark is applied to the entire text (`") effective` in your case).

I'll try to put together a bug report showing the issue we're running into.

Meanwhile, we're working around it by trying to avoid the case -- in your example, our work-around would be to set `end` to `key: 1, offset: 9` instead of the beginning of `key: 2`.

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
