### ISSUE TITLE
My cursor shift on SlateJS when I add a special mark on a part of my text

### ISSUE THREAD

**Issue by Hocoh** [ianstormtaylor/slate#2142]
I'm working with SlateJS, when I add some special on my text the result is that the cursor shifts and is not longer aligned with the place onwhich the text ouput. Then I don't understand why that flaw occurs. I wonder how to fix it.

[Here my sandbox.io snippet](https://codesandbox.io/s/7492zoz0pq)
 
Salutations

**Comment by lichenglu** [comment]
Experiencing the same issue now...

**Comment by lichenglu** [comment]
Here is a GIF from @Hocoh's sandbox:

![ss](http://g.recordit.co/DUx9CYaMoA.gif)

As you can see, the cursor is jumping around, and inserting texts does not go after the cursor

**Comment by ericedem** [comment]
The problem is that when the marks are getting rendered, they are adding a leading / trailing space to the display:

`<strong> {props.children} </strong>;`

should be

`<strong>{props.children}</strong>;`

The selection is based off anchors / offsets. So say you have `abcde`, you select `bcd`, then hit `ctl + b`. What happens is the selection is from offset 1 to offset 4, but because the bold has been rerendered as ` bcd `, you get `a bcd e`. The selection hasn't changed, so the editor thinks you are now selecting ` bc` which is from offset 1 to 4 still.

I'm inclined to think that this is expected behavior for marks and not a bug. What do you think?

**Comment by ianstormtaylor** [comment]
@ericedem great catch, you're absolutely right. This sounds like just a mistake in rendering to me.

**Comment by lichenglu** [comment]
@ericedem That totally makes sense! Thank you.

However, I am wondering what if user wants to append a prefix to `marks` or `inlines`? For my use case, the original text is like `hello world`, once user marks the text as `CodedText` (for qualitative research), then I will append a prefix to the original text like `[Code 1] hello world`. This use scenario will cause the issue right?

**Comment by ericedem** [comment]
@lichenglu You can always update the selection manually if you need to, though I don't think extending marks is a great way to go. Inlines (or maybe decorations) are probably more appropriate if you want to add extra structure to the existing text.
