### ISSUE TITLE
How to use onMouseDown and other Events

### ISSUE THREAD

**Issue by matt-erhart** [ianstormtaylor/slate#2188]
What's the best way to implements events such as onKeyDown, onKeyPress, onKeyUp, onMouseDown, onMouseMove, onMouseUp in slate? Currently, I'm using a container div and state to listen for and track these kinds of events. It works fine for me but would never work as a plugin, so I assume there must be a better way.

**Comment by ericedem** [comment]
@matt-erhart Good question. I'd recommend asking questions on the [slack channel](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md#asking-questions), you'll much faster responses there.

in the meantime, there are some docs on using event handlers with slate: https://docs.slatejs.org/walkthroughs/adding-event-handlers

And they are also available in plugins as well. https://docs.slatejs.org/slate-react/plugins#event-handler-properties

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by itsarnavsingh** [comment]
This is very inconvenient as it is really hard to search questions on slack.
