### ISSUE TITLE
[Q] How to approach autocompletion / schemas

### ISSUE THREAD

**Issue by wmertens** [ianstormtaylor/slate#221]
I am toying with the idea of using Slate for editing plain text with a schema. For the sake of example, a [crontab file](https://en.wikipedia.org/wiki/Cron#Format). Each line has a strict format but could use help within the line.

For example, if you are on the hour field in the line, it could show a placeholder with examples, and if you fill in something that's not valid, it could color it red with a message. For the command, it could show an autocomplete with examples and previous commands.

How would I go about using Slate for this? Is this a good/bad fit?

**Comment by ianstormtaylor** [comment]
Hard to say. I think if it's only ever going to be used for a crontab input, and it doesn't need collaborative editing or marking up the document with styles, then it might not be the best fit, since a simpler system of adjacent `<input>` elements might work better. But if it's more complex, it might be a fit. It would get complex to implement the schema logic though.

**Comment by ianstormtaylor** [comment]
(Sorry didn't mean to close.) Let me know if that makes sense!
