### ISSUE TITLE
Capability to disable console.log statements.

### ISSUE THREAD

**Issue by ctrlplusb** [ianstormtaylor/slate#222]
They are useful when debugging slate, but they get in the way when I attempt to debug other parts of my system.  Being able to toggle them would be great.

**Comment by ianstormtaylor** [comment]
Hey @ctrlplusb do you mean the `debug` calls? Right now they should be Local Storage based, so that if you have `debug="*"` set they will show up. You can disable all debug calls by removing the `debug` key, or you can disable Slate's only by doing something like `debug="*,-slate:*"` I believe. Let me know if that helps!

**Comment by ctrlplusb** [comment]
Aha, sorry I had no idea you were using the debug library. Should have checked. Thanks!

**Comment by ianstormtaylor** [comment]
No worries!
