### ISSUE TITLE
code-highlighting will add a new line when copy from the Slate and paste. 

### ISSUE THREAD

**Issue by solsos** [ianstormtaylor/slate#2228]
#### Do you want to request a _feature_ or report a _bug_?

 first step to copy the "log('Buzz');" from the Editor and then paste it back. It will add a new line to the code. 
![image](https://user-images.githubusercontent.com/17923026/46543006-d4be8600-c88d-11e8-85a0-a2dda3e3ad9d.png)

**Comment by SmilinBrian** [comment]
That example is just intended to show that code syntax highlighting is one of the kinds of things you can do with Slate, it's not intended to be a fully functional code editor.

The example could be fixed by adding an `onPaste` handler that just forces plaintext to be inserted (instead of the `code` - `code_line` - `text` Node structure that it Pastes by default).

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
