### ISSUE TITLE
Keydown does not work in plugins demo

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#2243]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

In the plugins demo (https://www.slatejs.org/#/plugins), cmd+z and enter do not show any response (while insert by onBeforeInput is working).

**Comment by ianstormtaylor** [comment]
Thanks for reporting @zhujinxuan! The issue is the the plugins themselves aren’t updated yet (working on this now). We should probably change that demo to not use external plugins but just define a few plugins in the file next to the editor instead so that it doesn’t have external dependencies to update.
