### ISSUE TITLE
start thinking about converting more logic to queries

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2249]
#### Do you want to request a _feature_ or report a _bug_?

Idea.

#### What's the current behavior?

Right now there are certain pieces of "core" that are less configurable, because there hasn't been an easy way to make them so—for example, copying/cutting fragments, inserting fragments, etc. There are also places where we've delegated to plugins without any standardization, meaning that plugins have to do more work—for example parsing HTML.

#### What's the expected behavior?

I think with the introduction of queries (and commands) we can start thinking slightly differently about what core `slate` or React-specific `slate-react` provides as hooks for plugins.

For example, imagine a `parseHtml` query that by default does nothing, but when overridden would make pasting HTML easier. It would allow core to be able to set a standard in terms of implementation, without forcing the actual logic/behaviors onto everyone's editor.

Similarly, there might be a `getFragment` query that returns a fragment from the active document, modifying it if need be. Or it could even be implemented as a command, not sure on that one.

Point being, I think there are probably more opportunities now to make some of these core behaviors easier to override for people. So if anyone has ideas, let us know!

**Comment by bryanph** [comment]
It might be nice to put some core behaviour in plugins so that it is clear that they are a logical entity that can be approached in a different way if the user needs to.

For example, this suggestion I made a while ago: https://github.com/ianstormtaylor/slate/issues/2075 is one particular way of dealing with a selection. In this approach, selection turns to a "block selection" once we move the selection to a block different from the anchor block. Besides that, there is the currently built-in selection approach which allows mixing inline selections and block selections.

So perhaps we could offer two plugins which each provides a different selection mechanism (names are bad, I know):

* **slate-selection-default**: allows mixing inline and block selections
* **slate-selection-block**: only alllows selecting either inlines or blocks

One of these has to be set to create a usable Slate instance but this way we can avoid importing a lot of dead code. As for commands, these plugins could perhaps implement some kind of interface that Slate requires for overriding selection behavours (this interface could for example require the plugin to implement a set of commands).

I hope that kind of makes sense.

**Comment by justinweiss** [comment]
As an example, table handling is one area where I'm really excited about queries and commands. Grid selection has to be 100% custom right now, and it would be nice to be able to have the table plugin override things like "Bold just these cells" or "Clear these cells (instead of deleting the nodes)" or "copy the contents and structure of this set of cells." It would be so nice if a table plugin could take charge of these queries (`getFragment`, or 'which blocks / texts are in the current range') when it detected a 2d selection, instead of having to have the main editor or other plugins delegate to it.

**Comment by ianstormtaylor** [comment]
Going to close as non-actionable, but you all get the idea!
