### ISSUE TITLE
Merging of changes: targeting a change

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#2255]
#### Do you want to request a _feature_ or report a _bug_?
discussion

#### So...?

I will try to explain the issue with an example I am currently dealing with: **uploading an image**

There are three states the editor can be in.

1. Before, without the image
2. Showing the image while it is uploading (including a progress bar)
3. After, with the image uploaded

In order to provide correct undo behaviour, we have to change the history stack between states 2 and 3.

**From state 1 to 2:** When entering state 2, the history stack should push an `insert_block` op so that whilst we are uploading, undo will abort uploading and give us state 1 again.

**From state 2 to 3:** When entering state 3, the history stack should be modified so that undo will result in state 1. To achieve that, ops must be merged into a previous change.

**Edge case 1:** between state 2 and 3, the user can perform other operations (like insert_text, etc.), hence merging in this case must occurs not at top level of the stack, but somewhere below. We must somehow target a given change (array of ops) and merge into that change, modifying the history accordingly.

#### Get to the point, you fool

My question is, how can we possibly achieve **edge case 1**? Namely, target a change that has happened in the past and merge new operations into that change so we get the desired history?

**Comment by ianstormtaylor** [comment]
This is something that I've wrestled with. The simplest solution I think I've come to, is to only have two states. And instead of inserting a "placeholder" block, don't actually insert anything until the image is fully uploaded and insertable. 

This can be communicated differently in the UI. Maybe with the upload indicator in the bottom corner or something. Or if you don't need interstitial editing, then in a modal.

One of the reasons for doing it this way is if you're doing collaborative editing, it's strange for a 2nd user to randomly see a big "placeholder" jump in without any content in it. Better to just only have the image show up once it's fully loaded. And then the history is a lot easier to manage.

**Comment by bryanph** [comment]
@ianstormtaylor hmm good point, I was overthinking it a bit I guess. :man_shrugging: 

Is there ever a case where you would want something like this?

**Comment by justinweiss** [comment]
Would it work if you used `replaceNodeByKey` to replace the placeholder node, without saving the `replaceNodeByKey` change to the undo stack? Then, the undo that would normally undo the placeholder image would undo the actual image insert, which is (I think) the behavior you want.

**Comment by isubasti** [comment]
I would do it differently. I will make the image component stateful and store the uploading state on the image component not on slate's state and once image is successfully uploaded then update the image block's data with the image's url.

**Comment by bryanph** [comment]
@justinweiss the problem is that if you do this the history is inconsistent. It works for undoing, but not when you then try to redo the change again.

@isubasti but in this case you have something in your editor that slate is unaware of, which I thought slate didn't support (although there is this Island component suggestion by @ianstormtaylor https://github.com/ianstormtaylor/slate/issues/2072)

**Comment by justinweiss** [comment]
@bryanph yep, you’re totally right — that wouldn’t work.

@ianstormtaylor if you are inserting an image, and there’s time between when the image is inserted and when it’s uploaded, wouldn’t you have a problem if the state of the editor changed between it being inserted and it finishing uploading? For example, what if you dragged an image into path `[3]`, and then removed the block at path `[2]`? I think you’d either need to block editing during upload (and I think that wouldn’t work in the collaborative case, because someone else could be changing the document), or you’d have to wait until the image is done before you could insert it, or your image uploader would need to know about all of the changes being made in the editor, so it could adjust its path accordingly.

**Comment by bryanph** [comment]
@justinweiss yes that is what I ended up doing, just blocking input whilst uploading. Honestly, in practice it doesn't really matter because usually uploading an image happens instantly. So what I end up doing is only rendering a placeholder when the uploading takes longer than 1s more or less.

For the collaborative case, what you are describing is basically the domain of OT. This is something I'm hoping to tackle at one point. Seems like it is quite the challenge though. The following OT visualizer is pretty helpful: https://operational-transformation.github.io/visualization.html. This is for text-only though, we have a different model with slate to keep consistent.

**Comment by isubasti** [comment]
@bryanph slate would still know parts of it if you use image placeholder but if you do any operation on the image such as cut/copy/drag then it will still be an empty image placeholder if that makes sense.

**Comment by bryanph** [comment]
Well I resolved this by implementing @ianstormtaylor's recommendation, so I'll just close this.
