### ISSUE TITLE
consider implementing "placeholders" as decorations

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2257]
#### Do you want to request a _feature_ or report a _bug_?

Idea.

#### What's the current behavior?

Right now we have the special `renderPlaceholder` logic, but it gets a bit opinionated about where to render the placeholders, and it's a bit more confusing to understand how it works because it adds yet another concept to the rendering logic.

#### What's the expected behavior?

I wonder if we could replace it purely with decorations instead. The default case would be a decoration applied to the document only when it has no text. And then maybe it can be styled with `::before` or `::after`? Or with `contenteditable="false"` children? Or with portals? Not exactly sure what will result in proper browser support.

**Comment by bryanph** [comment]
Perhaps we can define this in the schema and pass a prop in renderNode that indicates this node needs to be rendered as a placeholder and let the user be responsible for rendering the node as a placeholder?

**Comment by ianstormtaylor** [comment]
@bryanph I think it should remain a rendering-only concern though, and not be tied to the document structure though.

**Comment by ianstormtaylor** [comment]
@bryanph although maybe I’m misunderstanding! Perhaps if we had `renderNode` called on the `document` node then we’d already have the ability to do these things. Is that what you mean? That could be cool.

**Comment by bryanph** [comment]
@ianstormtaylor not really but that sounds like it might be better idea :smile: 

The `renderPlaceholder` does two things right?

* Determine if the block being rendered is considered "empty"
* Actually rendering the placeholder

So I thought maybe that first part can be done in the schema somehow or just in slate internally because a block being empty just means that 

1. it is a block
2. it has no children

right? and then we can just call renderNode with a isEmpty prop or something like that so that we can render a placeholder instead.
