### ISSUE TITLE
Ctrl+z with empty history causes crash

### ISSUE THREAD

**Issue by klis87** [ianstormtaylor/slate#2260]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
If there is no history, `undo` will throw `Cannot read property 'object' of undefined`
https://codesandbox.io/s/98qo5jwk2p

#### What's the expected behavior?
`undo` shouldn't crash when history is empty.

**Comment by Slapbox** [comment]
This remains an issue with Slate-React 0.19.3 and Slate 0.42.4

https://codesandbox.io/s/6wm7p6vmn

**Comment by Slapbox** [comment]
After a bit more investigating:


**Works** - This is what I had tested with:
```js
{
  "document": {
    "nodes": [
      {
        "object": "block",
        "type": "paragraph",
        "nodes": [
          {
            "object": "text",
            "leaves": [
              {
                "text":
                  ""
              }
            ]
          }
        ]
      }
    ]
  }
}
```


**Crashes:**
```js
{
  "document": {
    "nodes": [
      {
        "object": "block",
        "type": "paragraph",
        "nodes": []
      }
    ]
  }
}
```

----

My project uses the HTML serializer and the initial state I pass in is: `<p></p>`. The cause seems pretty clear here, blocks without text nodes, but what's the right way to remedy it @ianstormtaylor?

**Comment by Slapbox** [comment]
The root cause seems to be that undoing causes this schema normalization rule to be undone, resulting in a node without a text in it. https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/plugins/core.js#L104

**Comment by Slapbox** [comment]
Whoops... I updated the fiddle above but didn't mention that. Dumb. Here's the demo: https://codesandbox.io/s/6wm7p6vmn

I don't want to jump to hacky solutions either. I also don't want to change anything in history too dramatically if possible since I'm pretty close to a working solution.

-----

### The issue symptoms

The `undo` doesn't provoke an outright error, but it sets the focus and anchor to null due to no text node inside the paragraph. After that when you try to type, you've got no point to reference, and at that point every keystroke is an error: https://gist.github.com/Slapbox/566ff20583b3ea271565b6241d45dc92

![image](https://user-images.githubusercontent.com/6835891/47940929-9f27af80-dec2-11e8-9575-4aece8af1465.png)


### My take:

**Ideally the first undo batch in the stack as it currently exists wouldn't be there. It contains startup normalization operations and initial selection, things that I don't think we'd conceivably want to allow to be undone.**

I tried to hunt down where that first normalization takes place, but was spending way too much time on this task so I moved on. If it's possible in the current architecture, we can `withoutSaving` the initial normalization and avoid this.

**Comment by ianstormtaylor** [comment]
I think this might be fixed in `slate-react@0.21`, could someone check?

**Comment by ianstormtaylor** [comment]
It sounds like the real issue is that the selection isn't getting reset to the beginning of the document when removing the last node via `undo()`? It shouldn't be possible to leave the document in an invalid state as far as normalization goes. But the selection might need to also have this behavior applied.

**Comment by klis87** [comment]
@ianstormtaylor I just updated slate to `0.43.7` and slate-react to `0.20.8`, I cannot reproduce this error anymore so I am closing, thx for great update, all issues I had in `0.42` are gone :+1:
