### ISSUE TITLE
How to generate MD format?

### ISSUE THREAD

**Issue by markolofsen** [ianstormtaylor/slate#2276]
How to convert slate-content to markdown?

How I does it see:
1. Save content from slate to db (JSON?)
2. Load content for slate from db
3. Convert content to MD format (with Python) — << How?

**Comment by tomaratyn** [comment]
I think you will have to write your own converter. Iterate through the document tree (it's just JSON, parseable in Python) and convert blocks/marks into markdown. 

One of the core ideas of Slate is that there is no mandatory schema, so there is no standard converter.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by jbriales** [comment]
@ianstormtaylor maybe sharing a link to the relevant Slack channel would be useful here?
