### ISSUE TITLE
Right arrow key doesn't move the cursor through void nodes

### ISSUE THREAD

**Issue by alizeaiter** [ianstormtaylor/slate#2318]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
Pressing the right arrow key doesn't move the cursor through void nodes

https://jsfiddle.net/fj9dvhom/2547/

slate@0.42.4 and even 0.42.1
![rightarrowbug](https://user-images.githubusercontent.com/20495861/47474578-e2758480-d817-11e8-94f5-eb0ce1b1b4af.gif)

#### What's the expected behavior?
The right key should move the cursor the same way the left arrow does but reverted.

**Comment by Slapbox** [comment]
Works for me on my void image nodes, so it's not all void nodes, but it's definitely a real issue.

**Comment by alizeaiter** [comment]
@Slapbox, actually the problem only happens when the `onKeyDown` prop is used.

**Comment by ianstormtaylor** [comment]
@alizeaiter you need to call `next()` in the `onKeyDown` handler, otherwise the default behaviors won't fire. 

It's a bit confusing because some selection handling behaviors are browser-native (so they keep working) and some are handled by the plugins, although more will move to plugins over time I think.

**Comment by ianstormtaylor** [comment]
No worries, it's a bit confusing. Good luck! Also feel free to ask in the Slack channel if you have other questions, people tend to reply more quickly in there.
