### ISSUE TITLE
code-highlighting  example fix

### ISSUE THREAD

**Issue by An0nymous0** [ianstormtaylor/slate#2319]
1.https://www.slatejs.org/#/code-highlighting

2.Two carriage returns

![image](http://g.recordit.co/SWCGHLgb2k.gif)

**Comment by ericedem** [comment]
I think I found a bit of a better solution for this. As best I can tell, decorations themselves never get normalized. This is why we end up with `null` values on the points even though they should be getting normalized away.

There are two entry points for creating decorations `setDecorations()` and `decorateNode()`. The approach I'm thinking is that `Decoration` should have a normalization method that looks like:

```js
normalize(node) {
  return this.merge({
    anchor: this.anchor.normalize(node),
    focus: this.focus.normalize(node),
    mark: this.mark.normalize(node),
  })
}
```

And then we should normalize when we have access to a node. So in [`getDecorations()`](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/interfaces/element.js#L452), we normalize before they get used anywhere:

```js
return decorations.map(dec => dec.normalize(this))
```

We need to do it here, because `getDecorations()` gets called when the document is being rendered already, and we can't wait for a top level normalization. This seems to work pretty well locally but I havne't done extensive testing. I'm most worried about performance.

We also need to normalize at the top level in case someone passes decorations in directly through something like `setDecorations()`. I think this needs to happen in `Editor#normalize()` along with the document normalization, but still wrapping my head around how this would work. Probably needs to happen after the document finishes normalizing, and just another map to normalization like the example above.

@ianstormtaylor What do you think?

**Comment by tommoor** [comment]
This is by far the most common error coming out of our Slate editor… @ericedem still thinking of taking on this fix?

**Comment by ericedem** [comment]
@tommoor Ahh sorry, this one fell off my radar. This is the branch I was working out of [is here](https://github.com/ericedem/slate/tree/fix-code-highlighting-example) if you want to take a look at the code for your own PR. I haven't been working on Slate much recently but will probably be digging back in in the next few weeks and might be able to tackle this.

**Comment by thesunny** [comment]
Fixed it here https://github.com/ianstormtaylor/slate/pull/2698
