### ISSUE TITLE
set_selection operation doesn't report proper anchor when deleting/typing?

### ISSUE THREAD

**Issue by javascriptlove** [ianstormtaylor/slate#2320]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

There is something wrong with cursor/selection onChange. When we delete something from the input box with value "12345", it reports the `anchor` to be at position 5, while it should be position 4 already, because we just deleted 1 symbol. So

```
anchor:
  object: "point"
  offset: 5
```

Should be 

```
anchor:
  object: "point"
  offset: 4
```

![](https://javascriptlove.github.io/gifs/Oct-25-2018%2011-08-30.gif)

-----

Second issue is that when I'm typing something, the set_selection operation doesn't even fire, so my backend will think I'm still on position 5

![](https://javascriptlove.github.io/gifs/Oct-25-2018%2011-08-55.gif)

Standalone jsfiddle to test deleting/typing:

https://jsfiddle.net/javascriptlove/xc7mqyzg/39/

React 16, latest slate 0.42.4, slate-react 0.19.6, Chrome 69 on Mac OS X

#### What's the expected behavior?

Expected set_selection to run when typing, and expected anchor point to be properly reported when deleting. Is this working as designed?

**Comment by ianstormtaylor** [comment]
@javascriptlove the `set_selection` is only fired when the selection is changed from where it was based on re-selecting, not based on when the content changes and it happens to change the selection. To get a "true" selection you'd need to transform the current location by all of the operations, like `insert_text` and `remove_text` as well.

I think the only reason we're seeing `set_selection` at all in the first example is to set `marks:null`, but it should ideally not be setting any of the other properties, since they aren't changing from where they are. That's a separate issue though.

**Comment by javascriptlove** [comment]
Got it, thank you
