### ISSUE TITLE
MoveNodeByPath broken?

### ISSUE THREAD

**Issue by skogsmaskin** [ianstormtaylor/slate#2328]
#### Do you want to request a _feature_ or report a _bug_?
I was trying to add some tests for the ``by-path`` commands, and tried adding a simple test for just switching positions of two blocks. I can't get it to work, it will just replace one of the blocks.

I.e. ``change.moveNodeByPath([0], [1], 1)``

#### What's the current behavior?
It will replace one of the blocks leaving only one of the two blocks behind.

Relevant fiddle: https://jsfiddle.net/skogsmaskin/t54xc1ap/1/

#### What's the expected behavior?

As I understand moveNodeByPath it should not replace blocks, but just move it? I want to move the first block below the second one.

Could be I misunderstand something here, some input would be appriciated.

**Comment by ianstormtaylor** [comment]
@skogsmaskin might it have something to do with the inconsistent behavior mentioned in https://github.com/ianstormtaylor/slate/issues/2192?

**Comment by skogsmaskin** [comment]
@ianstormtaylor Yeah, that's probably part of the problem (the path annotation for the newPath param is very confusing). But I consider it a bug that it will actually delete/replace nodes like in the above fiddle? It should maybe throw an error instead until ``moveNodeByPath`` is refactored like you propose in #2192.

**Comment by jtadmor** [comment]
@skogsmaskin @ianstormtaylor I believe that the particular fiddle was not showing an actual break in `moveNodeByPath`.

I was able to get the operation to work as expected by changing the code to call the underlying `applyOperation` directly: https://jsfiddle.net/La0bsjm1/3/

I think the reason we were seeing that behavior was because of the `CorePlugin` rule preventing mixing `block` and `text` nodes: https://github.com/ianstormtaylor/slate/blob/7a6de8725c21343f265f95b5ab916c586040dec6/packages/slate/src/plugins/core.js#L66

The jsfiddle is actually moving a `paragraph` node to be the child of a `paragraph` that already has an existing `text` child node, so (I think) the new node was just being removed right after the `move_node` operation went through.

**Comment by ianstormtaylor** [comment]
Is this fixed now?

**Comment by nz-chris** [comment]
Doesn't seem to be fixed. I ended up using `editor.applyOperation` with type as `move_node` instead.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
