### ISSUE TITLE
No serializer defined for mark of type "quote"

### ISSUE THREAD

**Issue by tuanhuu** [ianstormtaylor/slate#2335]
error : No serializer defined for mark of type "quote" 
https://github.com/ianstormtaylor/slate/blob/master/docs/walkthroughs/saving-and-loading-html-content.md

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
