### ISSUE TITLE
consider migrating from Immutable.js "Records" to plain objects

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2345]
#### Do you want to request a _feature_ or report a _bug_?

Discussion.

#### What's the current behavior?

When Slate was first created, [Immutable.js](https://facebook.github.io/immutable-js/docs/) was the best and most popular way to handle immutability in React. However, it has many downsides for our use case:

- **CON: It requires a `fromJS` step to build the collections/records.** Since the objects aren't the native JavaScript data types you get from JSON, we have to have an interim step that instantiates the Immutable.js data model. This can be costly for large documents, and there is no way around it. This is **especially** problematic in server-side environments where serializing to/from JSON blocks Node's single thread.

- **CON: Reading values is more expensive.** Immutable.js is optimized for non-crazy-slow writes, at the expense of read operations being much slower than native JavaScript. Since Slate's model is a tree, with many node lists, this ends up having a significant impact on many of the common operations that take place on a document. (See [this question](https://stackoverflow.com/questions/42004939/performance-immutable-js-map-vs-list-vs-plain-js) for more information.)

- **CON: It introduces a fairly steep learning curve.** People getting started with Slate often get tripped up by not knowing how Immutable.js works, and its documentation isn't easy to understand. This results in lots of "wheel reinvention" because people don't even realize that helper methods are available to them.

- **CON: It makes debugging harder.** In addition to a learning curve, debugging Immutable.js objects adds extra challenges. There's a browser extension that helps, but that's not good enough in lots of places, and you end up having to us `toJS` to print the objects out which is very tedious.

- **CON: It increases bundle size.** The first increase in size comes from just including the `immutable` package in the bundle at all, which adds ~50kb. But there is also a more insidious bundle size increase because the class-based `Record` API encourages monolithic objects that can't be easy tree-shaken to eliminate unused code. Whereas using a utility-function-based API, similar to Lodash, would not have this issue.

However, it does have some benefits:

- **PRO: Custom records allow for methods/getters.** This has been the primary way that people read values from Slate objects. Because Slate (and rich text in general) deals with some complex data structures, having common things packaged up as methods allows us to reduce a lot of boilerplate and reinventing the wheel for common use cases.

- **PRO: It offers built-in concepts like `OrderedSet`.** These allow for more expressive code in core than otherwise, because we'd need to reinvent the wheel a bit to account for JavaScript not having some of these concepts. Although truth be told this is probably a fairly minimal gain.

---

Since Slate was first created, [`immer`](https://github.com/mweststrate/immer) has come on the scene (thanks to @klis87 for kickstarting discussion of it in #2190) which offers a way to use native JavaScript data structures while maintaining immutability. This is really interesting, because it could potentially have big performance and simplicity benefits for us.

All of the **CON**'s above would go away. But we'd also lose the **PRO**'s. That's what I'm most concerned about, and what I'd like to discuss in this issue... to see what a Slate without Immutable.js might look like, and how we could mitigate losing some of its benefits.

Without the ability to use classes and prototypes for our data models, we'd need to switch to using a more functional approach—exporting helpers in a namespace, like we currently already do for `PathUtils`. One question is whether this will be painful...

Looking at our `rich-text` example, we'd need to change how we do things in several places.

https://github.com/ianstormtaylor/slate/blob/8eb8e26958ef6c9337e838bfd46fc2cc55d7fe51/examples/rich-text/index.js#L54

We no longer have getters on our models, so `value.activeMarks` doesn't work. Instead, we'd need to change this to:

```js
return Value.getActiveMarks(value).some(mark => mark.type == type)
```

Similarly, there's no `value.blocks` any more: 

https://github.com/ianstormtaylor/slate/blob/8eb8e26958ef6c9337e838bfd46fc2cc55d7fe51/examples/rich-text/index.js#L66

So we'd need:

```js
return Value.getClosestBlocks(value).some(node => node.type == type)
```

This is actually nice because we're no longer using potentially expensive getters to handle common use cases—calling functions is more clear.

But we also can't use helper methods like `document.getParent`.

https://github.com/ianstormtaylor/slate/blob/8eb8e26958ef6c9337e838bfd46fc2cc55d7fe51/examples/rich-text/index.js#L148

Instead we'd need to use:

```js
const blocks = Value.getClosestBlocks(value)
const parent = Node.getParent(value.document, blocks[0].key)
```

Similarly, we can't do:

https://github.com/ianstormtaylor/slate/blob/8eb8e26958ef6c9337e838bfd46fc2cc55d7fe51/examples/rich-text/index.js#L293-L295

And would have to instead do:

```js
const blocks = Value.getBlocks(value)
const isType = blocks.some(block => {
  return !!Node.getClosest(document, block.key, parent => parent.type == type)
})
```

But we also get to remove some expensive code, since we don't need to deserialize anymore:

https://github.com/ianstormtaylor/slate/blob/8eb8e26958ef6c9337e838bfd46fc2cc55d7fe51/examples/rich-text/index.js#L41-L43

That's all for the rich text example, but it would definitely be a big change.

---

I'm curious to get other folks's input. Are there other **PROS** or **CONS** to Immutable.js that I haven't listed above? Are there other ways of solving this that I haven't considered? Any thoughts! Thank you!

**Comment by Slapbox** [comment]
Wow that's a tough call...

For what it's worth, the Immutable Formatter extension doesn't work in Electron, so Immutable does make debugging quite a bit more difficult as I have to use `toJS()` constantly while debugging, but that's definitely far from a primary concern.

**Comment by ianstormtaylor** [comment]
@Slapbox yup, very tough call. If we were starting fresh it seems like it would be a no-brainer, but hard to gauge benefits vs. costs now. Thanks for the input though! Anything is helpful, just trying to kick around ideas.

**Comment by PierBover** [comment]
I’m no expert in Slate, but I like the changes you’ve posted to the rich text example.

Personally I think removing dependencies and going closer to the metal is good for a project like Slate.

I can’t help with the codebase but I could help with the docs and examples if it’s worth anything.

**Comment by skogsmaskin** [comment]
In my opinion we need to focus on stabilising what we have now. There has already been two heavy refactors lately. Those were needed and gave very clear benefits. This one I'm not so sure about (I agree with what @grsmvg said).

Besides I think such a re-write would take a lot of focus and energy away from  bug-fixing, cross browser compatibility (as fore slate-react), and general UX concerns. And introduce a whole lot of new bugs in the re-write phase.

**Comment by renchap** [comment]
A point you did not mention: not using Immutable will also reduce the size of Slate's dependencies. If you are not already using Immutable in your app, it adds 55kb (minified, not gzipped) of JS to your bundles. It is really best for "core" libraries like Slate to come with as small as possible overall size (dependencies included).
Having less / smaller dependencies is also a big plus when you need to choose a library, for size but also licence concerns (as you need to check the licence for all deps).

**Comment by ppoulard** [comment]
IMHO, we can go further : I think that an entire refactoring of the internal Slate state would worth it if it includes CRDT considerations. I didn't dive inside that part of the code, and I may be wrong, but I'm not sure that 2 updates operations (add or delete) could be switched safely ; there is no notion of which user session did which change. We need this because undo/redo is tightly coupled to its owner (think about user experience : what if you concurrently edit things and when you want to undo you change, it would delete another user addition ?)
See https://github.com/ianstormtaylor/slate/issues/259

If you just replace Immutable with whatever, you'll have to replace later that whatever with a CRDT-friendly library if you intend to supply real-collaborative edition :

- someone has already proposed Teletype-CRDT : https://github.com/atom/teletype-crdt but it seems to work only on characters, not a JSON structure

- someone  else proposed Automerge (https://github.com/automerge/automerge) but it seems that it works on JSON, not on characters (well, a chunk of character would be replaced entirely, not by delta ; but I'm not sure ; Automerge.Text support characters only). See https://github.com/ianstormtaylor/slate/issues/259#issuecomment-377482517 in this example, Automerge have to escape from the Slate model (and the performance would be certainly bad), but if Slate was based on that model it would be much more efficient.  
It's worth to have a look at this presentation, because it defines the prerequisites :
https://www.infoq.com/presentations/crdt-tachyon-collaborative-editing
and from those principles, having an absolute reference of JSON + characters is what is needed ; in Slate, I found some data that looks like that :
`{"object":"operation","type":"remove_text","path":[0,1,0],"offset":0,"text":"Genetic","marks":[]}]
`

- Y.js (http://y-js.org/) that manages its own Map and List data structures

Maybe the latter is the more suitable.

**Comment by ericedem** [comment]
> PRO: Custom records allow for methods/getters

Is this something we could just achieve with build in javascript classes (which support getters)? If so, could Immer support them?

**Comment by ppoulard** [comment]
In fact, to go on with my previous idea, Immutable (or Immer, that does the same but differently) just changes the state of a single client, whereas it doesn't make sense to manage immutable objects because an undo operation is no longer sequential when several people are editing collaboratively the same document.

We don't need to replace Immutable, we need a new strategy for having a data structure that accepts updates in orders that may vary according to each clients.

**Comment by ppoulard** [comment]
Ian suggested (https://github.com/ianstormtaylor/slate/issues/259#issuecomment-242504922) that Slate should be unopinionated about OT/CRDT considerations.

I'm not sure it is easily possible : if Slate data model is aside CRDT data model, you have to maintain both together (like with the Automerge example), and as far as I know, the Slate data model doesn't consider absolute reference of its atoms, which is the key point in CRDT : the problem with indexes is that they shift, how would you find the location of a Slate change in the counterpart model ?

That said, I'm not well aware of the internal Slate data model (perhaps I'm wrong) ; as mentioned previously, it is hard to read because it relies on Immutable and I don't know that library.

**Comment by ianstormtaylor** [comment]
Thinking about it more, I think the best way to make this change would be to do it in two stages:

1. **Deprecate Methods.** Change all of the current instance methods to be implemented as static methods, and created deprecation warnings for the existing instance methods. This would be completely backwards compatible, with warnings logged for all changes. But it also continues to use Immutable.js in the interim step. 

2. **Remove Immutable.js.** Change the models to not use Immutable.js any more. This would not be backwards compatible, because of Immutable.js's own helper methods that it exposes, which would be the hardest thing to migrate properly. However the instance-to-functional migration would already have happened with the deprecations previously.

**Comment by renchap** [comment]
If you go with those big changes, might I suggest starting to use Typescript for Slate's core? It is not hard to incrementally use typescript nowadays as its only a Babel plugin (I did a coffee => js => ts migration for my app incrementally, I dont regret it at all and both can really cohabit).

**Comment by PierBover** [comment]
> But it is definitely something that most people never find. Whereas if we using plain JavaScript data structures people would end up using lodash, or whatever else they liked, for all of these types of things. And as browser's further improve their standard library they could remove more and more of the imports.

The JS community moves very fast and many projects have suffered from coupling to solutions that died or simply went out of fashion (eg: Coffee script). By using native structures Slate will be able to better stand the pass of time.

**Comment by ianstormtaylor** [comment]
@renchap I'm open to using TypeScript, but I'm not sure I want to couple it to this idea. But if someone wants to help TypeScript adoption, I think a decent next step would be to open a pull request with a single small-to-medium-sized file converted to using types and we can have a discussion around it there.

**Comment by renchap** [comment]
@ianstormtaylor The thing with moving to Typescript is to start to type your core model first. Once it is typed, you can start to type the functions that are using it, and expand. Hence why I think it might go along, as if all the structure is rewritten using a new paradigm, it is a good idea to rewrite it in TS first.
But I agree this is not 100% tied, and it will be probably best to have a TS-compatible setup (Babel, linter, …) first, so the impact of moving to Typescript for the model change is just changing the file extension and starting to use types.

**Comment by zhujinxuan** [comment]
Hi, may I know how we can deal with cache with immer?

I am afraid of something like this in user side:
```
const path = document.getPath(path);
path[0] = 1;
```

**Comment by ianstormtaylor** [comment]
@zhujinxuan that's a good question, I'm open to ideas.

Thanks to Immer, I believe all of the core JSON models would be frozen in development mode, so they can't be mutated. We might want to do a similar freezing for return values. But in that example you gave, I think that mutation is okay, because it's up to the user to not do things like that if they don't want their effects.

For caching, one thought was that potentially the only cache that truly matters is the `keys -> paths` dictionary. The others might not be necessary with the move away from Immutable.js since the read performance would be improved.

For the `keys -> paths`, I was thinking about whether we could have a global cache that was restricted heavily in length, maybe the last `~100` lookups by reference? It might get us enough of the benefits, since the caches often become stale. And we could potentially limit it to only being used on `Document` nodes too for further guarantees.

But I'd love to hear other ideas here!

**Comment by zhujinxuan** [comment]
@ianstormtaylor BTW, there are two caches.  The other is `this.__cache.validateNode`, though it does not matter the complexity.  

I think it is a good idea of global `keys->path`, but in this solution, it seems we cannot simply `Block.fromJSON({...})` because `Block.getDescendant` will fail because the globally `keys->path` is not set for this Block (if the path is relative to the document root).

I am not sure whether it is a good idea to have an global `WeakMap(node, [key, path])`;  Because it is a weakmap, we do not need to worry about the memory leak if the node is recycled.  And we can easily visit other nodes' cache without using `node.__cache`.

**Comment by ianstormtaylor** [comment]
@zhujinxuan that's a good point, it could not be `Document`-only in that case, you're right. Using a `WeakMap` could be interesting too!

**Comment by zhujinxuan** [comment]
@ianstormtaylor Great.  I will open a experimental PR to replace the current `__cache` with a global weakmap.  And we can see how the code may be alike.

**Comment by ianstormtaylor** [comment]
Just came across another place where we are weirdly using the two different representations... the `decorateNode` middleware returns decorations, but its the one place where you can't just return either without downsides. 

Right now if you return `Array`, all the other `decorateNode` middleware must also use `Array`. And if you return `List`, then all the others would need to use lists. Or they would all need to handle both cases. (This is required to get `next()` to work as expected.) For now everywhere it using arrays, and it's not big issue, but it's just another place for confusion.

**Comment by steida** [comment]
@ianstormtaylor That's why types are so helpful. Can't imagine write code without them anymore. Btw, asked Lee Byron https://twitter.com/steida/status/1058442668911529984

**Comment by steida** [comment]
Btw, asked Lee Byron https://twitter.com/steida/status/1058442668911529984 what he thinks about immutable to Immer, and he suggested Immutable 4.

**Comment by steida** [comment]
Sorry for maybe a dumb question but related to potential model rewrite. Isn't possible for all commands like toggleMark etc. being pure functions aka with `value` input and output? I am playing with useReducer hook and it would be nice to be able to control Slate model within reducer.

**Comment by ianstormtaylor** [comment]
@steida can you give a code sample? A few constraints to remember:

- Need to use operations as the lowest-level changes for collaboration support.
- Need to allow commands to be overridable by plugins.
- Need to be able to run queries inside commands.

But it could be, not sure.

**Comment by steida** [comment]
Code sample:

```js
function dispatch(value: SlateValue, action: EditorAction) {
    switch (action.type) {
      case 'toggleMark': {
        return toggleMark(action.mark, value)
        break;
      }
      default:
        return value;
    }
  }
```

**Comment by ianstormtaylor** [comment]
@steida let's talk about this in https://github.com/ianstormtaylor/slate/issues/2342 instead of here to keep it focused. But for other context as to why some of those constraints are things we want, check out https://github.com/ianstormtaylor/slate/issues/259 https://github.com/ianstormtaylor/slate/issues/2334 https://github.com/ianstormtaylor/slate/issues/2066 https://github.com/ianstormtaylor/slate/issues/2206 https://github.com/ianstormtaylor/slate/issues/2249 for current thinking. Not saying it's impossible, or even that those constraints are hard coded, but those are the goals we're aiming for.

**Comment by steida** [comment]
So, how did you decide? Will you rewrite it? Or make it work, make it right, make it fast?

**Comment by PierBover** [comment]
Also, is there any kind of ETA for this deep change? Like mid or late 2019?

I'm building a commercial product with Slate and I would need to know approximately how long the project will be stalled since this change will impact the API.

**Comment by ianstormtaylor** [comment]
> So, how did you decide? Will you rewrite it? Or make it work, make it right, make it fast?

@steida what does that even mean?

> Also, is there any kind of ETA for this deep change? Like mid or late 2019?
> 
> I'm building a commercial product with Slate and I would need to know approximately how long the project will be stalled since this change will impact the API.

@PierBover Slate's in beta right now, so these kinds of questions are not easy to answer. We are not at the stage of this project's lifecycle that we can give development roadmap guarantees many months or years into the future. But if not knowing this change's timeline would be prevent you from using Slate, then that might mean that you shouldn't be using it in production.

If by "stalled" you mean the time from when this change starts development to when it is merged, I'd estimate from a few days to a few weeks. Most changes so far have had short start-to-merge times. (For example, see https://github.com/ianstormtaylor/slate/pull/2337 https://github.com/ianstormtaylor/slate/pull/2221 https://github.com/ianstormtaylor/slate/pull/1313 https://github.com/ianstormtaylor/slate/pull/1993.)

---

Based on all of the arguments **PRO** and **CON** above, I think it is likely that we will make this change, but I don't have a timeline. It could be in a week, or it could be in a few months, or it could be in a year. 

Slate is not sponsored by any organization and is run entirely on individual contributions. When I need a feature added, or a bug fixed, or part of the architecture improved for my own use then I devote time to it, and same goes for everyone else. And for the most part, if people need something but no one needs it enough to devote time to it, it doesn't get done.

**Comment by PierBover** [comment]
Thanks, just wanted to get an idea. I completely understand your position.

**Comment by steida** [comment]
> "Make It Work Make It Right Make It Fast" This formulation of this statement has been attributed to KentBeck; it has existed as part of the UnixWay for a long time. http://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast

It means, by my own personal experience, I would first complete Slate before rewrite it from scratch both with types and different state model. Or, I would stop everything else and rewrite it entirelly from the scratch. But if you have another opinion, feel free to ignore me.

**Comment by Dundercover** [comment]
If we are mostly just interested in the js objects of immer then maybe it's better to roll our own freezing utility for dev environments and unfreezing in #2030 ?

**Comment by klis87** [comment]
@Dundercover According to my understanding actually Immer would increase performance, according to benchmarks with similar gains to ImmutableJS, but without cost of converting to and from Immutable objects to native ones.

**Comment by Dundercover** [comment]
@klis87 Alright, I don't understand how it could be though, since it's only about mutating a state in production. But it might be good to use immer anyways if we don't want to deal with the complexity/maintainability.

**Comment by klis87** [comment]
@Dundercover mutating object is faster than updating in JS, because this requires creation of copies, which is especially problematic for deeply nested objects. Not only copying takes time, but also it pollutes memory and gives more work to garbege collector. Solutions like immer/immutable js is not only about protection before unintended mutations, but also/mostly for improving performance.

**Comment by Dundercover** [comment]
@klis87 that is true, I didn't think about that we still needed immutable objects in production.

**Comment by ianstormtaylor** [comment]
Another thing to consider is how to handle keys for nodes. Because right now they are auto-generated for nodes when constructed. But if we want to eliminate the traverse-and-construct step of things, we won't have that opportunity to create keys. 

We might need to store temporary keys in a `WeakMap` somehow as well, but this would change things to result in a new key each time the node is changed. Potentially we might want to introduce a new idea of "path reference" instead, which can be tracked across operations? The real reason we need keys on the frontend is to keep track of nodes even as operations are applied. But if we let people create a "ref" to a path that could resolve that need.

It should also allow people who want to set long-lived keys set them directly on the objects without having to jump through hoops.

**Comment by ianstormtaylor** [comment]
Another thing to consider is how keys are used in `slate-react` to find nodes in the document. We might need to move to react-specific data attributes that are attached to the DOM, instead of re-using keys for this purpose.

**Comment by lxcid** [comment]
I think the most important property in Immutable.js that I value is immutability. Immutability have the benefit of triple equals (`===`) the record or sub-record and if its true, you are guarantee that nothing is changed. This work really nicely with `shouldComponentUpdate()` or pure component.

Also, because its have structural sharing, this is achieve with minimal cost, as oppose to actual copy and mutate.

The actual naming for these properties are [Persistent Data Structure](https://en.wikipedia.org/wiki/Persistent_data_structure) for anyone interested.

I believe Immer could achieve Persistent Data Structure, without a over bloated interface.

My worry is that contributors or users coming in will introduce mutation to plain object and break this property which can be hard to debug if Slate depends on it.

**Comment by knpwrs** [comment]
> My worry is that contributors or users coming in will introduce mutation to plain object and break this property which can be hard to debug if Slate depends on it.

While this repository is written in JavaScript, I think for something like this it may be worth considering TypeScript. A while back I contributed changes to immer which let it modify `readonly` properties: https://github.com/mweststrate/immer/pull/161

Here's a very basic example from that PR:

```ts
import produce from 'immer';
 
interface State {
  readonly x: number;
}
 
// `x` cannot be modified here
const state: State = {
  x: 0;
};
 
const newState = produce<State>((draft) => {
  // `x` can be modified here
  draft.x++;
});
 
// `newState.x` cannot be modified here
```

I'd say if there's serious consideration to move on to using immer instead Immutable.js then you might as well simultaneously rewrite at least the data layer in TypeScript since the conversion from Immutable.js to immer constitutes a rewrite anyway.

**Comment by thesunny** [comment]
Coming into this discussion late but after reading this thread I thought about a possible solution to the "Pure JavaScript objects work better" but "Pure JavaScript objects don't have custom methods" issues.

Quite possible I'm missing something but how about a syntax like this using the examples in the first post?

```js
$.getActiveMarks(value).some(mark => mark.type === type)
$.blocks(value).some(node => node.type === type)
$.getParent(document, blocks[0].key)
const isType = $.blocks(value).some(block => {
  return $.getClosest(document, block.key, parent => parent.type === type)
})
```

For it to work, each of the values would have to have a `type` associated with them but I think the current model already does.

The implementation would look something like
```js
// defining methods for $ with how something like inheritance might work
const node = {
  text() {},
  filterDescendants() {}
}

const value = {
  ...node, // inherit from node
  getActiveMarks() {},
  blocks() {},
}

const document = {
  ...value, // inherit from value
  getParent() {},
}

// This is the object you use to call everything else defined where the key is the object's `type`
const $ = define({ node, value, document })

function define(definitions) {
  const methodNames = new Set()
  Object.values(definitions).forEach(definition =>
    methodNames.add(Object.keys(definition))
  )
  const $ = {}
  methodNames.forEach(methodName => {
    $[methodName] = defineMethod(methodName)
  })

  // defines the method on the $ object
  function defineMethod(methodName) {
    return function(target, ...args) {
      const method = definitions[target.type][methodName]
      if (method == null) throw new Error(`method ${methodName} not found for object type ${target.type}`)
      method(...args)
    }
  }
}
```

**Comment by zhujinxuan** [comment]
Hi, I think @thesunny 's idea on using a `$` as an interface is a good solution, but it may have a small problem when:

```
$.getActiveMarks(value).find(m => m.type === 'bold')
$.getActiveMarks(value).find(m => m.type === 'bold').anchor
$.getActiveMarks(value).find(m => m.type === 'bold').doSomething()
```

Then what we shall return for `$.getActiveMarks(value).find(m => m.type === 'bold')`, a bold mark itself so we can continue the chain call, or a bold mark proxy that we can continue the chain call.

We can allow the bold mark proxy visit mark properties just like mark, but it will require us define proxies for our current models for chain call.

**Comment by Slapbox** [comment]
Can anyone comment on what kind of difference this would make in node rendering speed in terms of percentage improvement? I pretty much never see performance issues with Slate itself but rendering a document for the first time can have some slight delays. The slowdowns are a lot more significant on mobile but pretty much imperceptible on desktop.

**Comment by thesunny** [comment]
@zhujinxuan yeah, my proposal is syntactic sugar primarily designed to make things a little easier to read while still respecting the idea that all the values are pure JSON. It's not a very good replacement for models with methods.

The equivalent syntax would be something like:

```js
$.getActiveMarks(value).find(m => m.type === 'bold')
$.getActiveMarks(value).find(m => m.type === 'bold').anchor
const marks = $.getActiveMarks(value).find(m => m.type === 'bold')
$.doSomething(marks)
```

Another proposal could be to wrap the JSON before calling the methods and I actually kind of like the readability of this. I was going to propose this as well originally:

```js
$(value).getActiveMarks().find(m => m.type === 'bold')
$(value).getActiveMarks().find(m => m.type === 'bold').anchor

// option 1
const marks = $(value).getActiveMarks.find(m => m.type === 'bold')
$(marks).doSomething()

// option 2
$($(value).getActiveMarks.find(m => m.type === 'bold')).doSomething()
```

**Comment by thesunny** [comment]
Hmm... and yet a third way is to always return the values wrapped automatically and have the data always kept in a JSON value. This way it's easy to convert back and forth without any work.

In other words:

```js
$(node).json === node
```

Or to get active marks, do something with it, and then get the resultant JSON value:

```js
$(value).getActiveMarks().find(m => m.type === 'bold').doSomething().json

**Comment by thesunny** [comment]
It feels like I'm having a discussion with myself but I have been thinking about the alternatives and the trade-offs.

The three alternatives are:

- methods off of types like `Node.getActiveMarks`
- methods off of generic like `$` but really can be anything including a regular name
- an object constructor off of generic like `$` but really can be anything including a regular name

I'm gravitating towards the `$` with method because it is safer from upgrades and it is safer from user errors in this style `$.getActiveMarks(node)`:

- If we have to use the type before the method name, the problem is if future versions of Slate required us to change the code for certain types. For example, let's say that we have a method like `Node.getText` but we later find due to an internal implementation change that `Document.getText` or `TextNode.getText` need to have a different implementation. This also makes the code harder to use because we have to know the right version to call. `$.getText(node)` is easier to use and survives the implementation change without having to refactor user code.
- For the proposal where we wrap objects before calling methods and then returning another wrapped object, we have the dangerous issue of forgetting to return the `json` object. If we use the wrapped json object, the editor might not crash but we're putting in bad data that eventually may cause issue and it would be hard to detect where the wrapped object came from.
- Even if we used the version where it always returns a json object after the call, we end up having references to wrapped objects like `node = $(myNode)` and it could be easy to accidentally pass the wrapped node into the editor. Feels safer to never have any wrapped objects lying around.

**Comment by Slapbox** [comment]
@thesunny - I've been following the discussion; I just don't feel that I'm in the position to make good design choices in this situation. Keep up the good work!

**Comment by Slapbox** [comment]
@zhujinxuan can you expand on your comment? Can you put the equivalent code (either current or as proposed by thesunny) for what you're proposing side by side? I'm not clear on what currying `node` does in this context.

**Comment by ianstormtaylor** [comment]
I think using just `Slate.*` would be fine. I'd want to avoid `$` since it's so tightly coupled in peoples's minds to jQuery. But I agree with you @thesunny that they should be methods that return plain JSON objects, not any custom chaining logic.

**Comment by adjourn** [comment]
This discussion makes me very excited and I can't wait.  

Bundle size is one of my top priorities, goal: vendor.js < 150Kb and Slate is last piece in the puzzle. 

I've built 2 moderately complex editors and I never had time nor will to learn Immutable API except the very required parts. This might just show my ignorance but I think that it also says something else. 

+1

**Comment by brendancarney** [comment]
Could we start by mimicking most of the API with functions and getters on the object directly?

**Fake example API:**
```
const value = {
  nodes: [
    { key: 1, text: "Hello " },
    { key: 2, text: "World" }
  ],
  get text() {
    return this.nodes.map((node) => node.text).join("")
  },
  getTextForNode(key) {
    return this.nodes.find((node) => node.key == key).text
  }
}

value.text == "Hello World"
value.getTextForNode(1) == "Hello "
```

**Comment by dragosbulugean** [comment]
@ianstormtaylor what's your current position on this matter? has anybody started working on this migration?

**Comment by ianstormtaylor** [comment]
@dragosbulugean good question. For the next steps on making this happen, check out: https://github.com/ianstormtaylor/slate/issues/2495 — a list of the smaller steps that go into being able to make this change. If anyone can help with any of the steps (or happens to discover another thing we need to fix) that would be awesome!

As soon as we have the precursors done we can make the breaking change.

**Comment by wmertens** [comment]
Question: What is the benefit `immer` would bring over plain objects? It's easy to freeze all incoming values (in dev mode*) but otherwise just use them without changing them or adding proxies.

I'm just playing devil's advocate - it could very well be that deep changes are too annoying to to manually, or that `immer` does them lazily which might make things faster than plain objects.

Another potential problem is that `immer` seems to use Proxy which is not available in older JS engines (mostly IE and older Samsung Internet, so it might not be an issue at all)

* freezing [might incur a performance penalty](https://benediktmeurer.de/2017/08/10/frozen-prototypes/), at least in 2017

**Comment by ianstormtaylor** [comment]
I believe `immer` would be an implementation detail, only inside Slate core. To everyone else it’s just a regular JSON object that happens to be frozen to imitate immutability. 

I’m unsure of what the browser support is. But we don’t want to re-invent the wheel and write the immutability logic ourselves when a popular existing solution with no external API impact exists.

**Comment by knpwrs** [comment]
> Question: What is the benefit `immer` would bring over plain objects

Directly mutating objects is much more natural than immutably updating objects. This is presumedly why Immutable.js was chosen in the first place, because it offers an API which feels like direct mutation.

> Another potential problem is that `immer` seems to use Proxy which is not available in older JS engines (mostly IE and older Samsung Internet, so it might not be an issue at all)

Immer automatically falls back to a getter/setter-based solution, much like Vue or Mobx. Source code here: https://github.com/mweststrate/immer/blob/0ad9a91e189685b24714686bd6a42699ce02feae/src/es5.js

**Comment by renchap** [comment]
> Question: What is the benefit `immer` would bring over plain objects? It's easy to freeze all incoming values (in dev mode*) but otherwise just use them without changing them or adding proxies.

Immer already only freezes objects only in dev mode

> I'm just playing devil's advocate - it could very well be that deep changes are too annoying to to manually, or that `immer` does them lazily which might make things faster than plain objects.

I feel that properly dealing with deep updates would end up with rewriting Immer

**Comment by wmertens** [comment]
> I feel that properly dealing with deep updates would end up with rewriting Immer

I had a look at Immer, and I think I agree. The main benefit of Immer would be doing multiple mutations in one go, which would either not be implemented or recreated when doing immutability manually.

The only way to really be sure is to implement it both ways and benchmark, which I think would show trade-offs on both sides.

I resign as devil's advocate ;)

**Comment by knpwrs** [comment]
> The only way to really be sure is to implement it both ways and benchmark, which I think would show trade-offs on both sides.

I've actually done benchmarks of immer vs ramda vs plain JS for deep immutable updates. I don't have the benchmarks around anymore, but all solutions were on the order of tens of thousands of updates _per second_ and trading blows for the top spot. In terms of performance, there was no clear winner.

In terms of simplicity, however, there was a clear winner. I think it's obvious by now which one I like. :)

**Comment by steida** [comment]
"immer vs ramda vs plain JS" It's like comparing apples with apples with apples.

**Comment by steida** [comment]
After a lot of rethinking, I believe Immer is the best solution.

**Comment by lazharichir** [comment]
> Could we start by mimicking most of the API with functions and getters on the object directly?

We should definitely limit the breaking changes as much as possible for the end users. Using JS `Class` and the `get` getters would help with keeping the API similar, if not the same. Especially as the API is actually super well designed and makes so much sense while using it.

However, I do agree ImmutableJS is a pain, especially server-side. Have to give us on using the Value.fromJSON() because of that and now I work just with the JSON tree.

**Comment by knpwrs** [comment]
Immer supports classes now, FYI: https://github.com/mweststrate/immer#supported-object-types.

There is also a low-level `createDraft`/`finishDraft` api that is very useful for building libraries: https://github.com/mweststrate/immer#createdraft-and-finishdraft

**Comment by ianstormtaylor** [comment]
I forgot, one of the issues in terms of removing keys from nodes, is that when rendering in React-land there's no stable key to use, which leads to issues.

**Comment by ianstormtaylor** [comment]
Another thought: I think once we’re using JSON-based models we’ll move fully to interface-based helper functions. 

Right now things we have “mixins” that approximate this by attaching common methods to the prototypes. And we can rely on instances to do `instance.object === ...`. 

But in the future we’ll be exposing a bag of helper functions that operate on plain objects and arrays. We could continue to require that those objects have an `.object` property to tell us what’s what. But that’s kind of awkward. Instead we can just operate against an interface. 

Since decorations and annotations both implement the `Range` interface, you could call `Range.contains(annotation, path)`. And since they (now) both implement the `Mark` interface too you could use them with mark-related helpers.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
