### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by vdms** [ianstormtaylor/slate#241]
Tried to use **word** to get bold, it didn't happen.

**Comment by ianstormtaylor** [comment]
Hey @vdms, do you mean that you type `**bold**` into one of the examples and nothing happened? 

If so, that's normal, because the examples just show you how to implement different types of functionality, but they don't try to handle _all_ the functionality anyone might want. They're there to show you how to use the API. I've got that specific `**bold**` functionality working in my own editor, and I might open-source a library for it in a bit, but it wouldn't be in Slate's "core" library. Does that make sense? Happy to explain further if you have any questions!

**Comment by ianstormtaylor** [comment]
Gonna close this, but let me know if you have any more info or questions!

**Comment by vdms** [comment]
That makes sense. Thank you.
