### ISSUE TITLE
Prepare for React futures

### ISSUE THREAD

**Issue by ctrlplusb** [ianstormtaylor/slate#2420]
I'm so happy to see how Slate has continued to grow and is so well maintained. 👍 I've finally had an opportunity to use it again, and I reached for it without hesitation.

One thing I have noticed is that warnings get thrown out when running Slate with React's [`StrictMode`](https://reactjs.org/docs/strict-mode.html) enabled.

It would be great to compile a list of the things that need to be updated/refactored in order to get Slate lined up for the future of React.

Currently I see the following:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Editor$$1 which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in div (created by Content)
    in Content (created by Editor$$1)
```

The fix for this is [detailed here](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage).

Here is a demo showcasing Slate, whilst making use of the new Concurrent and Hooks features of React:
https://codesandbox.io/s/qvoxpl3x4j

**Comment by YurkaninRyan** [comment]
Would the solution to this be to keep a ref map for all of the nodes in the editor? 😬

**Comment by adjourn** [comment]
Slate's own `findDOMNode` already uses `win.document.querySelector('[data-key="${key}"]')`.

Any particular reasons not to replace remaining instances with something similar?

`findDOMNode` is used 2 times [here](https://github.com/ianstormtaylor/slate/blob/a09c3c2fdfe87605988a13e968643f81b4936978/packages/slate-react/src/plugins/before.js#L80) and [here](https://github.com/ianstormtaylor/slate/blob/a09c3c2fdfe87605988a13e968643f81b4936978/packages/slate-react/src/plugins/before.js#L340), both being `ReactDOM.findDOMNode(editor)`, I think it should be possible to replace both of these with `querySelector` because editor element also has `data-key`? But is it unique if there are two editors?

Third one is used in `getHtmlFromNativePaste` ([link](https://github.com/ianstormtaylor/slate/blob/1923888af1b07b6c21ea20b0a9f054a5cbb27654/packages/slate-react/src/utils/get-html-from-native-paste.js#L16)). And that's it according to quick search.

**Comment by adjourn** [comment]
`findDOMNode` is used only 2 times, [here](https://github.com/ianstormtaylor/slate/blob/a09c3c2fdfe87605988a13e968643f81b4936978/packages/slate-react/src/plugins/before.js#L80) and [here](https://github.com/ianstormtaylor/slate/blob/a09c3c2fdfe87605988a13e968643f81b4936978/packages/slate-react/src/plugins/before.js#L340), both being `ReactDOM.findDOMNode(editor)`. Wouldn't `editor.base` get the exact same element? Problem solved.

There's also [`getHtmlFromNativePaste`](https://github.com/ianstormtaylor/slate/blob/1923888af1b07b6c21ea20b0a9f054a5cbb27654/packages/slate-react/src/utils/get-html-from-native-paste.js#L16) but that's not even used anywhere.

**Comment by ianstormtaylor** [comment]
Unfortunately, since I think we need access to the "real" DOM node, we might have to enforce using `React.forwardRef()` for all of the components in `renderNode`?

**Comment by tobiasandersen** [comment]
FWIW I think the plan is to make `forwardRef` the default behavior in future versions of React (see https://twitter.com/dan_abramov/status/1109512531209584640)

**Comment by ianstormtaylor** [comment]
@tobiasandersen interesting, good info!

That makes using `forwardRef` seem more fine in the interim, since it'll just be transparent in the future and people can opt out.

That said, I realized we actually separate the "spreadable" props into a separate `props.attributes` dictionary already. Which means I think we can just add `attributes.ref` there and it'll pass through fine.

I'm kind of torn on whether I like the `attributes` separated out, but at least it makes clear what is a DOM attribute that we need set on a real DOM node, vs. what is just extra information to use for rendering your own stuff.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
