### ISSUE TITLE
Deep merge for data

### ISSUE THREAD

**Issue by steida** [ianstormtaylor/slate#2429]
For any non-trivial data `setBlocks` properties does not work, because the data prop is overridden entirely. The current workaround is copy paste Commands.setBlocksAtRange logic into an app, but that's not ideal. 

Is this use case too rare or am I missing something?

```js
editor.setBlocks({
  data: { props: { style: { valueStyle: { id: styleId } } } },
});
```

**Comment by ianstormtaylor** [comment]
My gut tells me this isn't something Slate is likely to support out of the box, because merging always ends up being implementation-specific. And if an API merges by default it's usually hard to tell it about cases where you don't want to merge. But you can always create (and even open-source) a `mergeBlocksData` command and use that instead.

**Comment by steida** [comment]
And properties as a transformation functions? That's would be very nice, because now I have to copy paste code, which is not nice.
