### ISSUE TITLE
Better Docs for transform functions

### ISSUE THREAD

**Issue by joehua87** [ianstormtaylor/slate#243]
Hi @ianstormtaylor I've just created a small tools for easier explorer transform functions because:
- I see that the test fixtures is very helpful docs to explore slate
- It is getting very frustrated to navigate, open & closing files when seeing

You can see it at https://joehua87.github.io/slate-transform-explorer/
Did you see it's helpful to integrated into the main docs?

**Comment by oyeanuj** [comment]
@joehua87 this looks great, and I could see this being super helpful. I think one other thing that might help in making the functions even easier to understand is some sort of a visual demo - whether actual editor there, or a gif of what the transform operations do. Being able to picture what the function names suggest and the functions do would be super helpful!

Thanks for creating it!

**Comment by ianstormtaylor** [comment]
Hey @joehua87 that is a really awesome idea!

I'm somewhat close to revamping the transforms a little bit (with hopefully only a few breaking changes) related to https://github.com/ianstormtaylor/slate/issues/213 so I'd like to see where we get after that before integrating, just because it might involve a lot of rewriting work.

I think it might be even more useful to have images instead of having to parse the YAML, at least for newcomers. That might be something we can invest in once the transforms settle down and we feel good about what is in core. Thanks for opening this!

**Comment by joehua87** [comment]
@ianstormtaylor @oyeanuj I've updated to use Slate's Editor for preview

**Comment by joehua87** [comment]
Hey @ianstormtaylor I think that the fixtures should render the real-life data, for example:
```
{
  "nodes": [
    {
      "kind": "block",
      "type": "paragraph",
      "data": {
        "key": "value"
      },
      "nodes": [
        {
          "kind": "text",
          "text": "word"
        }
      ]
    }
  ]
}
```
"key": "value" should be something like "align":"right" so that we can easily see the difference when render to review

**Comment by ianstormtaylor** [comment]
Ah nice, using the editor is super helpful!

I think we'll actually want to separate it from fixtures. Basically each transform example can have its own fixtures which are designed to be the most clear. The reason for that is that writing test fixtures already takes a lot of time, so I'd rather not impose too many more restrictions on them, at least for now. I've still got a ton of fixtures that still need to be written too :$

**Comment by ianstormtaylor** [comment]
Hey @joehua87 thanks again for building this and opening this issue!

I'm going to close this in attempt to get closer to zero open issues, but it's good food for thought as we build out better docs for transforms. Thanks!
