### ISSUE TITLE
How to use Slate.js with Vue.js?

### ISSUE THREAD

**Issue by ShardulNalegave** [ianstormtaylor/slate#2435]
#### Feature Request

What should I do if I am using vue.js?

**Comment by trun222** [comment]
Fork it and rewrite it in Vue.

**Comment by CameronAckermanSEL** [comment]
Hi. For a Vue application, you may still make use of the slate core library (it does list React as a peer dependency but I'm pretty sure it's not actually used there).

For the slate-react library, you will either need to fork it and write an equivalent yourself, or you can include React as a dependency into your application and make use of the frontend react component.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by mprinc** [comment]
Here is what I've found: https://github.com/marsprince/slate-vue

**Comment by Guan-Erjia** [comment]
https://github.com/Guan-Erjia/slate-vue3
