### ISSUE TITLE
Using Slate without React?

### ISSUE THREAD

**Issue by kokujin** [ianstormtaylor/slate#2445]
Is it possible to use Slate with a different component framework instead of React? If yes, can someone point me to some example code?

Thanks

**Comment by CameronAckermanSEL** [comment]
https://github.com/ianstormtaylor/slate/issues/2435

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
