### ISSUE TITLE
setBlocksAtRangeWithCallback proposal

### ISSUE THREAD

**Issue by steida** [ianstormtaylor/slate#2447]
I suppose this is useful and can't be implemented in userland, because we would have to copy-paste setBlocksAtRange code. 

```js
function setBlocksAtRangeWithCallback(editor, range, callback) {
  const { value } = editor;
  const { document } = value;
  const blocks = document.getLeafBlocksAtRange(range);

  const { start, end, isCollapsed } = range;
  const isStartVoid = document.hasVoidParent(start.key, editor);
  const startBlock = document.getClosestBlock(start.key);
  const endBlock = document.getClosestBlock(end.key);

  // Check if we have a "hanging" selection case where the even though the
  // selection extends into the start of the end node, we actually want to
  // ignore that for UX reasons.
  const isHanging =
    isCollapsed == false &&
    start.offset == 0 &&
    end.offset == 0 &&
    isStartVoid == false &&
    start.key == startBlock.getFirstText().key &&
    end.key == endBlock.getFirstText().key;

  // If it's a hanging selection, ignore the last block.
  const sets = isHanging ? blocks.slice(0, -1) : blocks;

  editor.withoutNormalizing(() => {
    sets.forEach(block => {
      editor.setNodeByKey(block.key, callback(block));
    });
  });
}
```

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by ianstormtaylor** [comment]
Actually I think I see what you mean, opened: https://github.com/ianstormtaylor/slate/issues/2746.
