### ISSUE TITLE
Retrieving value from immutable data?

### ISSUE THREAD

**Issue by getnashty** [ianstormtaylor/slate#2480]
I'm new to immutable, but generally it hasn't been too tough to figure out.

This works, but causes a crash if there are no activeMarks:
`editor.value.activeMarks.first().data;
`

This always returns null:
` editor.value.getIn(['activeMarks', 0, 'data'], null);`

Is there a different way I should be retrieving deeply nested values in Slate? @ianstormtaylor

**Comment by CameronAckermanSEL** [comment]
Hi,

We have a slack channel for discussing help topics like this. The issue tracker isn't very good for this purpose because of the flow of issues coming in.

https://slate-js.slack.com/

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
