### ISSUE TITLE
How do I get current leaves?

### ISSUE THREAD

**Issue by KingJeason** [ianstormtaylor/slate#2486]
How do I get the lowest leaves for which the current coordinate is located?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by KingJeason** [comment]
I'm sorry for my unclear express
