### ISSUE TITLE
Handling <br/> html serializer creates double space

### ISSUE THREAD

**Issue by alex-hioperator** [ianstormtaylor/slate#2508]
Hey there!

I have a need to be able to paste the following code into the editor

`<p>hello world</p><p><br></p><p>hello again</p>`

That inner `<p><br></p>` causes the editor to generate extra spans before and after the <br> tag, and this somehow adds an extra space into the editor :/. I've verified that all of the examples of the editor show this behavior too (try copy and pasting some HTML with that format). 

I'm trying to figure out a way to work around this. I am using the `slate-html-serializer` to handle the serialization. I have a special rule for handling the br:

```
{ 
              deserialize(el) {
			if (el.tagName.toLowerCase() !== "br") return;
			return {
				object: "inline",
				type: "br"
			};
		},
		serialize(object, children) {
			if (object.type !== "br") return;

			return <br />;
		}
}
```

I've also got the renderNode code as follows:

```
case "br":
    return <br />;
```

I've also tried the using newline in the deserializer, but that resulted in the same behaviour :(.

Any ideas?

**Comment by pjshy** [comment]
can you ignore the br in paste html ?

**Comment by Alex07045** [comment]
I was able to work around it with some replacements of characters, though tbh if feels hacky. Wondering if there's a predictable way to handle the new lines?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
