### ISSUE TITLE
 When insert inline image, the caret position should be below

### ISSUE THREAD

**Issue by hengkx** [ianstormtaylor/slate#2510]
#### Do you want to request a _feature_ or report a _bug_?

_bug_
#### What's the current behavior?

[test-slate](https://github.com/hengkx/test-slate)
windows 10,chrome latest
![image](https://user-images.githubusercontent.com/8358236/50434057-ccb73500-0916-11e9-9e4f-f06fe301bbb6.png)

#### What's the expected behavior?

![image](https://user-images.githubusercontent.com/8358236/50434117-1dc72900-0917-11e9-9d03-213f2b665f71.png)

the caret position should be below

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by Pardeep94** [comment]
@hengkx do you find any solution for this ?
