### ISSUE TITLE
Calling decorateNode does not affect Value.decorations

### ISSUE THREAD

**Issue by impulse** [ianstormtaylor/slate#2534]
#### What's the current behavior?
`decorateNode` does not update `this.editor.value.decorations`
[jsfiddle](https://jsfiddle.net/fj9dvhom/2749/
)
#### What's the expected behavior?
`decorateNode` will update `this.editor.value.decorations` like `setDecorations()`

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
