### ISSUE TITLE
Where can I get the latest documentation for placeholder?

### ISSUE THREAD

**Issue by li-si** [ianstormtaylor/slate#2563]
#### Do you want to request a _feature_ or report a _bug_?

question

#### What's the current behavior?

Can someone tell me where can I get the latest documentation for slate-react-placeholder? 
I cannot find any documentation for placeholder in the latest documentation at https://docs.slatejs.org/.

**Comment by thesunny** [comment]
Hi @li-si here is the documentation.

https://docs.slatejs.org/slate-react/editor#placeholder

Since it's a core plugin, there is no need to add the plugin. It is already included in Slate.

In the future, you will find you get faster answers to questions in the Slack channel

https://slate-slack.herokuapp.com/
