### ISSUE TITLE
Slate selection cannot select only vertical areas

### ISSUE THREAD

**Issue by CodePlayer** [ianstormtaylor/slate#2566]
#### Do you want to request a _feature_ or report a _bug_?

**bug** can also consider as **feature**

#### What's the current behavior?

![editor-selection-table-demo](https://user-images.githubusercontent.com/3793502/51976465-a65d5a00-24bf-11e9-9efd-09cf1925e165.gif)

#### What's the expected behavior?

![slate-editor-selection-demo-expected](https://user-images.githubusercontent.com/3793502/51976470-ac533b00-24bf-11e9-93ba-0f68cc56481a.gif)

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
