### ISSUE TITLE
Deleting inline node deletes extra character

### ISSUE THREAD

**Issue by devincma** [ianstormtaylor/slate#2611]
#### Do you want to request a _feature_ or report a _bug_?
A bug.

#### What's the current behavior?
Deleting an inline `Footnote` node deletes an extra character.
https://codesandbox.io/s/5v5xkjk4on?fontsize=18

![](http://g.recordit.co/cLeZ09Oyno.gif)

On Latest Chrome, MacOS, latest Slate and Slate-React.

#### What's the expected behavior?
Only deleting the inline node (i.e. the superscript).

**Comment by ericedem** [comment]
I'm not quite sure this is a bug. The footnote is being rendered as part of the inline node as a display item, not as additional content added to the editor. So when the user hits backspace, slate looks at the current position (after the inline), tries to delete back one character, and only finds one character to remove; in the example above the `"e"` character. The character gets removed, the inline is empty, so the whole inline is removed from the document.

I haven't worked with notations like this so I'm not sure best practice here, that would be a good thing [to ask in the slack channel](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md#asking-questions).

You could add custom delete behavior, that checks to see whether you are trying to backspace over a footnote, in which case you could just unwrap the inline.

Another option could be to add the footnote character to the document itself and add styling using marks or decoration. This would be nice because you would get delete behavior out of the box but it does mean you would end up with hanging footnotes if you delete the character it is supposed to be attached to.

**Comment by devincma** [comment]
@ericedem Ah I see. Those are good suggestions, I'll try them. Thanks, Eric!
