### ISSUE TITLE
read only mode doesn't update immediately

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#262]
As reported via Slack, enabling read-only will sometimes leave the cursor in a block, which allows a single extra edit to be made before the contents is actually read-only.

Fiddle to demonstrate: https://jsfiddle.net/u0tfxf7u/3/

I think this is probably because `shouldComponentUpdate` in `Node` doesn't take into account read-only for blocks, so the cursor isn't removed. Might be able to add that logic to `Content`, or could pass down the `readOnly` prop to leaves?

**Comment by arekkas** [comment]
Similar to #272 this only happens in chrome. Firefox is doing it fine

**Comment by arekkas** [comment]
this happens in chrome and firefox, but in firefox I have to reselect slate whilst this is not required in chrome. could be related to #272

**Comment by edencore** [comment]
I'm eager to fix this bug, but I'm still very new to React. This is what I found out: when you change `readOnly` state, `shouldComponentUpdate` method inside `Content` returns false, because `isNative` set to true for some reason. So the easiest way to fix this would be:

```
if (props.state.isNative && props.readOnly == this.props.readOnly) return false
```

Of course, it's a workaround so I'm looking for a better way to do that. Could you give me some hint about it? Where should I look for wrong `isNative` assignment or something like this?

**Comment by ianstormtaylor** [comment]
@edencore I _think_ actually it might be solved by checking to see if `readOnly` has changed, and returning `true` instead.

Such that it would be something like:

```js
if (props.readOnly != this.props.readOnly) return true
if (props.state.isNative) return false
```

But I'm just throwing that out off the top of my head. If you get it worked, I've love to accept a PR!
