### ISSUE TITLE
Deleting Plaintext Emoji as First Character Throws Error

### ISSUE THREAD

**Issue by ragurney** [ianstormtaylor/slate#2632]
_bug_

#### What's the current behavior?

Inserting an emoji in plain text -- either by using `insertText()`, copy pasting, or using Mac's emoji picker -- as the first character in the editor, then hitting the left arrow once and hitting backspace results in an error: `slate.js:6451 Uncaught TypeError: Cannot read property 'text' of null`
Sandbox example: 
![](http://g.recordit.co/1A2xwR1acl.gif)
https://codesandbox.io/s/8zyqw2jy38

This also happens in the Slate.js example editor:
![](http://g.recordit.co/lQknljBVw8.gif)

#### What's the expected behavior?

Allow the backspace, resulting in the replacement character (�). I'd be happy to open a PR if this is indeed a bug. 

Thanks!

**Comment by realknack** [comment]
This indeed seems to be a bug, have to press arrows 2 times too in order to get caret to the other side of emoji. Pressing arrow once moves caret visually to other side but if you hit backspace or any other character, deletion/insertion happens in the middle of emoji/between 2 � (not sure how that works).

Im surprised this is not getting many reactions, all emojis inserted by mobile keyboard are inserted as plain text right? I guess the reason behind this is that mobile support was "officially" just added.

**Comment by brendancarney** [comment]
Looks like a bug to me. We'd definitely welcome a PR!

**Comment by ragurney** [comment]
Alrighty, I'll take a crack at it!
