### ISSUE TITLE
get previous inline blocks to cursor position

### ISSUE THREAD

**Issue by vamshi9** [ianstormtaylor/slate#2639]
#### Do you want to request a _feature_ or report a _bug_?
 A feature.

#### What's the current behavior?
If I want to get all the inline blocks which are of type `span`, I could get it with 
`this.editorRef.value.document
      .filterDescendants((node) => node.type === 'span')
      .toArray()`.
Now, if I have inline blocks as .....inline1.......inline2.....inline3......inline4 and my cursor is in between inline2 and inline3, how can I fetch previous inlineNodes which are of type `span`?   

#### What's the expected behavior?

I am thinking like there has to be a feature like `getPreviousInlineBlocks `to get all inline blocks prior to cursor position.

**Comment by brendancarney** [comment]
Hi @vamshi9, this can be accomplished by getting all the nodes in the block, checking the index of the current node, and using that to determine the previous ones. I don't think it would be something added to the API directly, since it's not super common. If you have more questions, please feel free to ask in the slack channel. Thanks!
