### ISSUE TITLE
Link-editing via hovering menu

### ISSUE THREAD

**Issue by joe-loco** [ianstormtaylor/slate#264]
Hi, we’re trying to build Medium-style link editing via a hovering menu. We’re running into a problem where, when focusing the link input, the selection is lost. See the following video:

![selection-example](https://cloud.githubusercontent.com/assets/1944/17896918/93b29db4-6952-11e6-81db-8d97d8877dd1.gif)

Is there a way to keep the selection somehow while the input is focused? Or do we have to use a (temporary) mark as workaround?

Thanks!

**Comment by ianstormtaylor** [comment]
Hey @joe-loco good question. My guess is that there isn't (except maybe in Firefox which supports multiple selections I think) because the selection is handled at the browser level. 

If you definitely need to show the selection still, you might have to use marks. (Random thought: there might be something crazy you could do with `<iframe>` elements to actually maintain two selections at once.)

Just took a look at Medium and Dropbox Paper, and it looks like neither of them keep the selection active when editing the link, so from a UX perspective you might be able to get away with not having it stick. (Although I agree that it's not as nice.)

**Comment by joe-loco** [comment]
Thanks! I might try using marks then.
