### ISSUE TITLE
Schema rules: Separate validate and normalize

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#265]
Hi @ianstormtaylor,

I am new to Slate, and experimenting with the recently added schema rules. So far, I like how clean the schema implementation is. I am curious about the rationale behind this design:

What is the purpose of separating the rules in two functions `validate` and `normalize` ? In the [current implementation](https://github.com/ianstormtaylor/slate/blob/0755e6b226dd854a0d49789f5142b3eaec5760eb/lib/models/state.js#L375), they could easily be merged into one.

At first I thought I was going to write some code twice, because `normalize` would need to find again what `validate` spotted as invalid in the first place. But in the end, I found myself implementing most of the logic in `validate`, and use generic `normalize` functions, with a clean data contract for the `value` parameter. For example, if `validate` spots a node that need to be removed, it would pass this node as a `value.toRemove` property, and `normalize` will remove any node passed in `value.toRemove`. Is it how you envisioned these functions to interoperate ?

**Comment by ianstormtaylor** [comment]
Hey @Soreine good question! I honestly haven't thought about it enough to have a solid stance either way, so I could be convinced.

I think my thought process was that it might be nice to have a `validate` code path that you could call that wouldn't edit the state. Imagine just using `state.validate()` instead of `state.normalize()` when for example showing a user-facing error for the editor's content. (Password must be X characters.) On vacation right now for a couple more days, so slightly out of it, so there may be flaws in my thinking there haha.

**Comment by Soreine** [comment]
Enjoy your vacation. It's not a good idea to separate them. It's basic separation of concerns.
Also, it makes sense for issues like this one: https://github.com/ianstormtaylor/slate/issues/266
