### ISSUE TITLE
Can't call `setValue` on Editor React component

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#2664]
#### Do you want to request a _feature_ or report a _bug_?
BUG

#### What's the current behavior?
`Editor` react component instance is missing the `setValue` method.
In plugin event handler, I can't call `editor.setValue` as it's `undefined`.

#### What's the expected behavior?
`Editor` react component instance has the `setValue` method.
It should be possible to call `editor.setValue` from plugin event handler.

**Comment by bengotow** [comment]
Hey! I believe the Editor React component is meant to be used as a totally uncontrolled component (where there's an initial state and then you can read the state out), or as a controlled component (where there's a `value` prop and an `onChange` prop, and the parent is expected to store the value in state and re-render the Editor.) It sounds like you need to use the latter approach. There's no need for a `setValue` method because you just re-render the Editor component with the updated value, eg: `<Editor value={newValue} />`.

**Comment by czechdave** [comment]
While that is technically true, any plugins that have handlers don't have access to the actual `Editor` controller then. If I log the `editor` prop in say `onKeyDown` handler, I can't call `editor.setValue` as it's undefined.

**Comment by adjourn** [comment]
@czechdave Editor seems to invoke `this.controller.setValue()`, not `this.setValue()`.

Anyhow, something prevents you from editing `value` that you pass down to editor as `props`? And how would that even work if you'd set Slate internal value imperatively? Passed in `value` and Slate internal value would go out of sync. No?

**Comment by neutraali** [comment]
**Slate** needs more docs on how to utilize the Editor in an _uncontrolled_ way, without having to deal with handling 1000s of state transitions. I'm looking for something like `setValue` as well since it's mentioned in the docs, but when I try to access it from the Editor `ref` it's undefined.

**Comment by adjourn** [comment]
@neutraali  FIY, Slate core `Editor` and React `Editor` component are two different things, that's why you see `Editor` both under `SLATE CORE` and `SLATE REACT` sections in documentation sidebar. 

React component doesn't have `setValue` but it does have a reference to to core (`ref.controller`) which has `setValue`. 

Maybe you should ask around in Slate Slack. I've done several complex editors, including collaboration and I've never needed to this API/controller directly. Maybe there's a less imperative/frustrating way.

**Comment by alangibson** [comment]
@adjourn Have you considered open sourcing an editor, especially one with collaboration? It would be enourmously helpful for people trying to learn Slate since most examples out there are pretty basic.

**Comment by ianstormtaylor** [comment]
Hey, this is by design because `setValue` is an internal-type method for setting things up. Event handlers should not be calling `editor.setValue` and should instead be using operations to achieve this.
