### ISSUE TITLE
How we can delete table ?

### ISSUE THREAD

**Issue by slgauravsharma** [ianstormtaylor/slate#2706]
I want to delete table.
i saw there is method  removeNodeByKey(key) to delete node. i need key for delete the table

Scenario:-  on click of table cell that time i populate delete button and by using delete button to delete table. but i cn't figure out to find key of table.
#HELPPLEASE #TABLESLATE #TABLE 
if any other solution for delete the table then please let me know. thanks in advance.
Slate version:- 0.45.0

**Comment by CameronAckermanSEL** [comment]
Hi!

We have a slack channel for questions like this: https://slate-js.slack.com/

Also check out the properties on the `editor.value.selection` object, this should give you what you need. https://docs.slatejs.org/slate-core/selection

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
