### ISSUE TITLE
can i custom link like the photo

### ISSUE THREAD

**Issue by wangxingxing123654** [ianstormtaylor/slate#2718]
#### Do you want to request a _feature_ or report a _bug_?

![image](https://user-images.githubusercontent.com/28847126/56849592-09c51f80-6929-11e9-8bbf-09c222bb444f.png)
just like the photo show . when i click the  link icon, there will be a select show up,how can i 
to do this?

**Comment by CameronAckermanSEL** [comment]
Please read the issue template before submitting an issue:
```
#### Do you want to request a _feature_ or report a _bug_?

<!-- 
If you have a question, ask it in our Slack channel instead:

https://slate-slack.herokuapp.com/
-->
```

Questions like this should be asked in the slack channel.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
