### ISSUE TITLE
How to split editor in two columns ?

### ISSUE THREAD

**Issue by slgauravsharma** [ianstormtaylor/slate#2724]
i want to split editor in two column can you give me idea how to achieve this funtionality ?
if possible code then its so appreciable. thanks
i already post in slack channel also but not getting any response #HELPPLEASE
screenshot to more specified requirement.
![twocolumn](https://user-images.githubusercontent.com/25609444/56959078-e2a96080-6b69-11e9-9ca3-d89d27c4b8dc.png)

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
