### ISSUE TITLE
Schema rules question: How to use transforms at range

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#274]
I feel like I am missing something that could make implementing `normalize` easier. Until now, I was fine using only the all mighty `setNodeByKey` to update the nodes I am validating.

But this time I need to update marks. And `setNodeByKey` does not seem to affect the `Text` nodes. There are a lot of convenient, higher-level [document transforms](http://docs.slatejs.org/reference/models/transform.html) available. But they work on a `Selection` range parameter, not some node keys. I would love to be able to use them, but I feel like I cannot for several reasons:

1. The `Selection` we pass could break because of it is not aware of the transformation of any previous normalization [1]. A solution could be to `transform.apply()` at the start of `normalize`, and determine the correct `Selection` from there, but I don't know the negative effect this can have.
2. The only easy way I know to create a `Selection` is to use the [selection transforms](http://docs.slatejs.org/reference/models/transform.html). But it feels awkward to  do `const range = transform.someSelectionTransform().apply().selection` just to obtain a `Selection`. Who knows how many steps the `transform` already contain. It could be doing a lot of work for nothing.

Does someone know an easy way to do high-level document transforms, without having to work on a `Selection` ?

[1]: Side note : All the `validate/normalize` rules I write do not take into account the potential transformations made by other rules. It can result in conflicts, for example if a rule updates a node that was removed by another. So far so good, I am careful with the order of my rules and their relative operations. I just thought it is worth mentioning because it can cause trouble.

**Comment by ianstormtaylor** [comment]
Hey @Soreine very good question :) as usual!

---

Side note: Totally agree about the problem with having to keep track of ordering and side effects. That is because of a poor decision in the current API to apply all of the transforms at the end, instead of as each method is called. In the `add-operations` branch I've changed this so that `transform.state` has all of the previously run transforms applied, so this should become not a problem soon!

---

As for updating marks, you're right to have issues there since it's not really possible right now except using the range-specific functions. On the `add-operations` branch I've added a few more low-level `*ByKey` methods. Although it seems like once the `state` is properly updated after each transform is run this might not be an issue for you any more?

I'm hoping to get that branch out as soon as possible (working to make sure it doesn't introduce any new bugs right now since it's almost complete). Until then I'm not sure there's much you can do, except for making sure the transforms don't conflict, sorry about that!

**Comment by Soreine** [comment]
Thanks for the answer, as usual ;)

----

Side note: That's good news. I believed there was a well thought out reason for the `transform.apply()` to be made only once, at the end. `validate` will still be called with the original nodes. But at least, `normalize` has the chance to fallback if there are conflicting changes.

----

The `*ByKey` methods will be very welcome! And indeed, if the `state` is properly updated, I will be able to do this kind of things:
```
function normalize(transform, node, value) {
    const range = transform
      .moveToRangeOf(node)
      .apply({ snapshot: false }).selection
    
    return transform.removeMarkAtRange(range, ...)
}
```

However, I see that `add-operation` branch [makes `Transform` mutable](https://github.com/ianstormtaylor/slate/pull/249/commits/18d567672c404ab74c36fdf99f67741a95424ab8).  I guess this would break the above code. What was the reason to make it mutable ?

Anyway, these issues are not critical for me, so don't worry, better take the time. Best of luck in finishing this PR. I am confident you will come up with a simple and elegant solution, as always.

**Comment by ianstormtaylor** [comment]
For mutability, my thought was that since transforms are expected to be continuously chained together, it would make more sense to have them be mutable and save performance on all of the interim steps required to get from start to end. I could be convinced this is a bad idea though!

For the `range` code above, you could actually call the method on the selection itself instead of needing to use the transform variant. Which would look something like:

```js
const { state } = transform
const { selection } = state
const range = selection.moveToRangeOf(node)

return transform.removeMarkAtRange(range, ...)
```

Or you could even just use the `Selection.create` to create a new range instead:

```js
const range = Selection.create({
  ...
})

return transform.removeMarkAtRange(range, ...)
```

Let me know if that answers your question!

**Comment by Soreine** [comment]
I missed the methods on `Selection` itself. I think I live too much in the doc, not enough in the code. I did that and it solved my problem. Thanks!
