### ISSUE TITLE
treat "hanging" ranges in a consistent way

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2746]
#### Do you want to request a _feature_ or report a _bug_?

Bug / improvement.

#### What's the current behavior?

Rich text editors depend on a special behavior when a range spans multiple blocks and the end is right at the beginning of a block. For example:

```jsx
<document>
  <paragraph><anchor />Some text...</paragraph>
  <paragraph><focus />More text.</paragraph>
</document>
```

We often need to do special behaviors, like ignore the extra "hanging" block when iterating over the blocks. This happens with inlines too, like:

```jsx
<document>
  <paragraph><anchor />one <link><focus />two</link> three</paragraph>
</document>
```

#### What's the expected behavior?

We should add first-class support for "hanging" selections like this. The iterables like `node.blocks()` and `node.inlines()` should have a `includeHanging` option to toggle this, defaulting to `false`. Other parts of the codebase will then get this behavior automatically.

For the cases where people do want the extra "hanging" nodes, they can opt-in by passing `includeHanging: true` and get them, but I think it would be the exception.

**Comment by justinweiss** [comment]
I'm not sure if it's the same issue (or would be fixed by the fix for this), but I've run into hanging problems especially when triple-clicking. Here's an example:

![Screen Recording](https://user-images.githubusercontent.com/1020/64574208-65fe6e00-d323-11e9-80cb-c805a078ec23.gif)

It's hard to know what the right thing to do is here. Imagine the "Human" cells are empty. Is a selection hanging into the other node, or is the person trying to select two nodes? I don't think there's a way to tell the difference. I think some editors solve this with dummy nodes at the end of each block to capture a hanging selection and report it as "hanging," to do the right thing. Considering how much code deals with zero-width spaces for void inlines, I don't know if we want to pile another of that kind of hack on top 😄 

Let me know if you'd rather this be a separate issue, this seemed like the right place to start bringing it up.

**Comment by ianstormtaylor** [comment]
@justinweiss seems like as good a place as any! Would be nice to have all of the different edge cases related to hanging selections in one spot.

I'm thinking that "the person was trying to select a hanging selection" might be a case that can be thrown out. As long as hanging selections are handled in a known way, it might be okay to handle them that way even when the person tried to select it. For example, if it was nudged back to be non-hanging there, that seems reasonable?

**Comment by justinweiss** [comment]
When the hanging selection spans multiple table cells, I think nudging it back is the right thing to do.

In other places, that might not be the right thing to do. For example, in most editors, you can triple-click on a paragraph and hit delete. That will remove that paragraph node entirely, instead of removing just the text inside it. Same thing with a list item.

I don't think it's a do-or-die feature, but some people are used to that behavior, and it would be nice to support.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
