### ISSUE TITLE
Decorators are being wrongly added to adjacent nodes

### ISSUE THREAD

**Issue by luisateixeira** [ianstormtaylor/slate#2807]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behaviour?

Decorators are being wrongly added to adjacent nodes when adjacent nodes are inline or have marks.

In this example, I'm decorating words that match "line". It only finds one match but decorators are being added to all the other nodes within the same block that have marks or are inlines: https://codesandbox.io/s/competent-firefly-lysyr 

#### What's the expected behaviour?

The decorator should only be applied to nodes that match the key/path in decorations.

**Comment by adjourn** [comment]
https://github.com/ianstormtaylor/slate/blob/a5a25f97dde1de06ef0746e6f5285c04e503351c/packages/slate-react/src/components/node.js#L174-L182

Currently all block decorations gets passed to each of its Text node and downstream methods are not equipped with enough information to decide if to add decoration to current Text node or not (and of course it adds it to all Text nodes). 

It would be possible to decide it on Text level but we'd need to use `getPath` in each node which is not desirable (or pass `i` from `nodes.map` down as a prop and build `path` in each level dynamically).


Not sure if deciding on Node level has any caveats but this hack seems to fix given example:

```js
const newDecorations = node.getDecorations(editor)
const children = node.nodes.toArray().map((child, i) => {
  const Component = child.object === 'text' ? Text : Node
  const sel = selection && getRelativeRange(node, i, selection)

  // Merge all decorations
  let allDecs = newDecorations.merge(decorations)

  // Invoke `getRelativeRange` for all decorations,
  // Text node recieves only the decorations it needs.
  const decs = allDecs
    .map(d => getRelativeRange(node, i, d))
    .filter(d => d)
    // This would pass all the decorations this
    // particular block has to each Text node.
    // .concat(decorations)
```

**Comment by Slapbox** [comment]
Is anyone working on this? This is a fundamental feature, but it's been broken for a third of a year. I'm just finally revisiting Slate 47, which I abandoned initially because of this back in June.

@ianstormtaylor & @adjourn, what's the preferred approach to fixing this? I'll try to find some time to work on this, but I don't want to offer up a solution that's going to be rejected. 

I don't have a holistic enough understanding of Slate to know what a wise approach to this is. @adjourn thank you for providing some context for this issue. Are there problems with the second solution you suggested here?

> It would be possible to decide it on Text level but we'd need to use getPath in each node which is not desirable (or pass i from nodes.map down as a prop and build path in each level dynamically).

Btw, @adjourn the snippets you referenced are slightly outdated, in the interest of clarity, would you be able to update your post when you get a second with the newest code. I could just post the updated lines, but duplication/fragmentation in discussion threads is a scourge I don't want I don't want to visit on us.

**Comment by Slapbox** [comment]
Can anyone clarify the relationship between this issue and these others?

https://github.com/ianstormtaylor/slate/pull/2970
https://github.com/ianstormtaylor/slate/issues/2895

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
