### ISSUE TITLE
Make marks work with compositions (input requested)

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2851]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When turning on a mark, for example by pressing the `bold` button, any composition inserted text will not display the marks.

Here is a screencast from @HGZwebdesign from this comment https://github.com/ianstormtaylor/slate/issues/2839#issuecomment-498226527

https://m.imgur.com/a/tivN5eY

#### What's the expected behavior?

We expect the user's compositional input to immediately display in `bold`.

There are three approaches that I can think of to solve the `bold` issue.

1. Save the current state of the mark and when the composition completes, apply all the marks like `bold`. Not ideal because you never see the mark (i.e. the bold) until the composition is completed.

2. Rerender immediately when there is a modification to text even if it interrupts a composition. Not ideal because it interrupts the composition. This could affect things like IME (foreign language input).

3. As soon as the user changes the marks, insert an empty inline with the styling applied. This solves the styling issue but likely affects the internals of Slate.

This is likely something that @ianstormtaylor will have to decide the approach on. It feels like the approach either needs to be `2` or `3` though or user's might believe the editor is broken.

**Comment by samuelcolvin** [comment]
Should be noted that is is an android (only?) bug, doesn't occur on desktop.

**Comment by thesunny** [comment]
@samuelcolvin I believe this affects all edits that are treated as compositions as per the title.

For example, I tested a composition in Japanese on an iPhone and it doesn't work either.

It is likely that the edit you tested on a desktop browser worked because it was not using compositional input. It is possible to do even foreign input without using compositions. For example, Korean worked on my iPhone (inputs were coming in one character at a time) but Japanese did not (inputs were batched into compositions).

As a side note, Kanji is completely broken right now in Slate on an iPhone. After you select one, the text is completely deleted. Without selecting a Kanji though I can still see that the marks were not persisted.

**Comment by knubie** [comment]
@thesunny Just tried this on desktop chrome with Japanese and it worked. Seems like this might be limited to iOS and Android for some reason.

**Comment by ianstormtaylor** [comment]
Hey, there are lots of open Android-related issues that are out of date with the latest `0.50` release because the codebase was completely rearchitected. We'll need to figure out how to have proper support for Android going forward based on `beforeinput` events somehow. I'm tracking this in https://github.com/ianstormtaylor/slate/issues/3112, so I'm going to close this in favor of that one. 

If it cannot be implemented simply in core with `beforeinput` we'll likely need to have a separate plugin for android support be created, because it's too much of a departure from all of the other simpler logic in core and very hard for me to test or respond to issues. Using a separate plugin should be possible now as the newest version simplifies a lot of the internals.

Thank you for understanding.
