### ISSUE TITLE
Merge Tags or fields ? 

### ISSUE THREAD

**Issue by Nothing-Works** [ianstormtaylor/slate#2857]
## I think a feature

Merge tags allow users to dynamically add content to the HTML later,

like curly brackets {{ ... }} or square brackets [ ... ] or any other.

Thanks

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
