### ISSUE TITLE
How can I find out if selection is in first/last line and first/last position

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#289]
I want to be able to know if the selection is at

first character (easy one: `editorState.selection.startOffset === 0`):

```
| This is the first line
This is the second line
This is the last line
```

last character:

```
This is the first line
This is the second line
This is the last line |
```

first line:

```
This is the | first line
This is the second line
This is the last line
```

last line:

```
This is the first line
This is the second line
This is the | last line
```

**Comment by ianstormtaylor** [comment]
Are these all inside a single block? Or are they multiple blocks?

**Comment by arekkas** [comment]
Can be both

Gesendet mit meinem HTC

----- Reply message -----
Von: "Ian Storm Taylor" <notifications@github.com>
An: "ianstormtaylor/slate" <slate@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Author" <author@noreply.github.com>
Betreff: [ianstormtaylor/slate] How can I find out if selection is in first/last line and first/last position (#289)
Datum: So., Sep. 4, 2016 02:38

Are these all inside a single block? Or are they multiple blocks?

**Comment by ianstormtaylor** [comment]
If they're all separate blocks it should be pretty simple using `selection.isCollpased && selection.hasEdgeIn(node)`.

But if they're in the same block, I'm not really sure, since it would depend on the CSS applied to know which line the cursor is currently in I'd think. I think at that point it gets custom (outside of core's concerns). But I could be convinced otherwise if there's a simple solution.

**Comment by arekkas** [comment]
@ianstormtaylor thanks for the answer. `hasEdgeIn` is definitely useful. I tried figuring out that stuff (same block) some time ago with contenteditables but never really managed. Is there a way to find the x/y coordinates of the selection?

**Comment by ianstormtaylor** [comment]
Yup! There's is. Check out the hover menu example. I'm not totally sure if it works with collapsed selections on second thought though. Haven't tested it there.

**Comment by uinz** [comment]
Hi, 
How to achieve it in version 0.7?

**Comment by Gab1988** [comment]
In case useful for others my requirement was to determine whether the selection was at the end of the paragraph at any given time
The slice is needed since I had to remove nested paths due to bullet/numbered lists inside my editor

` const point = Editor.end(editor, editor.selection.anchor.path.slice(0, -1));
    const atLastChar = Point.compare(point, editor.selection.focus);`

**Comment by kikouousya** [comment]
a way here
```typescript
export const getSelectedBlock = (editor, selection?) => {
  selection = selection || editor.selection
  const path = selection?.focus?.path
  if (!path) return []
  return Editor.above(editor, {
    at: path,
    match: n => isBlock(n)
  }) || []
}

export const getNodeText = (node) => {
  if (node.text) {
    return node.text
  }
  return node.children?.map(getNodeText).join("")
}

export const selectedLineEnd = (editor: Editor, selection?) => {
  selection = selection || editor.selection
  const [block, path] = getSelectedBlock(editor, selection)
  return Range.isCollapsed(selection) && selection.anchor.offset >= getNodeText(block).length - 1
}
```
