### ISSUE TITLE
Redos are lost when focus is changed

### ISSUE THREAD

**Issue by evasteingrims** [ianstormtaylor/slate#2891]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

A. Redos are lost when trying to undo past the history stack using keyboard shortcut
B. Redos are lost when focus is changed

This is problem in the history example: https://www.slatejs.org/#/history

**To replicate (A):**
1. Type some text
2. Undo past the history stack using keyboard shortcut
3. Click on editor to give it focus and try to redo using keyboard shortcut. It won't work

|Redos are lost when trying to undo past the history stack using keyboard shortcut |
| -- |
| ![slate-issue](https://user-images.githubusercontent.com/11168195/59844738-21c68780-934b-11e9-909d-251cd0792ce7.gif)|
**NOTE**:  This works if you undo/redo using the buttons in the toolbar

**To replicate (B):**
1. Type some text
2. Change focus in the editor by clicking somewhere else
3. Try to redo using keyboard shortcut. It won't work

|Redos are lost when focus is changed |
| -- |
| ![slate-issue2](https://user-images.githubusercontent.com/11168195/59844554-b7ade280-934a-11e9-94ac-7aa9ac594cce.gif)|

Chrome Version 74.0.3729.169
Safari Version 12.0.1 (14606.2.104.1.1)
MacOs 110.14.1 (18B75)

#### What's the expected behavior?

Undo/Redo history should be retained.

**Comment by riosn-n** [comment]
Similar problem occurs if -in the [rich text editor](https://www.slatejs.org/#/rich-text) example- you select a piece of text, mark it as bold, then hit Ctrl+Z twice, Ctrl+Y doesn't work anymore.

**Comment by bryanph** [comment]
It is because setting the selection is seen as an "undoable action" (an operation). We might want to consider separating setting the selection from the operation mechanism and instead infer it from the operations that occur. This could also clear the way to handling multiple selections (such as with OT) in the future?

**Comment by Slapbox** [comment]
If anybody wants an (undocumented) starting point, I'm pretty sure my PR resolves that, but it's outdated and incomplete: https://github.com/ianstormtaylor/slate/pull/2347

**Comment by julienR2** [comment]
thanks @bryanph and @Slapbox for giving some feedbacks and hint to dig the issue.
One thing I still don't get, is why would we wipe the redos ? It doesn't seems the common behaviour on any other editing tools/input/text area

I've been testing to prevent cleaning it (by setting manually `editor.tmp.merge` to `null` using the event `onFocus` and it seems to work fine.. At least I can't find yet any wrong behaviour about it.. Am I missing something ?

**Comment by Slapbox** [comment]
@julienR2 the clearing of redos is just an overlooked scenario for the history management logic, not necessarily intentional. If I recall, it happens because the editor inserts an event into the undo/redo stack when the editor is blurred.

I'm not sure if what you're doing will have side effects, but running the Slate built in tests with the same configuration you're using should give you an idea of what it breaks.

The PR #2347 is pretty much entirely undocumented and out of date, but at the time it fixed that issue with only one test failure.

Unfortunately I won't have time to revisit the issue until some time in 2020, but if anyone wants to work on fixing it, I can provide guidance based on what I recall/what I can decipher of my own work.

**Comment by evasteingrims** [comment]
https://github.com/ianstormtaylor/slate/pull/2948 seems to have fixed **A** but **B** is still not fixed. Redos are lost when there is a selection change. Does anyone know if somebody is working on fixing this?

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Comment by evasteingrims** [comment]
> I believe that this may be fixed by #3093, which has changed a _lot_ of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

This has not been fixed so I created a new issue: https://github.com/ianstormtaylor/slate/issues/3140
