### ISSUE TITLE
Data model "Documents and Nodes" documentation could be clearer

### ISSUE THREAD

**Issue by tomconnors** [ianstormtaylor/slate#2903]
#### Do you want to request a _feature_ or report a _bug_?

Docs

#### What's the current behavior?

The "Data Model" docs page has a section "Documents and Nodes" with some wording that could be cleaned up. Specifically:

> **Blocks may contain either other block nodes, or inlines and text nodes**. This constraint helps you avoid boilerplate if statements. You can trust blocks either wrap other blocks, or contain actual content.

It's not clear from this whether block nodes can directly contain text nodes. If they can, the wording should perhaps be "The immediate children of block nodes may be other block nodes, inline nodes, or text nodes". If they cannot, the wording could be "The immediate children of block nodes may be other block nodes or inline nodes."

> **Blocks and inlines must always contain at least one text node.** This constraint ensures that the user's cursor can always "enter" the nodes and that ranges can be created referencing them.

This one might be improved be specifying that the text nodes don't need to be direct children.

**Comment by tomconnors** [comment]
Sorry for the noise, I understand this now. The first of those, IMO, doesn't drive home the mutually exclusive part hard enough. Perhaps it would be improved by something more explicit like "Block nodes may contain other block nodes, inline nodes, and text nodes. Any particular block node may only contain exclusively block nodes or a combination of inline and text nodes."

**Comment by jorgeavaldez** [comment]
I may also add that I ran into issues comprehending these at first as well. It took multiple readings of this particular section in general.

I think it would be generally helpful to describe these constraints within the individual documentation for the respective nodes, i. e. the Block documentation page should describe constraints for what must be included within a Block node, same for the Inline page, et cetera.

This way I can rely on the individual model documentation instead of needing to also read through the data model documentation when an issue arises as a result of my having only looked at that particular piece of documentation once when I began. While this can definitely be construed as my own fault, having the section under "Guides" is a little misleading.

At this point the value of doing so would only benefit those who are not yet familiar with these intricacies, but in doing so we can help prevent them running into the same pitfalls that I myself have experienced by being explicit up-front within their respective model documentation since it would make sense to check those pages when an issue or questions arise.
