### ISSUE TITLE
placeholder text receives block styling

### ISSUE THREAD

**Issue by RyanEdwardHall** [ianstormtaylor/slate#2908]
I'm assuming this is a bug, at least for me it's really unexpected behaviour. If you go to an example (https://www.slatejs.org/#/rich-text) and delete all the text, you're left with the placeholder text. If you then click a block styling button like h1 or h2, the placeholder text receives that style. I would expect the placeholder text to remain static and that only new input would receive the formatting.

**Comment by brycehill** [comment]
I am experiencing this too in our instance of slate. It's odd, if you look at the rendered HTML, the `h1` tag is never removed:

<img width="651" alt="Screen Shot 2019-10-21 at 9 58 01 AM" src="https://user-images.githubusercontent.com/2396642/67226147-5295f680-f3e9-11e9-873f-86f0ff7236df.png">

**Comment by ianstormtaylor** [comment]
The built-in placeholder is kind of stupid-by-design. It's goal is to match a simple `placeholder=` prop that people are used to from `<input>` or `<textarea>` elements. It's based on having there be no "content" in the editor. Only a single empty block of text to be inserted into.

In this case, it's kind of questionable what to do. The editor is empty, but instead of an empty paragraph there's an empty heading. I think the current behavior is alright by default. If you need any more custom placeholder logic it's up to you to implement your own placeholder. But this sounds like a good question to go into the FAQ probably.

**Comment by VictorBargains** [comment]
I believe this bug was closed prematurely. To me, the core bug is that even though the placeholder message is not part of the `editor.children` value, it gets rendered as if it is. It's a red herring to think of this problem being solved by replacing the Placeholder component with a custom one. The problem is not which component is used. The problem is where the placeholder component is inserted: specifically it is made one of the decorations on the Children component, and it is rendered as the deepest nested leaf node, inside any marks like bold or italic. This is wrong. If it is actually in the rendered Children of the editor, it should be at the root level, or only nested within the root block (paragraph) but not inside any marks or other elements.

I don't understand the Editable.tsx code well enough to propose a fix, but I believe this to be the root cause of the bug.
