### ISSUE TITLE
marks removed cannot be undone

### ISSUE THREAD

**Issue by cvlmtg** [ianstormtaylor/slate#2926]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

if you remove some marks and then press undo, they are reapplied in the wrong way. e.g. go to https://www.slatejs.org/#/rich-text, select some text, add bold, remove bold, then press ctrl-z to undo. the marks are reapplied on the wrong characters

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6401008/61184914-3862b480-a653-11e9-99a8-fa841e1f533b.gif)

info:

* macOS 10.14.5
* Chrome 75
* slate 0.47.4
* slate-react 0.22.4

#### What's the expected behavior?

slate should correctly undo the operation. looks like slate is trying to create the reverse of the last operation applied instead of simply restoring the previous immutable state

**Comment by justinweiss** [comment]
I think this is happening because when the ["split node before", "split node after", "remove mark"] is being undone, it happens as ["add mark", "merge node after", "merge node before"].

Usually, if you merge a node into another node, you'd want it to take on the same marks as the node you're merging it into. Like if you're merging a paragraph into the previous paragraph, and the previous paragraph is bold, you want the other paragraph to be bold, too. During this kind of undo, that doesn't make sense.

I wonder how we could detect those two situations and do something differently?
