### ISSUE TITLE
Slate component handlers should not be required to be pure

### ISSUE THREAD

**Issue by steida** [ianstormtaylor/slate#2927]
From a code, I write, it looks like Slate component handlers are required to be pure. Yep, my code is 💯 React Hooks. When I create a new Slate handler with properly updated closure context, Slate is still using the previous reference. Slate component is not resilient. https://overreacted.io/writing-resilient-components/

This could be solved easily only with refactoring to Hooks and eslint-plugin-react-hooks.

**Comment by steida** [comment]
In other words, Slate should allow dynamic event handlers.

**Comment by josephluck** [comment]
I have come across the same issue in my hooks app as well - it's bad because it means that callbacks passed in to slate (like `handleEditorKeyDown`) must be memoised, which means that they cannot use any dependencies like state or props.

Would be amazing if this was fixed soon - I'm not too familiar with the Slate internals, but happy to help if I can!

**Comment by ianstormtaylor** [comment]
Open to ideas for this. The reason that handlers are memoized is because the handlers actually are combined to create their own "plugin", which affects the schema. And re-computing the plugins stack on every render seemed like a high cost. I can't remember the exact details.

But I'd love to have this restriction removed if possible, if someone wants to look into it.

**Comment by steida** [comment]
@ianstormtaylor I had a similar issue with Slad (my contentEditable experiment) because of how a state is propagated in React. I solved it by maintaining inner editor state.

https://github.com/steida/slad/blob/be99dddb065627ee47a5dd5877e1351bea0ebbb6/packages/slad/components/Editor.tsx#L101

**Comment by newdelop** [comment]
I have a problem that's unrelated and I am brand new at this, so bear with me.  I am having lots of issues with third parties or hackers getting in my phone and installing apps to watch listen steal or copy things from my phone, and they are to control my phone at times what do i do??

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
