### ISSUE TITLE
Can't add more than one mark dynamically to the same block

### ISSUE THREAD

**Issue by mrwnmonm** [ianstormtaylor/slate#2947]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

We are adding marks dynamically in `componentDidMount`  

#### What's the current behavior?
Slate only adds one mark for each block

#### What's the expected behavior?
Slate should add as many marks as we add to the block

![Annotation 2019-07-26 213417](https://user-images.githubusercontent.com/1739939/61976874-3999c700-afed-11e9-9d7d-773dcd894f7c.png)

In the above image, the word **abstract** in the first line should be a mark too, but slate adds only one mark per block.  

Here is our code for adding the marks:

```js
editor.withoutSaving(() => {
  for (const [node, path] of document.texts()) {
    const {text, key} = node;
    const parts = text.split(' ')
    let offset = 0

    parts.forEach((part, i) => {
      const possibleHeteronym = heteronyms[part.trim().toLowerCase()]
      if (possibleHeteronym) {
        let length = part.trim().length
        let mark = Mark.fromJSON({data: {type: 'heteronym'})
        editor.addMarkByPath(path, offset, length , mark)
      }

      offset = offset + part.trim().length + 1
    })
  }
})
```

What is weird is this code works perfectly if you [added annotations instead of the marks](https://github.com/ianstormtaylor/slate/blob/master/examples/search-highlighting/index.js#L188). But unfortunately the serializer doesn't recognize annotations, so it is useless to us. :(

**Comment by mrwnmonm** [comment]
I figured it out. The path can't be the same. So how to do this?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
