### ISSUE TITLE
Feature request: Node depth

### ISSUE THREAD

**Issue by mull** [ianstormtaylor/slate#298]
I see this being mostly useful for blocks, but for consistency I would add it to any node. A clear example where it's useful:

```
type: unordered-list
    type: list-item
        type: text
        type: unordered-list
            type: list-item
```

Now imagine you're working on a list plugin (I am) and you need to figure out how to handle a <TAB> keypress. You need to look at the depth of the current item and the parent item (or in this case parent of parent) to figure out if you can actually go one step "deeper" (i.e. wrap in another unordered-list.)

I would be happy to work on a PR, though I need a tiny bit of guidance, if you feel this is useful. I would add a `depth<Number>` to most of the models and at some point in the code figure out where to add this. Could be an extensive PR I guess. Happy to get pointers!

**Comment by Soreine** [comment]
Hello @mull,

#### Concerning this issue

If we want to get the depth of a node, it could suffice to provide a `getNodeDepth(key)` method on `Node` (hence `Document` too). It is unnecessary  to keep it as property of every model, don't you think ?

#### Concerning lists in particular

I am also working on a [list plugin](https://github.com/GitbookIO/slate-edit-list). I ended up implementing `getItemDepth` myself since I am just interested in counting the nested list items, not the absolute depth of a block (so ignore blocks wrapping the list, and nested blocks inside the leaf list item to measure).

I'll probably open an issue for some features I really miss for my list plugin:
- All the transforms by key, that should be added with the `add-operation` PR. 
- And also a transform that unwrap a single block by key (not the behavior of `unwrapBlockAtRange` which unwrap all blocks of a certain type, or `unwrapBlock` which unwrap only the deepest blocks.

I could still work around this (except for [one issue](https://github.com/GitbookIO/slate-edit-list/issues/13)), but it was cumbersome.

**Comment by mull** [comment]
I wish I had looked at `Node` to see if this existed after you mentioned it in the other issue.

I'm so happy to see that you fixed the behavior in your plugin, now I get to stop working on mine! :-D

**Comment by Soreine** [comment]
:D I'll be happy to receive your input on the plugin (or even contributions ;) )

**Comment by ianstormtaylor** [comment]
Actually there is a `getDepth(descendant)` on `Node` already too :)

**Comment by mull** [comment]
I should be ashamed.
