### ISSUE TITLE
How do you know if the editor has any content

### ISSUE THREAD

**Issue by JinJieTan** [ianstormtaylor/slate#3009]
How do you know if the editor has any content

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by JinJieTan** [comment]
I just want to know how to determine if there is any content in the current editor, because I find that the values generated after I auto-focus to compare are not equal
