### ISSUE TITLE
Chaining insert transforms

### ISSUE THREAD

**Issue by mull** [ianstormtaylor/slate#303]
I'm trying to figure out why I can't call `insertInline(...void).insertText(' some text')` in in one go. It seems like the second call is ignored. Maybe I've missed something in docs or something but this seems like a bug to me.

See this fiddle: https://jsfiddle.net/920ztjzv/1/

**Comment by ianstormtaylor** [comment]
Ah, my guess is that the selection is being set to the inline node itself after inserting, and that `insertText` aborts early when the range is a void node, since it can't contain text. 

After quick research, it seems like across editors the behavior for what to do when trying to insert text on a void node (like an image) isn't really consistent. So I think it's probably good for Slate to disallow it as it currently does, since it would have to get schema-specific to do anything useful.

Does that make sense? Let me know if you think there's something better it could be doing. The workaround would be to ensure that after inserting a void node, you've moved the selection to the text node after it.

**Comment by mull** [comment]
Well what I actually want to do here is insert a void inline and then some text after it. :)

**Comment by ianstormtaylor** [comment]
Ah I see, but you can't because we haven't solved that "add extra empty texts around void inline" issue yet, yeah?

**Comment by mull** [comment]
Thanks ian. Sorry for the stupidity, and thanks for the patience! 😁

**Comment by MaxGfeller** [comment]
@mull An easy workaround can look like this:

```javascript
state
  .transform()
  .insertText(text)
  .moveBackward(text.length)
  .insertInline(whatever)
  .apply()
```

Basically you just insert the text before the inline and then place the cursor back. The only problem with this is that the cursor is not at the right position afterwards.

**Comment by cobbweb** [comment]
@mull Another option, maybe you can leverage `insert{Node|Text}ByKey`?
