### ISSUE TITLE
allow annotations to be serialized/deserialized

### ISSUE THREAD

**Issue by mrwnmonm** [ianstormtaylor/slate#3030]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug.

#### What's the current behavior?
The serializer doesn't recognize annotations.

#### What's the expected behavior?
The serializer recognizes annotations and includes its markup in the output.

While annotations don't exist in the docs, it does exist in the [examples](https://github.com/ianstormtaylor/slate/blob/master/examples/search-highlighting/index.js#L188), but unfortunately, it is not recognized by the serializer or the deserializer.

**Comment by CameronAckermanSEL** [comment]
I'm _pretty sure_ this is a deliberate design decision. Annotations are meant to be throw away, temporary mark up on the document and as a result it's not something that gets exported when the value is converted to JSON, and by extension when the value gets serialized to a different format. Marks would be more appropriate for permanency.

What is your use case for using the serializer?

**Comment by mrwnmonm** [comment]
We convert marks to SSML, we want to apply some marks automatically at the beginning, and for some reason that doesn't work with marks, slate can't mark many words in the block, it just marks the first one.  
But it works with annotations, but annotations are not recognized by the serializer. Maybe we could apply annotations, then we go convert annotations to marks. Will try that.

**Comment by ianstormtaylor** [comment]
I'd be down for the serializers to support annotations. They'd probably end up being serialized similarly to marks. And for deserializing they'd need to be de-duped by `key` to result in a single range. (Probably cheapest way is to just always grow the annotation based on the new `anchor/focus` points.)

@CameronAckermanSEL you're right, but that's for "decorations". Annotations now live in the JSON as part of the data model. (I realize this is a little confusing since they're so close in name! 😄)

**Comment by justinweiss** [comment]
I think it's going to be a little more involved. In order to create an annotation, you need the full path / offset that annotation refers to. But it looks like deserialize doesn't have that context when building up nodes. You'd somehow need to pass partial paths down as you build the tree, or flag all of the annotated nodes somehow and build up the annotations later, right?

**Comment by justinweiss** [comment]
It turns out flagging / fixing works well. I have a PR here: https://github.com/ianstormtaylor/slate/pull/3092

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
