### ISSUE TITLE
[Android] Text corruption and crash when autocomplete

### ISSUE THREAD

**Issue by gracicot** [ianstormtaylor/slate#3046]
#### Do you want to request a _feature_ or report a _bug_?

A bug

#### What's the current behavior?

[video showing the bug](https://i.imgur.com/wuE9iA6.mp4)

Before the text corruption, the text autocompletion I pressed was "J'aimerais".

It happens everytime, Andoid version 9 with Google keyboard on chrome.

It don't seem to happen when there is no letter in the first line.

#### What's the expected behavior?

The expected behavior is to autocomplete the word correctly and not crash.

#### Additional notes

When it happens, I noticed a case of mutation that is not covered in the current android composition plugin.

It assumes that only the first mutation may contain character data:

```js
 const firstMutation = mutations[0]

 if (firstMutation.type === 'characterData') {
     resolveDOMNode(firstMutation.target.parentNode)
 } else ...
```

But when the crash happen, five mutation is applied, and the character data is the last mutation in the list:

```js
[
    MutationRecord {type: "childList"} // removes `<span data-slate-leaf="true" data-offset-key="4:0"><span data-slate-string="true">Jai</span></span>`
    MutationRecord {type: "childList"} // Adds a `<br />`
    MutationRecord {type: "childList"} // adds a text node before the `<br />` containing the text
    MutationRecord {type: "childList"} // Removes the `<br />`
    MutationRecord {type: "characterData"} // character data of the new text node
]
```

My bet it would be that the removal of the leaf and string node without restoring the DOM might be the source of the crash.

**Comment by thesunny** [comment]
@gracicot First of all, thanks for the great breakdown of what is happening with each mutation.

It's been a while, but if I recall correctly, we go through a matching phase to determine what action actually happened when a batch of mutations come in. At this point, we can match against that final `MutationRecord {type: "characterData"}`.

So, when matching we want to be careful that we don't over-match. For example, there may be other cases where the final mutation is a `characterData`. At the very least, after integrating a proposed fix (do this as your final step), run the rest of the composition tests and make sure to go through each tab of tests (Split/Join, Insertion, Special, Empty and Remove) here: https://www.slatejs.org/#/composition/split-join

After you have a match to the autocomplete, you will probably want to do the same as the other diff based mutations. Basically, do a DOM diff, revert the DOM, apply the diff and put the cursor position in the correct place. You should be able to use existing code and there may already be a method defined to do all of it which you should re-use.

Also, you may want to check a number of different autocomplete cases. Like some autocomplete may add several characters, some might simultaneously correct a spelling mistake and therefore may end in a delete mutation. We'd want to catch all the cases related to this.

You are right that it is probably the removal of the lead and string node but will also be the additions as well. Basically, once Android does the mutation, React loses track of everything and its internal pointers can even be pointed at the wrong elements. That's why we have to revert the DOM to an earlier state with all the pointers intact before we let slate carry out the mutation.

Hopefully this is enough to get you going again (responding to your Slack message). If you need further clarification or have some specific questions, let me know.

**Comment by ianstormtaylor** [comment]
Hey, there are lots of open Android-related issues that are out of date with the latest `0.50` release because the codebase was completely rearchitected. We'll need to figure out how to have proper support for Android going forward based on `beforeinput` events somehow. I'm tracking this in https://github.com/ianstormtaylor/slate/issues/3112, so I'm going to close this in favor of that one. 

If it cannot be implemented simply in core with `beforeinput` we'll likely need to have a separate plugin for android support be created, because it's too much of a departure from all of the other simpler logic in core and very hard for me to test or respond to issues. Using a separate plugin should be possible now as the newest version simplifies a lot of the internals.

Thank you for understanding.
