### ISSUE TITLE
Inline image problem.

### ISSUE THREAD

**Issue by stefan1968** [ianstormtaylor/slate#305]
So, I'm having problems with inline images. I use your example code as a template. I replace the insertBlock in the insertImage function to insertInline, and comment out the onDocumentChange that adds a paragraph after an inserted Image. I run the demo, clear the current contents and add an image, but I can't type anything after or before the image. Or even delete the image, it seems stuck.

I'm trying to achieve the functionality of a series of inlines thumbs i can insert at any point and the cursor moves to the end of the images so i can start typing, but something very strange is going on. Can you shed any light?

**Comment by ctrlplusb** [comment]
Hey there, I am sorry to hear you are having problems.  A small tip from my side.  With these types of questions I would definitely consider putting it on Stackoverflow along with a snippet of your code (or an example rep).  Generally I find that I get quicker responses from Stackoverflow than relying on library authors to help me debug my code. Library authors tend to be very busy people. :)  

If the Stackoverflow post doesn't yield any results you could always consider then linking to it via an issue in this (or whatever other) github project.  

Better to have thousands of eyes on your problem rather than one right. :)

**Comment by ianstormtaylor** [comment]
Hey @stefan1968 it sounds like you might be running into the same issue as reported here: https://github.com/ianstormtaylor/slate/issues/234 — closing in favor of that. This isn't yet fixed, but if anyone wants to submit a PR that would be awesome!
