### ISSUE TITLE
renderNode is ignored when used as part of a plugin

### ISSUE THREAD

**Issue by ssalka** [ianstormtaylor/slate#3050]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

OS: macOS 10.13.6
Browsers: Chrome 77.0.3865.90, Firefox 69.0.2
Package versions:
  * react: 16.9.0
  * react-dom: 16.9.0
  * slate: 0.47.8
  * slate-react: 0.22.9

#### What's the current behavior?
Passing a `renderNode` plugin as described in the [rendering docs](https://github.com/ianstormtaylor/slate/blob/master/docs/guides/rendering.md#nodes--marks) has no effect - e.g., when trying to wrap a node in a styled `<span>` below, the resulting elements produced by the editor don't match in the DOM, and instead render under the default behavior.

Please note, I tried to use [this JSFiddle](https://jsfiddle.net/fj9dvhom/1/) from the issue template to demonstrate this behavior, but the dependencies in there are out-of-date/no longer work, and I wasn't able to find a current CDN mirroring of slate & slate-react.

```tsx
function MyEditor() {
  const [value, setValue] = useState(Value.fromJSON({
    document: {
      nodes: [{
        object: 'block',
        type: 'paragraph',
        nodes: [{
          object: 'text',
          text: 'A line of text in a paragraph.'
        }]
      }]
    }
  }));

  const [plugins] = useState([{
    renderNode: props => <span {...props} style={{ color: 'red' }} />
  }]);

  return (
    <Editor
      value={value}
      onChange={change => setValue(change.value)}
      plugins={plugins}
    />
  );
}
```

#### What's the expected behavior?
The given `renderNode` function should be used for rendering nodes - in the case of the above example, all the rendered text should be red.

**Comment by pbackup12345** [comment]
@ssalka This bug is in the documentation. 
Please see [this](https://docs.slatejs.org/walkthroughs/defining-custom-block-nodes). Also [this](https://docs.slatejs.org/slate-react/plugins).
In short `renderNode` was split to `renderBlock` and `renderInline`. You should use those.
Also please pay attention to the proper use of props when creating custom nodes.
You use here `<span {...props} >` whereas you should use `<span {...props.attributes}>`.
It is also described under the first link above. That said it needs to be fixed in the documentation.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
