### ISSUE TITLE
In 'image demo', the control of range is abnormal !!!!

### ISSUE THREAD

**Issue by JinJieTan** [ianstormtaylor/slate#3055]
https://www.slatejs.org/#/images

在这个例子中，当图片和文字一起复制，而且图片是最后一个内容时，粘贴后光标位置不正确.

In this example, when the image and text are copied together, and the image is the last content, the cursor position is incorrect after pasting

我尝试了很多办法，但是当我复制的最后一个内容是图片时，光标任然不正确
![20191009_163025](https://user-images.githubusercontent.com/47209029/66465198-fc54b980-eab2-11e9-8b52-45f80668aa2e.gif)

I tried many things, but when the last thing I copied was an image, the cursor was still incorrect

please help me !! thank you

**Comment by JinJieTan** [comment]
When I paste, the cursor should go after the image, but not to the end of the example 

I used a lot of methods have not solved, so help you, thank you!

**Comment by JinJieTan** [comment]
@tslocke @justinweiss @rgrove sorry, this is a trouble for me , Hope to be advised

**Comment by CameronAckermanSEL** [comment]
What in particular is incorrect about the cursor when the image is pasted at the end of the document?

**Comment by JinJieTan** [comment]
当图像和文字一起被粘贴到末尾时，光标应该在图像后面，而不是前面




When the image is pasted to the end with the text, the cursor should be behind the image, not in front







发自我的iPhone


------------------ Original ------------------

**Comment by JinJieTan** [comment]
In the above demonstration, the second paste, the cursor is incorrect
The cursor should stay behind the image, not in front



发自我的iPhone


------------------ Original ------------------

**Comment by JinJieTan** [comment]
![20191009_163025](https://user-images.githubusercontent.com/47209029/66533346-2f478d80-eb45-11e9-95b0-5d7fc442dd88.gif)

有什么办法，可以解决，上面第二次粘贴造成光标移动到图像前面的问题吗？

Is there any way to solve the above second paste caused the cursor to move to the front of the image?

**Comment by JinJieTan** [comment]
![20191010_152232](https://user-images.githubusercontent.com/47209029/66547547-0ee1f800-eb72-11e9-9638-3ae6007671dd.gif)

图像和文字一起粘贴后，光标始终停留在图片前面，而不是图片后面

When the image and text are pasted together, the cursor remains in front of the image, not behind it

Dear  CameronAckermanSEL 

Can you help me?

**Comment by JinJieTan** [comment]
@kommen @tslocke @justinweiss   can you help me ?

**Comment by CameronAckermanSEL** [comment]
So first, I think it would be good to be a little more patient with other people here. We, like you, all have day jobs and can't immediately drop everything to help as much as we may want to :)

Second, I think this is a support issue. You have been told _repeatedly_ that questions like this need to happen on the slack channel, *not* in a github issue. If you want assistance, the least we ask for is cooperation in using the preferred communication method.

To address this particular error, you might look into a couple things:
1. I believe what might be happening is that the image is being calculated in such a way where it doesn't get inserted into the document immediately on paste so the selection goes to the text block because it's there, and then the image gets inserted later and doesn't move the selection. 

You could address this by writing an alternate paste handler that handles the case where the image being pasted already has a complete image block that doesn't need recalculation

2. You could also write an alternate paste handler that ensures the selection is explicitly moved to the end of the paste fragment at the end of the paste. 

In both cases you probably want to consult the paste example and write a paste handler based on that

**Comment by JinJieTan** [comment]
Thank you, I'm doing that, but how do I get the content of the picture when I mix it with text?

**Comment by JinJieTan** [comment]
I tried to solve this problem by rewriting the handling of the paste event. But do I think the paste example of that picture should be modified? Or I have a submission request

**Comment by JinJieTan** [comment]
I have a very perfect solution for rich text paste copy image code, can I submit it? ?
