### ISSUE TITLE
better integrate with React Hooks

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#3056]
#### Do you want to request a _feature_ or report a _bug_?

Improvement.

#### What's the current behavior?

The `slate-react` library was written before hooks, and while we were still tied to Immutable.js. It would be nice if it was written to accommodate React Hooks better. I haven't figured out exactly how this would work while still solving for the constraints we have with plugins...

But if people have ideas I'd love to hear them!

**Comment by steida** [comment]
In my editor, I decided to replace plugins with editor reducer, but it's still an idea need to be validated. As for Slate, I highly recommend Eslint react-hooks/exhaustive-deps plugin. The issue you are probably will fighting is whether reregister all listeners on any state change or not. Reregistering should be cheap, but probably error-prone. That's why useReducer is so useful, dispatch always preserves its identity. I am still not sure whether it's ideal because when Editor has two states, inner and outer. But it works for my use case, so it's probably OK. Another potential catch is useEffect versus useLayoutEffect. In my Editor, it forced me to split Editor to client and server versions, which was actually a very good design decision solved another issue related to SSR. From my point of view, you will have to decide how much you want to change how Slate is designed. If as minimal as possible, you can rewrite it to hooks easily, but you will have to use useRef everywhere.

https://twitter.com/dan_abramov/status/1102010093388947457?lang=en

**Comment by ianstormtaylor** [comment]
@steida in your editor can plugins override other plugins's event listeners?

I'm down with changing the architecture to accommodate hooks if it makes the architecture better for sure. Can you example more about how the reducing architecture works? and the client vs. server versions?

**Comment by steida** [comment]
As for reducer, the basic idea is that "plugin" must be a pure function because reducer must be pure. Instead of listeners, there are actions. The whole reducer is pluggable and composable, so it should work. But as I said, it's an experiment, let's see.

As for client and server version, it's explained here: https://github.com/steida/slad/blob/master/packages/slad/components/Editor.tsx#L18

I must highlight that all I am doing right now is just changing text, no further modifications yet. I started with Mutation Observer for everything, but it was a mistake. It's almost impossible to distinguish changes made by a user and changes made by something else. So I refactored everything to beforeinput. I will not support IE nor Edge (old one), and the good news is Firefox started implementing before input several weeks ago. I also decided not to use Immer, because 1) console.log sucks even with `original` helper 2) it encourages writing code which is not composable. Functional optics are much better. You can use Slad as an inspiration, it's still very young and simple.

**Comment by ianstormtaylor** [comment]
Can you explain the Immer anti-composability argument? Curious about that. 

Do plugins in your editor have the ability to override functions from other plugins, but then call back into the they want? For example like someone overriding the `splitBlock` command to handle the special case of splitting in lists or tables.

**Comment by steida** [comment]
I understand this architecture seems not to be as easy to use as Slate plugins are. But it's all about the right API which will emerge once we will have solid primitives.

**Comment by steida** [comment]
@ianstormtaylor I deleted my answers because of your behavior.

**Comment by ryanmitts** [comment]
I think I read that plugins will be moving to a different approach like composition, is this hook rewrite intended to happen before or after that change? I have some ideas around hook, but depending on how the plugin structure will be I don't know if it's worth looking into how.

**Comment by ianstormtaylor** [comment]
@ryanmitts great question! I don’t have anything planned for hooks so far, so after. 

The one thing I’m wary of with hooks is that it seems like potentially the most “hook-native” API would need to be entirely implemented in hooks? Not something we want to do since non-React use cases are important. 

At this point I’m mostly interested in hearing other people’s thoughts on what the best hook-based API would be. So I’d love to hear what you’re thinking!

**Comment by ryanmitts** [comment]
Could you have a 'special' plugin for the editor that allows setting and changing the implementations of the various callbacks/handlers passed into the editor? You can use hooks to only re-set the handlers when they change.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
