### ISSUE TITLE
Up and Down key not working in custom block

### ISSUE THREAD

**Issue by hitochan777** [ianstormtaylor/slate#3059]
I have a custom block that shows `+` icon on the left of the actual content, as shown below.
But when I try to move up and down with arrow keys it just loses focus. Without the `div` tag containing `+` it works fine.  
Is this related to [the tutorial document](https://docs.slatejs.org/walkthroughs/defining-custom-block-nodes#defining-custom-block-nodes) that says as below?
> You must render the children as the lowest leaf in your component.

![slate_up_key](https://user-images.githubusercontent.com/6002787/66575099-52f3ed80-ebb0-11e9-9839-39b748aa4adc.gif)

```jsx
const LineBlock = props => {
  return (
    <div {...props.attributes}>
      <div style={{display: "flex"}}>
        <div>+ </div>
        <div>{props.children}</div>
      </div>
    </div>
  );
};
```

- [Reproduction code in Codesandbox](https://codesandbox.io/s/dark-sunset-qsupn)
- Environment: 
  - OS: MacOS
  - Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
  - Slate version: 0.47.8

#### Expected Behavior
I can move a cursor up and down with arrow keys.

**Comment by CameronAckermanSEL** [comment]
Hi, this is because of the way content editable works. Content editable wants to be able to put the cursor where the + character is on the DOM, but the slate model doesn't recognize that as a valid selection area because there's no node representing the + character. 

You might be able to get away with making the + user-select: none in css, but this might have some weirdness in different browsers. The other thing you can do is render the + outside of the editor, but that'll also be complicated and have some downsides.

The checkbox list example might give you some examples on how to deal with this problem.

**Comment by hitochan777** [comment]
@CameronAckermanSEL Thank you so much for your help. 
I looked at the checkbox list example and basically I need to set `contentEditable` to false to the components I don't want slate to recognize as a valid selection. I am right?
