### ISSUE TITLE
How to DIY my schema attribute?

### ISSUE THREAD

**Issue by imcuttle** [ianstormtaylor/slate#3107]
I want to DIY my schema like `isVoid`, then we could write some schema plugin like `isVoid`.

```javascript
const myBlockPlugin = {
   schema: {
           blocks: {
                'block-tag': {
                    // Note here
                    isWhole: true,
                    parent: {object: 'document'}
                }
            }
   },
  // ...
}

plugins: [
   isWholeSchemaPlugin(),
   myBlockPlugin()
]
```

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
