### ISSUE TITLE
Android and annotation don't work together

### ISSUE THREAD

**Issue by victorpavlenko** [ianstormtaylor/slate#3111]
#### Do you want to request a _feature_ or report a _bug_?
BUG

#### What's the current behavior?
On android, do not work correctly if annotations are installed
Any version of android

#### What's the expected behavior?

[http://www.giphy.com/gifs/MC8lXkg4y62loF9R8W](url)
Blue underlining and yellow highlighting are annotations. 
As the cursor moves, it comes to the highlight annotation, and jumps back.
If I try to position the cursor after the highlight annotation, it jumps to the beginning again.

**Comment by Dalzhim** [comment]
@victorpavlenko : I have never seen Android annotations before and the URL you have provided does not work at this moment. Could you please enlighten me?

**Comment by ianstormtaylor** [comment]
Hey, there are lots of open Android-related issues that are out of date with the latest `0.50` release because the codebase was completely rearchitected. We'll need to figure out how to have proper support for Android going forward based on `beforeinput` events somehow. I'm tracking this in https://github.com/ianstormtaylor/slate/issues/3112, so I'm going to close this in favor of that one. 

If it cannot be implemented simply in core with `beforeinput` we'll likely need to have a separate plugin for android support be created, because it's too much of a departure from all of the other simpler logic in core and very hard for me to test or respond to issues. Using a separate plugin should be possible now as the newest version simplifies a lot of the internals.

Thank you for understanding.
