### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by tar-aldev** [ianstormtaylor/slate#3115]
#### Do you want to request a _feature_ or report a _bug_?
Bug

[codesandbox](https://codesandbox.io/s/vigilant-northcutt-14fzb)
Information about your OS, browser, Slate version, etc.
ubuntu 18.04, Chrome, 
"slate": "^0.47.9",
 "slate-react": "^0.22.10",

#### What's the current behavior?
When new value is selected I fire toggleMark with new data, but font size remains the same(It adds extra span with new style, but previous one is still in the dom)

#### What's the expected behavior?
Should be able to change font size either by toggle mark or in any other way.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
