### ISSUE TITLE
Writing HTML inside markdown

### ISSUE THREAD

**Issue by jacargentina** [ianstormtaylor/slate#3127]
I need to be able to write HTML inside my Markdown, using [rich-markdown-editor](https://github.com/outline/rich-markdown-editor)
 
How to ?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
