### ISSUE TITLE
Editor broken(including examples on slatejs.org)

### ISSUE THREAD

**Issue by jessekelly881** [ianstormtaylor/slate#3145]
Currently all of the examples on slatejs.org are broken and when trying to use slate I get  "Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":18}"

**Comment by DamareYoh** [comment]
Hi @jessekelly881 , thanks for filing the issue. It's hard to diagnose your issue with the lack of information you provided. All of the examples are currently working for me. 

Please fill out the information missing on the template, at least with some information about the browser your using.

**Comment by jessekelly881** [comment]
Hey. Apologies. The browser I am currently using is google chrome "Version 73.0.3664.3 (Official Build) dev (64-bit)" I update my browser and see if that fixes things.

**Comment by jessekelly881** [comment]
Working well with Google Chrome version 78. Sorry again for the bother. Although, a little more back comparability seems needed. Chrome version 73 is only a few months old and slate is completely unusable on it.

**Comment by DamareYoh** [comment]
No bother at all, thanks for the follow up :)

**Comment by ianstormtaylor** [comment]
This likely because we rely on `beforeinput` events, maybe 73 hadn't had those yet. But either way, I think the market share of 73 is very low. (This is only a problem for the latest rewritten version of Slate, if you need older browser support use `0.47`.)

**Comment by saltire** [comment]
I'm seeing this issue on some of the examples. If I try to make a selection that includes a checkbox in the Checklists example, or the video in the Embeds example, OP's error message shows up in the console. This happens in both Firefox 70 and Chrome 78.

Also, clicking a checkbox gives me `i.findPath is not a function`, though that may or may not be a separate issue.

**Comment by cshen4** [comment]
I also have the above mentioned problem, i see the error `editor.findPath is not a function` when i run the examples repository and click on the checkbox in the Checklists example.

**Comment by focux** [comment]
I'm also having this issue. If you go to the mention example in slatejs.org and select a mention it crashes.

**Comment by gotoprototype** [comment]
I have this issue in the _images_, _Embeds_ and _Mentiones_ with all browsers I tested it with:

- Chromium 78.0
- Firefox 70.0
- Firefox 71.0
- Firefox Nightly 72.0

Couldn't reproduce on the _Checklists_ example.
---
However I found a makeshift solution:
**Give the `Element` nodes child an non empty string as text:**
`children: [{ text: 'NOTEMPTY', marks: [] }]`
even an blank space is enough.

I forked @focux sandbox, so others can easily test it themselfs:
https://codesandbox.io/s/great-cloud-8jbry
The `R2-D2` mention works now, the `Mace Windu` still crashes, because it's children text is an empty string.


e.g.
https://github.com/ianstormtaylor/slate/blob/31df397930c7515e0bc7832f972d5b44473d024d/site/examples/images.js#L75

https://github.com/ianstormtaylor/slate/blob/31df397930c7515e0bc7832f972d5b44473d024d/site/examples/mentions.js#L157

It also has to be changed in the initialValue JSON objects:
https://github.com/ianstormtaylor/slate/blob/31df397930c7515e0bc7832f972d5b44473d024d/site/examples/embeds.js#L119

**Comment by focux** [comment]
I was able to track down the error at least in the mention example, maybe could be related to the others one.

https://github.com/ianstormtaylor/slate/blob/31df397930c7515e0bc7832f972d5b44473d024d/site/examples/mentions.js#L198
For some reason when I remove that line and pass the mention name through the children text property, it works perfectly. It seems that Slate isn't able to find the node if you click a text that wasn't added by a children text element.

I'm not sure but I think that there's additional metadata that Slate isn't able to get when you add the text directly in the element component.

**Comment by Josh-McFarlin** [comment]
Was this fixed? Still getting the error `TypeError: editor.findPath is not a function` even if the text is not empty.

**Comment by antonstjernquist** [comment]
Why was this closed? This is still an issue for me, and what it looks like for a few other people?

**Comment by Josh-McFarlin** [comment]
@antonstjernquist is your issue findPath? You should use ReactEditor.findPath(editor, ...)

**Comment by antonstjernquist** [comment]
> @antonstjernquist is your issue findPath? You should use ReactEditor.findPath(editor, ...)

Nope, my issue is:
`Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":33}"`

Chrome 73

**Comment by hannahblair** [comment]
> > @antonstjernquist is your issue findPath? You should use ReactEditor.findPath(editor, ...)
> 
> Nope, my issue is:
> `Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":33}"`
> 
> Chrome 73

Same is happening for me too, on Chrome 75.

**Comment by arel** [comment]
Same is happening to me on Chrome 79. I'm getting the `Cannot resolve a DOM point from Slate point...` error simply by setting the editor value. For instance,

```javascript
const [value, setValue] = useState(
  [
    {
      type: 'paragraph',
      children: [{ text: '' }],
    },
  ]
);

<Slate editor={editor} value={value} onChange={v => {
  window.prevValue = value;
  window.nextValue = v;
  window.setValue = setValue;
  setValue(v);
}}>
  <Editable />
</Slate>
```

If I type any string in the editor and try to set the state to a previous value I get the same error:
```javascript
// in console (after entering some value in the editor):
setValue(nextValue)  // works
setValue(prevValue)  // throws "Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":8}"
```

**Comment by joshtronic** [comment]
> If I type any string in the editor and try to set the state to a previous value I get the same error:
> 
> ```js
> // in console (after entering some value in the editor):
> setValue(nextValue)  // works
> setValue(prevValue)  // throws "Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":8}"
> ```

troubleshooting a similar issue myself. seems to be related to the cursors position when going to the next state. if you go from a long string with the cursor near the end of the line then set the value to a shorter bit of text (in my case resetting back to the initial state to clear the editor) then slate freaks out.

when I move the cursor to the start of the line before resetting it, things work as expected. speculative solution for me is to move the cursor back to the beginning of the line before doing the reset.

**Comment by CameronAckermanSEL** [comment]
Hey guys, I'm going to close this thread for a couple of reasons:

1. The original issue that was opened was related to the user trying to use slate 0.5x with Chrome73. Chrome 73 doesn't have the `onBeforeInput` event that slate needs to function on chrome, therefore 0.5x is not supported on that version (or any version of chromium lacking `onBeforeInput`). The issue was closed because that was the resolution.

2. The issue people seem to continue posting about here is an unrelated issue with regards to `cannot find path` errors. These errors as far as I have read in this thread are universally caused by users attempting to `setValue` or change value state **without immediately reconciling selection to a valid path**. The selection is managed internally by slate, and is not managed by the value any longer. So if you change the value without repairing an invalid selection, you get this issue.

Please continue this conversation in another issue if you so desire, but the fix is to select something else.
