### ISSUE TITLE
slate-schema validation does not respect children's `min` prop

### ISSUE THREAD

**Issue by flavordaaave** [ianstormtaylor/slate#3165]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

![](http://g.recordit.co/q6dXlmyTWt.gif)

See [https://www.slatejs.org/examples/forced-layout](https://www.slatejs.org/examples/forced-layout)

Slate: 0.50.0
Browser: Safari & Chrome
OS: Mac

#### What's the expected behavior?

When deleting the `title` block a `child_min_invalid` error should be thrown.

**Comment by dmarkow** [comment]
It seems that some of the min/max counting isn't dealing with the `match` part of the rule properly.

Here's an example child_min_invalid test that should pass but doesn't. Since there is no `<element b>` the validation should fail.

Given the following test:

```js
export const schema = [
  {
    for: 'node',
    match: { a: true },
    validate: {
      children: [
        { match: { b: true }, min: 1 },
        { match: { c: true }, min: 1 },
      ],
    },
  },
]

export const input = (
  <editor>
    <element a>
      <element c>one</element> // test passes if I make this <element b> instead
    </element>
  </editor>
)

export const output = <editor />
```
- Validation should fail and the test should pass since there is no `<element b>`, but it doesn't. The test fails, leaving `<element c>` in the output.
- If you remove the `match` part of each rule (so it's just two `min` rules) the test passes.
- If you change `<element c>` to `<element b>` the passes.
