### ISSUE TITLE
fix "inline" to match only inlines, not texts

### ISSUE THREAD

**Issue by objectlegal** [ianstormtaylor/slate#3191]
Currently, it seems as text elements are included in certain inline queries.

For instance, the hasInline method includes texts:
```
hasInlines(editor, element) {
    return element.children.some(function (n) {
      return Text.isText(n) || Element.isElement(n) && editor.isInline(n);
    });
}
````

In a similar manner, matching for 'inline' returns the current text node with the below code, if the selection is within a text of a paragraph (i.e. no "classic" inline such as a `link` is present).
```
ec.match(editor, editor.selection.anchor.path, 'inline')
```
(Interestingly enough, when the anchor is placed within a text of an inline, the above code actually returns the inline).

It might be that the behaviour described is intended, but otherwise I suggest to make a clearer distinction between inlines and texts, so that inlines are queried with .hasInlines and matched with .match(editor, path, 'inline') on the one hand, and texts are queried with .hasText and matched with .match(editor, path, 'text') on the other hand

/Mewle

**Comment by ianstormtaylor** [comment]
Hey @objectlegal, thanks for opening this, I totally agree.

The current "inline" vs. "text" concept isn't as clear as I'd like. The one complicating factor is I couldn't find a good word to refer to "either inline or text elements"—in other words elements that flow as inline elements in the document. That concept is one that's often used instead of explicitly inline or explicitly text nodes.

Do you have any naming ideas?

There's also the confusion between "highest" or "lowest" inline/block in the tree. I had originally been having the `'inline'` keyword be the "highest inline" and the `'block'` keyboard be the "lowest block" because those are the 90% cases. But that's definitely not that clear.

**Comment by objectlegal** [comment]
Thanks. 

I am having difficulties as well coming up with a clear cut name. In such situation, I think clarity should trump brevity, so we could go with `inlineOrText`, `non-block` or something of the like. 

I agree regarding the last matter; that seems to me to be in line with most use cases. IMO, its fine to keep it that way (documentation could explain this) but in order to cater for the other cases, it might the worth adding a forth argument to the match method, giving the user the ability to choose `asc` or `desc`

**Comment by ianstormtaylor** [comment]
Having a fourth argument is a great way to do it. Once #3184 is done we can make the argument `'highest'` or `'lowest'` and potentially have `Editor.match` delegate straight to `Editor.nodes` instead of re-defining it's logic.

Actually, I totally forgot too that with #3174 we can do `['text', 'inline']` and avoid having to come up with another keyword entirely!

**Comment by objectlegal** [comment]
Great!

When discussing the topic of matching, I've figured that the Editor.match and Editor.nodes methods could be enhanced so that:

.match could take the editor.selection as the `at` argument, returning matches throughout the selection

and/or

.nodes could take a filter function as a second argument. Example usage to retrieve all paragraphs in the selection:
```
Editor.nodes(editor, (node) => node.type === 'paragraph')
```

**Comment by ianstormtaylor** [comment]
Actually it does take an `at` option, which defaults to the current selection. And the `match` argument can be a function that receives `([node, path])`.

**Comment by ianstormtaylor** [comment]
Fixed in https://github.com/ianstormtaylor/slate/commit/ea62ad9e4419be2370426009c511fbea9f7daa19
