### ISSUE TITLE
Changes to the defaultValue prop are not detected by the Slate React 

### ISSUE THREAD

**Issue by DamareYoh** [ianstormtaylor/slate#3200]
#### Do you want to request a _feature_ or report a _bug_?

Bug/Feature/Discussion :)

#### What's the current behavior?

Currently, if a user updates the `defaultValue` prop on the `<Slate>` component, this change is not honored. This precludes a user from being able to control the state of the editor in any way that originates from outside the Slate context.

I am unsure if this is deliberate, but I'm pretty sure it's because this memo call is only keying off the editor component

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/hooks/use-slate.tsx#L38

Slate: 0.50
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

#### What's the expected behavior?

Generally, uncontrolled components have a contract where changing the `defaultValue` prop resets the component state to use that value. I think users would generally expect that to be the case with the `defaultValue` prop for the `<Slate>` component.

**Comment by DamareYoh** [comment]
That said, the react documentation on the uncontrolled component pattern does not explicitly mention this at all https://reactjs.org/docs/uncontrolled-components.html#default-values

**Comment by ianstormtaylor** [comment]
Oh weird, I thought `defaultValue` was meant to not be changeable except for the very first render? Based on [this](https://github.com/facebook/react/issues/4101#issuecomment-111307019) but I couldn't find a more recent statement. 

I'm down to have it mimic whatever the React behavior is though.

And separately if people want to open an issue for making `<Slate>` controlled instead of un-controlled I'm down to discuss it!

**Comment by DamareYoh** [comment]
A number of folks on stack overflow seem to disagree with me that this is an idiomatic behavior for react, so seems like the `<Slate>` component is doing the right thing for `defaultValue` https://stackoverflow.com/questions/30727837/react-change-input-defaultvalue-by-passing-props/41962233

**Comment by PeterKottas** [comment]
This was discussed at length yesterday on slack. Basically the train of thought is we should have a controlled version of the slate. Reasoning:
a) What if you sync state with the server via signalR (realtime colaboration editor)
b) What if you fetch data from API? Now you have to not render until final data is available Which seems a little bit hacky. 

The bottom line is there is currently no way of changing the value from outside. I am happy to provide more examples @ianstormtaylor if needed. This issue is a little bit awkwardly named IMHO. The defaultValue is fine as far as I can tell, but there definitely should be a way to control the editor state from outside.

**Comment by zz373609** [comment]
> Oh weird, I thought `defaultValue` was meant to not be changeable except for the very first render? Based on [this](https://github.com/facebook/react/issues/4101#issuecomment-111307019) but I couldn't find a more recent statement.
> 
> I'm down to have it mimic whatever the React behavior is though.
> 
> And separately if people want to open an issue for making `<Slate>` controlled instead of un-controlled I'm down to discuss it!

what if I want to have the value from one request, is any props I can pass in, otherwise, how Cn I load the value from backend

**Comment by PeterKottas** [comment]
Just for the sake of argument, right now to make it work, I've added a slateStateTimestamp to my store which is simply utc timestamp of when was the data last fetched. This timestamp is then used as key for the Slate instance. Every time I fetch fresh data, I update this value. It works well but understandably, it's quite hacky.

**Comment by zz373609** [comment]
it is like too hacky, why it is not provide a value props or something, it is like too react

**Comment by PeterKottas** [comment]
Cause it's in beta buddy, a lot of people are trying to figure out a lot of stuff. It's never easy.

**Comment by bmingles** [comment]
I read a bit about defaultValue this morning, and sounds like the standard behavior for uncontrolled components is what @ianstormtaylor had originally thought. Changing `defaultValue` is only intended to set the initial value and does not trigger a re-render on change. 

So, seems like that may not be the mechanism for this. I was able to work around this by changing the `key` prop whenever my `defaultValue` needs to change which seems consistent with how uncontrolled components work in React. That said, it would be good to have an api specifically for setting the value from an external change.

**Comment by bmingles** [comment]
I've created #3209 to discuss API design in a more general way since the behavior of `defaultValue` seems to be as expected and consistent with other uncontrolled components.

**Comment by DamareYoh** [comment]
I think for the time being it seems like the proposal is not idiomatic for React. Closing
