### ISSUE TITLE
Plugin that uses custom elements (Mark|Element ...)

### ISSUE THREAD

**Issue by PeterKottas** [ianstormtaylor/slate#3204]
#### What's the current behavior?
The plugin system changed recently, and while I like the "compose" nature of it, I believe there's one crucial thing missing (or I am missing it). Previously, the plugin could hook into render(Mark|Element). Now, this is not possible. Therefore if your plugin contains functionality to augment this functionality, you have to 
a) Know about it
b) Create something along the lines of:
```
renderElement = (props) => {
    const { attributes, element, children } = props;
    const comp = BlockStyleElement(props)
      || LinkElement(props)
      || ImageElement(props)
      || VideoElement(props)
      || MentionElement(props)
      || EmojiElement(props)
      || <div {...attributes}>{children}</div>;
    return addAlignmentStyles(element, comp);
  }
```

What if at some point, the plugin that previously didn't rely on rendering logic suddenly adds one with new release. You need to manually figure out what's going on and fix it which can create room for mistakes.

Slate: 0.50.9
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

#### What's the expected behavior?
Maybe I am missing something, but I think there should be a way to add this stuff from inside the plugin, thus making it the responsibility of the plugin author to set everything up.

I could imagine something along the lines of:
```
withPlugin(editor: Editor) {
  // This would add the component to an array, and cycle around it checking for nulls and moving forward.
  editor.addRenderMark(myRenderMarkFunctionality);
  return editor;
}
```

**Comment by timothyarmes** [comment]
I understand what you’re saying, and it’s a bit of a surprise at first. Personally though I find this clean seperation between editor behaviour and rendering to be clean - there’s nothing hidden going on and the code’s much easier to understand at a glance.

It also allows you to, for example, use a plugin for certain behaviour, but render the element yourself. That will make it much easier to use third party plugins. I previously used DraftJS plugins, but it was awful since they pulled in loads of stuff that I didn’t want (such as a different JS to CSS layer).

Now it’s just functional composition for behaviour, with plugins adding useful commands. Any other features are exported separately. Simple, and it’ll be much easier to maintain the project, which means there’s less likelihood of it being abandoned. This is a good thing too :)

**Comment by PeterKottas** [comment]
I understand all of that, not saying it doesn't make sense, but still, some of the points I made I believe stand. Especially the notes about 

> What if at some point, the plugin that previously didn't rely on rendering logic suddenly adds one with new release. You need to manually figure out what's going on and fix it which can create room for mistakes.

**Comment by zbeyens** [comment]
I also like the plugins defined in a single place, at the moment I am creating some helper functions so it behaves a bit like before. For example, I like to encapsulate everything related to image in `ImagePlugin`: editor logic, toolbar button, default component, etc.

Example interface:
```js
interface Plugin {
    [key: string]: any;
    editor?: PluginEditor;
    renderElement?:
      | ((props: CustomElementProps) => JSX.Element | undefined)
      | undefined;
    renderMark?:
      | ((props: CustomMarkProps) => JSX.Element | undefined)
      | undefined;
    onKeyDown?: (e: any, editor: Editor) => void;
  }

export const ImagePlugin: (options: { component, type }) => Plugin
```

For the rendering, a user can overwrite the default component and other options. Note that there is no tree-shaking in the case that the user doesn't want at all the plugin rendering logic.

So we would have to export as well `withImage`, `ImageRenderElement`, `ImageRenderMark` etc. There we have SoC and the best of both worlds (0.47 vs 0.50)

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/issues/3177 because I think it's a duplicate
