### ISSUE TITLE
Lazy loading Slate components that are offscreen?

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#3234]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Offscreen components must be rendered to DOM (it seems)

Slate: 0.45.1
Browser: Electron
OS: Windows

#### What's the expected behavior?

I don't know what behavior I'd expect with my code exactly as written, but I'm not clear on _why_ this fails. It fails with: `Error: Unable to find a DOM node for "179". This is often because of forgetting to add `props.attributes` to a custom component.`

```js
return (
  <LazyLoad
    placeholder={<MyPlaceholderComponent {...attributes} />}>
    <MyActualComponent {...attributes} />
  </LazyLoad>
)
```

Is there some way to make this work? I'm confused as to what _exactly_ is going wrong here, which makes it tough to move forward on.

**Comment by Slapbox** [comment]
Closest thing we can do now appears to be:

```js
return (
  <LazyLoad
    placeholder={<MyPlaceholder {...attributes}>{children}</MyPlaceholder>
    <MyActualComponent {...attributes} />
  </LazyLoad>
)
```

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
