### ISSUE TITLE
Attempted import error

### ISSUE THREAD

**Issue by qprquo** [ianstormtaylor/slate#3241]
#### Do you want to request a _feature_ or report a _bug_?
report a bug

#### What's the current behavior?
when trying to
`import { createEditor } from 'slate'`

getting this error:

`/node_modules/slate/dist/index.es.js
Attempted import error: 'createDraft' is not exported from 'immer'.`

Slate: 0.50.8
Browser: All
OS: Windows 

#### What's the expected behavior?
Has to be imported properly

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
