### ISSUE TITLE
how to trim all the paragraph blocks? 

### ISSUE THREAD

**Issue by JasLin** [ianstormtaylor/slate#3245]
#### Do you want to request a _feature_ or report a _bug_?

question or Bug ?

#### What's the current behavior?

we want to trim all the paragraph'text 

```js
trimText = (event) => {
  event.preventDefault();
  const { editor } = this;
  const { value } = editor;
  const { document } = value;
  document.nodes.forEach(node => {
    if (node.type === 'paragraph' && !!node.text) {
      const path = node.getPath(node.key)
      const marks = node.getMarks()
      const end = node.text.length
      editor.replaceTextByPath(path, 0, end, node.text.trim(), marks)
    }
  })
}
```
but, it could not get path correctly while nodes iterate, it raised Error:

```js
Uncaught Error: `Node.assertDescendant` could not find node with path or key: List []
```

Slate: 0.47.8.
Browser: Chrome 
OS: Mac 

#### What's the expected behavior?

trim all the ```paragraph``` block's text

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
