### ISSUE TITLE
HTML serializer is missing

### ISSUE THREAD

**Issue by ejoebstl** [ianstormtaylor/slate#3246]
Not a bug or request, rather a question related to development:

It looks like the [HTML serializer](https://github.com/ianstormtaylor/slate/blob/6fc0bc85e6b02c81db84a781f01f51ed249a0173/packages/slate-html-serializer/src/index.js) was removed recently.

Is there an alternative? 

Why was it removed?

**Comment by ianstormtaylor** [comment]
The HTML serializer was removed because it was clunky to use, hard to debug, finicky across environments, etc. With the simplified data model in `0.5X` you can achieve the same end result in much less code by writing the serializer yourself as a simple function, since it's almost fully custom logic that is schema-dependent.

The same goes for deserializing from HTML, which can you do using a simple function and the help of the `slate-hyperscript` package.

Check out the [Serializing](https://docs.slatejs.org/concepts/09-serializing) guide for more information about serializing/deserializing.

**Comment by ejoebstl** [comment]
Exactly what I wanted to know - thank you!
