### ISSUE TITLE
markdown-shortcuts.js is does't work

### ISSUE THREAD

**Issue by vc2008man** [ianstormtaylor/slate#3267]
when i copy the example/markdown-shortcuts.js source code.
it does't work. the error message like
![image](https://user-images.githubusercontent.com/2211185/70368594-9b493680-18e7-11ea-88e0-d48322b328ce.png)

whats wrong with me? and what can i do to fix it? thanks.

my env:
MAC OS \ Chrome \ React v16.12.0

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by vc2008man** [comment]
> Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions.
> 
> However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help.
> 
> Thanks for understanding!

OK.
Slate is a gooooooood editor~ i'm excitement when i find it.
and i think i found what happened about my question, but i have no idea to fix it ,so sad! whatever, thanks a lot. thank u for ur reply.
