### ISSUE TITLE
Support for migrations

### ISSUE THREAD

**Issue by PeterKottas** [ianstormtaylor/slate#3272]
#### Feature request
I've been thinking about how I could make the usage of slate in production easier for me (and possibly others). The thing is:

- There are quite a few breaking changes. 

In terms of code, I don't mind it that much. Yeah, it's a pain and it's all for a good reason. I am fine with that.

- These breaking changes often change the structure of the editor state.

Now, this, in my opinion, is a problem. The state is often persisted in various storage (server/client side) and as a result of these changes, companies, especially the ones that have a lot of data, can run into trouble. Also, it is not always clear how and when the state structure changed. Yes there is the changelog which is extremely useful, but it requires some serious time to investigate and act on these changes.
I am suggesting a way to potentially mitigate this:
Create slate-migrations package
This package would simply contain a folder migrations, and for each braking change in the state, a new migration would be created and placed in this folder. The interface for a migration could look something like:
``` typescript
export interface Migration {
  // Semver range
  fromVersionRange: string;
  // Semver single version
  toVersion: string;
  migrate: (value: any) => any;
}
```
Notice the 'any' for value, we obviously can't strongly type migrations as it would reference a code that could have changed in the meantime.
Slate could then take an extra field 'migrations' which would be an array of migrations.
The state of the editor would have to change from an array of nodes to an object in order to keep the version in it. So:
``` typescript
{
  version: '0.52.2', 
  children: Node[]
}
```
Would effectively become the value of the editor. The version could be picked up from the package version of slate.
When first initialized, the Slate could look at the version and the migrations field, try to migrate and if it succeeds, it would then use the migration chain to migrate the value to the most recent state.
It would be fully up to users to include as many migrations as they want (if any).
I have previously successfully implemented something like this here:  
https://github.com/react-page/react-page/pull/554#issuecomment-413847279 It also contains some pseudo-code on how the migrations would work.

I'd like to know what you all think about this. Please note that while this is an extra package, and some extra code, the maintenance would be minimal, as migrations are pretty much 'create once and never touch again' kind of thing. The added responsibility of creating migrations might suck a little bit, but it has great value for users. Also to create migrations is actually not too much work. Check for instance the migrations here: 
https://github.com/react-page/react-page/tree/master/packages/plugins/content/slate/src/migrations
these actually handle the changed slate state for versions around 40 (I don't remember which exactly).
Also if we have the information of the version on the state, we can gracefully fail and provide information on the reason for the failure if it failed because the state is incompatible.

I am happy to implement this functionality but before I start the work, I want to make sure it's ok with everybody here.

**Comment by PeterKottas** [comment]
I think the most important thing we have to discuss here is the fact we would have to change the state from an array back to an object. To be honest, I prefer an object anyways as it gives you a chance to attach metadata to the whole state. Otherwise, it's pretty damn difficult to figure out where to put stuff like the version for instance. I know some time ago, it used to be an object. I don't know the reason why it was changed to an array but unless it was extremely important, I think it brings value to switch it back.

**Comment by PeterKottas** [comment]
@ianstormtaylor , I've implemented some of the work on my fork. I just need a little bit of guidance in terms of changing the value to an object. I am not sure if I should simply use Node type for the value instead of Node[]. Or if I should introduce a new Document thing that would, for instance, look something like this:
``` typescript
export interface Document {
  version: string;
  [key: string]: any
}
```
I think there's value in having an explicitly typed version on the thing, but there's obviously a bunch of ways of doing this, I just want to chose "the expected one" right from the beginning. Cheers!

**Comment by ianstormtaylor** [comment]
I'm not sure this is something that should live in core.

Slate's position now that it uses an interface-based API is that it helps you model your own domain as JSON. There are lots of custom properties in the data model, and any of them could also be involved in migrations. Especially the more Slate settles on the new data model, the more likely those changes are going to be userland migrations and not migrations to Slate's core interfaces.

So I think a migrations tool like this should live in userland instead.

For the `version` property. I think that too is something that can be controlled however people want to do it, and doesn't necessarily need to live directly correlated with the `children` nodes. For example, in your database you might store a document as:

```js
{
  data: [...],
  version: '1',
  created_at: '2019-12-08T19:22:53Z`
}
```

Using your own version scheme, because any changes to custom properties will also necessitate migrating the data. And any extra properties like `created_at`, etc. would also live there. But then when you create an editor, you don't need to actually pass in any of that extra stuff, just the `data`.

You might also decide to version by date (like Stripe) instead of by a number, so that you versions look like `'2019-12-08'`.

And most of the time you'll want the migrations to be one-off functions that you migrate everything one time, and not go up/down for each request.

All of it is very domain-specific.

The actual migration functions, which convert data between versions of Slate's core data models, sound very useful. And those could easily live in a `slate-migrations` package if someone wants to maintain that. People would then import them whenever they need to change versions if something has changed, and run them against their database. But they wouldn't need to store a version number anywhere unless they wanted to, since they always know what version they are on.

**Comment by PeterKottas** [comment]
Fair enough, tbh, I am mostly motivated to do this for my own benefit (while of course happy to share if others find it useful). That means I am ok with doing this on my side. All you're saying makes perfect sense, I understand you want to avoid bloating the core. One thing I'd say though is something like this will likely be used by many. At least by many who use this tool in real-world apps. And to maintain custom logic (or 3rd party packages) to deal with changing nature of the slate-specific state (which could be consider API to an extent) might be confusing. Also, this can demotivate users to upgrade to the recent version (something that I believe happened with gitbook for instance, although based on their manifest, maybe that was also about API changes).

The thing is, having this included officially might serve as a good motivation for people to adopt. Something along the lines of "If we breaking-change, we'll help you migrate out of the box" is quite tempting.

Worst case, I am happy to help maintain slate-migrations if nothing else. To go back to version, I'd prefer to keep the version as slate version. To put it simply, this is all about slate-version. If the schema of the state never changed, we wouldn't need this functionality. And this way, it would be straight forward to reason about this and point at the changelog for details. It is true though, that versions could mean for instance adding or removing plugins in the user-land. But tbh, I see that as a slightly different topic. That is something that people have under their control. The major thing I see as a problem now is **Hardship of upgrading slate versions**. I would really like to make that process smoother.

**Comment by PeterKottas** [comment]
Btw my current code for Migrator @justinweiss . It would be great to see if you are doing something extra that I am missing.
``` typescript
export interface MigratableState {
  version: string
  [key: string]: any
}

export interface MigrationResult {
  changed: boolean
  migratedState: MigratableState
}

/**
 * @class the class used to migrate plugin content between toVersion
 */
export class Migration {
  fromVersionRange: string
  toVersion: string
  migrate = (state: MigratableState): MigrationResult => ({
    changed: false,
    migratedState: state,
  })

  constructor(
    toVersion: string,
    fromVersionRange: string,
    migrate: (state: MigratableState) => MigrationResult
  ) {
    if (
      !migrate ||
      !toVersion ||
      !fromVersionRange ||
      semver.valid(toVersion) === null ||
      semver.validRange(fromVersionRange) === null ||
      semver.lt(toVersion, fromVersionRange)
    ) {
      throw new Error(
        `A migration toVersion, fromVersionRange and migrate function must be defined and proper, got ${JSON.stringify(
          { migrate, toVersion, fromVersionRange }
        )}`
      )
    }
    this.toVersion = toVersion
    this.migrate = migrate
    this.fromVersionRange = fromVersionRange
  }
}

export const Migrator = {
  migrateState(
    state: MigratableState,
    migrations?: Migration[]
  ): MigrationResult {
    let migrationResult: MigrationResult = {
      migratedState: state,
      changed: false,
    }
    if (!migrations) {
      return migrationResult
    }
    if (!state || !state.version || semver.valid(state.version) === null) {
      console.warn(
        'State or state version not defined when attempting to migrate.'
      )
      return migrationResult
    }
    let currentDataVersion = state.version
    while (true) {
      const migration = migrations.find(m =>
        semver.satisfies(currentDataVersion, m.fromVersionRange)
      )
      migrations = migrations.filter(
        m => !semver.satisfies(currentDataVersion, m.fromVersionRange)
      )
      if (!migration) {
        // We assume all migrations necessary for the current version of plugin to work are provided
        // Therefore if we don't find any, that means we are done and state is up to date
        break
      }
      currentDataVersion = migration.toVersion
      migrationResult = migration.migrate(migrationResult.migratedState)
    }
    return migrationResult
  },
}
```

**Comment by ianstormtaylor** [comment]
I totally understand what you're saying. 

And I see why people would want free help with migrating. But I've tried to make very clear that Slate is in beta—that breaking changes will occur—and I don't have the bandwidth to maintain code that I myself don't need. When I migrate anything that lives in the database I write a small script to perform the migration and that's it. If there are things that need to be migrated over time, I'll write a small utility and place it on the code path to make it seamless (like you're describing), and then remove it when the migration is complete. 

But these things are **always** domain-specific. 90% of the migrations people will be performing going forward will be for userland requirements changing, not something Slate is concerned with.

For almost all of the changes to the data model pre-`0.5X` (or maybe even all) the changes were backwards compatible. Because people had to call `Value.create` it was simple to make this work by using warnings. With `0.5X` there was a massive change to the data model and thus the one-time migration is harder.

Granted it was a huge change, but it was a one-time huge change. That doesn't mean that Slate's core should all of a sudden take on the complexity of making arbitrary changes seamless to migrate across any version for people. We're biased by the one-time change being very recent, but it's still uncommon. And that's a lot of extra scope. 

It's fine if someone wants to take on that burden, but I can't justify it.

---

Instead, if people want to think about what a low-cost solution is... 

I think it's pretty clear that it would be valuable if someone wrote up a simple script that took `0.47` data and transformed it into `0.5X` data. It can live in a Gist and be shared in the Slack channels. I can even put a link to it in the pinned issues. And the maintenance cost would be near-zero, but we'd receive 90% of the benefits.

There are often solutions for these kinds of one-off tasks that don't need to be solved by taking on high-cost additions to core.

**Comment by PeterKottas** [comment]
Sure, makes sense. Happy to keep it on my end then. Maybe the code I posted here will be useful for some folks. Quick question, when you do migrations, do you migrate on the database side? Or do you simply keep the state in the db as is and add the front-end javascript migration which, when saved updates the state in the db? I am just curious because, in your comment, you said:

> and then remove it when the migration is complete.

In my case, it would be kind of hard to figure out if all data indeed has been migrated (if it happens solely on the front end side). Use cases vary though of course.

**Comment by ianstormtaylor** [comment]
I'll usually add a one-way shim to make it seamless on the frontend first, then run a full migration on the database, and then remove the shim afterwards. That way you only have a small period of time where the data is in an unknown state while transitioning, instead of keeping old versions forever. But the transition itself is still without downtime.

If your use case gives the data directly an end user to use though you'd need something more seamless because you can't upgrade out from under them.

And if your use case doesn't involve processing the data anywhere except to render an editor on the frontend you could get away with just a shim and keep older versions in the database forever.

**Comment by PeterKottas** [comment]
Thanks Ian. I think I can figure out some sort of combination of both, but for the time being, I guess the shim will be enough.

**Comment by oyeanuj** [comment]
@PeterKottas Did you ever end up creating any kind of package for migrations?

**Comment by PeterKottas** [comment]
@oyeanuj Nothing freestanding that can be used solely by slate, but you can check https://github.com/react-page/react-page/tree/b6c83a8650cfe9089e0c3eaf471ab58a0f7db761/packages/plugins/content/slate/src/migrations for an example of migrations and https://github.com/react-page/react-page/blob/db777ca3df54b3547adf7f6b3b9988bc63f1b7da/packages/core/src/service/plugin/classes.ts searching for "migration" for implementation. Not sure if that helps but it's the best I have :)

**Comment by webel** [comment]
@PeterKottas appreciate you sharing those files, I'm trying to migrate from 0.33 to the current version and you've given me a nice starting point!

**Comment by webel** [comment]
Here's what I ended up with: https://gist.github.com/webel/545f229fe79c2176dbaed9023de46e12

**Comment by PeterKottas** [comment]
@webel You're welcome. Glad it helped and ty for sharing your version.
