### ISSUE TITLE
Slate Plain Serializer attemp import error

### ISSUE THREAD

**Issue by tolgaistinyeuniv** [ianstormtaylor/slate#3295]
Hello, what I try to do is I try to get data from slate editor and send via ajax. 
I tried to install slate-plain-serializer, to use Plain.deserialize, but didn't work.

What should I try, or test?
Thank you.

```
./node_modules/slate-plain-serializer/lib/slate-plain-serializer.es.js
Attempted import error: 'Block' is not exported from 'slate'.
```

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by PrimeObjects** [comment]
I have this issue as well, it worked in the previous version.
it is a simple import 
import { Block } from 'slate'

**Comment by KASOGIT** [comment]
Same error coming from nowhere, someone knows what to do ?

**Comment by jjcroftiv** [comment]
I ran across this too.  In the recent versions, > .50, you don't need the plain or html serialization packages.  See docs: https://docs.slatejs.org/concepts/09-serializing.
