### ISSUE TITLE
How to insert an node like <hr />

### ISSUE THREAD

**Issue by gyh9457** [ianstormtaylor/slate#3306]
#### Do you want to request a _feature_ or report a _bug_?
One question. I have asked on slack, but unfortunately no one has answered it so far.

![image](https://user-images.githubusercontent.com/13557235/70693174-e4d6be80-1cf7-11ea-8663-d72ee7b5054d.png)

#### What's the current behavior?
as the picture shows。

I want to know how to insert an `<hr />` . I looked up the examples but didn't get inspired, 
I try to use insert_node , but I don't know what node should look like

`editor.exec({` type: 'inser_node'}, node: /** `??*/);

`Or is there any relevant reference material, I have read the documentation several times

I also looked at some other repositories,  like https://github.com/Canner/canner-slate-editor, but the api seems to change a lot.

Slate: 0.53.0
Browser: Chrome  Windows

#### What's the expected behavior?
Some inspiration

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
