### ISSUE TITLE
should selection.marks be null by default?

### ISSUE THREAD

**Issue by mull** [ianstormtaylor/slate#331]
It seems counter-intuitive. Wouldn't an empty Set/List make more sense? I'm not seeing where the `null` value makes sense, and what one can get out of it (rather than just checking for an empty list.) 

I think this was introduced in 0.14, but maybe I'm wrong. :)

**Comment by ianstormtaylor** [comment]
👍  I agree! Sorry about that, for some reason I thought the `null` was the value being used normally.

Are you down to make the PR?

**Comment by ianstormtaylor** [comment]
Looking into this, I realized why this is the case. When `selection.marks == null`, that is because no marks have been applied to the collapse cursor, such that when new text is inserted it will inherit whatever marks were in the document at the insertion points.

However, when `selection.marks` is an empty `Set`, it means that the cursor specifically has an empty set of marks associated with it, such that even if the insertion point has marks, when text is created it will have no marks added.

So we actually need the distinction I think.

**Comment by mull** [comment]
Thanks! Sorry for not responding with a PR 😞

**Comment by ianstormtaylor** [comment]
No worries at all, I know it's a bigger ask than it feels like 😄
