### ISSUE TITLE
path of rendered element

### ISSUE THREAD

**Issue by cvlmtg** [ianstormtaylor/slate#3335]
#### Do you want to request a _feature_ or report a _bug_?

feature

#### What's the current behavior?

currently an element being rendered receives two props: `element` and `attributes` and this makes impossible to create interactive elements. in the previous version of slate this was possible because each node had a `key` property and it was possible to operate on the node like e.g. `editor.setNodeByKey(node.key, node);`

Slate: 0.55.2
Browser: all
OS: all

#### What's the expected behavior?

each element being rendered should receive a `path` props or some other mean to make it possible to operate on that element

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by cvlmtg** [comment]
@ianstormtaylor Hi, actually mine wasn't a usage question, it's the request for a feature that was present in the previous release and that is currently missing. Maybe did I describe it poorly?
