### ISSUE TITLE
editor.selection is delayed so selection is undependable to find current element

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3338]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

Press a cursor key and the cursor position is not updated in `editor.selection` for between 100ms and 200ms on a fast computer.

This causes funkiness like holding down `tab` in a table. We read the current `td` and move to the next but because of the slow selection updates, the cursor jumps several times to the same `td` because it is returning the old selection (i.e. cursor has moved but we keep getting the `td` from before the move because of the old selection).

Also the cause of other issues to do with cursor movement.

Slate: 0.55.3
Browser: Chrome
OS: Mac

#### What's the expected behavior?

In earlier Slate like 0.47, the `editor.selection` was updated within a `requestAnimationFrame`.

**Comment by thesunny** [comment]
I think I found the cause of the delay and it's in the `debounce` in the `onDOMSelectionChange` method here https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editable.tsx

@ianstormtaylor I noticed that you switched lodash's `_.throttle` to the `debounce` package and this is probably what is causing the issue. Looking at the docs, lodash's throttle invokes on both the leading and trailing edge of the call by default and you are using the default call. This means that in 0.47 we get the first selection change immediately.

This differs from `debounce` which always waits until [x]ms has ellapsed before firing for the first time.

Are you okay with switching back to `lodash's throttle method?

**Comment by ianstormtaylor** [comment]
Hey @thesunny thanks for investigating this. If I remember right, there was some reason I ended up using `debounce` instead of throttle, but I can't remember why.

I think the _ideal_ would be to use neither, and just let the code run very frequently? But I feel like I remember there being an issue with that too (other than performance, which I'm okay to wait and see if it's even a problem).

If you can verify that switching to `_.throttle` fixes it I'm down to revert that. Although I'd prefer to use a smaller dependency, since it seemed like `lodash` was always really complex to ensure that the bundle size stayed small.

Ideally I'd love to get rid of throttling or debouncing entirely.

**Comment by thesunny** [comment]
There's two ways to keep the bundle size small.

1. Use the npm package `lodash.throttle` which is just the throttle code extracted.
2. Use the `lodash` package but import it with a path like `import throttle from 'lodash/throttle'`

I tend to use #2 in my code because I get access to other `lodash` methods when I need them without having to add more packages; however, if `throttle` will ever be the only import, it's probably better to use the `lodash.throttle` package.

Which one makes more sense for `slate`?

**Comment by ianstormtaylor** [comment]
The 2nd one sounds good to me.

Yeah I'd love to see both of them removed instead.
