### ISSUE TITLE
Calling Editor.setNodes from inside onChange causes swallowed exception or freezes the browser

### ISSUE THREAD

**Issue by sirgru** [ianstormtaylor/slate#3366]
Bug report.

https://codesandbox.io/s/slate-reproductions-ddlpy
![http://g.recordit.co/jtObeBxRHK.gif](http://g.recordit.co/jtObeBxRHK.gif)
To reproduce:
Click the text. The value is printed to the console. The property wasn't set. Move the line 26 down. Click the text again. The value should be printed to the console, but it isn't. 
This in on version 0.57. On 0.54 whole browser freezes, like there is an infinite loop.

Browser: Chrome
OS: Windows

**Comment by sirgru** [comment]
Added gif.

**Comment by CameronAckermanSEL** [comment]
Hey @sirgru . I took a look and I think the problem you're experiencing is that the change you're applying in this onChange is then causing the editor to fire yet another onChange that reprocesses the mutation logic. In short, it is indeed an infinite loop problem.

My suggestion is that instead of doing mutations in onChange, you should find a more specific event handler to apply mutations. This affords a couple of benefits
1. onChange is kept as efficient as possible. onChange gets fired every single time the editor state changes in any way and logic in there is a hot spot on a flame chart.
2. You avoid most of these infinite loop problems. For instance, mutations in response to an onKeyDown handler may fire an onChange, but it'll only go through that life cycle once.

I'm going to close this issue. Please feel free to ask for it to be reopened if you feel more discussion is warranted.
