### ISSUE TITLE
Attempted import error: 'Value' is not exported from 'slate'.

### ISSUE THREAD

**Issue by thaind97git** [ianstormtaylor/slate#3378]
Hello, when I try to parse `Slate value` into html using `slate-html-serializer`. But I recieved an error like this:
```
./node_modules/slate-html-serializer/lib/slate-html-serializer.es.js
Attempted import error: 'Value' is not exported from 'slate'.
```
My code:
```
import HTML from 'slate-html-serializer';

<Slate editor={editor} value={value} onChange={value => {
      const html = new HTML();
      console.log(html.serialize(value))
      setValue(value)
}}>
```

**Comment by cvlmtg** [comment]
@thaind97git are you perhaps using slate-html-serializer with slate > 0.47 ?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
