### ISSUE TITLE
Strange cursor position when inline-block followed by text

### ISSUE THREAD

**Issue by LiuJi-Jim** [ianstormtaylor/slate#3390]
#### What's the current behavior?

cursor moves to the upper edge of paragraph, when it is next to an inline-block element and previous to text.

\[inline-block\](cursor)\[text\]

for example 
![image](https://user-images.githubusercontent.com/2749742/71471242-daddb100-2809-11ea-8b47-6c7a84d4609e.png)
to make it more clear, i make the mention element taller.

Slate: 0.57
Browser: Chrome
OS: Mac

#### What's the expected behavior?

cursor should align to text correctly.

**Comment by sgurenkov** [comment]
This is browser default behavior I believe. You’ll need some css trick to fix it

**Comment by thesunny** [comment]
Since this is a browser issue, I'm going to close unless someone can figure out a way to solve this in a generic way; however, I would consider experimenting with using `line-height`, `margin-top`, `margin-bottom` as well as vertical alignment and positioning to see if it can be fixed for your particular case.

If you do find a solution, may be worthwhile to create a PR that would solve this issue in the examples.

**Comment by he110vv0r1d** [comment]
@LiuJi-Jim hello, this bug has bothered me too, is there any solution to fixed it?
