### ISSUE TITLE
Can not open slatejs example in Edge browser

### ISSUE THREAD

**Issue by wenyuyangpku** [ianstormtaylor/slate#3400]
Can not open [slatejs example](https://www.slatejs.org/examples/richtext) in Edge browser.

![image](https://user-images.githubusercontent.com/47671625/71650038-6e6b2200-2ce1-11ea-9a2a-450bc9ebe200.png)

**Comment by Killavus** [comment]
This is because Slate-React is being bundled with target TSconfig set to `esnext`. You may want to change that to `ES6` - this way object spread in `Editable` component will get transpiled properly.

Editor is still kind of broken after that, though. I'm looking for polyfills necessary to make it usable for now.

**Comment by DamareYoh** [comment]
does it work on the chromium based edge? I suspect the legacy edge is unlikely to be supported out of the box

**Comment by stephenjelfs** [comment]
@DamareYoh You're quick: I think the "legacy" non-chromium Edge has only been "legacy" for a couple of hours! It would still be nice to get this fixed, if possible, for people who like to support at least the latest two versions of Chrome, Firefox and Edge :)

**Comment by tylde** [comment]
It is possible to change in tsconfig from `esnext` to `es6`?
