### ISSUE TITLE
Super confused about adding node data.

### ISSUE THREAD

**Issue by Hammond2789** [ianstormtaylor/slate#3420]
```
onUpdateData = (key, value) => {
    this.state.editor.setNodeByKey(nodeKey, value);
  }
```
So the nodeKey is correct, the value is just an object, but during deserialize/serialize the data is not there. Am I doing something wrong here?

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
