### ISSUE TITLE
Unexpected scrolling when type any character

### ISSUE THREAD

**Issue by sorokinvj** [ianstormtaylor/slate#3427]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

When type (any character) page is scrolling somewhere on the center of text

On the screencast I'm typing 'S' and the page scrolls

![ScreenFlow](https://user-images.githubusercontent.com/4914235/72356250-db6ab880-36e0-11ea-910b-d084be26df78.gif)

Minimal repo - https://codesandbox.io/s/github/sorokinvj/slate-bug/tree/master/?fontsize=14&hidenavigation=1&theme=dark

Slate: "0.57.1"
Browser: Chrome Version 79.0.3945.117 (Official Build) (64-bit)
OS: Mac 10.14.6

#### What's the expected behavior?

no scrolling when typing 
(may be only when the text is on the last visible line in a viewport)

**Comment by sorokinvj** [comment]
I tried it without styled-components, same result – when text is bigger that viewport scrolling is happening

**Comment by ryanmitts** [comment]
This happens when a single element is taller than the scrollable area. Each time there is a selection (like after typing a key), Slate tries to scroll the mid point of the element as much as it can to the middle of the screen if either the top or bottom of the element is not within the viewable area of the editor.

From playing around with this issue, it seems like that is the behavior that would be most desired for most situations and the easiest to implement for Slate (it's a single line to the `scroll-into-view-if-needed` library).

Maybe I'm making an assumption, but in most rich text documents, would large walls of text usually be broken up into paragraphs that aren't likely to span the entire viewable area? In that case, the issue will not appear.

I can fix the issue in the demo you have by checking if the bounding box of the selection range is above or below the scrollable area of the viewport, and then scrolling the element into view only if it isn't, and scrolling to the top of the element if the selection is closer to the top, and to the bottom if the selection is closer to the bottom.

This however makes the assumption that a Slate document only cause the body of the page to scroll, and it wouldn't ever be within a nested element that scrolls.

Maybe a prop to the Editable can be added or something that is a callback to scroll a leaf into view when Slate needs to, using custom logic for someone's use case where they can make an assumption about how the editor is placed and used.

**Comment by sorokinvj** [comment]
Hello Ryan,

Thanks for your detailed answer! While reading I thought – "Oh maybe I prepare data for Slate in a poor way. In fact I have only one paragraph which really extends the boundaries of a viewport, what happen if I make just inline elements out of source text?". I tried to implement this idea, but it got even worse, now text, after first typed symbol, is just disappearing:

https://codesandbox.io/s/blissful-jackson-ote1r?fontsize=14&hidenavigation=1&theme=dark

> I can fix the issue in the demo you have by checking if the bounding box of the selection range is above or below the scrollable area of the viewport, and then scrolling the element into view only if it isn't, and scrolling to the top of the element if the selection is closer to the top, and to the bottom if the selection is closer to the bottom.

Could you please share a piece of code, how can I do I that? Shall I override Editor with some disableScroll function? Or it is a window.scrollIntoView that needs to be overridden?

**Comment by ryanmitts** [comment]
@sorokinvj 

Glad you got it working.

[This](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editable.tsx#L197) is the part that is causing the issue with your original example.

In your case, since you can assume that the entire body of the page is the scrolling element, you can do something like this:

```
if (newDomRange) {
      domSelection.addRange(newDomRange!)
      const leafEl = newDomRange.startContainer.parentElement!
      const rangeBoundingRect = newDomRange.getBoundingClientRect()
      const viewportHeight = window.innerHeight
      const leafElBoundingRect = leafEl.getBoundingClientRect()
      const selectionAboveViewport = rangeBoundingRect.top < 0
      const selectionBelowViewport = rangeBoundingRect.top - viewportHeight > 0
      if (selectionAboveViewport || selectionBelowViewport) {
        scrollIntoView(leafEl, {
          scrollMode: 'if-needed',
          block: selectionAboveViewport ? 'start' : 'end',
        })
      }
    }
```

Which made me think a hook here that someone can choose to override the scrolling logic might be cool.

**Comment by arcanis** [comment]
The hook would be useful, I find the current behavior a bit surprising. In my case the editor doesn't take the full height, but it doesn't matter: if the active block container isn't entirely in the viewport (for example if only 5 out of 6 lines are displayed), typing will cause the scroll to change in rather extreme ways.

I wonder if a mix of your snippet and [this one](https://gist.github.com/alisey/3744577) would work, but I'm not sure I can integrate it cleanly at the moment without a proper hook 🤔
