### ISSUE TITLE
Decorators do not work if renderLeaf function is memoized

### ISSUE THREAD

**Issue by ryanmitts** [ianstormtaylor/slate#3447]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

If the `renderLeaf` method is memoized, then decorators will not be rendered.

https://codesandbox.io/s/slate-decorator-usecallback-bug-fv18m

Slate: 0.57.0
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

#### What's the expected behavior?

The decorators are rendered.

#### Notes

This appears to be because Text elements do not take into account the decorator list to determine if they should re-render or not. The current search highlight example is making use of the fact that `renderLeaf` is changing every render.

**Comment by mpkelly** [comment]
Odd one as my own code looks like:

```
  const renderLeaf = useCallback(
    (props: RenderLeafProps) => handleRenderLeaf(props, plugins),
    []
  );

  const decorate = useCallback(
    (entry: NodeEntry) => handleDecorate(entry, plugins, editor),
    []
  );
```
And decorate is working fine. I am not doing a search but I am doing on-the-fly code highlighting which works without any issue. 

The sandbox does work if you use `[search]` instead of `[]` as the dependency arg for the `useCallback` call for `renderLeaf`, though my understanding is that an empty array should be fine here, too. Using `[search]` will at least avoid the unnecessary re-renders that would happen without memoizing.

**Comment by bartzy** [comment]
@mpkelly are you using 0.57.1, or a version from master?
I get the same behavior as @ryanmitts

**Comment by mpkelly** [comment]
Hi @bartzy, I am using `0.57.1` My code is actually on Github now. See [here](https://github.com/mpkelly/react-editor-kit/blob/master/packages/editor-kit/src/editor/Editor.tsx) and [here](https://github.com/mpkelly/react-editor-kit/blob/2c4aae42af99894ebd4ac325596e11f9c195fcce/packages/editor-kit/src/features/code/CodeHighlighterPlugin.tsx#L66).

**Comment by bartzy** [comment]
That's really weird. As soon as I add useCallback to renderLeaf,
decorations stop updating. Any idea what can cause that?

**Comment by bartzy** [comment]
@mpkelly Is it possible that your leaf/element component(s) are just getting rerendered on every change for some other reason, and that's why decoration works?

**Comment by mpkelly** [comment]
@bartzy decorating only fires on change AFAIK. I think any time the text content in the editor changes the decorate callback should fire though I don't think it will fire if only the selection changes. This is how it works for me anyway. I am using decorate in a code highlighter component and decorations are applied on initial load of the editor as well as in real-time when I type into the code block.

**Comment by bartzy** [comment]
@mpkelly I don't think that's the intended behavior, though (fire decorate only on change). Take the Search highlighting example - no changes are made to the document when searching, but it should fire the decorate method. The reason it fires is because the renderLeaf function is not memoized (as @ryanmitts noted).

**Comment by mpkelly** [comment]
@bartzy decorate is a callback function so it can only fire after some sort of change or event. Note that I am including initial load (or more accurately, initial render) as a change, too. 

The reason the search example works is because the call to `setSearch` re-renders the `<Editable/>` which then triggers a call to `decorate`. You always need to trigger a re-render in someway. For me that's happening on text input but maybe even just clicking is enough. I don't know how Slate manages this internally. 

You will probably get more answers on the [Slack channel](https://slate-js.slack.com/).

**Comment by bartzy** [comment]
@mpkelly You can take a look at @ryanmitts example in codesandbox. It's the search highlighting example with `renderLeaf` wrapped in `useCallback`. It still re-renders with setSearch but decorations no longer work.

**Comment by mpkelly** [comment]
@bartzy I'm not disputing there is a bug. I looked at this sandbox already when I first found this issue. All I am saying is that it's now broken in every case as it works in my project even though I use `useCallback`. 

If you're blocked then your best bet is to fork Slate and apply Ryan's fix (see pull request above) and then build Slate yourself.

**Comment by bartzy** [comment]
Sure, thanks!

**Comment by usunil0** [comment]
I faced the same issue, solved it by using @mpkelly 's solution.

> Odd one as my own code looks like:
> 
> ```
>   const renderLeaf = useCallback(
>     (props: RenderLeafProps) => handleRenderLeaf(props, plugins),
>     []
>   );
> 
>   const decorate = useCallback(
>     (entry: NodeEntry) => handleDecorate(entry, plugins, editor),
>     []
>   );
> ```
> 
> And decorate is working fine. I am not doing a search but I am doing on-the-fly code highlighting which works without any issue.
> 
> The sandbox does work if you use `[search]` instead of `[]` as the dependency arg for the `useCallback` call for `renderLeaf`, though my understanding is that an empty array should be fine here, too.


also i had to pass `[search]` into the renderleaf 
```
   const renderLeaf = useCallback(
   (props: RenderLeafProps) => handleRenderLeaf(props, plugins),
     [search]
   );
```

**Comment by yume-chan** [comment]
Looks like this has already been fixed. I updated versions of slate dependencies in the CodeSandbox and it correctly updates highlights when searching.

https://codesandbox.io/s/slate-decorator-usecallback-bug-forked-qwrkie

![image](https://user-images.githubusercontent.com/1330321/186649725-c7aa4b18-a31b-4ba2-9f9d-31b78cd5207b.png)
