### ISSUE TITLE
Toggling a Mark Blug

### ISSUE THREAD

**Issue by camdagr8** [ianstormtaylor/slate#3455]
#### What's the current behavior?
When I try to toggle a substring of a mark, it blows up with the following error:

```
Cannot resolve a DOM node from Slate node
```

####  Here's my code for toggling the mark:
```js
import op from 'object-path';
import { Editor, Transforms, Text } from 'slate';

export const isMarkActive = (editor, format) => {
    const marks = Editor.marks(editor) || {};
    return op.get(marks, format, false) === true;
};
export const toggleMark = (editor, format) => {
    const isActive = isMarkActive(editor, format);

    Transforms.setNodes(
        editor,
        { [format]: isActive ? null : true },
        { match: Text.isText, split: true },
    );
};
```

#### Screen Recording
<img src="http://g.recordit.co/CZMLyp9Pot.gif" />

#### System:
Slate: 0.57.1
Browser: **Chrome** / Safari / Firefox / Edge
OS: **Mac** / Windows / Linux / iOS / Android

**Comment by camdagr8** [comment]
Never mind, I had a bug in my <Leaf /> component.

**Comment by cs-intellineers** [comment]
@camdagr8 I realize this is a few months old but can you generalize the bug you had and tell how you solved it?

I have the same error showing up when I click in an image node (data-slate-node="element" data-slate-void="true").
I believe I am not setting this properly to being void and that is the reason I have this issue but I am lost at this point.
And your issue is the only link that shows up when googling `Cannot resolve a DOM node from Slate node`

**Comment by cs-intellineers** [comment]
@camdagr8 Sorry for bothering you. I resolved this issue. I checked the [image example](https://github.com/ianstormtaylor/slate/blob/master/site/examples/images.js) again.
I had to wrap my image tag (`<img [...] />`) in two `div`s in order to add the `children` and I should have attached the `attributes` to the outermost `div` instead of the `img`.
