### ISSUE TITLE
Editor.nodes function doesn't return the node.

### ISSUE THREAD

**Issue by neohotsauce** [ianstormtaylor/slate#3481]
```
const isBlockActive = (editor, format) => {
  const [match] = Editor.nodes(editor, {
    match: n => n,
  })
  console.log(match)
  return !!match
}
```
I am getting `undefined`, I am supposed to get the node. :l
I cloned it from [richtext.js](https://github.com/ianstormtaylor/slate/blob/master/site/examples/richtext.js)  but the `isBlockActive` function doesn't seem to work.

**Comment by neohotsauce** [comment]
its an issue with gatsby,

**Comment by kwhitejr** [comment]
@neohotsauce I tried using this solution with the [Hover Toolbar](https://github.com/ianstormtaylor/slate/blob/master/site/examples/hovering-toolbar.tsx#L45) example, to no avail. Curiously, the following log never runs
```
const isBlockActive = (editor, format) => {
  let match = false
  for (const [node, paths] of Editor.nodes(editor, {
    match: n => n.type === format,
  })) {
    console.log(node); // this log never runs, which leads me to believe the block as a whole never runs.
    if (node.type === format) match = true
    break
  }
  return !!match
}
```

Any thoughts? Been scratching my head for a while.

**Comment by styxlab** [comment]
There seems to be an issue with `Editor.nodes()` function when used in `Next.js` too as it always returns `undefined` on first render. Like for Gatsby this is most likely due to SSG. My current workaround is to use pure js instead:

```
const isBlockActive = (editor, format) => {
   const index = editor.children.findIndex(node => node.type === format)
   return index >= 0
}
```
But I think we should dig further into the `Editor.nodes()` function in order to find the root cause.

**Comment by styxlab** [comment]
Turns out my issue does not have anything to do with SSG, the issue is that `Editor.nodes` returns `undefined`, if `editor.selection` is null (the current element is not selected). This can happen easily, if you have a button on an image element.

https://github.com/ianstormtaylor/slate/blob/228f4fa94f61f42ca41feae2b3029ebb570e0480/packages/slate/src/interfaces/editor.ts#L849

This can be mitigated by providing an optional `at` property. However, I think this behaviour is not intuitive at all. The default behaviour should be that the entire tree is selected.

**Comment by JanStorm** [comment]
In my opinion, this function has to use editor.selection, because we only want to mark the format buttons as active, when user has a element selected, which uses the format. (So he then could toggle it off) In my solution i only use only the cursor position, but it seems to work for me.
In this workaround im searching in the editor.children for the format myself:
```js
const isBlockActive = (editor: Editor, format: string) => {
    const cursorPosition = editor.selection?.focus;
    const elementPath = cursorPosition?.path;
    let match = false;
    if (elementPath && elementPath.length > 0 && editor.children) {
        let element: any = editor.children[elementPath[0]];
        for(let i = 1; i < elementPath.length; i += 1) {
            if (element?.type === format) {
                match = true;
                break;
            }
            element = element.children[elementPath[i]];
        }
    }

    return match;
}
```
