### ISSUE TITLE
Unique identifier for Nodes

### ISSUE THREAD

**Issue by alfechner** [ianstormtaylor/slate#3489]
#### Do you want to request a _feature_ or report a _bug_?

Request a feature.

#### What's the current behavior?

I migrate my implementation from a older version of Slate to the current one. The API has been rewritten and improved.

I've got a use case in my old case witch doesn't seem to be covered anymore. Previously Nodes had unique keys assigned which could be used in i.e. `replaceNodeByKey`. My code heavily relies on this feature. Actions taken in an Element change it's definition.

For example: An Image Element which holds an URL. I need a edit button to change the URL to another one. So far I replaced the Node's definition by the new one using the method mentioned above.

I asked about that in the Slack channel. People proposed to set the new Node by path using `setNodes`. But nobody knew how to get the path of the Node without having some kind of unique identifier.

If this kind of identifier is really needed to perform such actions I'd love to see it back in the library.

**Comment by CameronAckermanSEL** [comment]
Hey @alfechner , the API was rewritten to effectively not rely on keys to locate nodes anymore, instead this is done with paths. This alleviates the need for the API to recursively search the node hierarchy to locate a node by its key and is a performance improvement. I know it's a bit difficult to transition to the new paradigm, but I'd be surprised to see keys come back as a first class way of accessing nodes in response to this feature.

If you would like to bind keys to your nodes, the API allows this because you can freely add arbitrary properties to your nodes as you see fit (as long as you don't run into name collision with properties on the core interface). You can use this to write your own locate by key utilities and then that should yield you a path. If you like.

**Comment by alfechner** [comment]
@CameronAckermanSEL thanks for clarifying.

**Comment by alfechner** [comment]
A good example on how to do this can be found in the [embedded](https://github.com/ianstormtaylor/slate/blob/master/site/examples/embeds.js) example.

```js
 onChange={value => {
    const path = ReactEditor.findPath(editor, element)
    Transforms.setNodes(editor, { url: value }, { at: path })
}}
```

**Comment by raitucarp** [comment]
I've tried assign ID to nodes when normalizing, but it seems I catch bug when applying Transforms.setNodes .. 

https://github.com/ianstormtaylor/slate/issues/4641
