### ISSUE TITLE
editor.apply() with some problem

### ISSUE THREAD

**Issue by baijiahei** [ianstormtaylor/slate#3498]
when i use this object to apply

**insert character fine**,but when i **use unline,bold,code, another editor selection seem incorrect**,and occur an error:**Uncaught Error: Cannot find a descendant at path**

**Comment by CameronAckermanSEL** [comment]
Hey @baijiahei , it's hard to tell what's going on with this issue because the template wasn't used. Please write your issue and we can revisit it.

If this is a question about how to use slate, please visit the slack channel instead: https://app.slack.com/client/T1RFVK5FV/C1RH7AXSS/thread/C1RH7AXSS-1582240602.291300

**Comment by baijiahei** [comment]
![Apr-21-2020 17-50-02](https://user-images.githubusercontent.com/16861647/79851964-9b5e5480-83f8-11ea-8026-6bff940150ec.gif)

i use editor.apply(operation) to change another editor,menu item list,quote seems ok, but when i use **bold,underline** ,console will report **Uncaught Error: Cannot find a descendant at path** 

`const {operations} = editor`
`operations.map(item => {
        editor.apply(item)
      })`
