### ISSUE TITLE
when it isBlurred is true, isExpanded is still true.

### ISSUE THREAD

**Issue by chilijung** [ianstormtaylor/slate#351]
demo:
https://jsfiddle.net/chilijung/036pdt5s/

When the selection is blurred (the selection is not selecting anymore), `isExpanded` is still `true`, should `isExpanded` change to `false`? Thanks!

**Comment by Soreine** [comment]
I think it is the expected behavior. When the selection is blurred, it is still here, simply unfocused. On the demo, select a word in the text and click outside, the selection change from blue to gray. It does not prevent it to keep its range, and to stay expanded to select the word.
`isBlurred/isFocused` and `isExpanded/isCollapsed` are separate, independent state.

**Comment by chilijung** [comment]
@Soreine thanks for your reply, well then how could I know when it is blur and also not selecting words?

**Comment by chilijung** [comment]
I have a situation:

- select words and click out of the editor (not selecting words). `isBlurred` and `isExpanded` is both true.

- select words and click out another browser tab (still selecting words). `isBlurred` and `isExpaned` is both true.

Is this also a expected behavior?

**Comment by ianstormtaylor** [comment]
Yup, @chilijung it sounds like you're describing the expected behavior here! Let me know if you need anything else
