### ISSUE TITLE
Backwards selection anchored at the end of an inline block has unexpected behavior

### ISSUE THREAD

**Issue by JonathanWbn** [ianstormtaylor/slate#3544]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Selecting text when starting at the end of the line and that end being a link the selecting doesn't work.
![Screen Recording 2020-03-09 at 11 42 54](https://user-images.githubusercontent.com/19997520/76206178-d6674880-61fb-11ea-83fb-483637376625.gif)

Slate: 0.57.1
Browser: Chrome
OS: Mac

**Comment by kilrain** [comment]
I dug into this bug over the weekend a bit. The issue seems to have to do with the [zeroWidthString node](https://github.com/ianstormtaylor/slate/blob/16ff44d0566889a843a346215d3fb7621fc0ed8c/packages/slate-react/src/components/string.tsx#L73) inserted after an inline. Native DOM selection has a tendency to put the offset AFTER the zero width character (`offset: 1`) while Slate prefers to consider this state as `offset: 0`.

On the initial mousedown, the native selectionchange event sets the cursor to offset of 1... immediately, [Slate resets the offset to 0](https://github.com/ianstormtaylor/slate/blob/16ff44d0566889a843a346215d3fb7621fc0ed8c/packages/slate-react/src/components/editable.tsx#L165). After beginning to drag, native selection reverts to an anchor offset of 1 and Slate processes the update but, again, considers it as an offset of 0. This doesn't trigger a re-render (since Slate already thinks the selection anchor is offset 0), thus the [`useLayoutEffect`](https://github.com/ianstormtaylor/slate/blob/16ff44d0566889a843a346215d3fb7621fc0ed8c/packages/slate-react/src/components/editable.tsx#L133) does not get a chance to sync the DOM.

When Slate goes to re-render (as a result of the selection focus update) a native selectionchange event fires with the collapsed selection state we see in this bug. I could not successfully figure out where the collapsing selectionchange event is coming from.  If I dragged the mouse very slowly over a void inline node, I could get into a valid state where the void node was selected... but if I continue dragging another pixel, the selection would collapse on the other side of the void node (as we see in the original bug report).

**Comment by JonathanWbn** [comment]
Thank you, @kilrain, this was helpful. I found a solution and opened this PR: #3574.
