### ISSUE TITLE
List question

### ISSUE THREAD

**Issue by podviaznikov** [ianstormtaylor/slate#356]
Rich text example (http://slatejs.org/#/rich-text?_k=fc0q65) has this small problem with the list.

If you create a list you can't create element after the list anymore. Would be good if demo supported keys when clicking "Enter" twice removed last item of the list and user would be able to continue with outside of the list.

**Comment by SamyPesse** [comment]
Hey @podviaznikov, the slate examples are designed to be small POC of Slate.

But Slate is designed to be the framework to build editing UX, it should not handle these use cases in the core (@ianstormtaylor, feel free to correct me if I'm wrong ;) )

Since Slate is extensible, plugins can provide these UXs, at GitBook we built:

- [`slate-edit-list`](https://github.com/GitbookIO/slate-edit-list) to provide the list editing UX
- [`slate-trailing-block`](https://github.com/GitbookIO/slate-trailing-block) to ensure a paragraph at the end of the document
