### ISSUE TITLE
Can't continue editing at the end of editor

### ISSUE THREAD

**Issue by mailzwj** [ianstormtaylor/slate#3560]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

In this page [https://www.slatejs.org/examples/images](https://www.slatejs.org/examples/images). When I insert an image at the end of editor, I can't continue editing right after the image.

Slate: latest
Browser: Chrome
OS: Mac

**Comment by CameronAckermanSEL** [comment]
@mailzwj , this is because the image is a void block and cant be edited, and also can't be sibling to text. You can either:
1. Make the image an inline void block, this will let you inline it with text
2. Use a normalizer to ensure there's an editable block (per your domain rules) directly after void blocks
