### ISSUE TITLE
recent void node changes messes with child styling

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#358]
Hello, there were some void node changes recently that broke a lot of child styling in editor. Not sure the best course of action to solve these.

Adding `position: relative` to the spacer element causes the DOM engine to consider it when calculating positioning. This means that if the element above has a bottom margin and the item in the void node has a top margin, both margins are shown were as before they were "merged". <https://github.com/ianstormtaylor/slate/blob/e63a6b36ce422451935a9d83274351ff1641e13a/src/components/void.js#L95>

Adding `line-height: 0` to the top-most element was probably put there to counteract issues with a relatively position spacer, however it doesn't get reset! This means that the contents of the void node have a line-height of 0. I'm not sure it can be properly reset (initial and inherit won't help here) which leads me to believe that this is a terrible approach to whatever it was trying to solve. <https://github.com/ianstormtaylor/slate/blob/e63a6b36ce422451935a9d83274351ff1641e13a/src/components/void.js#L71>

**Comment by ianstormtaylor** [comment]
Sorry about that, totally my fault for forgetting that `line-height` would have cascading effects and be a breaking change. 

I had done it because it was very hard to find a cross-browser set of styles that worked for allowing the cursor to function as user's would expect in both `block` and `inline` void nodes, but I just realized that we can solve it by using the old styles for blocks, and the new styles for inlines, which removes the need for `line-height` at all.

Thanks for reporting!
