### ISSUE TITLE
useMemo: Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by cucar** [ianstormtaylor/slate#3580]
I get this error "Invalid hook call. Hooks can only be called inside of the body of a function component." when I try to use Slate as shown in documentation in a class component. How are we supposed to use Slate in class components?

Thank you,
Cagdas

**Comment by mpkelly** [comment]
@cucar you can wrap your Editor in a function component and then use that in a class-based component. If you just need memo then your class could extend `React.PureComponent`. 

If that answers your question then please close this issue.

**Comment by maxmatthews** [comment]
@mpkelly Could you post a code sample of either of these solutions?

**Comment by DamareYoh** [comment]
@MaxGfeller this is a matter of :

```
class MyClassComponent extends React.Component {
  ... stuff
}

function MyFunctionalComponent(props) {
  [state, setState] = useState(); // or whatever hook
  ... stuff
  return (
    <MyClassComponent {...props} />
  )
}

```

**Comment by CameronAckermanSEL** [comment]
Hey @cucar  I took a look at the documentation, and I don't see any instances where it's recommending that users attempt to use React hooks with a class based component. If I'm incorrect in this regard, please let me know what documents are specifically incorrect and they can be corrected.

The constraint of React hooks only being usable in a functional component is not something that is unique to slate, or is really within the scope of the documentation. Unfortunately the most I can recommend is that you read more about React hooks and how they might be used. I'm also unsure whether the library documentation strictly needs to provide an example of how to use slate in a class based component, because 
1. This is again not a problem unique to slate - there are common patterns and reference materials available for managing React hook features in class based components.
2. React in general is moving away from class based components and gradually this will become a less supported use case.

If you have any other questions, or suggestions pertaining to slate specific documentation, please feel free to continue the discussion, but for now I'm going to close this issue.
