### ISSUE TITLE
Copying and pasting decorated text and elements doesn't work on Safari

### ISSUE THREAD

**Issue by bibixx** [ianstormtaylor/slate#3589]
#### Do you want to request a _feature_ or report a _bug_?
A bug

#### What's the current behavior?
When trying to copy and paste decorated text or elements from slate input the pasted value is always a string. The issue happens both in my application as well as in the [Slate examples](https://www.slatejs.org/examples/mentions)

Correct me if I'm wrong but I couldn't find any issue that addresses this bug (or maybe Safari's limitations?). It's strange though as it should affect quite a lot of users

**Decorators**
![ezgif-7-3c9347953fd7](https://user-images.githubusercontent.com/14880213/78546179-4538c100-77fd-11ea-8933-1770901a2d48.gif)

**Elements**
![ezgif-7-5ddb2d700fff](https://user-images.githubusercontent.com/14880213/78546131-34884b00-77fd-11ea-9f4a-ce59e7b116a8.gif)

Slate: 0.57.1
Browser: Safari 13.0.5 (15608.5.11)
OS: MacOS 10.15.3 (19D76)

#### What's the expected behavior?
It should work the same as in the other browsers – the decorated text / elements should be pasted as they were copied

**Comment by williamstein** [comment]
I happened to be reimplementing the clipboard for slate in https://cocalc.com, and noticed this issue and have some remarks that might be useful to whoever fixes it for slate (not me).  In the file slate-react/plugin/with-react.ts try changing insertData as given below.   Anyway, reading through relevant code, there is a sort of half-way implementation of paste, which is there for no apparent reason and not used.   Maybe it was used in a previous version of slate and was unfinished in the rewrite, due to chrome/firefox letting you set any data on the DataTransfer object, and not realizing that Safari evidently does not allow doing this.      

This code below is just an ugly hack, and definitely not what I'm actually doing in my code.  But if you try it out, it'll mostly work and from there you can maybe do something much better than silently failing completely on Safari (or maybe other browsers too).     Incidentally, searching around suggests that Safari revamped their DataTransfer implementation in response to a ton of security concerns about a year ago, so maybe slate paste used to work in safari, but broke about a year ago...

```
  e.insertData = (data: DataTransfer) => {
    let fragment = data.getData("application/x-slate-fragment");

    if (fragment == null) {
      // On Safari (probably for security reasons?), the
      // application/x-slate-fragment data is not set.
      // My guess is this is why the html is also modified
      // even though it is never used in the upstream code!
      // See https://github.com/ianstormtaylor/slate/issues/3589
      const html = data.getData("text/html");
      if (html) {
        // It would be nicer to parse html properly, but that's
        // going to be pretty difficult, so I'm doing the following,
        // which of course could be tricked if the content
        // itself happened to have data-slate-fragment="...
        // in it.  That's a reasonable price to pay for
        // now for restoring this functionality.
        let i = html.lastIndexOf('data-slate-fragment="');
        if (i != -1) {
          i += 'data-slate-fragment="'.length;
          const j = html.indexOf('"', i);
          if (j != -1) {
            fragment = html.slice(i, j);
            return;
          }
        }
      }
    }

    if (fragment) {
      const decoded = decodeURIComponent(window.atob(fragment));
      const parsed = JSON.parse(decoded) as Node[];
      e.insertFragment(parsed);
      return;
    }

```

**Comment by dylans** [comment]
For what it's worth I believe this was fixed a while back and I can no longer reproduce it. Please reopen if you believe it is still an issue.

**Comment by julien-mamalian** [comment]
@dylans, we still have the same issue in Safari with the latest version

**Comment by Nikhil22** [comment]
Doesn't work for me. Line breaks are not honored when pasting in Safari.
