### ISSUE TITLE
Can't replicate serialization example (without small fix)

### ISSUE THREAD

**Issue by noahtren** [ianstormtaylor/slate#3609]
The [serialization example](https://github.com/ianstormtaylor/slate/blob/master/docs/concepts/09-serializing.md) in the docs only works on a single node, and not an array of nodes as it says it does. This is easily fixed by adding the `map_obj` variable below. If this is a viable solution and I'm not missing something, I'll be happy to submit a PR.

```javascript
const serialize = node => {
    if (Text.isText(node)) {
      return escapeHtml(node.text)
    }
  
    const map_obj = (Array.isArray(node)) ? node: node.children
    const children = map_obj.map(n => serialize(n)).join('')
  
    switch (node.type) {
      case 'quote':
        return `<blockquote><p>${children}</p></blockquote>`
      case 'paragraph':
        return `<p>${children}</p>`
      case 'link':
        return `<a href="${escapeHtml(node.url)}">${children}</a>`
      default:
        return children
    }
  }
```

**Comment by CameronAckermanSEL** [comment]
Hi @noahtren , thanks for the report.

It's a little subtle, but the verbiage of the example suggests you should pass the `editor` node to the `serialize` function.

> It also takes a single node as input instead of an array, so if you passed in an editor like:

https://docs.slatejs.org/concepts/09-serializing#html

I'd say the documentation as-is is correct, however, if you'd like to submit a PR to clarify you're more than welcome to :)

That said, I think this issue is resolved. Feel free to continue discussing or asking questions if you'd like.

**Comment by noahtren** [comment]
Ah, makes sense! I was using the editor's value property instead of the editor itself.
