### ISSUE TITLE
Export Key Class

### ISSUE THREAD

**Issue by alfechner** [ianstormtaylor/slate#3646]
There is a method `findKey` on `ReactEditor` which returns a `Key` object. The `Key` class is not exported from the `index.ts`, though. I can only import it from `dist`.

I'm wondering if it's smart to base my implementation on `Key` or if it's meant to be used internally only.

Does it make sense to export it from `index.ts`?

**Comment by CameronAckermanSEL** [comment]
Hi @alfechner , thanks for using slate.

For questions like this, we encourage you to visit the slate slack channel instead of asking on the github. This will help us keep the github issue tracker focused on bug reports and feature enhancements. This is outlined in the issue template, which next time we'd also appreciate you use.

Thanks for your understanding.
