### ISSUE TITLE
Broken Hovering Toolbar Example

### ISSUE THREAD

**Issue by adelsz** [ianstormtaylor/slate#3661]
Thanks for the amazing library!
I have noticed a bug on the `hovering-toolbar` example on `slatejs.com/examples`.
Editor crashes when pressing CMD-B with an active selection. We are running into the same bug on a project based off the `hovering-toolbar` configuration.

#### What's the current behavior?

1. Visit [https://www.slatejs.org/examples/hovering-toolbar](https://www.slatejs.org/examples/hovering-toolbar)
2. Select any word
3. Press CMD-B
4. Page crashes, printing:
```
Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":35}
```

Slate: 0.XX.X (version live on the demo website)
Browser: Chrome 81
OS: Mac OS

#### What's the expected behavior?

Page doesn't crash.

**Comment by CameronAckermanSEL** [comment]
Thanks for the report @adelsz . That's a pretty weird one. I was initially going to respond to you that it was possibly crashing because this example doesn't have any keyboard shortcut support, but it looks like this example is unique in the crashing behavior.

I'll mark this as `help please` and maybe someone can take a closer look. I might be able to look at it later too.
