### ISSUE TITLE
Decorate is duplicating leaves

### ISSUE THREAD

**Issue by delijah** [ianstormtaylor/slate#3693]
#### What's the current behavior?

If you insert more than one soft hyphen after each other, they get duplicated. renderLeaf is called twice for every soft hyphen (except the first one).

![soft-hyphen](https://user-images.githubusercontent.com/237739/82337915-94713480-99ec-11ea-812e-ff7a61fd49df.gif)

Sandbox: https://codesandbox.io/s/slate-reproductions-v99e1
OS: macOS Mojave 10.14.6
Browser: Google Chrome 81.0.4044.138 (Official Build) (64-bit)
Slate version: 0.58.0

#### What's the expected behavior?

For every inserted soft hyphen, renderLeaf should only be called once.

It looks like the problem occurs over here:
https://github.com/ianstormtaylor/slate/blob/d82ffe49a5253de08adab8f36ac7f07879037977/packages/slate/src/interfaces/text.ts#L91

But what is happening there is too complex for me to decipher.

**Comment by TheSpyder** [comment]
I can reproduce this in the search highlighting example:
https://www.slatejs.org/examples/search-highlighting

There is no visible issue, because search highlight adds a class without `::before` content, but a DOM inspector reveals 3 spans with the search highlight class (`css-evmfc5` in this screenshot).

![Screen Shot 2020-05-25 at 10 09 00 am](https://user-images.githubusercontent.com/298292/82768180-c2cd9480-9e70-11ea-8fe2-3275b79fde9a.png)

To replicate:
* insert the same text twice with no spaces (I used `eded`)
* search for that text (in my case `ed`)

It looks like something is adding a zero-width space in between the two matched decorate ranges, which is probably fine, but the zero-width space is given the same leaf properties as the matched ranges either side of it. I'm not sure if that is by design or not but it's certainly the cause of this issue.
