### ISSUE TITLE
Transform.moveNodes within nested container causes ALL children in container to be re-rendered

### ISSUE THREAD

**Issue by davidruisinger** [ianstormtaylor/slate#3740]
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?
Assuming you have a slate state like this:

```
[
  {
    type: "body",
    children: [
      {
        type: "video",
        children: [
          {
            text: "https://www.youtube.com/embed/22m5eU6uxeQ"
          }
        ]
      },
      {
        type: "paragraph",
        children: [
          {
            text:
              'Toggle this line to "bullet-list" => All nodes within "body" are re-rendered, causing video above to flicker.'
          }
        ]
      }
    ]
  }
]
```

And you use `Transforms.wrapNodes` (which internally calls `Transforms.moveNodes`) on the `paragraph` underneath the `video`, the `video` (and all other potentially existing nodes within the `body`) gets re-rendered even though it has not been touched.

[Codesandbox](https://codesandbox.io/s/prevent-re-render-of-children-gslvo?file=/src/slate-editor.tsx)

![P6NLJSkYcq](https://user-images.githubusercontent.com/5305150/84755247-b47f1e00-afc1-11ea-8cf7-b3728275b093.gif)

Slate: 0.58.3
Browser: Chrome
OS: Mac

#### What's the expected behavior?

Slate should only re-render the parts that actually changed so the video does not re-render (flicker).

**Comment by flavordaaave** [comment]
My use-case where this behavior is really causing problem:

- Inlinebar is positioned relative to selection
- Social embeds are rendered
- Formatting is applied from Inlinebar (e.g. toggle `bullet-list`)
- Social embeds are re-rendered causing Inlinebar to be incorrectly placed

See this [Codesandbox](https://codesandbox.io/s/prevent-re-render-of-children-with-inlinebar-8go9z?file=/src/slate-editor.tsx):

![HyR24ybKVs](https://user-images.githubusercontent.com/5305150/84761238-74239e00-afc9-11ea-9eca-02a4fc3ec50a.gif)

**Comment by TheSpyder** [comment]
Not that this shouldn't be fixed, but I thought most inline bars like that were absolutely positioned. Not actually embedded into the content.

**Comment by flavordaaave** [comment]
> Not that this shouldn't be fixed, but I thought most inline bars like that were absolutely positioned. Not actually embedded into the content.

@TheSpyder The inlinebar IS actually absolutely positioned but relative to the current selection. 
But since the embed is re-rendered, the selection (and the inlinebar) are positioned right in the moment where the embed is NOT fully loaded, yet.

A workaround could be to trigger a repositioning of the inlinebar after the embed has loaded.

**Comment by hgenru** [comment]
That also happens when you re-ordering root children. These causes re-render of all editor's components. I tried to wrap components to React.memo, but it's not working because all nodes render from scratch.

**Comment by hgenru** [comment]
But if I move nodes by myself it's just works. Without re-renders.
![image](https://user-images.githubusercontent.com/2411525/89836715-04b4cf80-db70-11ea-838d-80619a408d44.png)

**Comment by githoniel** [comment]
This is hard to fix when using `spliteNode` and `moveNode` transform.

`slate` have some bug in key-element refresh when using `spliteNode` and `moveNode` transform and it's not hard to fix. but keeping the component instance is not enough.

The problem is We can not re-use mounted dom piece when the component tree has change. `React` will unmounted and re-mounted all dom content if component class change or new component tree node.

We will always get a new node Container when using `spliteNode` and There must be part of content to be place in it, and it must be re-render and we can'not reuse old renderer dom because `React` only support re-use old dom piece in array using key.

moved node will get new parent node  when using `modeNode`. and their's component class change in react component tree. So, `React` will unmounted and re-mounted all dom content.

It's easy then we use native dom api， just get domNode and then `appendChild`. but I do not know how to implement `dom re-use` in `React`
