### ISSUE TITLE
0.58.3 Element.children has type `unknown` instead of Node[]

### ISSUE THREAD

**Issue by macrozone** [ianstormtaylor/slate#3769]
#### What's the current behavior?

the change to unknown from any seem to break the definition for `children` on a node as well:

```
const targetNode = Editor.node(editor, targetPath);
const onlyTextChildren = targetNode?.[0].children // is of type Unknown instead of Node[]
```

Slate: 0.58.3
Browser: any
OS: any

#### What's the expected behavior?

node.children should be of type Node[]

**Comment by timbuckley** [comment]
`Node` is a union type of `Text | Element | Editor`. Because `Text` does not have a `children` key, a given `Node` cannot be assumed to have that property unless you have proven that it's not a `Text` node. So if you type guard against it first with something like `if (!Text.isTetxt(targetNode)) {...}`, then `children` will have the correct type of `Node[]`.

**Comment by BrentFarese** [comment]
Closing this as it's not actually an issue with the types per @timbuckley comment above.
