### ISSUE TITLE
Proposal for Sponsored Open Source Android Support

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#3786]
I am considering a sponsored version of an Open Source Android Plugin for Slate for USD $25,000.

1. This is an alternative to the proposal for a Paid Android Plugin (also proposed by me) for USD $500 per license as described here https://github.com/ianstormtaylor/slate/issues/3573

2. The Android Plugin will be released as open source under the same license as Slate and will support at least the latest version of Android with similar features and limitations as the 0.47x Android Support 

3. Building Android support is a lot of work. We would love to be able to contribute for free (like Ian!), but the cost is high to burden alone. We contributed Android Support for Slate 0.47 which was working although not perfect and that cost about USD $40,000. That doesn’t include research we did prior to starting or the devices we had to purchase to test on.

4. It's uncertain how much it will cost to complete the 0.50x version of Slate Android. It may cost more or it may cost less. Either way, we are committing to completing it if we raise the funds. If it costs less, we will not be returning unused funds; if it costs more, we will cover the difference. Note that the 0.50x port is not trivial as another user worked for 3 months on it and it was never completed.

5. For clarity, we already spent USD $40,000, so even if the port costs $0, there will be no profit from this.

The port will be completed in partnership with Wayne Leroux with assistance from me. Wayne has built an impressive collaborative editor based on Slate (https://github.com/wleroux/slate-collaborative) so I have confidence in his ability to complete this project. He has also contributed other open source projects (https://github.com/wleroux?tab=repositories). I expect him to be able to complete the project; however, if for any reason he cannot, I will either complete it myself or will return the funds. Wayne and I intend to work together on a different Slate related project which would benefit from Android support.

If we are unable to raise the funds through sponsorship, we will revert to the paid model at USD $500 per license. For clarity, if we don't raise the funds through sponsorship and use a paid model but later receive the equivalent revenue in licensing fees from the paid model (USD $25,000 or 50 licenses), we will not then open source the code.

I recognize that this is a non-trivial amount to raise. I expect that companies that can afford to do so, will need to contribute more in order to meet this fundraising goal. To put the amount into perspective, this is the equivalent of contracting a senior developer for about 6 weeks. 3 organizations, contributing the equivalent of a contract valued at 2 weeks worth of work will reach the sponsorship goal (about USD $8000 each) or 50 smaller contributors paying what would be the licensing fee of USD $500.

Update: Now Live!

[Add Android Support to Slate - **KickStarter Campaign Now Live**](https://www.kickstarter.com/projects/sunnyhirai/add-android-support-for-the-slate-wysiwyg-editor)

**Comment by thesunny** [comment]
Hi everyone, just a quick update:

I've put together a KickStarter campaign and have submitted it. We are awaiting its approval. The campaign is in Canadian Dollars (we are a Canadian company) but we are raising the Canadian equivalent of the US dollars noted above.

We've started work on the Android Plugin part-time at the moment.

If we are able to raise the funds, our plan is to start work on the plugin full-time in August and upon completion release the plugin as an open source project.

As a reminder, if we are unable to raise, we plan to release the plugin under a paid license.

**Comment by signalwerk** [comment]
@thesunny I hope you also have thought of small tiers in the kickstarter campaign. I don't need Slate in a commercial product or client but would also like to contribute, since I have some private projects with slate. Plus I like what you did for 0.47!

**Comment by thesunny** [comment]
@signalwerk I have a pledge level at $50. Do you think that works?

**Comment by signalwerk** [comment]
@thesunny awesome! 🥳 can't wait to see that happening!

**Comment by thesunny** [comment]
Hi Everyone,

The KickStarter campaign is now live.

We will be grateful to all contributions towards the goal no matter how small.

That being said, in order to make this campaign a success, in my opinion, we will need both of the following:

1. Companies that use Slate for their business to contribute at a corporate level. It will be difficult to meet the pledge goal without this support.

2. Members of the community (people like you) to promote the campaign to your organization or to other organizations that would benefit from Android support in Slate.

Many have asked for this fundraising towards open source Android support. The work has been done to create the fundraising campaign but we need your help in order to make this a reality.

Support this fundraising campaign:

[Add Android Support to Slate KickStarter Campaign Now Live](https://www.kickstarter.com/projects/sunnyhirai/add-android-support-for-the-slate-wysiwyg-editor)

Note: If we raise above the fundraising goal, we will spend time to support earlier versions of Android.

**Comment by thesunny** [comment]
An update,

[The KickStarter campaign is now live.](https://www.kickstarter.com/projects/sunnyhirai/add-android-support-for-the-slate-wysiwyg-editor)

We have raised $2,351 out of $30,000 with 10 contributors. This means that 40% of the people that showed support for the Android plugin, have backed the campaign.

If you intend to back the campaign, please do so now and help build momentum.

Several of you asked me to seek sponsorship in GitHub issues, on the Slack Mobile channel and privately. To make this happen, it requires help from everybody to get it to the right people. For clarity, this is not a profit making venture for me or my company (we will lose money), but it is a way for the community to get a much needed feature into Slate.

**Comment by clauderic** [comment]
>  I've created a 12 page design document which includes all of the issues I encountered building Android support the first time along with the solutions I used to overcome those issues.

Hey @thesunny, the Kickstarter campaign mentions a 12 page design document. Is this something that can be reviewed by the community? 

The Kickstarter campaign is scarce on technical details on what the proposed approach would be, and I think it would help build confidence in the project if more technical details were shared.

The previous solution revolved around composition start / end events and `MutationObserver`. 
Is this still the planned solution moving forward?

I've spent the better part of the last month reviewing the Android plugin that was shipped in `slate-react@0.4X.X`, and am really appreciative of the work that you put into it. It has a number of issues that I've since been trying to fix.

While trying to fix bugs in the original Android plugin, I noticed that there are a number of things that I think were overlooked with the original solution:

- Composition events do not fire consistently the way you might expect them to in Android. For example, the `compositionend` event often only fires when the keyboard is dismissed, or sometimes fires out of sequence at the beginning of a composition, and therefore should not be relied on to determine the end of a composition
- The Slate value needs to be updated on every single text insertion / deletion / line break to allow for other plugins to interact on the value. The previous Android plugin only attempted to reconcile the mutations that had occurred on `compositionend`, which only happens when the keyboard is dismissed or the input is blurred as outlined above.
- Many plugins rely on `keydown` events to override the default browser behaviour (for example, on backspace or on enter). On Android, keydown events have unidentified keycodes, and therefore cannot be used reliably by plugins to augment the default browser behavior. 

  In an ideal world, plugin authors should not have to write plugins with a separate code path for Android, Slate should expose a universal way for listening for specific events such as `backspace` and `enter`
- Plugins can also affect the DOM and trigger changes that are then detected by the `MutationObserver`. There needs to be a strategy in place to distinguish between mutations that originated from a composition and mutations that originated from plugins. As outlined above, the `compositionstart` event is unreliable on Android, in my experience, the `beforeinput` and `input` events are a more reliable way to detect the start of a composition
- Some actions are extremely difficult to reconcile using `MutationObserver` alone. The main example that comes to mind is handling backspace properly, which can result in dozens of mutations that are difficult to decrypt. In my opinion, some actions such as backspace would be better handled using `beforeinput` rather than `MutationObserver` alone
- The original solution uses the `ReactDOM.unstable_flushControlled` method, which is no longer exported from the stable builds for `ReactDOM` as of `react-dom^16.11.0`

I am sharing these issues not to criticize any of the work that was done, but rather in the hopes that we can discuss them along with potential solutions so that these aren't overlooked in the next Android plugin.

**Comment by thesunny** [comment]
So why haven't some of these issues been fixed in 0.47x?

One thing to keep in mind is that I built the 0.47x version of Android but never used it.

I was working on a project that would eventually incorporate that version of Slate. But what happened was, Slate switched to 0.50x and removed Android support before I got to use it. So the last version I wrote, I spent a month on it (the mutations version) but after I released it, I didn't have cause to keep it updated.

The problems stayed unfixed or not optimized not because I couldn't fix or improve them, but because I wasn't using it and therefore couldn't justify spending time on it.

My hope for spending the time to build Slate Android before my project was so that others would learn Slate Android and start fixing bugs. Unfortunately, that didn't happen.

So, the main difference is that my project is released now and I will be using Android so these issues will be addressed.

Here is the Design Document (hosted on the project I was talking about by the way) although I suppose it's more of a "How I got 0.47x Android to work".

https://airshelf.com/thesunny/slate-android

I read all of your comments but I don't have the time to address them individually. They all make sense and I think I considered most or all of them at one point. The problem is Android is just not simple. I tried many more direct approaches and spent, I think, 2-3 months going in circles on the "without mutations" version for example. Some of this is documented in the link.

Also, keep in mind that if you are using it with the latest version of Android, it was never tested on it because it didn't exist. If it works at all, it's kind of lucky.

Oh, and the one thing that may never work is being able to intercept certain keypresses. The reason why is that Android may not provide that feature (haven't checked latest version of Android). You can't `preventDefault` some events that can be done in every other browser and that is by design by the Chrome Android team. This is also the reason why I have to revert the DOM.

**Comment by thesunny** [comment]
Hello everyone!

Some great news is that we have one Silver Corporate Sponsor. We now have CAD $9,501 of the $30,000 goal or about 1/3rd of the goal to complete an Android plugin.

In order to get Android support added, we need 3 more corporate sponsors at the silver level (CAD $6500) or one at the gold (CAD $13,000) with a silver.

There are only 17 days to go.

If you believe Android is important to your project, please reach out to corporations and/or contribute yourself. With over 18,000 stars on the Slate repo, I find it hard to believe that it's not possible to raise funding to add Android support to this project which effectively adds the reach of Slate to almost 40% of the OS market.

I know there are some big corporations that use Slate so please reach out to them.

**Comment by thesunny** [comment]
Well everyone, this is the last chance. There is about 24 hours left.

We've raised CAD **$18,461** out of CAD $30,000.

There is **$11,539** left to go.

If you've been waiting to see if this gets funded without you, it's not! Now is the time to make the commitment. We need two silver sponsors to make this happen.

[Last Chance at Android Support Kickstarter Campaign](https://www.kickstarter.com/projects/sunnyhirai/add-android-support-for-the-slate-wysiwyg-editor)

**Comment by thesunny** [comment]
We made the fundraising goal on the Kickstarter!

A very generous sponsor added CAD $11,000 (over one third) of the goal and pushed us just over.

For privacy reasons, I don't want to name individual contributors, but thank you to everyone that contributed. We are slated to start in the second week of September.

**Comment by Slapbox** [comment]
Holy cow! I was bracing myself for disappointment this morning. This news blew me away. Very excited!

**Comment by rsdrsd** [comment]
This is very good news.

**Comment by thesunny** [comment]
Hi everyone,

We have an alpha version of a Slate Android Plugin available here:

[https://github.com/wleroux/slate-android-plugin](https://github.com/wleroux/slate-android-plugin)

It's not a final release by any means, but if you want to get started with it and report any issues not listed before, it could help us isolate bugs. It's posted under Wayne Leroux's GitHub account at the moment but may be moved in the future.

Notes about the alpha release:

*   Requires the 0.59 version of Slate released a few days ago
*   Only works on Android 10 (may work on Android 11)
*   Continuous backspace has bugs
*   Auto-Complete has bugs

Please post here if you have any issues

**Comment by rsdrsd** [comment]
Can someone maybe explain why an editor like ProseMirror doesn't have these problems on Android? Is it due to the architecture used or does ProseMirror have all kinds of hacks for Android?

**Comment by jljorgenson18** [comment]
Prosemirror still has Android problems and there are plenty of hacks inside of Prosemirror. You also lose consistent support for backspace and other keys because Android doesn't send keyCode information consistently. Prosemirror has some interesting ways of guessing that you did a backspace and then resetting the content based on the mutation.

Prosemirror does have a really awesome mutation registration system that is really nuanced and has many workarounds in place, but there are still many, many issues across device, OS version, webview version, and keyboard combinations. They are primarily just issues baked into contenteditable/Android though.

Prosemirror is still very, very good at Android compared to almost any other option and we still had to do insane workarounds to resolve issues.

**Comment by jljorgenson18** [comment]
Also, Prosemirror has really intelligent composition support where it tracks compositions and but then protects the composition text node until the composition is complete. The problem with compositions is that if you interact with composition text nodes at all, it can derail the whole composition (especially on Android). Prosemirror also works around various selection bugs that plague Chrome/Android Chrome with their state syncing system

**Comment by coniel** [comment]
@thesunny Thanks a lot for this plugin!

I've run into an issue with soft line-breaks. Here's a [simple reproduction](https://gist.github.com/coniel/ef09c41acf67cfd29cc0a8cf605d3077) (it simply prevents the default Enter key behavior and inserts `\n` as text instead). This somehow results in an infinite `\n` insertion loop when hitting Enter:
![ezgif-7-4c5661bffcb4](https://user-images.githubusercontent.com/1728027/98655274-f2e9f080-2347-11eb-8016-84314c3189ed.gif)

**Comment by thesunny** [comment]
Hi @coniel thanks for letting us know. These bug reports are really helpful for us.

I've mentioned this post to @wleroux who is the developer that's working on this version of the plugin.

**Comment by wleroux** [comment]
Thanks @coniel! I've published a new version of `android-slate-plugin` (version `0.0.3`) to support soft line-breaks. :)

**Comment by swashata** [comment]
Hello,

When I select multiple words and try to delete, sometimes only the last letter is being deleted. Maybe it is happening because I am listening to selection and showing a popup toolbar. Please see this video. If needed, I can provide access to source code and a staging site to reproduce the issue.

https://youtu.be/OQQmAna6gWI

**Comment by coniel** [comment]
@wleroux Seems I forgot to thank you for the fix. So thanks! Can confirm that it works. I've been using the plugin since then and I've been seeing an error reported in my error logger, though I'm unable to reproduce it myself:
<img width="848" alt="Screenshot 2020-11-24 at 19 46 49" src="https://user-images.githubusercontent.com/1728027/100133528-8fa3a680-2e8f-11eb-9606-12504f3d8843.png">

**Comment by knubie** [comment]
I completely missed the kickstarter for this. Is it too late to donate to the project?

**Comment by thesunny** [comment]
Hi @knubie 

Thanks for your offer to contribute to the KickStarter.

We've reached our donation target and adding any more to it really wouldn't change the outcome. We really appreciate the sentiment though.

One thing that will definitely help improve the success/quality of the project more than a monetary contribution is to try the plugin in your project and report any bugs. That will help make sure that the final release will be at as high a quality as it can be.

**Comment by bjgrosse** [comment]
I really would love to use Slate for my project, but Android support is a must. I've been testing out the plugin and am hitting several issues (besides the already mentioned bugs around continual backspace and selecting multiple words + backspace only removing the last character).

Here is my codesandbox: https://codesandbox.io/s/loving-hermann-6bdpq?file=/src/App.js

The first bug: I put my cursor in the middle of a word:3

![image](https://user-images.githubusercontent.com/14151299/100591676-5edfc900-32f6-11eb-8631-8847cf690b68.png)

I press enter, and I get this:

![image](https://user-images.githubusercontent.com/14151299/100591696-6901c780-32f6-11eb-86ef-f2576b010367.png)

Continuing to press enter continues to generate duplicate characters:

![image](https://user-images.githubusercontent.com/14151299/100591749-7a4ad400-32f6-11eb-848c-b59a20e1f7be.png)

The second issue, I take these steps:

1. Put curser at end of first line
2. Hit enter
3. type 'test'
4. hit enter
5. hit enter again (screenshot shows the serialized editor value):

![image](https://user-images.githubusercontent.com/14151299/100592207-1674db00-32f7-11eb-88f2-d6afe15fa3a8.png)

6. hit backspace once
7. hit backspace again

![image](https://user-images.githubusercontent.com/14151299/100592235-1ffe4300-32f7-11eb-8fac-b536cb550a16.png)

8. Hit enter and get this error:

![image](https://user-images.githubusercontent.com/14151299/100592283-2ee4f580-32f7-11eb-821a-27c3c2c16a36.png)

Now there is a new line space after the word 'test' but moving the cursor to it, triggers the above error again. 

![image](https://user-images.githubusercontent.com/14151299/100592365-4e7c1e00-32f7-11eb-933e-ca502f425e89.png)

I hope this helps!

**Comment by wleroux** [comment]
Hello @bjgrosse , I could not replicate any of these issues. Which version of Android are you using? Which browser are you using?

**Comment by Slapbox** [comment]
@bjgrosse and also, what keyboard? I assume GBoard?

**Comment by dfee** [comment]
1. is the android plugin considered to be feature complete?

2. are you intending to merge that code into this repo, or maintain it separately? If maintain it separately, why?

**Comment by RobbyWH** [comment]
Hello i want to ask question, is the final release only supported for android 10 too?

**Comment by thesunny** [comment]
@dfee The Android Plugin is not considered feature complete at the moment. It is currently being tested against the latest version of Android. That said, it should be very good with one known bug of holding down the backspace key continually. This may be an issue that cannot be fixed and appears to be due to the fact that Android editing happens outside the JavaScript process. In other words, we can't seem to ever guarantee a state. If we read a document state (for example), it may have been modified by the time we reacted to it.

Ultimately, it would be great to have the plugin in slate proper. In the interim, we may keep it separate. The reason is that there is little expertise on the Android plugin and so it may be easy to break Android when there is a new Slate release. Unlike all the other OS and browser compatibility issues, Android takes a completely different approach to getting input and it does so, unfortunately, out of necessity. It is a separate implementation. By keeping Android as a plugin, we can lock the Android plugin to specific known good combinations of Slate and the Android plugin.

Over time, as expertise grows in the community, it may be reasonable to expect contributors to check for Android compatibility and run a suite of (currently) manual tests which hopefully can be automated at some point.

@RobbyWH Our deliverable with respect to the Kickstarter is the latest version of Android 10, but our hope is to deliver at least the latest 2 versions of Android. It may not be of that much additional benefit to go too far back in terms of Android support because it can add a lot of weight and complexity to the code. Generally speaking, the newer versions of Android have been easier to build for in my experience as they continue to improve the browser.

**Comment by wleroux** [comment]
@swashata , I was not able to reproduce your issue. If this is an unsupported version, you can find that information under `...` > `Settings` > `About Chrome`? If it is a supported version, can you provide an environment where I can try it?

**Comment by wleroux** [comment]
@coniel I've updated the text diff algorithm to be more lenient. `0.0.4` should resolve your issue. What might be happening is the editor is trying to modify non-editable text within your editor, and the `slate-android-plugin` is not detecting the corresponding leaf node as a result.

**Comment by swashata** [comment]
Hi @wleroux Thank you for your attention. It is indeed an unsupported version (sorry I missed that).

Application version: Chrome 86.0.4240.198
Operating system: Android 11; IN2021 Build/RP1A.201005.001

The keyboard I used is GBoard. I will get back to you with a reproducible environment where you can try.

**Comment by markgrancapal** [comment]
Just want to report that I encountered the same issue @swashata posted here. 

Application version: Chrome 87.0.4280.66
OS: Android 10

`This may be an issue that cannot be fixed and appears to be due to the fact that Android editing happens outside the JavaScript process. In other words, we can't seem to ever guarantee a state. If we read a document state (for example), it may have been modified by the time we reacted to it.`

@thesunny is there no solution for this continues backspace bug?

**Comment by wleroux** [comment]
@markgrancapal I've recently acquired an Android 11 device to investigate @swashata's issue, haven't tried to reproduce it there. My test environment is very similar to yours (Chrome 87.0.4280.101, Android 10). Are you using the default keyboard or any other customizations?

RE: backspace issue... The issue with the backspace has to do with how Android handles contenteditable and Slate's cursor synchronization code. Android modifies the cursor out-of-band from javascript, which makes it impossible intercept the changes before Slate's synchronization code. The approach we took was to avoid modifications to the Slate codebase entirely.

My current hypothesis on the issue is that in attempting to override Slate's default handling of composition events, we introduce these other issues. There is no way to override Slate's default handling of composition events without either preventing default or stopping propagation of these events, however without overriding the composition events, it doesn't work properly at all. I am working on validating that hypothesis.

**Comment by markgrancapal** [comment]
@wleroux Yes I'm using the default Keyboard GBoard.

That is quite complicated, handling the backspace issue. I hope you guys will find a solution on this. I'll test it again and send some feedback when you release a new version

**Comment by thesunny** [comment]
Hi Everyone,

It's the end of the year and, sadly, it looks like we aren't able release a complete version of the Slate Android plugin in time for the December 2020 goal. Wayne is continuing to work on the plugin and we will be focusing all of his available time on the Slate Android plugin until it is complete.

I was hoping to not have to get involved but if we aren't able to complete in a reasonable time, I'll consider my jumping back in as described in the Kickstarter.

Thank you for your patience. Android support will get done. As mentioned, it is something we need in our projects as well so we are strongly motivated to complete.

**Comment by cngeru** [comment]
Hello,
Will one have to use a plugin or will it be integrated into the library already ?

**Comment by thesunny** [comment]
@cngeru It will likely be integrated into the library eventually though I can't say that with 100% certainty.

The issue we are contemplating is that if the Android parts are difficult to maintain as Slate `master` is changed, we may want to lock an Android plugin to specific versions of Slate; however, as Wayne is working through the Android plugin, it appears that there are changes to Slate core that are required and for that reason, we may initially not release it as a plugin after all.

The short answer is, we're still not 100% sure about the initial release but the goal is that eventually it will be part of core. Even if it's not initially though, it should be a `yarn add` and hardly any code to get it working.

**Comment by clauderic** [comment]
Hey @thesunny / @wleroux, are you able to provide any updates on progress? 

I'm wondering if there's a work in progress branch I should be looking at seeing as there have been very few commits in the past few months on the master branch. 

If not, is there a way to contribute to help move things faster? The alternative would be for people like myself who'd like to help things move forward to fork the android plugin and work on it separately, but perhaps there's a way to combine our efforts here. Are you open to adding collaborators to the repository?

Currently the Android plugin has a number of issues that would need to be addressed before being considered "production" ready:

### `MutationObserver` vs `beforeinput`
The main architectural concern I have with the current implementation is that it relies solely on `MutationObserver` to reconcile the DOM with the Slate value, which assumes that the Android browser correctly modifies the DOM when events happen, which isn't always the case. In my experience, some actions are difficult / impossible to reconcile with the DOM using `MutationObserver` alone.

Further, even if the intent was indeed to ignore `beforeinput` events and rely solely on `MutationObserver`, the plugin isn't overriding the handling of `beforeinput` events that Slate is listening for, which is causing issues such as improperly handling the text replacements that are suggested in the keyboard toolbar, since Slate is responding to these events before they result in DOM mutations. Here are three demos to illustrate:

**Slate + Android plugin:**

https://user-images.githubusercontent.com/1416436/104964358-414fe700-59aa-11eb-8c54-8cb811c2ef1f.mp4

**Slate only:**

https://user-images.githubusercontent.com/1416436/104965969-d7394100-59ad-11eb-9897-4cb3ec2f3d8b.mp4

**Native `contenteditable` div without Slate or Android plugin:**

https://user-images.githubusercontent.com/1416436/104966109-20899080-59ae-11eb-9c02-d31c8a7f78cd.mp4


### User interaction vs Other mutations
The other main concern I have with the current implementation is that currently, the Android plugin makes no distinction between mutations that may originate from a user interaction versus mutations that might originate from an action triggered by a transformation (for example, a mutation triggered by a plugin). Since commands / transformations can also affect the DOM, these will trigger changes that are then detected by the `MutationObserver`. 

There needs to be a strategy in place to distinguish between mutations that originated from a composition vs other mutations.

### User-agent detection
Finally, and this is less of a major concern, but currently, the android composition manager is being connected regardless of user agent, which feels like an oversight, and one that cannot be addressed by consumers since the Android plugin is built as a hook rather than a decorator. Hooks cannot be invoked conditionally, so this means that the responsibility of checking whether the code should run falls onto the Android plugin hook rather than the consumer.

**Comment by wleroux** [comment]
Hello @clauderic,

Here's a little bit of a technical update on this effort.

The original approach is non-viable and the repository has been abandonned. The original approach attempted to create a standalone plugin that would interface with the existing Slate code as-is. This approach worked relatively well for the devices I was testing on, however I ended up spinning my wheels trying to close gaps in edge cases. Furthermore, when additional users attempted to use it with their devices, it became apparant that differences could not be resolved with that approach. The plugin hooks exposed by the latest version of Slate do not provide us with the necessary trigger points. We've kept it around as it might be better than nothing, but we've been working on the next iteration.

The new approach is currently using a forked version of Slate. This allows me to modify Slate to provide the hooks required as needed. We're porting the 0.47 plugin (which worked pretty decently) to the latest version of Slate. However, both React and Slate has changed significantly since then. The port of the plugin code is completed and I'm currently working on the necessary hooks into the slate code. Once we're confident in our solution, we will be seeking to add these new hook points to Slate proper and release the plugin (with user-agent-detection) either as an independent plugin or as part of Slate proper.

The nature of this work doesn't lead to frequent commits: A significant portion of the work is basically solving mystery after mystery. A lot of debugging, manually testing multiple different devices, manually combing through mutation logs and corresponding reconciliation, mapping statements to equivalent statements in the newer version (e.g.: ReactDOM#unstable_flushControlled isn't accessible anymore, despite obviously being exported here: https://github.com/facebook/react/blob/9a2150719b971adf078eca5cecbb18c146545cbd/packages/react-dom/src/client/ReactDOM.js#L205). These are all very time-consuming activities that aren't very commit-rich. Furthermore, I try to commit when there's a tangible improvement to the solution, rather than the more frequent but ultimately useless WIP commits.

At this point, I don't think collaborative efforts would be benefitial. However once we get decent initial version with the new approach, there will be more opportunities for community involvement. Stay tuned!

**Comment by thesunny** [comment]
Just a quick update that @wleroux  got a version of Android support that appears to be mostly working which is the port of the 0.47x version but modified to work with the new design of Slate.

Wayne is continuing to clean that up. We also got an okay from Ian to use a swappable `editable.tsx` component that will allow us to more easily swap the entire input engine for Slate Android. This should keep the input engine separate while still being easy to reason about.

**Comment by clauderic** [comment]
Swapping out the `Editable.tsx` component is an interesting idea, but one that I would advise against. 

In the long term, it will lead to a lot of duplication of code, such as all of the handlers for drag and drop and copy paste, and also mean that bug fixes and new features need to be done in multiple places, which could easily lead to inconsistencies due to human error if one does not remember to update both places and it's not caught during review.

Instead, I'd like to propose a much more encapsulated strategy that would have a much smaller scope. The idea would be to conditionally switch between input handling strategies depending on the environment. This strategy minimizes duplication and allows to encapsulate the input reconciliation strategies.

I wrote a [small work-in-progess proof of concept branch to illustrate the strategy](https://github.com/ianstormtaylor/slate/compare/master...slate-rte:use-input-strategy ) using hooks as input strategies that adhere to a standardized interface in terms of the arguments they accept and their return values (polymorphism). They can both add DOM listeners on the editor's root DOM node or return React synthetic event listeners that should be added on the `<Editor>` div.

**Comment by clauderic** [comment]
I've [opened a draft pull request based on the strategy outlined above](https://github.com/ianstormtaylor/slate/pull/4071) in the hopes of sparking more discussion around the overall approach and bringing more transparency to the development of the Android reconciliation layer so that the community can help

It also introduces more changes to add better support for Android through this Mutation Observer strategy, some of which are directly based off of the work of @wleroux and @thesunny (specifically around text diffing).

https://user-images.githubusercontent.com/1416436/107285339-fe26e800-6a2c-11eb-878b-eb67d91c44af.mp4

**Things that are currently working:**

- Update text (with some issues)
- Replace selection (with some issues)
- Delete selection
- Insert line break
- Delete backwards

**List of known issues (non-exhaustive):**

- Issues updating cursor position when inserting identical text (for example, inserting the letter e multiple times in the word text when the cursor is after t: te|eext)
- Copy/paste should not be tracked as user input by the MutationObserver layer, but currently is
- Need to ignore mutations that happen within void nodes (contenteditable="false")
- Handle readOnly prop of editor

Feedback is welcome, and please report all issues on the PR so we can discuss them and find solutions. This PR is a rough first draft and there are likely many issues with it.

**Comment by thesunny** [comment]
Hi @clauderic,

First of all, I wanted to thank you for your thoughts, feedback and code contributions on adding Android support to Slate. I can see you really care about this project and are putting a lot of effort into its success.

I don't know if the project will get the most traction by having two Android forks building simultaneously and separately. The reason why is that due to the complexity of Android, it could be challenging to take bits and pieces from each of the two forks and combine them together without coordination. If you want to take a coordinated approach, what do you think of reaching out to Wayne on Slate's Slack, either on the `mobile` channel or as a direct message. His username is `Wayne`.

One thing to keep in mind if you decide to move forward on your own is that I'd recommend testing on at least the latest 2-3 versions of Android as per the statistics below. They do need to be tested separately (each Android version has different quirks), and ideally, you'd want real devices as the emulator isn't always accurate in my experience.

StatCounter Worldwide Android

![](https://user-images.githubusercontent.com/469587/107431384-397ff000-6adb-11eb-91fb-a7d5cd3d99a8.png)

StatCounter United States Android

![](https://user-images.githubusercontent.com/469587/107431737-ba3eec00-6adb-11eb-9049-ad5bdc626d92.png)

**Comment by clauderic** [comment]
Hey @thesunny, the intent is by no means to have two separate Android projects simultaneously working in opposite directions, quite the opposite really. Rather, the intent of opening a PR was simply to bring new ideas to the table and spark discussion on some of the technical challenges of bringing Android support to Slate.

I offered to collaborate with @wleroux a while ago, but at the time he did not think collaborative efforts would be benefitial. Would gladly collaborate with him if his views on the matter have changed, will reach out to him on Slack.

**Comment by thesunny** [comment]
@clauderic

Thanks for the clarification and again thanks for the work you are putting.

If Wayne pushed back on input at this time, It may be true that it's not the right time.

There is a point when I was working on Android where I didn't find it was optimal to solicit input. For me that was before it was stable because there were just so many things I had to be thinking about that I couldn't manage another train of thought at the same time.

I think Wayne is coming closer to that point where Android is closer to stable though. We have a meeting once a week, and he seems to be feeling confident that he is getting close.

Sunny

**Comment by signalwerk** [comment]
@clauderic Thank you for your input and your branch. I think it's always good to have someone to bounce off ideas and challenge some architectural decisions. I'm sure @clauderic and @thesunny appreciate your input and I hope your effort pays off in a better and more durable implementation in the end. As an outsider (user of slate, kickstarter, but not dev of slate) I highly appreciate all of your work and I think the idea you bring to the table sounds like you deeply care and have a good understanding how to keep a long maintainable android version alive. Please keep your inputs and engagement up! 

Thank you all.

**Comment by RobbyWH** [comment]
Hello @thesunny @wleroux , 

Is there any updates about the android plugin? Do you have a deadline to finishing this plugin?

thank you for your effort to make android plugin come true.

**Comment by thesunny** [comment]
Hi @RobbyWH, Wayne is continuing to work on it.

I was planning on making the following announcement about two weeks ago but I've been, unfortunately, dealing with something urgent at work which also came in the middle of trying to help complete the advanced TypeScript integration for Slate.

I discussed this with Wayne already and if he is unable to finish a version of the plugin by end of March, and he is not confident in finishing it, I will start personally working on completing the plugin.

**Comment by thesunny** [comment]
Wayne is now in the process of doing platform testing. If you want to experiment with Android support against your Android device (call it a preview), you can take a look here:

[https://github.com/wleroux/slate/tree/bugfix/android-keyboard](https://github.com/wleroux/slate/tree/bugfix/android-keyboard)

For clarity though, Wayne is doing the platform testing so the expectation is that this is not yet ready for production.

The goal is that this will be merged back into master when it's ready.

Also for clarity, the goal is to put this into a state where Android is usable. Even at the end of this process, there won't be a direct 1:1 correlation with Slate on other platforms. There are, amongst other things, hard limitations on what can be achieved with mutations versus the `input` handler, especially with respect to plugins. Over time, the hope is that the community can get Android even closer to being on par with other platforms.

**Comment by thesunny** [comment]
Wayne has completed a Draft PR for Android in Slate.

Please test and provide feedback.

#4200

**Comment by thesunny** [comment]
**Update:** Merged Android support. Please report any Android bugs as issues. #4200

**Comment by toddka** [comment]
Should [this page](https://docs.slatejs.org/general/faq#what-browsers-and-devices-does-slate-support) be updated? I'm just browsing the docs as a first time user and found this discrepancy: "Chrome on Android is supported on Slate 0.47 but is not currently supported in Slate 0.50+ though there is currently work being done on one"

**Comment by thesunny** [comment]
@toddka Yes, this should be updated! I'll fix the docs to reflect this.

**Comment by thesunny** [comment]
@toddka FYI, docs have been updated. Thanks for pointing this out..
