### ISSUE TITLE
Cannot select text within void nodes

### ISSUE THREAD

**Issue by davidruisinger** [ianstormtaylor/slate#3863]
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

- Open [Editable Voids example](https://www.slatejs.org/examples/editable-voids)
- Try selecting one of the labels using the mouse
- Selection is lost right away when releasing the mouse

![jPqQOxFnKu](https://user-images.githubusercontent.com/5305150/92390755-ca613280-f11b-11ea-92ba-505d1a868908.gif)

Slate: 0.58.4
Browser: Chrome & Safari
OS: Mac

#### What's the expected behavior?

Selection should stay

**Comment by BrentFarese** [comment]
Can you add detail as to why you think it's needed to be able to select content inside a `void` node like that?  Does this issue have to do with the fact that the `EditableVoid` in the example has `contenteditable={false}`.  The selection you are referring to is actually not Slate's selection, but is the browser's selection for normal HTML.  I agree it's somewhat odd that the browser selection becomes unset on release, but why do you need to "select" that content to begin with?  As mentioned, the `void` node is not an editable element like other elements in Slate.

Thanks!

**Comment by flavordaaave** [comment]
@BrentFarese In our application we use void elements for e.g. images and we render  render some additional info within the void elements that are esential to our editors in their daily workflow. So in case they added an image from our system to their written article they probably need some other info on that image later on in their article (e.g. a part of the description).

To illustrate what I mean I created a small example based on the "official" images example where you can show additional info on an image using the button underneath. Trying to copy a fraction of the text from the infobox is not working good because of the issue stated above.

[codesandbox](https://codesandbox.io/s/slate-void-selection-issue-n7ubr?file=/src/examples/images.tsx)

**Comment by ryanmitts** [comment]
From having issues with this kind of thing for a couple years, it seems there are two conflicting ideas for what a void node is, and what isn't, and how they should work. It should probably be documented or described in the docs how to handle both cases? I could probably write that up, but have never been sure what the expectation is of a void node to know if I'm capturing the intent.

The two cases seem to be:

1. Things like images and videos, where you want them to be selected as a block, but otherwise behave as not editable.
2. Things that have interactions or text inside that you want completely unmanaged by the parent editor (like the Editable Void example, which I actually contributed).

For the case described, it's because of this logic on the `onClick` handler, [here](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editable.tsx#L598).

The label for that input is selected, and therefore a click within the parent (main) Slate editor, and it notices its contained within a void element, therefore it should select said void element, but that deselects the text element. This logic works find for things like images, but not in the case described here.

You can avoid this by overriding the `onClick` handler and using `e.stopPropagation` to tell Slate not to default handle the click. In your own handler you check whether you want the void node to behave like case 1 or 2 above, and if case 2, then stop propagation.

On the Editable:
```
onClick={e => {
          const { target } = e
          const inEditor = ReactEditor.hasDOMNode(editor, target)
          if (inEditor) {
            const node = ReactEditor.toSlateNode(editor, e.target)
            // Check if you want the inside of the node to be completely ignored.
            if (node.type === 'editable-void') {
              // Slate recognized stopPopagation or preventDefault as marking the event as handled,
              // using stopPropagation since preventDefault prevents things like radio buttons from working.
              e.stopPropagation();
            }
          }
 }}
```

And actually, without this logic on the Editable Voids example, you get some strange behavior with two or more editable-void blocks, clicking in the "dead" space in those blocks, then into an editor, sometimes will not put the caret in the editor, you have to click twice.

You do however lose the ability to use `useSelected`, but you could probably write your own logic to replace that.

It seems there has been some thought in the past about this kind of nested concept, since `hasEditableTarget` in editable.tsx is checking the contentEditable field on the target. This prevents some of the other handlers from reacting to events within the void elements, without this logic, things like the input field wouldn't work in the Editable Voids example.
