### ISSUE TITLE
Don't use Node.nodes to only iterate child nodes

### ISSUE THREAD

**Issue by travigd** [ianstormtaylor/slate#3867]
https://github.com/ianstormtaylor/slate/blob/0bbe121d76c5c2313d939de8a7ebed3bfd37f62d/packages/slate/src/transforms/text.ts#L295-L298

This caught me off guard. I enforce in my schema that all nodes have a valid type, and I was getting strange errors about undefined type, which I eventually tracked down to these few lines of code. All this code is doing is using `Node.nodes` to iterate over all the child nodes in an array, but it ends up calling `editor.isInline` on the invalid node that it creates, which ultimately throws a `TypeError` (due to my implementation of `isInline`).

For now, I just added a check to avoid the error in `isInline`, but this seems like a bug.

**Comment by BrentFarese** [comment]
What is the actual bug here?  Please provide more info.  Thanks!

**Comment by travigd** [comment]
The bug here is that the line above calls `Node.nodes(...)` on a "synthetic" node only for the purpose of iterating over the array of nodes that it has (and all of its descendants).

Basically, it does:
```ts
const syntheticNode: Node = { children: fragment };
for (const entry of Node.nodes(syntheticNode)) { ... }
```

Because of this, `syntheticNode` ends up getting passed into the machinery for "normal" nodes (i.e., slate calls the `isInline` function on it). This is problematic™ because my inline function looks something like this:

```ts
function isInline(node: Node) {
  switch (node.type) {
    case "paragraph":
      return true;
    ...
    default:
      throw new Error(`Unknown node type: ${node.type}`);
  }
}
```

It throws an error (`Unknown node type: undefined`) because it passes the `syntheticNode` above into that function.

It feels like this shouldn't be happening, otherwise it's very hard to create invariants about your nodes (e.g., in my schema, every node has a `type` value).

**Comment by BrentFarese** [comment]
I am not so sure this is a bug at all.  `insertFragment` is essentially checking the `fragment: Node[]` parameter passed into the function before proceeding.  It seems like simply updating your `isInline` function did the trick, and I would say that function should be robust and account for a `Node` that might not have a `type`.  Going to close this issue but if there really is a bug glad to reopen.  Thanks!

**Comment by travigd** [comment]
I wholeheartedly disagree.

There's no reason to use `Node.nodes(...)` just to iterate over an array of nodes and their descendants, that could easily be a utility function.

I think the application developer should have control over their schema. I'd rather throw an error if my invariants fail than silently ignore it and hope for the best.

**Comment by BrentFarese** [comment]
The use of `Node.nodes` does not seems to be the issue to me, unless I'm missing something.  The issue appears to be that `Node.nodes` passes a `Node` without a `type` into your `isInline` function.  It seems to me that occurs because of the [matcher](https://github.com/ianstormtaylor/slate/blob/0bbe121d76c5c2313d939de8a7ebed3bfd37f62d/packages/slate/src/transforms/text.ts#L271) that gets called.  The `matcher` gets called on the "synthetic" node as you have put it, which is an `Element` (it has `children`) but lacks a `type` key. 

My suggestion for guaranteeing your invariants is to do that in a normalization.  It's up to you if you want to `throw` in your `isInline` function but it can break as shown here if some incoming node doesn't match your expectation.  `isInline` is really meant to return true/false based on whether a node is an inline, so if it doesn't have a type I would simply return false.

If you want to enforce your schema, try doing it in a normalization as you are guaranteed that all nodes passed into the normalization are from the `editor` and are not synthetic.

Closing this but I am glad to reopen if it's an actual bug or if you have a suggestion for changing the implementation.  Thank you!

**Comment by travigd** [comment]
I am suggesting a change in the implementation.

I see where you're coming from, but it seems to me that it doesn't really need to be this way. There's no great technical reason that we can't just have a utility method (something like `iterateDescendants`) here that just sidesteps the whole thing.

So my suggested change is add a `iterateDescendants` method to be called instead of using `Node.nodes(...)` here.

**Comment by BrentFarese** [comment]
That suggestion will not cause your error to go away.  The error arises not because of `Node.nodes` but because of the `matcher` function.  `Node.nodes` is a utility that allows you to iterate descendants, unless you are saying your issue is that `Node.nodes` iterates over the "synthetic" node when it doesn't have to?  Is that what you are getting at?  Glad to accept a PR with your proposal.  Thanks!

**Comment by travigd** [comment]
Yeah, to be clear, my issue is that the "synthetic" node ultimately gets passed into the `matcher` function but it doesn't need to be to satisfy the use case.

I'm basically proposing changing it to
```ts
function *iterateDescendants(nodes: readonly Node[]) {
  for (const node of nodes) {
    yield* Node.nodes(node);
  }
}
```

so that we never have to pass a "synthetic" node into the Slate machinery.

**Comment by BrentFarese** [comment]
Ah ok now I understand your specific issue.  Glad to reopen/consider if you want to submit a PR, although again I would encourage validating your schema to be at the normalization layer and not to rely on `isInline` for this use case.  Thanks.
