### ISSUE TITLE
'split_node' op: can't exclude node properties

### ISSUE THREAD

**Issue by bryanph** [ianstormtaylor/slate#3927]
#### Do you want to request a _feature_ or report a _bug_?
In `Editor.transform` a `split_node` operation always results in a spread of all object properties of the node that is being split into the newly inserted node. Because of that there is no way to exclude properties. The properties are already included in the `properties` property so there seems to be no need for this. 

https://github.com/ianstormtaylor/slate/blob/0bbe121d76c5c2313d939de8a7ebed3bfd37f62d/packages/slate/src/interfaces/editor.ts#L1484-L1486

#### What's the current behavior?
Node properties are always included into the newly inserted node for a `split_node` operation

#### What's the expected behavior?
Only merge properties from the `properties` object into the new node for a `split_node` operation

**Comment by BrentFarese** [comment]
I see your point.  But I am not so sure it is a `split_node` op if theoretically only some properties of the node being split are merged in.  Is this something that is better left to the dev - _e.g.,_ if you want to omit properties, omit them after the split?  If you can elaborate on your actual use case, that might help a bit.  I am just somewhat wary of removing this as a safeguard since then we have to be sure **_every_** call to `split_node` has a full set of properties/the correct properties.

**Comment by bryanph** [comment]
My use-case is setting a `uuid` on every element and so if a block is split I want to assign a new `uuid` to the split block. My first idea was to override `apply` and remove the `uuid` from `properties` in the `split_node` op but because in `apply()` the properties of the actual node are also merged in, the `properties` property basically has no effect. I would expect it to respect the `properties` property and just merge those properties. That is currently not the case. I solve this differently now by overriding the `insertBreak` command and doing the required work there. Because under the hood for `split_node` already all properties of the node are set on `properties` I don't see a need to merge in the node properties at `apply` time as well.

**Comment by TheSpyder** [comment]
> My use-case is setting a `uuid` on every element and so if a block is split I want to assign a new `uuid` to the split block.

This might not matter to you now, but please note that if you ever turn on real-time collaboration it is critical that `split_node` properties contain the exact set of attributes from the node that was split - no more, no less. Applying your own hand-crafted `split_node` operations that do not do this will lead to edge case convergence failures.

The correct way to approach this from an RTC perspective is to apply a normal `split_node` and then use a `set_node` to adjust the UUID on the newly split element.


> I am just somewhat wary of removing this as a safeguard since then we have to be sure **_every_** call to `split_node` has a full set of properties/the correct properties

As I mentioned in my PR, there is only one place split node operations are created, and it does guarantee the full set of properties:
https://github.com/ianstormtaylor/slate/blob/b1f291ef88d6d0ae921e61690e3661a4962db5e9/packages%2Fslate%2Fsrc%2Ftransforms%2Fnode.ts#L634-L640

**Comment by Xheldon** [comment]
> I see your point. But I am not so sure it is a `split_node` op if theoretically only some properties of the node being split are merged in. Is this something that is better left to the dev - _e.g.,_ if you want to omit properties, omit them after the split? If you can elaborate on your actual use case, that might help a bit. I am just somewhat wary of removing this as a safeguard since then we have to be sure **_every_** call to `split_node` has a full set of properties/the correct properties.

I also have a case: I want when I put the cursor in the Heading node and press the Enter key will split one Heading node to two node, the first is the text before cursor, it's keep be a Heading, but the second node be a Paragraph, and remove the props of Heading node, but I can't do that. It's always spread the props to new node.

**Comment by TheSpyder** [comment]
That's the same case as `uuid` though. Instead of adding a property you're changing one.

Fundamentally, hand crafting a `split_node` operation to avoid two separate API calls to split the node and then update the second block will break a core assumption about the contents of `split_node` operations. This might not impact cases where collaboration isn't used, but it could cause weird behaviour with undo/redo. And you never know when you might decide to add collaboration later.

I don't agree with the reasons this issue was created, but a side effect of my PR fixing the collaboration bug is that these scenarios will become feasible. I don't think that should stop us merging my PR, Ian has approved it after all, it's just worth noting.

**Comment by BrentFarese** [comment]
Fixed by #4004.
