### ISSUE TITLE
Cannot resolve a DOM node from Slate node: {"text":""}

### ISSUE THREAD

**Issue by Casen** [ianstormtaylor/slate#3930]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

```
Transforms.insertNodes(props.editor, [{
      type: 'image',
      src: url,
      children: [{text: ''}]
    }])
```
After inserting an image as a void node, and then clicking the image, the editor throws the error
```
Cannot resolve a DOM node from Slate node: {"text":""}
```
The resulting editor state when inserting an image: 

```
[{type: 'image', src: 'http://imageurl.com/image.jpg', children: [{text: ''}]}]
```

The resulting DOM: 
```
<img data-slate-node="element" data-slate-void="true" src="http://imageurl.com/image.jpg">
```

The area of the code responsible for determining focus is where the error is thrown:
https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/plugin/react-editor.ts#L211

Unless I am missing something, this bug doesn't make a whole lot of sense. I will keep poking around, but unfortunately the documentation seems very sparse after the latest update, so I am not sure what's up or down any more. Lots of outdated information floating around.

Slate: 0.59.0
Browser: Chrome
OS: Mac
#### What's the expected behavior?
Either nothing happens, or the cursor just rests on either side of the image.

**Comment by AlfonzAlfonz** [comment]
I've run into the same problem, but I've managed to fix it by rendering `{children}` somewhere in my void element.

**Comment by Casen** [comment]
Thanks for chiming in @AlfonzAlfonz !

I discovered this as well by digging into one of the hosted example projects. The documentation is just not very clear about how to handle void elements

```
const ImageElement = ({ attributes, children, element }) => {
    const selected = useSelected()
    const focused = useFocused()
    return (
        <div {...attributes}>
            <div contentEditable={false}>
                <img
                  src={element.url}
                  style={{
                      display: 'block',
                      maxWidth: '550px',
                      maxHeight: '20em',
                      boxShadow: `${selected && focused ? '0 0 0 3px #B4D5FF' : 'none'}`
                  }}
                />
            </div>
            {children}
        </div>
    )
}

```

As you mentioned, {children} must be passed. The outermost div must have the attributes rendered, followed by a div with contentEditable={false}, followed finally by an image tag. The children being rendered in the within the outermost div.

**Comment by BrentFarese** [comment]
@Casen is your issue solved via the solution above?  Can we close this issue?

**Comment by cmditch** [comment]
I just ran into this issue @BrentFarese and the snippet @Casen posted fixed the issue. 

Should we update the docs for void elements?

**Comment by Casen** [comment]
@BrentFarese Sorry for the late reply, we can totally close the issue. I agree with @cmditch that docs should be more clear.

**Comment by pramod2** [comment]
@Casen, thanks a lot! I was struggling with this and your suggestion finally fixed my problem. However, why is this the case that we need to wrap it with multiple divs? Understanding the reason may help prevent some other errors in the future.

**Comment by Zino-ctrlZ** [comment]
@pramodkandel I now its been years since this thread got updated, but did you ever find the reasoning behind this ?

**Comment by 12joan** [comment]
@pramodkandel @Zino-ctrlZ Slate expects that each selectable point in the editor maps to a selectable DOM point in some contenteditable element.

The `children` that must be rendered inside a void element looks like this:

```html
<div data-slate-spacer="true" style="height: 0px; color: transparent; outline: none; position: absolute;">
  <span data-slate-node="text">
    <span data-slate-leaf="true">
      <span data-slate-zero-width="z" data-slate-length="0">﻿
        &#FEFF;
      </span>
    </span>
  </span>
</div>
```

The `[data-slate-node="text"]` has a React `ref` prop that associates it with the empty text node in Slate. When the void element is selected (such as when you click it), Slate tries to find this DOM node so that it can place the DOM selection inside it. This is why we get an error `Cannot resolve a DOM node from Slate node: {"text":""}` if this DOM node is missing.

The `&#FEFF;` character is a [zero width no-break space](https://unicode-explorer.com/c/FEFF), and is there to make the `[data-slate-node="text"]` non-empty so that it's a valid selectable position. For the same reason, these DOM nodes must be in a contenteditable, meaning there must be no ancestors with `contenteditable="false"`.

This is why void elements should have an editable outer `<div>` containing `children` and an inner non-editable `<div>` (or similar) containing the visible content.

Here are some places in `slate-react`'s code to take a look at if you want to learn more:

- [`packages/slate-react/src/components/element.tsx`](https://github.com/ianstormtaylor/slate/blob/622fb11530811fffae284d463de1f49a1ef217a1/packages/slate-react/src/components/element.tsx#L111-L144), where the `[data-slate-spacer]` is defined
- [`packages/slate-react/src/components/text.tsx`](https://github.com/ianstormtaylor/slate/blob/622fb11530811fffae284d463de1f49a1ef217a1/packages/slate-react/src/components/text.tsx#L67-L93), where the attributes of the `[data-slate-node="text"]` are defined, including the `ref` that associates the DOM node with the Slate text node
- [`packages/slate-react/src/components/editable.tsx`](https://github.com/ianstormtaylor/slate/blob/622fb11530811fffae284d463de1f49a1ef217a1/packages/slate-react/src/components/editable.tsx#L461-L488), which contains the logic that converts the internal Slate selection to a DOM range (including getting the DOM node(s) containing the anchor and focus) and updates the DOM selection accordingly

Hope this helps!
