### ISSUE TITLE
Normalization opt-out

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#3955]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Right now, normalization is run on every keystroke, no matter what was changed.

Slate: 0.59.0

#### What's the expected behavior?

There could be second parameter to `normalizeNode` informing function about performed change:

```js
const normalizeNode = (entry, change) => {}
```

In the most basic case there could be object with following properties:
```ts
const change = {
    text: <boolean>, // Whether any text node was changed
    void: <boolean>, // Whether any void was transformed
    node: <boolean>, // Whether any node was transformed (except text content change)
    origin: <Location> // Which Location was origin of current normalization (ref would be more useful)
}
```

This way you can skip performing some normalization logic and make editor faster.

**Comment by CameronAckermanSEL** [comment]
It is deliberate that they are run on each change and the recommendation for normalization functions is to write them such that they abort as quickly as possible. 

In addition, I'm very confident this request is already implemented because the normalize function already passes node and path that are undergoing normalization. See the forced layout example: https://github.com/ianstormtaylor/slate/blob/master/site/examples/forced-layout.tsx#L9

**Comment by Mangatt** [comment]
Passed node and path are informing about current node, not about node that originated that change.

As of now, you can't reliably check children-parent relationship (e.g. check if parent node is correct type), because that normalization is sometimes not run (see #3950), so you have to rely on parent-children relationship (which is 1:n).

When you enforce schema (as most of us do in some way), you can run those potentially costly operations on every keystroke for possibly hundreds elements.
