### ISSUE TITLE
Should node data structure be optimized?

### ISSUE THREAD

**Issue by aunsuwijak** [ianstormtaylor/slate#398]
@ianstormtaylor According to this issue https://github.com/ianstormtaylor/slate/issues/180 the method like `getParent` and `assertDescendant` traverse the tree and being called many times, which causes performance issues.

There are 2 solutions I can think of that can solve the issue which are
- Reduce the number of method calls
- Reduce the execution time of the method

I think the second choice would be a better solution.

Correct me if I'm wrong. The current data structure of node is a simple tree which is bad performance on searching. (DFS, BFS)

There are some existing optimized tree data structure like BST, B-Tree or maybe completely new structure which might be higher search performance, which I think they can possibly reduce the execution time of the method.

What do you think about this idea?

**Comment by ianstormtaylor** [comment]
@aunsuwijak hey, good question. I think for right now most of the performance issues will be had not by improving the search method (although at some point that may be our bottleneck), but by things like:

- improving react rendering performance
- not traversing the tree unnecessarily
- not performing unnecessary checks during transforms

For now I think we should concentrate our performance optimizing efforts on those things, instead of on changing the data structure. But further down the road, if we decide that the data structure itself is the bottleneck, it might be worth doing more research. If you disagree though, feel free to write up some thoughts and investigate the performance issues, and I'm down to reconsider.

Thanks for asking!

**Comment by aunsuwijak** [comment]
Thanks you for the answer @ianstormtaylor 

I think improve react rendering performance should not be the first priority. Here are the picture of chrome timeline compare between simple state (paragraph, blockquote, etc.) and complex state (table) mutation by hit return on paragraph node (I already merged #354  and #364 ) 

**Simple state** (~170 ms)

![simple-state](https://cloud.githubusercontent.com/assets/5433223/19586511/c214a80e-977f-11e6-8136-17bc1f4537ab.png)

**Complex state** (~630 ms)

![complex-state](https://cloud.githubusercontent.com/assets/5433223/19586516/cc59427a-977f-11e6-9963-e218ce2abb6a.png)

You can see from the picture that react render is not the part that takes long execution time.
So I think react rendering does not imply the performance issue.

I totally agree to not traverse the tree if unnecessarily, but if there is some case that we can't fix or the fix will increase complexity. We should have some other solution for it.

I've tried remove `assertDescendant` (I think this one is unnecessarily), but method like `getParent` and `findDescendant` still need to be there and I can't think of any better algorithm to speed up this kind of method (DFS is current implementation right? should be the fastest on simple tree) without modifying node data structure.

**Comment by ianstormtaylor** [comment]
Interesting, when you say "complex state", what does that tree look like? And what are the actions that are being taken on the state in that example?

There very well might be a way to improve that performance a lot with memoization. One problem with `filter/find` is that they are usually used in the codebase right now with anonymous, one-time-use functions, which means they will never be memoized (like a lot of other methods are) since their arguments will always be unique-by-reference. So there's probably a way to speed those up.

The thing I want to avoid though is getting in discussions about changing the underlying data structure drastically before doing research to see what the specific causes for slowdown are. Especially because from a developer experience standpoint of understanding and reading the current data structure is pretty nice and clear.

I think there are probably many many places to improve the current logic, or at least many things that would need to be researched before we can conclusively say that the current data structure just isn't going to be fast enough no matter what we do.

**Comment by ianstormtaylor** [comment]
Another critical thing, which @Soreine has been working on, is getting benchmarks which we can use to standardize how we're talking about performance issues. One necessary step is to get a collection of test cases for common user interactions, eg.:

- Hitting backspace a bunch of times in a row until the start of a line
- Hitting enter to split a paragraph a bunch of times in a row
- Inserting a large, complex fragment into the middle of an already complex document
- etc...

Having a set of agreed-upon definitions for the behaviors that are currently slow, and that we then need to dive deep to optimize will be extremely useful.
