### ISSUE TITLE
Add CHANGELOG and releases

### ISSUE THREAD

**Issue by okonet** [ianstormtaylor/slate#399]
At the moment it's impossible to see what has been changed between releases.

**Comment by arekkas** [comment]
No it's not, you simply missed it: https://github.com/ianstormtaylor/slate/blob/master/History.md

**Comment by okonet** [comment]
Right, I missed `History.md`. I'd rename it to `CHANGELOG.md` for consistensy.

The `/releases` are empty, that's why I files the issue.

With the help of https://github.com/MoOx/github-release-from-changelog you can publish the content of the changelog to the releases.

**Comment by okonet** [comment]
Also, history.md isn't in sync with releases:

> 0.14.0 — September 10, 2016

thus releases have 

> v0.14.15

released 16 days ago

**Comment by arekkas** [comment]
> With the help of https://github.com/MoOx/github-release-from-changelog you can publish the content of the changelog to the releases

That's awesome!

> Also, history.md isn't in sync with releases:

history.md only documents breaking changes, patch versions usually only fix bugs and do not introduce regression issues which is why they are not documented.

**Comment by ianstormtaylor** [comment]
I'm planning on adding to `/releases` later, and will backdate them with all of the existing ones. But like @arekkas mentioned, for now the content lives in `History.md`.

It only keeps track of breaking changes (currently at minor versions) because too many things are being added/refactored right now to try and write them all down well.
