### ISSUE TITLE
Feature | Images | To upload from computer

### ISSUE THREAD

**Issue by abelardolg** [ianstormtaylor/slate#4036]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
An image can either be added by providing an url or pasting its url into the text...but couldn't I upload it from my computer?

Slate: 0.XX.X (last version)
Browser: Chrome / Safari / Firefox / Edge - any
OS: Mac / Windows / Linux / iOS / Android - any

#### What's the expected behavior?
To upload a picture from computer

**Comment by jacob-lcs** [comment]
this is just a editor framework, you should implement this function by your self

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. Check out the [contributing guidelines](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md) for more info.

Thanks for understanding!

**Comment by williamstein** [comment]
For the record, there seems to be a slate plugin that supports pasting images from the clipboard listed here:  https://github.com/udecode/slate-plugins#-plugins
