### ISSUE TITLE
Html Serializer retains excess whitespace between tags

### ISSUE THREAD

**Issue by LeeKevin** [ianstormtaylor/slate#407]
For example,

```
Html.deserialize(`<div>
    <strong>Test</strong> 
</div>`)
```

Will render **Test** with four leading spaces. I'm not sure if you want to leave this up to the developer to implement their own rules, but I believe we should provide a foundation that follows [spec](https://www.w3.org/TR/REC-html40/struct/text.html#h-9.1).

I would recommend changing the default text node rule at [html.js#L41](https://github.com/ianstormtaylor/slate/blob/f1a5d6f3b400c1b576ab4bcf6db97a6330d1d529/src/serializers/html.js#L41) to something like:

```
         if (el.type == 'text') {
             let text = el.data

             // Strip extra spaces
             if (!text.trim()) text = el.next && el.prev ? ' ' : ''

             return {
                 kind: 'text',
                 text: text,
             }
         }
```

**Comment by roadscape** [comment]
Whitespace normalization is not very straightforward; your change may break formatting in `<pre>` elements for example.

In [serializers/html.js#L94](https://github.com/ianstormtaylor/slate/blob/e63a6b36ce422451935a9d83274351ff1641e13a/src/serializers/html.js#L94), you can try changing

    const $ = cheerio.load(html).root()

to

    const $ = cheerio.load(html, {normalizeWhitespace: true}).root()

cheerio will pass this option directly to the underlying [htmlparser2](https://github.com/fb55/htmlparser2/wiki/Parser-options), unfortunately it does [not do a proper job](https://github.com/fb55/domhandler/issues/11).

I had much better results running incoming html through [htmlclean](https://github.com/anseki/htmlclean) before passing it to cheerio. But it seems to rely on regex and if this is the case I wouldn't trust it unless you knew incoming HTML was always well-formed.

**Comment by ianstormtaylor** [comment]
Yeah I agree that that's frustrating when what you want is for the whitespace to be ignored. 

But I think this is something we should leave as is, because it allows for the text editing behavior that people are used to (specifically `whitespace: pre-wrap`) where they can hit the spacebar multiple times to see multiple spaces show up. Without that the editor would feel strange. And if the HTML serializer ignored the spaces it would lead to cases where what was entered in the editor is not what was displayed later on reload. 

So even though it makes the pre-formatted string deserializing case more frustrating, I think this is the behavior we should keep. Thanks for opening this though! I hadn't really thought about that before.

**Comment by zhujinxuan** [comment]
@ianstormtaylor Sorry to interrupt you in a closed issue.  I am thinking about an advantage of no-extra space in serializing.

In the web-app, we can use
```
 new Promise( (resolve, reject) => {
  const prevHTML = serialize(deserialize(html));
  const nextHTML = serialize(deserialize(prevHTML));
  if (prevHTML === nextHTML) {
    resolve()
  } else {
    reject({prevHTML, nextHTML, html})
  }
}).catch(e=> notifyServerOrElsewhere(e))
```

With extra space, the validation is not so easy.

**Comment by ianstormtaylor** [comment]
@zhujinxuan I think this is something that should be handled outside of Slate if it's something you need. For the most part, the HTML serializer is used with programmatically generated HTML where whitespace is significant.

**Comment by zhujinxuan** [comment]
Got it. Thank you very much.
