### ISSUE TITLE
[Editable] forwardRef

### ISSUE THREAD

**Issue by Mangatt** [ianstormtaylor/slate#4082]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Editable is not able to hold `ref`

Slate: 0.60.4
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

#### What's the expected behavior?

Editable could be able to hold ref with `React.forwardRef`. Since this component is currently using ref internally, ref would have to be patched, but technically this does not pose a problem.

If there isn't reason for this limitation in Slate internals, I'll create PR.

**Comment by williamstein** [comment]
Comment from a user (hence a +1 for this idea): A few days ago I had no choice but to implement something very similar to this in my local copy of slate-react in order to implement scroll position save/restore (when you come back to editing a document, I need to restore the scroll position).   

https://github.com/sagemathinc/cocalc/commit/18b269425a0a2011cf99f2b933aad860b4d935d2

**Comment by skotchpine** [comment]
Same issue for us at userhero.io

**Comment by bryanph** [comment]
No reason, PR is welcome

**Comment by WillTaylor22** [comment]
Apologies for not contributing much - and thanks for all the great work, but just thought I'd +1 this as this would be super valuable for our startup.
