### ISSUE TITLE
Please maintain a proper changelog

### ISSUE THREAD

**Issue by tiberiuichim** [ianstormtaylor/slate#4102]
**Problem**

Slate is a great project, with very interesting ideas. It also continues to get more popular, so it's not like it's a dying library. I know there's issues with available maintainers and so on, but I can see releases are continuing to be made. The problem is, though, that there's no proper changelog maintained. The 0.59 release isn't even mentioned in the changelog, let alone the 0.60 release.

**Solution**

I think all PRs should include a changelog entry. There are Github actions that can guard the PR and fail it unless a CHANGELOG entry is included.

**Alternatives**

Software such as release-it can agregate the commits and produce a changelog, thought it's not at all as usable as a human-maintained changelog.

**Context**

Everyone else has it. It's industry standard and it's to be expected from any high-quality software.

**Comment by TheSpyder** [comment]
0.59 was an oversight, but 0.60 isn't _technically_ a release yet (it's still @next on NPM). You're right, though, a changelog should be done as development happens not all at the end.

**Comment by floriangosse** [comment]
For easier maintenance of the changelog, we could use [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) which can automate the changelog generation and the publishing for the package's version.

**Comment by ianstormtaylor** [comment]
I'd definitely like to get the releases automated with a Semantic Release–type system. I'm waiting until Sunny's able to get the TypeScript pieces sorted because I don't want to step on his toes while he's in the middle of fixing up `next`—but after that I'm down.

**Comment by stnwk** [comment]
Is there any way to know what to look out for when upgrading? Feel very insecure about doing this without any changelog/history for new releases 😬

**Comment by williamstein** [comment]
> Is there any way to know what to look out for when upgrading? Feel very insecure about doing this without any changelog/history for new releases 😬

I read the actual commit log, which is a lot of work, but very helpful: https://github.com/ianstormtaylor/slate/commits/master

I'm pretty invested in using slate though, and willing to put a lot of time into it.   Even with all its shortcomings, slate is the best choice right now, because the code is so well written (and fits into the tooling I use -- Typescript + React hooks) that I can always jump in and read and understand it, and slate is architected in such a way that you can often write a small extension to work around bugs in the core.    That said, with slate-react, I ended up having to fork it, and I've been manually merging in each of the good PR's (then commenting about my experiences on the PR).

Slate has huge potential, and I'm very grateful to everybody working on it.

**Comment by stnwk** [comment]
Agree, really love using slate - but the last npm-release was in September 2020 and with such a delicate package that encourages customising and building on top of its features, it feels very risky to upgrade without the confidence of a changelog and manually going through the commit history back to september 2020 is just ... a lot 😄

Thanks for your reply though, will do!

**Comment by williamstein** [comment]
> - but the last npm-release was in September 2020

I should add that I've been working with the @next npm releases, which come out every few weeks.  Releases are listed here: https://www.npmjs.com/package/slate

For me, using the @next version is really critical because of the vastly improved typescript support.   I have the impression that @next is getting close to being the official release soon, though that's not at all up to me...

**Comment by TheSpyder** [comment]
> manually going through the commit history back to september 2020 is just ... a lot 😄

Focus on the PR merges; most of the changes should have happened via PR and for those you can read the linked PR description.

**Comment by thesunny** [comment]
The biggest change is if you are using TypeScript. I added a new chapter in the documentation which should help you get started: [https://docs.slatejs.org/concepts/11-typescript](https://docs.slatejs.org/concepts/11-typescript)

Also made API reference improvements: Added missing `Editor` and `Path` objects. Split out the object references into their own pages.

**Comment by thesunny** [comment]
Added an entry to the Changelog for the TypeScript improvements with a link to the documentation.

**Comment by stnwk** [comment]
Thanks!

**Comment by thesunny** [comment]
Note: Added a link to the TypeScript documentation in `Changelog.md`. @TheSpyder if there are other important changes, especially breaking ones, feel free to make a PR for the Changelog and I should be able to merge them quickly if you **mention** me.

**Comment by ianstormtaylor** [comment]
I've updated the main changelog with the missing versions.

And I've also setup continuous releases using [🦋 Changesets](https://github.com/atlassian/changesets) which will automatically track releases and changes over time and generate changelogs for them. For now they are separate per-package, but hopefully in the future they will add the ability to keep them all in a single log again.

**Comment by tiberiuichim** [comment]
@ianstormtaylor Very much appreciated! Also, your return to the project is a huge confidence boost.

**Comment by Slapbox** [comment]
Are there changelogs for the versions from `0.50.x` to `0.61.x`? I hope?

**Comment by TheSpyder** [comment]
It was [moved into the docs](https://docs.slatejs.org/general/changelog) ([source](https://github.com/ianstormtaylor/slate/blob/main/docs/general/changelog.md)). Once the issue with changesets and monorepos is resolved it can go back into the project root.
