### ISSUE TITLE
Discussion: Memoization solution

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#411]
As @SamyPesse and I are investigating performances issues, we are having a look at the current memoization implementation.

We have noticed for example that the sole memoization of `findDescendantDeep` is taking up to 30% of the execution time during normalization calls. Several reasons:
1. `findDescendantDeep` is recursive, and gets called many times
2. its argument is a function, and we always pass an arrow function to it (unique reference every time), which prevent any cache hit
3. the cache grows indefinitely, and a lot of time is spent looking for cached results in the underlying `Immutable.Map` with no benefit (the calls to `hasIn` and `setIn` account for the mentioned 30%).

Of course, we are going to improve the case of `findDescendantDeep` (and similarly `findDescendant`). But this also opens up a new topic: the way we memoize methods. Currently, we use an in-house solution using an `Immutable.Map` cache. But should we consider using a popular implementation, like [memoizee](https://github.com/medikoo/memoizee) and such? It can bring:
- Better performances
- Cache management, with LRU limits for example

@ianstormtaylor what's your opinion?

**Comment by ianstormtaylor** [comment]
Good discussion.

Totally agree with (2). Any of the cases where we are using functions like `find` or `filter` on nodes are currently using arrow functions, which isn't great at all since it skips memoization like you mentioned. I believe fixing this issue (by not creating new functions each time) will drastically improve the performance, and will eliminate some of the issues with (1) and (3) as well.

For (1), I think the recursive nature might not be a problem if we can fix (2). Actually, when properly memoized where the results are hitting the cache, the recursive nature should actually speed things up, if I'm thinking about it correctly, since it allows the cache to work at all levels of the tree, so that small changes to leaf nodes don't have to throw out the cache for the entire tree completely. (I believe that's why I chose to design it that way, but I could be missing something.)

For (3), I also think that this will be less of a problem once we can fix (2), since the reason it's **so** unbounded is because it's guaranteed right now to never get a cache hit, so that combined with the recursion is creating lots of entries. I have a feeling that once the cache is properly being hit that this won't be a problem.

---

I'd be open to discussing using a different memoization technique if we decide that's the blocker. 

The reason I rolled my own for this case was because my idea was to create a memoization system that benefitted from the fact that we're using `Immutable` objects that don't change. Since a change requires creating an entirely new instance, I figured that memoizing on the instance itself gives us automatic cache busting without any extra logic. When a new instance is created, it has no cache, so all of the methods will  be properly computed again. But as long as an immutable instance sticks around, it only ever has to compute the result once.

A lot of the memoization libraries I looked at were specific to individual functions, and it felt like I was going to end up having to do some weird things to get the maximum benefit from `Immutable` instances. But I could totally be wrong there.

That said, even if we don't reach for another library, there's definitely a case to be made to somehow prevent the cache from growing indefinitely for each instance, if memory continues to be an issue. For now I **think** that properly memoizing the arrow functions will solve our issues.

---

How does that sound?

**Comment by Soreine** [comment]
Tying caches to each Node instance is a good idea, I had not realized that.

For arrows, it's not that easy. Take for example the case of `getDescendant` (which is itself memoized). Its implementation is simply `return this.findDescendantDeep(node => node.key == key)`. We can't make the arrow a static function because we need the `key` value in the closure.

For now, I will keep the iterator methods unmemoized. And I'll make sure we have specific memoized methods for cases like this. Continuing on the example of `getDescendant`, I will rewrite `getDescendant` to be recursively memoized on its own:

```js
  /**
   * Get a descendant node by `key`.
   *
   * @param {String} key
   * @return {Node or Null} node
   */

  getDescendant(key) {
    key = Normalize.key(key)
    return this._getDescendant(key)
  },

  // This one is memoized
  _getDescendant(key) {
    let descendantFound = null

    const found = this.nodes.find(node => {
      if (node.key === key) {
        return node
      } else if (node.kind !== 'text') {
        descendantFound = node._getDescendant(key)
        return descendantFound
      } else {
        return false
      }
    })

    return descendantFound || found
  }
```

**Comment by Soreine** [comment]
By the way, I think `Immutable` uses `Immutable.is` to lookup keys in a `Map`. Wouldn't it be faster if we only used `===` comparison to lookup keys in the cache ? Do we need to use `Immutable.Map` for our internal cache ?

**Comment by Soreine** [comment]
Most methods in Slate accept several types for the same argument, and coerce the arguments using `Normalize.foo` functions. For example, a method with a `key` argument, can accept a `Node` or a `String`, and use `Normalize.key` to coerce the argument. This is hostile to memoization.

With @SamyPesse, we think methods should not coerce arguments. It's good practice for developers to be explicit with variables and argument types, even if it costs a few more characters of source code :D

Can we remove it ?

**Comment by ianstormtaylor** [comment]
1. I think you're right about `Immutable.is`. I'm down to remove that and only ever do `===` comparisons. If you do it, can you profile it to make sure we're correct on that guess? I think I just used `Immutable.Map` since it was super easy to use `setIn` and `getIn` to achieve the functionality without reinventing. But down to ditch it.

2. For multiple arguments, I **could** be convinced to do that later, but right now until we get memoization figured out I'd like to leave it the way it is, so that we're not changing too much at once. I agree that it's bad for memoization, and some of them might just be too "magicky" in general, but I'd like to review that separately.

**Comment by SamyPesse** [comment]
@ianstormtaylor I've implemented a compromise: deprecate using a dev warning passing `Node` instead of `String`; and adapting all calls in the core: https://github.com/GitbookIO/slate/pull/2

The PR describes the benefits. And then later we can change the signature (the dev warning will noticed devs in the mid-time).


The memoization issues may sounds not important, but for example when pressing <kbd>Enter</kbd> memoized methods are called more than 1000 times (previously with a ~55% cache hit).

**Comment by ianstormtaylor** [comment]
Closing, since I think we came to a solution here.
