### ISSUE TITLE
Improve text editing for composition

### ISSUE THREAD

**Issue by cancue** [ianstormtaylor/slate#4127]
**Problem**
There are **composition bugs** that cannot be fixed.
That is because the entire editor area is content-editable and it re-renders every time.

IME has a reference of a specific text node during composition. However, when react re-renders the editor, the text node no longer exists. Therefore, on the next tick, the IME positions the cursor at the wrong location like the first node of the editor, and further, it does wrong actions (such as deleting a character that does not exist).

If composition bugs are not resolved, Slate cannot be used at production level in most languages.

**Solution**
Floating contenteditable input area like google docs.

- set the editor contenteditable=false
- make the floating contenteditable=true area outside of react, and keep moving on desirable position.

**Alternatives**
Prevent re-rendering compositioning leaf.

But I am skeptical of this way.
- It does not solve all problems.
(e.g. When the ancestors of the writing leaf were remotely deleted in a collaborative situation.)
- It makes the framework complex and obscure.
(Different browsers fire different events in different order. And every leaf and its ancestor elements should take these into account.)

**Context**
I'm not sure about location-related side effects. That's why I need feedback from people who are familiar with Slate or who have implemented floating contenteditable.

**Comment by williamstein** [comment]
>  That's why I need feedback from people who are familiar with Slate or who have implemented floating contenteditable.

I really appreciate you creating this issue.    Today I was trying to understand the situation with Android support, and ended up trying an experiment in which I used React.memo to disable re-rendering of the Children component while state.isComposing is true. This is a few lines of code modifying two files in slate-react/components; basically, pass state.isComposing as a prop to Children, and in childrent.tsx use `(prev,next) => !!next.isComposing` for the isEqual argument.   

With this change so that re-rendering doesn't happen while isComposing is true seems to have the following impacts:

1. As far as I can tell, entering text in complicated languages that use composition heavily suddenly works. 

2. A pleasant surprise: as far as I can tell, Android input works *without* using https://github.com/ianstormtaylor/slate/issues/3786#issuecomment-798773023 at all.  I've only tested for a little while, so who knows what surprises are still there.  But still, it's a dramatic improvement in Android support over the current release version of slate.
 
---

Thus it might not be the case that this assertion is correct "That is because the entire editor area is content-editable and it re-renders every time.".  Slate re-renders too much, but that may not be due to the entire editor being content editable, but instead due to the implementation (which is actually easy to change).  Thoughts?

**Comment by cancue** [comment]
@williamstein Thank you for your comment.

I think there are three types.
- **Type A - current slate way**
one contenteditable DOM to input and output
re-renders every time
- **Type B - draftjs way**
one contenteditable DOM to input and output
prevent re-rendering of composing component in some cases
- **Type C - google docs way**
one contenteditable DOM to input only (floating contenteditable area)
one non-conteditable DOM to output only

So, you are right. 'entire editor area is content-editable' is not the cause of It, and only refers to the common characteristics of Type A and B.

---
In your case (almost Type B), there are some issues.
- **The non-rendering state can persist.**
In Korean, a character is literally a composition of korean alphabets. Writing itself is a composing
(user inputs: ㄱ, ㅏ, ㄴ, ㅏ / outputs: ㄱ, 가, 간, 가나 / keeps isComposing = true)
As a result, isComposing remains true unless the user writes space, numbers, or any other characters but Korean.
And these composing-terminating inputting should not be prevented in custom keydown handler for IME to handle it.
- **You should handle all changes while isComposing is true. (e.g. remote changes by collaborators)**
At this point, there are many things to consider, and this approach cannot solve all problems.

---
Anyway, after I wrote this issue, I discovered that there are a lot of drawbacks in Type C as well.
Users will not be able to use OS level features for textfields. (e.g. automatic conversion of handwriting on iPad, cursor dragging on iOS, etc.)
So I think Type B is better now, but it is not a clear solution.

I hope to add compositioning range setter to the composition specification on Web API.

**Comment by cancue** [comment]
After more investigation,
I founded some solutions for compositions.

**Problem 1.**
> Select All + Start Composition broke editor

When a user start composition with selections of nodes, browser will delete those DOMs.
To prevent errors, pre-deleting lines should be added here.
https://github.com/ianstormtaylor/slate/blob/c52dcd330b69810ec54e5ddf736df1453c112aa2/packages/slate-react/src/components/editable.tsx#L260-L265
But this is not enough, because browser will merge nested spans and the inconsistency between real DOMs and react components cause error.
So I should change the Text component of slate-react to resolve it. However, this restricts the flexibility of the custom leaf nodes.

**Problem 2.**
> Preventing re-rendering with collaboration issue

When a user is composing on the text node, remote changes about that node should not updated. (preventing re-rendering)
This cause inconsistency between DOM-based offset and the remote-state-based offset.
Overwriting remote changes after composition being finished could be a solution, but I want to handle this based on CRDT.
So I'm trying to change slate Location concept to my own CRDT point rather than relative offset.

In my case, these would work, but it doesn't seem to fit the direction of this framework.
So I close this issue.
