### ISSUE TITLE
General issues with async programmatic manipulation of editor

### ISSUE THREAD

**Issue by aehlke** [ianstormtaylor/slate#423]
I'd like to follow up with more specific details, but for now I'm opening this ticket to track this class of issue. I'm working on a plugin that needs to fetch results from an API which it then uses to manipulate the editor's state. I've run into several issues with state transformations triggering at coincidental timings that cause the editor to raise uncaught errors.

Just to better understand some context: from the API documentation at least, it seems this use case has not been explored much yet? A lot of the transformations seem to be catered toward users invoking them via commands (by operating on cursor selections, for the most part). Manipulating the selection in order to trigger transformations is also clumsy (e.g. restoring the original user cursor is not easy) so I'm thinking I'm treating in uncharted territory with this use case.

I think I have workarounds for the issues I've run into so far, but would like to explore this further.

**Comment by ianstormtaylor** [comment]
Hey @aehlke not sure if you've solved this or not, since it's a bit vague. But in general, when working with asynchronous transforms be sure to use `editor.getState` right before trying to modify it, otherwise you might end up with a stale state being used, in which case any changes that were made between the time it was accessed and the time the async operation was completed might be lost.

I'm doing to close this issue since it's not easily actionable. If you run into specific things, feel free to open another one (best to include code samples).
