### ISSUE TITLE
List items cannot be deleted if they are the first element

### ISSUE THREAD

**Issue by churichard** [ianstormtaylor/slate#4241]
**Description**
A list item (in an unordered or ordered list) cannot be deleted if it is the first element in the editor.

**Recording**
![266b44b0-30fb-47c5-a91b-0c3b7e4957be](https://user-images.githubusercontent.com/4218237/117188742-3f136c00-ad92-11eb-9c07-40b15d96a82b.gif)

I'm pressing backspace in this recording, but the bullet point persists.

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/richtext
2. Create a list as the first element
3. Try to delete it and observe that it cannot be deleted

**Expectation**
List items should be able to be deleted, regardless of where they are in the editor.

**Environment**
- Slate Version: 0.62
- Operating System: Windows 10
- Browser: Chrome

**Context**
Related to https://github.com/ianstormtaylor/slate/issues/3469
Could have same root cause as https://github.com/ianstormtaylor/slate/issues/3408

**Comment by cameracker** [comment]
Hi @churichard , you should be able to get this fixed in your own editor by writing on onKeyDown handler that converts the selected block to a paragraph (or whatever your default block is) when the user hits backspace at the start of the list item text. The reason the example doesn't do this is because it's meant to be a short example to get users started and it's a little bit outside the scope of it to have the full suite of idiomatic list behaviors.

Thanks!

**Comment by ferreiro** [comment]
@cameracker I'm following your advice. How can I detect in a bullet/list whether the current node is empty? In the `onDOMBeforeInput` I don't know how to get the active block to check if it's empty.
