### ISSUE TITLE
The editor breaks down if you type in the first paragraph and then clear the editor

### ISSUE THREAD

**Issue by fredure** [ianstormtaylor/slate#4258]
**Description**
If type text on the first line and then clear the editor (pass an empty paragraph), the editor will break.

I suppose that the logic of restoring the cursor position breaks. The logic does not take into account the position offset.

**Recording**
![May-13-2021 13-49-30](https://user-images.githubusercontent.com/8024592/118115863-2c341380-b3f2-11eb-84d9-21ea15838a77.gif)

**Sandbox**
https://codesandbox.io/s/slate-reproductions-forked-d8obd?file=/index.js

**Steps**
To reproduce the behavior:
1. Type text on the first line
2. Click on the "Сlear editor" button
3. See error

**Expectation**
No error

**Environment**
Slate Version: 0.62.0.
Operating System: all.
Browser: Google Chrome 88.0.4324.192.

**Comment by thesunny** [comment]
@fredure you need to use Transforms to clear the editor content. Because you're not doing that and just replacing the value, the selection now exists in a place that doesn't exist in the content. When you use Transforms, it will also adjust your selection for you.

Closing for now unless I'm misunderstanding something about the issue.
