### ISSUE TITLE
Element children text not displayed if element is void

### ISSUE THREAD

**Issue by tappyy** [ianstormtaylor/slate#4284]
**Description**
Element children text is not displayed when element is void.

**Sandbox**
Comment out line 30 in the sandbox below and see that children text appears as expected.
https://codesandbox.io/s/slate-reproductions-forked-mnvsn

**Steps**
To reproduce the behavior:
1. Create a plugin that sets the `isVoid` property of an element as `true`.
2. Create a custom Element renderer to render children of void element.
3. Add your void element to the editor with children that contains text.
4. See that children text is not displayed

**Expectation**
My expectation would be that the children of a void element is displayed, though not editable.

**Environment**
- Slate Version: 0.63 (sandbox uses 0.58 though it reproducible in 0.63 also)
- Operating System: Windows
- Browser: Confirmed in Chrome 90 and Firefox 88

**Context**
I have looked at the source code but can't find where the children of a given node are rendered. I am happy to contribute if someone could point me in the direction of this, or if anyone has any ideas of solutions.

Thanks for the awesome editor!

**Comment by cameracker** [comment]
Hi @tappyy , the void elements are meant to be used in a context where slate is asked to render the block but otherwise not intervene in any way with the rendering or user interaction of its children. You can have "child" elements in a void node in the normal react way, but slate will not attempt to do anything with the `nodes` collection of a void block. See the images and embedded video example for more information.
