### ISSUE TITLE
minHeight is no longer respected in slate-react 0.62+

### ISSUE THREAD

**Issue by hanford** [ianstormtaylor/slate#4314]
**Description**
This [commit](https://github.com/ianstormtaylor/slate/commit/00393bb18548976d4e79c8bc46d54b2125bb6701#diff-18ef6af284404b1670857e562c183f2da6774d81bb65ed39d82fe124f769787b) introduces a regression where slate editors min-height is now constantly being set.

**Recording**
![image](https://user-images.githubusercontent.com/2148168/120557004-20fd5380-c3b2-11eb-8ca9-7ac16043dba9.png)

**Sandbox**
https://stackblitz.com/edit/react-f4v5on

**Expectation**
I should be able to control the minHeight of my editor based on this value

**Environment**
- Slate Version: 0.62+

**Context**

I'm no longer able to specify a `minHeight` on my `<Editable />` and have it be respected, this is problematic because I have been relying on minHeight to specify the size my editors initialize with

**Comment by gfohl** [comment]
Looks like line 43 in `packages/slate-react/src/components/leaf.tsx` might be overriding it, if there is a placeholder:
`editorEl.style.minHeight = `${placeholderEl.clientHeight}px`

**Comment by aaron-swarm** [comment]
As a workaround:

```
useEffect(() => {
  const editorEl = document.querySelector<HTMLDivElement>(
    '[data-slate-editor="true"]',
  );
  editorEl.style.minHeight = `${rows * 24}px`;
}, []);
```

**Comment by tom2strobl** [comment]
https://github.com/ianstormtaylor/slate/blob/25afbd43001cdee852af6386d2b701d943b788da/packages/slate-react/src/components/leaf.tsx#L32 is pretty dirty since it only works if there is only one slate instance on a page. the workaround of @aaron-swarm doesn't help in this case either since both fire `querySelector` from `document` which always targets the first slate instance on the page.

So right now it is completely impossible to have two slate instances, where the first one has a minHeight of 60px and the second one of 100px. No `renderPlaceholder` and no useEffect-hacky-business can do anything since the leaf.tsx hardcoded line will always pick up the first instance and then forcefully overwrite minHeight on that one. The first editor will always get the 100px, because https://github.com/ianstormtaylor/slate/blob/25afbd43001cdee852af6386d2b701d943b788da/packages/slate-react/src/components/leaf.tsx#L40 writes it to that instance and we can't bypass that.

**Comment by hanford** [comment]
I've been able to restore the older functionality by directly commenting out the useEffect in slate-react with this patch: https://gist.github.com/hanford/4f5c2257ef51500cf4182efbe86194fe

I'd recommend using this with https://www.npmjs.com/package/patch-package

**Comment by ironAnd** [comment]
As a workaround:
Editable has `min-height: "auto"` by default.
You can add container around Editable to change `min-height` like this:
```
<div style={{ minHeight: '150px' }}>
    <Editable ...>
</div>
```

**Comment by DevTrader** [comment]
> 

However, it doesn't affect the actual input height, it compromises the UX of the clickable area to edit

**Comment by alexpeev9** [comment]
```
                import { Editable } from "slate-react";

                <Editable
                    renderElement={renderElement}
                    renderLeaf={renderLeaf}
                    style={{
                        outline: "none",
                        lineHeight: "24px",
                        width: "100%",
                        height: "auto",
                        minHeight: "48px",
                        maxHeight: "100%",
                    }}
                />
```

I couldn’t find a proper workaround and the height kept defaulting to 48px and automatically adjusted as soon as typing began. The only solution I found was to set all input heights to a larger fixed value so it doesn’t change when the user starts typing.
