### ISSUE TITLE
Adding and removing paragraph in rich text example produces errors

### ISSUE THREAD

**Issue by tyler-johnson** [ianstormtaylor/slate#437]
Not sure if this affects all blocks or just paragraphs. This may be two different issues.

When adding a paragraph block in the slate rich text example the following error is produced:

    Uncaught TypeError: Cannot read property 'map' of null(…)

When deleting a block this error is produced:

    Warning: Encountered different references for identical node values in "shouldComponentUpdate". Check that you are preserving references for the following node:

**Comment by ianstormtaylor** [comment]
Just realized, the uncaught error happens when typing the first character in an empty paragraph. Investigating this now.

The second error is actually a Slate warning for performance. These were added in `0.15` to make it more clear when bad practices are seeping through, and a few are still remaining in the codebase.

Thanks for reporting!
