### ISSUE TITLE
can't select links with double-click in firefox

### ISSUE THREAD

**Issue by arekkas** [ianstormtaylor/slate#440]
![cant-select-hyperlinks](https://cloud.githubusercontent.com/assets/3372410/20457838/8bf3cfbc-ae94-11e6-88e7-12023fb76c7d.gif)

Maybe a regression from the recent isRender patch?

**Comment by thesunny** [comment]
For anybody thinking of tackling this, I got most of it done but don't know if I'm the right one to finish it because I think there needs to be some generic word selection code in core.

Using the code below, double clicking the link will properly select the link in Firefox.

I thought I was done but when checking behavior on Chrome, it seems like the correct behavior is to select the nearest word. So if there are two words in the link, a double-click should only select one of the two words in the link.

```js
// edits to "/examples/links/index.js"

const schema = {
  nodes: {
    paragraph: props => <p>{props.children}</p>,
    link: (props) => {
      const { data } = props.node
      const href = data.get('href')

      // preventDefault to allow onDoubleClick to fire
      function onClick(e) {
        e.preventDefault()
      }

      // fixes a Firefox bug that prevents double clicking to select a link
      function onDoubleClick(e) {
        const {editor} = props
        const state = editor.getState()
        const newState = state
          .transform()
          .moveToRangeOf(props.node)
          .apply()
        editor.onChange(newState)
      }

      return <a {...props.attributes} onClick={onClick} onDoubleClick={onDoubleClick} href={href}>{props.children}</a>
    }
  }
}
```

Note that I could not get the `onDoubleClick` event to fire in Chrome at all, even after using the `event.preventDefault()` trick `onClick`. This was fine because Chrome worked the right way; however, if the intent is to normalize all browsers by making double click always select the entire link, there may be some more work to do to see if we can capture the Chrome double click.

**Comment by thesunny** [comment]
My bad.

Looks like the code to do this is in here:

https://github.com/ianstormtaylor/slate/blob/40367533358854ccb277d5e06900226e0f188107/src/utils/string.js

Will give it a shot again later; however, it's looking like this might be a lot of code for an example.

Let me know if I should just not waste time on an edge case for an example.

**Comment by ianstormtaylor** [comment]
@thesunny thanks for investigating!

I think the main issue is that we have something going wrong in the core selection-handling code like you mentioned. Ideally (and I assume very possible) we wouldn't need to touch anything in the examples or elsewhere. My guess is that there's an error somewhere in our [`OffsetKey.findKey`](https://github.com/ianstormtaylor/slate/blob/master/src/utils/offset-key.js#L56) private util function.

**Comment by ianstormtaylor** [comment]
Leaving more information here for myself. 

The source of the issue is that the selection logic doesn't correctly handle selections that are in reference to non-text elements. In Chrome/Safari, the double-click is expressed as a `Range` relative to the text element. In Firefox, it is expressed as relative to the paragraph.

The trick is that offsets on text nodes are character-granularity, but on non-text nodes they are child-node-granularity. From MDN:

> If the startContainer is a Node of type Text, Comment, or CDATASection, then the offset is the number of characters from the start of the startContainer to the boundary point of the Range. For other Node types, the startOffset is the number of child nodes between the start of the startContainer and the boundary point of the Range.

So if the OffsetKey logic is updated to handle that we should be good. I'll take a look soon!
