### ISSUE TITLE
Slate content not changed - Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":86}

### ISSUE THREAD

**Issue by elenaaralla** [ianstormtaylor/slate#4412]
**Description**
When change editor text via jquery, the change is not reflected on the editor content and the following error occurs:

_Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":86} _

**Sandbox**
https://codesandbox.io/s/slate-reproductions-forked-2yx13?file=/index.js

**Steps**
Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":86}
1. select a text (07/27/21, for example) on the editor 
2. click on button 'Set date'
**Result**: onChange() fired; selection in the editor highlighted; the editor content changed (as you can see on console) :)

1. click on button Test
**Result**: onChange() not fired and the editor content not changed (as you can see on console) :(

**Expectation**
onChange() fired and editor content updated when change selection text via jquery

see on https://stackoverflow.com/questions/68664137/slate-content-not-changed

**Comment by cameracker** [comment]
Hi @elenaaralla, you're experiencing this crashing behavior because the supported workflow is for you to make modifications to the editor state programmatically via the `controller`. There's an example of how to do that [here](https://docs.slatejs.org/walkthroughs/02-adding-event-handlers) and then [here's](https://docs.slatejs.org/api/transforms) a larger set of mutations you can make against the document.

I'm going to close this issue because the use of jquery in this way is not supported, and there are directly supported methods that will fulfill your usecase.

**Comment by elenaaralla** [comment]
Hi,

thank you; 
so, if I would replace a selected text with a datepicker that can change the value of selected text how can I do?
Thank you,
Elena.
