### ISSUE TITLE
Update immer to remove the high severity vulnerability 

### ISSUE THREAD

**Issue by evansrobert** [ianstormtaylor/slate#4434]
Hi, @thesunny @ianstormtaylor, I stumbled upon a vulnerability introduced by package **immer@5.3.6**:
### Issue Description
I noticed that a vulnerability [**CVE-2020-28477**](https://snyk.io/vuln/SNYK-JS-IMMER-1019369) detected in package **immer<8.0.1** is directly referenced by **_slate@0.59.0_**.
   However,  **slate@0.59.0** is so popular that a large number of latest versions of active and popular downstream projects depend on it ([20,413 downloads per week](https://www.npmjs.com/package/slate/v/0.59.0?activeTab=versions) and about **56 downstream projects**, e.g., @react-page/react-page 0.30.0, payload 0.8.1, @onzag/itemize 0.0.157, @bodiless/richtext 0.2.8, slate-transcript-editor-fork 0.1.55, etc.). 
In this case, the vulnerability [**CVE-2020-28477**](https://snyk.io/vuln/SNYK-JS-IMMER-1019369) can be propagated into these downstream projects and expose security threats to them.
   As you can see, **_slate@0.59.0_** is introduced into the above projects via the following package dependency paths:
(1)`@slate-collaborative/client@0.7.2 ➔ @slate-collaborative/bridge@0.7.2 ➔ slate@0.59.0 ➔ immer@5.3.6`
    **......**

I know that it's kind of you to have removed the vulnerability since **_slate@0.63.0_**. But, in fact, the above large amount of downstream projects cannot easily upgrade **slate** from version **_0.59.0_** to _**(>=0.63.0)**_:
    The projects such as **@slate-collaborative/bridge**, which introduced **slate@0.59.0**, are not maintained anymore. These unmaintained packages can neither upgrade **slate** nor be easily migrated by the large amount of affected downstream projects.  

   **Given the large number of downstream users, is it possible to release a new patched version with the updated dependency to remove the vulnerability from package slate@0.59.0?**

### Suggested Solution

Since these inactive projects set a version constaint **0.59.\*** for **slate** on the above vulnerable dependency paths, if **slate** removes the vulnerability from **0.59.0** and releases a new patched version **_slate@0.59.1_**, such a vulnerability patch can be automatically propagated into the downstream projects.

In **_slate@0.59.1_**, maybe you can try to perform the following upgrade:
`immer ^5.0.0 ➔ ^8.0.1`;  
**Note:**
**_immer@8.0.1(>=8.0.1)_** has fixed the vulnerability [**CVE-2020-28477**](https://snyk.io/vuln/SNYK-JS-IMMER-1019369).
Of course, you are welcome to share other ways to resolve the issue.

**Comment by TheSpyder** [comment]
We understand your concern, but we can't go around using tricks to force unmaintained packages to upgrade. Slate doesn't even guarantee stability, we certainly can't guarantee security. As @ianstormtaylor has written [in the readme](https://github.com/ianstormtaylor/slate/blob/083a3da2203840e337dd1e5b6c6896096a7f7c6c/Readme.md#L42):

> 🤖 **Slate is currently in beta.** Its core API is useable right now, but you might need to pull request improvements for advanced use cases, or fixes for some bugs. Some of its APIs are not "finalized" and will have breaking changes over time as we discover better solutions. There isn't currently a `1.0` release schedule, we're still getting the architecture right.

Popularity doesn't change this status. So long as Slate is in beta, we will not be patching older versions.

Unfortunately there's no other solution we can offer, yarn resolutions can't be used to force the upgrade because [a code change was required to upgrade beyond immer v5](https://github.com/ianstormtaylor/slate/pull/3850/files#diff-36e80a658eb32e4912dc75f66345c365d4c599d9de5b32b633f441b03f571575).

My recommendation is submit a patch to inactive projects and hope the maintainer is still at least watching for PRs, or someone else offers to take over maintenance.
