### ISSUE TITLE
Crash during mouse selection on Chrome over multiple nodes

### ISSUE THREAD

**Issue by neural9** [ianstormtaylor/slate#4490]
**Description**
When selecting across Nodes in Chrome, the editor crashes out.

**Recording**
![slate_crash](https://user-images.githubusercontent.com/15861273/132087847-02180b6f-184e-45c7-80cc-2242a7efbdb2.gif)

**Sandbox**
https://www.slatejs.org/examples/editable-voids 

**Steps**
To reproduce the behavior:

- Going to the example: https://www.slatejs.org/examples/editable-voids in Google Chrome ( 92.0.4515.159 ). 
- Enter text in name and hand radio ('test' and left)
- Select from top to bottom using mouse click and drag
- Big red face is shown

**Expectation**
No crash.

**Environment**
- Slate Version: slate@0.65.3
- Operating System: Mac Big Sur
- Browser: Chrome 92.0.4515 

**Context**
I think this is something to do with selecting void nodes. I came across it when selecting large pieces of text and then applying formatting to it. I don't think the formatting has anything to do with it. It happens randomly in my code, but it is very consistent in the official slate example above.

**Comment by nemanja-tosic** [comment]
The error comes from the tripple click fix, see #4490

**Comment by TheSpyder** [comment]
#4492

**Comment by bytrangle** [comment]
Sorry everyone. The crash is due to the triple click fix I introduced. Previously, triple clicking a block in Chrome will incorrectly select the subsequent block. The gist of my fix is as followed:
- Check if triple click is taking place.
- If it is, find the correct anchor and focus node of the selection and returns that to Slate. One of many actions inside this `if` block is to look for a block with attribute `[data-slate-string]`. This block exists in the Rich Text example, but it isn't in Void Nodes.

On paper, triple clicking should have nothing to do with this problem, but my conditional logic for checking triple click is too broad, so it also applies to Void Nodes:
```
if (IS_CHROME && anchorNode?.nodeValue !== focusNode?.nodeValue && domRange.focusOffset === 0) {
  // ...
}
```
