### ISSUE TITLE
node validation should be top-down for performance

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#452]
This is a discussion on performance for normalization.

We are currently memoizing the validation of each node against a schema, through `Node._validate`. While this prevents calling validation rules twice on the same node, it does not keep us from iterating over every node.

The [logic to normalize a Node and its children](https://github.com/ianstormtaylor/slate/blob/master/src/transforms/normalize.js#L95-L116) should be memoized at the Node level. If I normalize a Node again, with the same Schema as before, the normalization should result in the same new Node and children (or no change). So if we can memoize that, and **skip the iteration on children altogether**, this could be a great performance improvement, for core Schema and plugins Schema.

The current limitation to implement that, is that we pass the whole transform as argument to normalization, which breaks the memoization. Conceptually, that should be the signature of the normalization function:

```
Ideally: Node, Schema -> Node
Currently: Node, Schema, Transform -> Transform
```

The hard part is that a Transform includes the whole Document and the global Selection. But I think we should be able to refactor it to use restricted transforms:

```
Refactored 1: Node, Schema -> NodeTransform
```

A NodeTransforms would be a list of operations restricted to the scope of a given Node. Then the end Transform would be a composition of NodeTransforms.

There's just one catch: the Selection. Maybe the selection could be part of the signature. We would pass it if and only if it is within the Node:

```
Refactored 2: Node, Schema, Maybe(Selection) -> NodeTransform
```

A NodeTransform could then normalize the Selection if required.

All this is theoretical, but I wanted to start this discussion now...

**Comment by ianstormtaylor** [comment]
Hey @Soreine, I definitely like this thinking!

I have a potential alternate solution that might be simpler. Right now we're doing both the normalization and the validation by iterating over the whole tree, depth-first (or "bottom-up"). We need to do the depth-first approach for normalization, since we want to solve the inline discrepancies before moving onto the block nodes, which I _think_ makes sense.

But I wonder if we could instead make validation top-down at first, and only move to bottom-up once we determine we need to actually normalize something. If so, the validation itself would be memoized at the highest levels, and prevent traversal.

We'd essentially change the validation logic to incorporate recursively validating the children nodes. So if a whole branch of the tree hasn't changed it will abort right away without traversing. But if it has changed, it will perform the bottom-up validation/normalization logic to fix it.

Does that make sense? 

(I think there are probably a few different ways to do it, but one might be to have `validateNodes` and `validate` as two separate methods, where `validateNodes` just validates the node itself, then recurses down the tree calling `validate` on all descendants. Which means that if there are validation errors, the actual `validate` method has already been called on each node, so those results are memoized which could speed things up too potentially.)

I might be missing a case, just thinking off the top of my head.

**Comment by Soreine** [comment]
I approve your simpler solution 🌱

**Comment by Soreine** [comment]
I think this is done now.
