### ISSUE TITLE
Selection of emojis (inline void) no longer works

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#457]
When testing the emojis example (http://slatejs.org/#/emojis?_k=9hqx0r), it's now impossible to select an emoji (by clicking on it or moving cursor on it).

**Comment by SamyPesse** [comment]
After investigation, the bug appeared between `0.15.3` and `0.15.4`. Probably caused by https://github.com/ianstormtaylor/slate/commit/d28114061962a911068afb467b73cb48c54aba71

Basically when clicking on an inline void (or moving cursor using keyboard), the selection moves into it and then the `onSelect` moves it back in the previous text node.

This is a critical issue for us since we are using inline void for images and other nodes.

**Comment by ianstormtaylor** [comment]
Fixed in `0.15.10`!

Thanks for the extra info, that was super helpful. Turns out the reason is because Chrome/Safari don't allow selections to be at offset `0` of an inline element that has other inline elements before it. They will convert those automatically into a selection at the last index of the previous element...

So now we can keep the rendering flag removal, but with updated selection logic to automatically use the ending offset of inline voids instead of the starting one!
