### ISSUE TITLE
Hotkeys do not work with Cyrillic keyboard layout

### ISSUE THREAD

**Issue by fredure** [ianstormtaylor/slate#4591]
**Description**
If you switch to the Cyrillic layout, enter text and try to cancel it through a hotkey Ctrl+Z, then nothing will work.

**Recording**
Do not record hotkey press.

**Sandbox**
https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1. Go to demo.
2. Change the layout to Cyrillic.
3. Type text.
4. Press hotkey Ctrl+Z.

**Expectation**
Pressing the hotkey canceled the text input.

**Environment**
- Slate Version: [e.g. 0.59]
- Operating System: all.
- Browser: all.

**Comment by devmor-j** [comment]
I guess this is related to the `create` function in [hotkeys.ts](https://github.com/ianstormtaylor/slate/blob/20acca4bc8f31bd1aa6fbca2c49aaae5f31cadfe/packages/slate-react/src/utils/hotkeys.ts).

I have the same issue in any language except English.

The reason might be that we check keys by their `key` not their `code`. The `key` on *KeyboardEvent* is based on the language of the system but `code` is always refering to the keyboard keys.

So if we use the `isCodeHotkey` function instead of `isKeyHotkey` from `is-hotkey` then the problem is solved.

here is the source for the [is-hotkey functions](https://github.com/ianstormtaylor/is-hotkey/blob/ce651bddc8eff239b2219f19466efb7961864664/src/index.js).

If you'd like I can send a PR.
