### ISSUE TITLE
Nested contentEditable does not work as expected

### ISSUE THREAD

**Issue by deanblacc** [ianstormtaylor/slate#4666]
**Description**
Given the following code for an element:

```
switch (element.type) {
  case 'paragraph':
    return (
      <span contentEditable={false}>
        <p contentEditable={true} {...attributes}>
          {children}
        </p>
      </span>
    )
}
```
the paragraph content should be editable and it is. However all new edits are pushed to the font of the text as seen in the video below.

**Recording**
https://user-images.githubusercontent.com/4340994/142467845-7ab43e49-ce35-46ff-9acd-d54981c66a21.mov

**Sandbox**
[Sandbox](https://codesandbox.io/s/slate-reproductions-forked-lvgi4)
To reproduce, simply try to edit the text that says its editable

**Expectation**
The cursor should not move after an edit. This expected behaviour is performed outside of Slate in plain HTML.
https://user-images.githubusercontent.com/4340994/142467727-9a4371b2-8770-41df-a39f-e92fd563c684.mov

**Environment**
- Slate Version: 0.66.5
- Operating System: macOS
- Browser: Chrome, Safari, Firefox

**Comment by deanblacc** [comment]
Tested this against the latest release (used in the sandbox) but the cursor issue is definitely still a thing

**Comment by ryanmitts** [comment]
What is the intended use case?

To me it makes sense this would not work. The [contenteditable](https://www.w3.org/TR/2008/WD-html5-20080610/editing.html) spec mentions that an editable element with a non-editable parent would start a new editing context. Given that Slate child nodes are rendering within the different context, its confusing to me what the expected behavior is here.

If you want to have a non-editable component to an element, you could do something like:

```
switch (element.type) {
  case 'paragraph':
    return (
      <p {...attributes}>
        <span contentEditable={false}>Non editable</span>
        <span>
          {children}
        </span>
      </p>
    )
}
```

**Comment by deanblacc** [comment]
hey @ryanmitts youre perfectly correct. I can't remember why I initially felt like I needed the `contentEditable` prop. Closing !
