### ISSUE TITLE
Non actual state in onSelect event handling

### ISSUE THREAD

**Issue by eden-lane** [ianstormtaylor/slate#467]
Not sure it's a bug, it might be me missing something.
I have the following code:
```
onSelect(event, data, state, editor) {
    console.info(state.focusInline ? 'inline' : 'non-inline')
}
```
So when I focus inline it should write 'inline' to console and it should write 'non-inline' in other cases. For some reason it writes *inline* when change focus from inline element to non-inline and vice versa. So it shows _previous_ state. 

Can you confirm this?

Here is the fiddle: https://jsfiddle.net/y0u1s0mg/1/
Just make some text bold with *ctrl + b*, then open console and try to focus words

**Comment by ianstormtaylor** [comment]
Hey @eden-lane, I think the issue is that you're after the `onSelectionChange` behavior instead. 

`onSelect` is the lower-level handler for managing `select` events being fired from the `contenteditable` element. It fires and traverses the plugin stack, and the editor-level props are always considered first. So they're called before the core plugin has actually set the new selection.

**Comment by eden-lane** [comment]
@ianstormtaylor works like a charm, thanks!
I didn't find any information about that in the docs. Am I missing something again or it's not there yet?
Anyway, thanks for your work and for quick reply! Have a nice day

**Comment by ianstormtaylor** [comment]
@eden-lane I think it's there, but not super obvious maybe. I've just added an extra not so that hopefully it's less confusing in the future!

**Comment by eden-lane** [comment]
Awesome! Thanks 👍
