### ISSUE TITLE
Drag & drop doesn't create a new history batch, undo deletes text

### ISSUE THREAD

**Issue by djagya** [ianstormtaylor/slate#4694]
**Description**

When using Slate with `slate-history`, you get a list of `undo` batches. The problem: When you drag & drop a text/element, that action doesn't create a new history batch, instead writing it in the current one. If you then "undo" the drag & drop, it will undo everything in that batch -- deleting a text/element, or un-applying marks, etc.

Drag & drop should create a new batch in the `undo` list.

**Recording**

On recording I write some text (one batch in `undo`), then drag & drop it to the first paragraph, then "undo" - the text gets deleted. I then "redo" - and the text appears where I dropped it, no at the original place.

![Nov-25-2021 17-32-55](https://user-images.githubusercontent.com/2600431/143531953-44f053fb-374d-4d38-b16b-f2a545f0456b.gif)

**Sandbox**
https://codesandbox.io/s/slate-history-dnd-bug-repro-45qd3

**Steps**
To reproduce the behavior:
1. Go to https://codesandbox.io/s/slate-history-dnd-bug-repro-45qd3
2. Create a new paragraph in the editor
3. Type som text
4. Select it, long-press on selection, drag & drop it to the first paragraph
5. Now undo (Cmd + z on Mac)
6. See the text you typed gets deleted

**Expectation**

Drag & drop action should create a new batch in the history's `undo` list. Undoing drag & drop should return the element back to the original place. Only the second "undo" should delete a text/element.

**Environment**
- Slate Version: 71.0, Slate history: 0.66.0
- Operating System: MacOS
- Browser: Chrome 96
- TypeScript Version: [e.g. 3.9.7 - required only if it's a TypeScript issue]

**Context**

I would be glad to contribute and create a PR, but a pointer to where potentially the problem lies would be appreciated! IIUC there's nothing wrong in the history plugin, it's something we need to fix around how Slate transforms nodes when drag & dropping.

**Comment by imdbsd** [comment]
im also facing this, when try to debug, found out the history was splitted between delete and inserted data that has been dropped. i think it because this line https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/editable.tsx#L965.

Not sure if it should use `moveNodes` transformation instead delete then insert it, but i cannot figure out how to move the dragged data with moveNodes. And not sure why it not merged in one history on history-plugin here https://github.com/ianstormtaylor/slate/blob/main/packages/slate-history/src/with-history.ts#L82

**Comment by bryanph** [comment]
I think this happens because `set_selection` operations are currently always merged:
https://github.com/ianstormtaylor/slate/blob/fece5c157099b5ddef9f6dc8d070f2fdb3724b90/packages/slate-history/src/with-history.ts#L117-L119

And in the `onDrop` method in `Editable`, the drop target is selected before actually moving the content:
https://github.com/ianstormtaylor/slate/blob/fece5c157099b5ddef9f6dc8d070f2fdb3724b90/packages/slate-react/src/components/editable.tsx#L957

So that always gets merged with the previous undo stack. Solution might be to wrap that select above in a `withoutMerging` call
