### ISSUE TITLE
editor.insertText never gets called inside plugins on android

### ISSUE THREAD

**Issue by fridaystreet** [ianstormtaylor/slate#4709]
**Description**
if you create a withMyPlugin and have it override the editor.insertText function, the function is never called when inserting text on an android device

**Steps**
create a plugin and override the editor.insertText function, console.log the output, it never gets called on android

**Expectation**
the editor.insertText function is called like other functions when user enters text on andorid

**Environment**
- Slate Version: latest
- Operating System: android
- Browser: Chrome

**Comment by fridaystreet** [comment]
sorry not sure why the cross platform label was added, I did choose bug for specific platform

**Comment by alessiogaldy** [comment]
I took a look at this issue, and if I change this line https://github.com/ianstormtaylor/slate/blob/735d2d047aa5a7ded7d1180fcbda6008f58943a8/packages/slate-react/src/components/android/android-editable.tsx#L563 to call `Editor.insertText`, the plugins work again.
I am unsure if this is the correct fix because I don't know when `Editor.insertText` should be used instead of `Transforms.insertText`. The regular `Editable` component uses both.
I hope this helps narrow down the issue 🤞

**Comment by dylans** [comment]
> sorry not sure why the cross platform label was added, I did choose bug for specific platform

fwiw, I think the label gets applied when something breaks cross-platform compatibility.

**Comment by dylans** [comment]
> I took a look at this issue, and if I change this line
> 
> https://github.com/ianstormtaylor/slate/blob/735d2d047aa5a7ded7d1180fcbda6008f58943a8/packages/slate-react/src/components/android/android-editable.tsx#L563
> to call `Editor.insertText`, the plugins work again.
> I am unsure if this is the correct fix because I don't know when `Editor.insertText` should be used instead of `Transforms.insertText`. The regular `Editable` component uses both.
> I hope this helps narrow down the issue 🤞

`Editor.insertText` simply calls this: https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/create-editor.ts#L169-L182 which checks for a selection and if the selection contains marks. If no selection it does nothing, if selection contains marks, it calls `Transforms.insertNodes`, or if no marks, it calls `Transforms.insertText`.

So yes, overriding `Editor.insertText` will get ignored since the underlying code calls `Transforms.insertText` in both the Android and non-Android Editable code.

My suggestion would be to raise a PR that replaces the Transforms calls with Editor so that all calls with the React editor can be extended/overridden consistently. I'm happy to review a PR or work on it when time permits.

**Comment by fridaystreet** [comment]
@alessiogaldy @dylans thanks so much for sorting this out
