### ISSUE TITLE
`onChange` called twice

### ISSUE THREAD

**Issue by joelburget** [ianstormtaylor/slate#477]
Here's a test case of a simple controlled slate where I believe `onChange` is called twice for each input (but only once per backspace). https://jsfiddle.net/dinojoel/2zokvrvt/18/

**Comment by joelburget** [comment]
Different behavior with the addition of an `onBeforeInput`-swallowing plugin: https://jsfiddle.net/dinojoel/2zokvrvt/20/

**Comment by ianstormtaylor** [comment]
Hey @joelburget! 

In your `onChange` handler you're creating a new `State` and passing that to `setState`. That's going to create weird things, one of which is the duplicate input, since the old state has a property on it called `isNative` that isn't carried over. Why the need to create a new state? I think you'd want to use the transforms API instead to change things.

If you want to change things before they the change has occurred, you can also use the `onBeforeChange` handler.

**Comment by joelburget** [comment]
Cool -- I didn't understand the importance of transforms. As I understand it (now), trying to build state myself is an antipattern. I'm satisfied, closing.
