### ISSUE TITLE
How to recognise custom markdown syntax & deserialize

### ISSUE THREAD

**Issue by TrySpace** [ianstormtaylor/slate#4777]
**Problem**
I'm breaking my head trying to figure out out how get __underline__ and ~~strikethrough~~ syntax to work.
I believe `underline` is not a native markdown thing, and you can see it here on github too, but slate will render it as **bold**.
Strikethrough does seem standard, looking at several cheatsheets etc.

So, looking at this example: https://www.slatejs.org/examples/richtext, that works, but I need it the other way around, so I need original markdown to load, and slate to recognise `__` as `underline`...

### What works
If I serialize the text, including the double underscores: `__something__`, that works, and I can store the pure markdown-string.

### What doesn't
But once I try to deserialise it, with for example `remark-parse` and `remark-slate`,  I don't get any Leaf with any property like `leaf.underline`.

## Request/question
Now I know these are external libs, but is there a functionality within slate where I can add custom formats, like the `__` or `~~`?? Without adding more external libs. I'd like to use the existing serialising function from the examples.
I'm not finding it in the docs, I'm not finding any references or examples to deserialisers that customize the properties returned. (**Only customisable with existing, recognised syntax...**)

### Example
I can only figure out how to deserialise from HTML (in the docs), but then _still_, it won't detect `__` as a leaf or block, so I don't get any property to respond to and output the correct thing like this:

```js
switch (chunk.type) {
   case 'underline':
      return `__${children}__`;
...etc

// or:

if (leaf.underline) {
   return `__${children}__`;
}

...etc

```
This works for `bold`, `italic` etc. But how to get a custom property on type?

It seems somewhere internally, slate is coercing unknown syntax to `**bold**` type... What am I missing?

**Solution**
Some documentation how to define custom markdown types

**Alternatives**
Quill?? Struggling to find a good react / markdown editor, with good, recently updated de-/serialisers

**Comment by dylans** [comment]
afaik, remark-slate doesn't support underline out of the box because it's non-standard, see https://github.com/hanford/remark-slate/issues/29

Strikethrough should work, though it may be a different mark than expected, see https://github.com/hanford/remark-slate/pull/23/files for the original PR that added it.

The lack of underline in markdown is one of its biggest shortcomings in my opinion, and the suggestion to embed html to support it is not a great choice. Markdown in general is very difficult to fully round trip with RTE which typically support more format options than markdown supports.

I've not had a chance to dig into the recent changes, but perhaps now that https://github.com/inokawa/remark-slate-transformer/pull/89 had landed, remark-slate-transformer might be a more viable option.
