### ISSUE TITLE
"Could not find a descendant node with key" on moveNodeByKey

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#489]
I thought this one was fixed, but apparently it still happens, for example when using `moveNodeByKey`. Or am I doing something wrong?

https://jsfiddle.net/2zokvrvt/24/ (wait 3 seconds, check console)

I'm stumbling across this error on different occasions, though this one was the only I could really reproduce.

**Comment by ianstormtaylor** [comment]
Hey @bkniffler thanks for the report!

For this case, a bit of backstory: We recently deprecated the ability to pass in node's themselves instead of the nodes's keys. So for example `moveNodeByKey` should now be:

```js
transform.moveNodeByKey(node.key, parent.key, index)
```

Instead of:

```js
transform.moveNodeByKey(node, parent, index)
```

Although we did it with a warning in the console, not with an error, so it was odd that this error was being thrown. 

After doing a bit of digging, it seems like the reason is because `Node#getCommonAncestor` wasn't properly normalizing keys from nodes ever in the first place, which was a bug.

I've just added a fix for this behavior on master, which will now make it work but still log the warning to the console about deprecation. Thanks for finding it! (If you don't want to wait for the release, you can change it to `node.key` and it should work immediately!)

(Also side note: `Could not find descendant node with key` happens whenever a descendant is accessed via a key that doesn't exist in the document, so you might see it crop up again related to different issues/bugs.)

**Comment by bkniffler** [comment]
Thanks @ianstormtaylor, it works fine now (https://jsfiddle.net/2zokvrvt/26/)! Also thanks for the explanation, I'll keep it in mind.
