### ISSUE TITLE
[IME] Chrome/macOS: entering accented letters from the Accent Menu using arrow keys inserts double character

### ISSUE THREAD

**Issue by jens-lilt** [ianstormtaylor/slate#5038]
**Description**
The issue is similar to the one here: https://github.com/ianstormtaylor/slate/issues/982

There is a bug in Chrome/macOS with entering an accented letter from the [Accent Menu](https://support.apple.com/kb/PH25643?locale=en_US) (by holding down a key and using the arrow keys to select the accent character).

What's the current behavior?
When using arrow keys to select the accent character and pressing enter, the non-accented character appears along with the accented one.

What's the expected behavior?
A single, accented letter is inserted.

**Comment by jens-lilt** [comment]
@BitPhinix here's the issue you requested

**Comment by siliconeidolon** [comment]
Also occurs when pressing a number key to select the accented character.

**Comment by BitPhinix** [comment]
Arghh, this is a really annoying one with really tricky timing 👀 

<img width="580" alt="Screenshot 2022-07-11 at 14 05 09" src="https://user-images.githubusercontent.com/13185548/178260249-02baa210-2fa7-4ee6-8e90-6b85b055c5d1.png">

When holding down 'a' to type a with an accent the first 'ArrowLeft' key down is triggered with `isComposing=false` and before any event indicating that it is composing. Immediately afterward the 'normal' composition start/update events are fired and all following events have `isComposing` properly set, and because the composition start is fired before the selection change selecting the character / after the beforeinput we keep the selection obtained by manually handling the arrow keys which doesn't match the dom state.

**Comment by BitPhinix** [comment]
Found a fix, sorry for only getting to this now, had a busy last week 🙏

**Comment by felipeleusin** [comment]
Hi, I tested this again in he playground and I'm note sure this completely fixed. Testing on Safari latest after composition starts the accent is being applied to a new letter rather than the previous one.

![slate_accent_issue](https://user-images.githubusercontent.com/167921/192561849-91b67eda-8f72-4fdd-a712-7ea1dff02d5b.gif)
