### ISSUE TITLE
[bug] Void node onClick behavior

### ISSUE THREAD

**Issue by gabrielrtakeda** [ianstormtaylor/slate#508]
My use case is better described with the screenshot below:
**Use case screenshot**
<img width="163" alt="screen shot 2016-12-07 at 20 09 56" src="https://cloud.githubusercontent.com/assets/5435389/20988812/75fb4dba-bcb9-11e6-8b18-77d5f70e7114.png">
When I click in the text ("Hello" or "World"), the link works but, when I click on the image (void inline image), the link don't works.

I have tested with `readOnly` prop set to `true` in the Editor component and, when I click on the image, it seems that the click was dispatching some action that enables `state.selection.hasEdgeIn(node)` to true, avoiding the default behaviour of the `<a />` tag.

**When I click on the image, even when `readOnly={true}`**
<img width="157" alt="screen shot 2016-12-07 at 20 23 25" src="https://cloud.githubusercontent.com/assets/5435389/20989241/265f4e26-bcbb-11e6-9390-7721b533396e.png">

The code that I working on currently is below:

**ImageNode**
```js
const ImageNode = ({ node, state, attributes }) => {

  const isFocused = state.selection.hasEdgeIn(node)
  const src = node.data.get('src')
  const className = isFocused ? 'active' : null

  return (
    <img
      {...attributes}
      role="presentation"
      className={className}
      src={src}
    />
  )
}
```

**ImageTransform**
```js
export const insertImage = state => {
  const src = 'https://orig06.deviantart.net/7869/f/2009/131/9/e/zubat_icon_by_the_fry_bat.gif'
  return state
    .transform()
    .insertInline({
      type: 'image',
      isVoid: true,
      data: { src }
    })
    .focus()
    .apply()
}
```

**LinkNode**
```js
const LinkNode = ({ node: { data }, attributes, children }) => (
  <a
    {...attributes}
    href={data.get('href')}
  >
    {children}
  </a>
)
```

**LinkTransform**
```js
export const hasLinks = state => state.inlines.some(inline => inline.type === 'link')

export const insertLinkStrategy = state => {
  if (hasLinks(state)) {
    return state
      .transform()
      .unwrapInline('link')
      .apply()
  } else if (state.isExpanded) {
    const href = window.prompt('Enter the URL of the link:')
    const newState = state
      .transform()
      .wrapInline({
        type: 'link',
        data: { href }
      })
      .collapseToEnd()
      .apply()
    return newState
  } else {
    const href = window.prompt('Enter the URL of the link:')
    const text = window.prompt('Enter the text for the link:')
    return state
      .transform()
      .insertText(text)
      .extendBackward(text.length)
      .wrapInline({
        type: 'link',
        data: { href }
      })
      .collapseToEnd()
      .apply()
  }
}
```

Any suggestion that how I can fix this?

**Comment by gabrielrtakeda** [comment]
I get around this handling the `onClick` inside my Node but, I don't know if it is the best solution for that.

**LinkNode**
```js

const LinkNode = ({
  children,
  attributes,
  node: { data },
  editor: {
    props: { readOnly }
  }
}) => (
  <a
    {...attributes}
    className="link-node"
    href={data.get('href')}
    onClick={({ target: { tagName } }) => {
      if (readOnly && tagName === 'IMG') window.location = data.get('href')
    }}
  >
    {children}
  </a>
)
```

**Comment by ianstormtaylor** [comment]
My guess is the reason this is happening is because of the `onClick` handler being used inside void nodes, here: https://github.com/ianstormtaylor/slate/blob/master/src/components/void.js#L61-L78

I'm not sure off the top of my head if there are any bad consequences from removing the `e.preventDefault` which would probably result in the correct behavior for you?

But it sounds like in `readOnly` mode we should definitely ignoring that handler though.

**Comment by kommen** [comment]
I also just have a situation where the `e.preventDefault` comes into my way: I have an inline node which has an onDoubleClick handler. That is never called though as the `preventDefault` in the onClick interferes with it.

**Comment by kommen** [comment]
Never mind, turned out my issue was something else. Sorry about that.

**Comment by bkniffler** [comment]
Hey there, any news on this issue?

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
