### ISSUE TITLE
When insert the `\t` inside the editor the cursor is not showing up. 

### ISSUE THREAD

**Issue by linliTian** [ianstormtaylor/slate#5196]
**Description**
The cursor is disappear, after using the function to instead the test. 

**Video**

https://user-images.githubusercontent.com/70226567/201754397-596ac8fb-41a8-450c-abc3-9bd9f21cf00e.mov

**Sandbox**
[A link to a sandbox where the error can be reproduced. ](https://codesandbox.io/s/zen-grass-x24pvt)

**Steps**
To reproduce the behavior:
1. Go to editor
2. Click any place inline, let the cursor inside
3. Click the button to insert the `Tab`
4. Then the cursor is disappear.

**Expectation**
the cursor is still flashing and the `Tab` is inserted.

**Comment by RavenColEvol** [comment]
@linliTian I'll try to help here.
I'm not not sure what's going in the background but whenever you do a click on button by default
window selection get set on the button. You can check it by click on button and consoling `document.getSelection()`.

Here even if you have added `event.preventDefault()` the selection got set somewhere between the process.

Solution:
You can use `onMouseDown` instead of `onClick` to avoid that selection being set with `event.preventDefault()` and it will work as expected.

Here is the link to sandbox: https://codesandbox.io/s/tender-mcnulty-3c5gf5?file=/src/App.js

**Comment by linliTian** [comment]
Cool, I used another solution by adding the `ReactEditor.focus(editor);` at the end of function. 

```js

  
import { ReactEditor } from 'slate-react';
const TAB = '\t';

  const insertTab = (event) => {
      event.preventDefault.();
      editor.insertText(TAB);
      ReactEditor.focus(editor);
    }
```
