### ISSUE TITLE
iOS/iPadOS. AutoCapitalize not working in first paragraph. 

### ISSUE THREAD

**Issue by fredure** [ianstormtaylor/slate#5199]
**Description**
iOS/iPadOS. AutoCapitalize not working in first paragraph. 

**Recording**
https://user-images.githubusercontent.com/8024592/202745341-1a9168f2-2f06-4ed9-9427-179ade81e49a.MP4

**Sandbox**
https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1. Go to demo with empty editor.
2. Click to editor.
3. Сheck if the shift key is pressed.
4. See error.

**Expectation**
AutoCapitalize is active for the first paragraph.

**Environment**
- Slate Version: last
- Operating System: last iOS/iPadOS
- Browser: Safari

**Comment by Sigkill79** [comment]
Are there any planned fixes or workarounds for this? We're also having this problem.

**Comment by alex-starostin** [comment]
Same here

**Comment by ugrinovsky** [comment]
The problem is still relevant for iPadOS, as safari userAgent is the same as desktop version.
navigator.platform shows IntelMac.
![2024-09-16_13-50-40](https://github.com/user-attachments/assets/a8a7f49c-a130-4eb0-9c21-fab876daf69c)
![2024-09-16_13-54-31](https://github.com/user-attachments/assets/dc054590-b483-475e-b603-199268279d91)
