### ISSUE TITLE
Editor.above throws `Invalid attempt to destructure non-iterable instance` error

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [ianstormtaylor/slate#5215]
**Description**
I recently upgraded to `0.87.0` from `0.81.1`. 
Calling `Editor.above(editor)` throws the following error.
```
TypeError
Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

In version `0.81.1`, the same issue is not present.
 
**Sandbox**
Error behaviour [sandbox](https://codesandbox.io/s/slate-js-playground-forked-q87w0x?file=/src/components/DemoEditor.js) with version 0.87.0.
Correct behaviour [sandbox](https://codesandbox.io/s/slate-js-playground-forked-7t5srk?file=/src/components/DemoEditor.js) with version 0.81.1

**Steps**
To reproduce the behavior:
1. Go to the sanbox urls mentioned above
2. Click on any text in the editor.
3. Hit enter
4. See error in error behaviour sandbox & no error in correct behaviour sandbox

**Expectation**
`Editor.above` function must work as usual. 

**Environment**
- Slate Version: 0.87.0
- Operating System: MacOS
- Browser: Chrome

**Comment by tamilvendhank-helptap** [comment]
**Update:** 
The issue starts to appear from version `0.85.0`. Until `0.84.0`, `Editor.above` works as usual.

**Comment by JoshAntBrown** [comment]
Seeing this too, we think the issue must be something to do with this code in the function https://github.com/ianstormtaylor/slate/blob/3c49ff28b3d188f69d8361bd682b7e8d0a1c13b6/packages/slate/src/interfaces/editor.ts#L360-L373 introduced by https://github.com/ianstormtaylor/slate/commit/3c49ff28b3d188f69d8361bd682b7e8d0a1c13b6. 

The error thrown is because Editor.above appears to be returning undefined, but then our code tries to destructure this assuming Editor.above will always return something.

**Comment by radu-cs** [comment]
It still breaks even with this fix implemented when the project is build, but works as expected in develop mode.
I am using a link editor and it breaks here:
```
  const editor = useSlate()
  const [node, path] = Editor.above(editor, {
    at: selectionForLink,
    match: (n) => n.type === 'link'
  })
```
Any ideas?
Thank you in advance.
