### ISSUE TITLE
(Demo) Duplicate characters entered around markup boundary in Firefox

### ISSUE THREAD

**Issue by mishavee** [ianstormtaylor/slate#523]
On the demo page http://slatejs.org/

Entering a character on the boundary of a markup area puts the character outside the boundary, and a duplicate character inside the boundary.

![dup entry bug](https://cloud.githubusercontent.com/assets/13145938/21211568/da3f8794-c2d8-11e6-9d59-7f34d237b301.gif)

I had the issue on:
Firefox 50.1.0 on Windows 8.1 64-bit.
Firefox 49.0.2 on Lubuntu 64-bit.

I didn't get the same issue in Chrome, which continued with the text to the left of the cursor.

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
