### ISSUE TITLE
Chrome 112 crashes editor after presence of tab in content

### ISSUE THREAD

**Issue by dylans** [ianstormtaylor/slate#5390]
**Description**

Cross-reported at https://bugs.chromium.org/p/chromium/issues/detail?id=1431935

**Steps**
To reproduce the behavior:
1. Chrome 112, https://www.slatejs.org/examples/richtext , paste some content with a tab character
2. You'll see double characters added
3. Eventually the editor crashes

**Expectation**
No duplication of text characters or inconsistency between Slate state and DOM

**Environment**
- Slate Version: latest
- Operating System: any
- Browser: Chrome 112

**Comment by dylans** [comment]
Observed that this issue only happens when typing a-zA-z or space.

That led me to this line: https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/editable.tsx#L496

There's a check in Slate to support React's native vs. non-native event handling for beforeInput events, e.g. https://github.com/facebook/react/issues/11211

If I change https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/editable.tsx#L502 to native = false for Chrome, works around this issue, but it's unclear why.

It's as if the native event is getting treated as a long-press event.

So I would feel much better if I knew what caused this regression for Slate in Chrome 112 (intentional or not)

**Comment by dylans** [comment]
Short term fix is something along the lines of "change https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/components/editable.tsx#L502 to native = false"

There is some update from the Chrome team, so they are looking into it and know roughly what change to Chromium caused the regression: https://bugs.chromium.org/p/chromium/issues/detail?id=1431935#c7

**Comment by dylans** [comment]
Fix has landed in Chrome. Unclear exactly when it will land, but it looks like in both a patch release of 112 and in 113.

**Comment by sibljon** [comment]
Hi everyone. Thanks for all the hard work reproducing and investigating so far. This issue was helpful to me, as was the link to the Chromium issue.

I just tested in Chrome 112 and 113 and neither seems to have fixed the issue. However, Chrome 114 has indeed fixed the issue. [Here's a screencast of my testing, in case this is valuable to anyone.](https://user-images.githubusercontent.com/442307/234570943-04304523-1c45-4f90-90d0-d84717f72299.mp4)

As I understand it, there's chance that 112 or 113 will get the fix in a patch release, but that doesn't seem to have happened yet, and whether that is to happen or not seems unresolved in the Chromium issue. Would you consider making a patch to the Slate library for the time being? If I understand correctly, @dylans "short-term fix" requires us forking Slate, correct?
