### ISSUE TITLE
Stack creation issue

### ISSUE THREAD

**Issue by pulse14** [ianstormtaylor/slate#557]
I think the way of editor component `componentWillReceiveProps` works can cause a major performance issue
```javascript
 for (const prop of PLUGINS_PROPS) {
      if (props[prop] == this.props[prop]) continue
      const { onChange, ...rest } = props // eslint-disable-line no-unused-vars
      stack = Stack.create(rest)
      this.setState({ stack })
}
```
If someone (like me) do that : `<Editor plugins={[...]}/>` the stack get recreated every render. Which cause the `BLOCK_RENDER_RULE` render function get recreated. Which cause a full rerender since subtrees are deleted when component types are different...

Maybe the docs should be updated ? Or this function ?

Thank you

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
