### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by frederickfogerty** [ianstormtaylor/slate#560]
There are no typescript definitions for this project that I can find, either here or on DefinitelyTyped/@types. Does anyone have any definitions? 

It would be great if the definitions could be exported from the module directly, it makes adoption a lot easier, and keep the definitions close to the source. 

🙌🏻

**Comment by ianstormtaylor** [comment]
For context, I'm open to adding type definitions to the library in the future, if we start using typed source code, or after it's very stable. But until one of those things happens I'm avoiding adding type definitions purely for the maintenance burden.

**Comment by bsouthga** [comment]
As a stopgap, I created this https://github.com/CrossLead/slate-dts which generates the typings from the source code and publishes scoped typings packages (for example `@crosslead/slate-typings`)

**Comment by styu** [comment]
@ianstormtaylor I was going to add type definitions to `DefinitelyTyped` and then I saw this issue - is this something you're open to now, or do you still want to wait?

**Comment by andykent** [comment]
I started work on some handwritten typedefs this week (just `slate` and `slate-react` for now)...

https://gist.github.com/andykent/202e819c35bd720e73302849c76fab33

It's actually my first typedef for an external lib like this so I'm sure I've made some huge errors but it seems to be working for me. Also, wow, Slate maybe wasn't the easiest project to start with, there's a pretty large API and some quite rich types.

I've put them in a Gist for now in case they are useful to others as I think it's a good step forward from the autogenerated ones mentioned above but it would be great to get something in Slate itself or DefinitelyTyped if not. 

Note: I largely based the types on the public docs but noticed there is quite a lot more undocumented APIs in the source, @ianstormtaylor are things not in the public website docs to be considered private? or are the docs just lagging behind?

**Comment by JanLoebel** [comment]
Thank you @andykent and @majelbstoat! I created two basic repositories to store the files and add some information how to use them in a current project to find other bugs and improve the definition further. Please feel free to create any Pull-Request or add issues. Thank you for the great work so far :)

https://github.com/JanLoebel/types-slate-react
https://github.com/JanLoebel/types-slate

**Comment by chilbi** [comment]
[https://github.com/chilbi/slate-demo/tree/master/src/types](https://github.com/chilbi/slate-demo/tree/master/src/types)

**Comment by mattcopas** [comment]
@chilbi Thanks for your link! 

I've almost got it to work - I had to install @types/immutable - however I've now got the compilation error: **Module not found: Can't resolve 'slate' in 'slate-ts-project/node_modules/slate-base64-serializer/lib'**

(I've got node_modules on the tsconfig exclusion list of course).

Does this compile fine for you? Any ideas?

Thanks

**Comment by YangusKhan** [comment]
Hello, I just wanted to make everyone aware I opened [a PR at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26761) and started adding @JanLoebel repositories -- only the base 'slate' module for now.

**Comment by RXminuS** [comment]
Ok, I think we need to rethink this because the @JanLoebel typedefs and @YangusKhan at this point diverge quite a bit from actual implementation. Wouldn't it make sense to put up a PR in this repo and keep the typings in sync? It's only one types.d.ts file.

I'm going to sit tonight and try to fix up the (awesome) base work by @JanLoebel and submit one.

**Comment by RXminuS** [comment]
Actually, @chilbi 's definitions seem to cover most of it already!

**Comment by RXminuS** [comment]
Another option is to do what I think Redux etc do...generate typescript definitions from the JSDoc comments. I tried it out on a test file and it seems to work Ok. A bit like @bsouthga but we can avoid a lot of `any` types that way. https://github.com/jumpinjackie/jsdoc-typescript-plugin

**Comment by YangusKhan** [comment]
I'm flexible to work with anything. I just wanted to get the ball rolling in the DefinitelyTyped repo. I've also got a PR active for slate-react from @JanLoebel work, plus some local work for html- and plain- serializers based on @chilbi

**Comment by travigd** [comment]
@YangusKhan As @RXminuS pointed out, a few things in that  PR are a bit old (e.g. use of kind, as opposed to object) and, in my own hacking, I found it impossible to accurately type the schema normalize methods w.r.t. different kinds of contexts. [This gist](https://gist.github.com/travigd/b2b144b4d6b6cff1eaac3023f3106e98) is what I'm using in my own project, and then my normalize methods are typed as...

```ts
normalize = (change: Slate.Change, violation: SchemaViolation, context: ViolationContext) => {
  switch (violation) {
    case SchemaViolation.NODE_DATA_INVALID:
      const dataInvalidContext = context as NodeDataInvalidContext;
      // do rest of stuff with type safety using dataInvalidContext
  }
};
```

I tried with overloading but it wasn't working for me:
```ts
function normalize(change: Slate.Change, violation: SchemaViolation.CHILD_OBJECT_INVALID, context: ChildObjectInvalidContext)
function normalize(change: Slate.Change, violation: SchemaViolation.NODE_DATA_INVALID, context: NodeDataInvalidContext)
function (...) {
  // Do stuff here by discriminating on violation and letting TypeScript figure out the overloads
}
```

It would be significantly easier if `context` included `violation`, because then TypeScript could accurately figure out which specific type `context` is:
```ts
// In declaration f ile
interface NodeDataInvalidContext extends CommonViolationContext {
  violation: SchemaViolation.NODE_DATA_INVALID;
  key: string;
  value: any;
}

// In normalize method.
switch (context.violation) {
  case SchemaViolation.NODE_DATA_INVALID:
    // TypeScript knows that context is NodeDataInvalidContext now
}
```

@ianstormtaylor Is that something that could be added?

Also, HUGE +1 to adding TypeScript definitions to the project.

**Comment by zhujinxuan** [comment]
There is a way to have typescript definition by alias. However, too many methods exists in slate/model and slate/changes.  And typescript for schema context can be quite crazy. 

Personally, I do not mind maintain a type definition when API changes in future.  (.flow.js or .d.ts are both fine)  But I do not have time to define types.

**Comment by zhujinxuan** [comment]
BTW, there is a note about adding definitions.

In JSDoc, Text are considered as one of Node in `packages/slate/src/models/node.js`.  However, `Text` does not inherit node methods.

**Comment by RXminuS** [comment]
@travigd I'm not too familiar with the context, can't seem to find it in the docs. Do you know where to read up on it? Think we can maybe trick something together with conditional types based on the return value or inference?

**Comment by travigd** [comment]
@RXminuS 
* https://docs.slatejs.org/slate-core/schema#normalize
* https://docs.slatejs.org/slate-core/schema#violations
* https://docs.slatejs.org/other-packages/slate-schema-violations (this is where the documentation describes the interfaces of the various `context`s)

I can think of a few attempts:
* TypeScript function overloading (didn't really work for me, but someone else might have better luck?)
* Adding a `violation` field to the `context` object to allow for ["discriminated unions"](http://www.typescriptlang.org/docs/handbook/advanced-types.html) (search for "Discriminated Unions, it's about halfway down), which is **by far the best way to do this** as far as I see, but would require altering (in a very minor and backwards compatible way!) the behavior of the slate core to support idiomatic TypeScript)
* Using `if` statements with type guards.

Here's what I mean by the type guards:

```ts
// Type guard via 'function ...(...): context is ... {' syntax
function isDataInvalidViolation(violation: SchemaViolation, context: any): context is NodeDataInvalidContext {
  return violation === SchemaViolation.NODE_DATA_INVALID;
}

function normalize(change: Slate.Change, violation: SchemaViolation, context: ViolationContext) {
  if (isDataInvalidViolation(violation, context)) {
    // Because of type guard, TS knows that  context is NodeDataInvalidContext
    console.log(context.key);
  }
}
```

That's less than ideal as far as I'm concerned, and disallows the use of `switch` statements (disregarding the `switch (true) { case /* expression /*:` type of thing).

**Comment by RXminuS** [comment]
Haha, sorry I meant discriminated not conditional. Yeah, that by far seems the most elegant solution and the change should not break anything since constructors are used everywhere.

**Comment by ianstormtaylor** [comment]
@travigd actually I was thinking of something similar recently in regard to https://github.com/ianstormtaylor/slate/issues/1923 — I’d like to change those objects that the normalizing functions receive to actually be `Error` instances. And then it would make the most sense to rename the “violations” to `error.code`. 

I think it would be one small step towards making the normalization logic slightly easier to mental model. And it sounds like it would be easier to type, so that’s a plus too.

**Comment by RXminuS** [comment]
I have some base versions of the Typings ready just trying to figure out how to organize them on DefinetlyTyped (so we have tests included and naming is aligned with internal Slate packages. Any tips of someone with experience? I'll post a link to the PR when it looks good.

**Comment by YangusKhan** [comment]
@RXminuS the Typescript folks also [merged in my slate-react definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26827), so if you're touching those too then make sure to take a look.

**Comment by YangusKhan** [comment]
Another heads up: [I did a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27087) at DefinitelyTyped for the base64, plain, and html serializers.

**Comment by FarmaanElahi** [comment]
Hey @YangusKhan I am unable to get the `slate-react` type to work
Getting this error `App.tsx:5 Uncaught TypeError: Cannot read property 'Value' of undefined`

**Comment by RXminuS** [comment]
Ok, finally had the time to sit down and manually type the whole core (https://github.com/ianstormtaylor/slate/pull/2144). Now working on the plugins. I'm actually going to post this as a PR in this repo anyways because I feel that maintaining this is going to be way easier long term then constantly having to chase after the PR's.

I've tried to keep the typings as closely matching to how the code is actually implemented to make it easy for contributors to find their way around. Also noticed a few bugs in the actual code because of typings.

Would love feedback. We're already using these types in production ourselves and so far they seem to be working quite well. I'm just polishing things and adding all the other packages. Any help is appreciated!

**Comment by YangusKhan** [comment]
There is a [PR at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28343) from @isubasti that's updating those types to 0.40. We should probably reconcile which declarations are the most complete. From a glance it looks like yours are.

**Comment by mattcopas** [comment]
For anyone using DefinitelyTyped, DefinitelyTyped is out of date for slate 0.42.2, due to various breaking changes

**Comment by AdamMurray** [comment]
Does anyone have updated typing for the following versions?
```
"slate": "0.42.3",
"slate-react": "0.19.4"
```

I'm new to both Slate and TypeScript and am having huge amounts of trouble getting things working.

**Comment by bengotow** [comment]
Thanks everyone for putting the types together, they're really extensive and a pleasure to use so far. 🙌 

Slate's API has been changing fairly regularly and I think that bringing the types into core (and using Slate via Typescript) would make it /much/ easier to stay on top of the changes since `tsc` identifies everything you need to update. I think that text editor code is prone to "edge case handling" that is difficult to put under test, and knowing that `editor.x.y.z` will still work without running it is nice.

**Comment by peterkulik** [comment]
Hello,

I'm absolutely newbie with slatejs. I'm using typescript and I have also added @types/slate to my project. When I tried to setup the basic scenario by the installation guide, I got two typescript errors:

> Object literal may only specify known properties, and 'text' does not exist in type 'NodeJSON'.  TS2322
> Property 'leaves' is missing in type '{ object: string; text: string; }' but required in type 'TextJSON'.  TS2322

This is the basic sample data in the guide: [https://docs.slatejs.org/walkthroughs/installing-slate](https://docs.slatejs.org/walkthroughs/installing-slate)

```
const initialValue = Value.fromJSON({
  document: {
    nodes: [
      {
        object: 'block',
        type: 'paragraph',
        nodes: [
          {
            object: 'text',
            text: 'A line of text in a paragraph.',
          },
        ],
      },
    ],
  },
})
```

I have modifed the TextJSON interface (text property is added, leaves is removed):
```
export interface TextJSON {
    key?: string;
    //leaves: LeafJSON[];
    object: "text";
    text: string;
}
```

I'm unsure this is the right solution, but it is working now.

**Comment by linonetwo** [comment]
I got:

```
As of slate@0.46, the `leaves` property of Text nodes has been removed. Instead, each text node contains a string of text and a unique set of marks and leaves are unnecessary.
```
 if I follow `ValueJSON`, so anyone can update it?

**Comment by aeplay** [comment]
I started working on the DefinitelyTyped refs according to the changelog, fixing the new TextJSON and related structures but couldn't (quickly) get the test to pass again.

Maybe someone wants to take it from there and submit a pull request to DefinitelyTyped?

https://github.com/aeplay/DefinitelyTyped/commit/dbe1ee19b2d531cc77e96cdf4ae726ff960854d3

**Comment by ianstormtaylor** [comment]
I'm curious about trying to make the editor itself easier to type for TypeScript. (But not at the expense of the UX we currently have.) If anyone who is good at TypeScript could try mocking up some ideas, I'd appreciate it.

I'm unsure how to type the Editor while still maintaining:

- Plugins that can define their own methods that will live on the editor.
- Plugins overriding existing methods on the editor.
- Userland getting a fully-typed `MyEditor` interface based on their plugins.

Right now we use plain objects, but I'd be open to using a `class`-based design if that made overriding and typing these things easier in the future.

Can this be well typed with TypeScript? or is this past it's abilities?

**Comment by travigd** [comment]
Classes can only implement statically known members. By this I mean that
```ts
class Editor<Foo> implements Foo {
  // ...
}
```
is not valid TypeScript.

One option might be type intersections.

```
class Editor {
  ...
}

type MyEditor = Editor & MyPluginInterface;
```
but that's not exactly ergonomic TypeScript.

**Comment by majelbstoat** [comment]
You can do, for example:

```
// Form.jsx

interface ChildArgs<Fields> {
  setFieldValue: <F extends keyof Fields>(field: F) => (value: Fields[F]) => boolean
  fields: Fields
}

interface Props<Fields> {
  children(args: ChildArgs<Fields>): ReactNode
  initialValues: Fields
}

interface State<Fields> {
  fields: Fields
}

/**
 * A UI form that 
 */
class Form<Fields> extends React.Component<Props<Fields>, State<Fields>> {
  constructor(props: Props<Fields>) {
    super(props)
    this.state = {
      fields: props.initialValues,
    }  
  }
}
```

which creates a generic, pluggable Form that you can use like:

```

// QuestionForm.jsx

interface FormFields {
  title: string
  description: string
  topicIds: string[]
  summaries: string[]
}

const QuestionForm = Form as new () => Form<FormFields>
```

**Comment by ianstormtaylor** [comment]
If someone could use the TypeScript Playground to sketch out how this might work, that would be very helpful! 

I'm at a point right now where I can choose to make the editor and plugins architecture slightly more TypeScript-friendly, which would increase the potential of being able to migrate in the future. But I don't know enough to do it myself, and if I do it wrong it will delay it. 

So anyone who wants to see TypeScript adopted, this would be the place to help.

**Comment by travigd** [comment]
> Plugins that can define their own methods that will live on the editor.

I'm not sure that this is possible in an "ergonomic" way and would (probably?) require a **lot** of TS hacks (especially using a lot of `any` internally). One method might be a DI-style thing where instead of defining methods on the editor, you access the methods defined on plugins by accessing them directly.

```ts
# Instead of...
editor.foo()
# you might do...
editor.plugin(MyPlugin).foo()
```
This doesn't look great to me though.

There are also other methods that are much more complicated with the type system. For example, you could define an editor type (not a class for the reasons I mentioned in previous comment) to the tune of
```ts
function BaseEditor() {
  return {
    addMark() { /* ... */ }
  }
}
type BaseEditor = ReturnType<typeof BaseEditor>;

type SlatePlugin = {};
type Editor<TPlugins extends SlatePlugin[] = SlatePlugin[] > = BaseEditor & Tuple2Intersection<TPlugins>;
function Editor<TPluginStack extends Array<SlatePlugin>>(plugins: TPluginStack): Editor<TPluginStack> {
  const editor = BaseEditor();
  for (const plugin of plugins) {
    Object.assign(editor, plugin);
  }
  return editor as any;
}

const myEditor = Editor([]);
myEditor.addMark();

const myPlugin = (options: {} = {}) => ({
  addFancyMark() {}
});
const myFancyEditor = Editor([myPlugin()]);
myFancyEditor.addFancyMark();

// Util types
type Tuple2Union<T> = { [P in keyof T]: T[P] } extends { [key: number]: infer V } ? V : never;
type Union2Intersection<U> = (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type Tuple2Intersection<T> = Union2Intersection<Tuple2Union<T>>;
```

This might be somewhat brittle though as it required a lot of type inference which is really easy to mess up based on how exactly you invoke the functions.

There probably is a way to be-able to get type-checker guarantees about the other plugins that are installed but all of this would more than likely require some very sophisticated typescript hackery.

> Plugins overriding existing methods on the editor.

This should be okay as long as the overridden methods keep the existing type contract.

> Userland getting a fully-typed MyEditor interface based on their plugins.
> Right now we use plain objects, but I'd be open to using a class-based design if that made overriding and typing these things easier in the future.

If you want to do a class-based design, you have to implement all the methods in the same file, which would probably be cumbersome given the number of methods that exist on the editor instance. To do TS at all, you'd probably have to do that. The alternative would be separating this out into separate sub-instances on the editor (e.g. instead of `editor.addMark` you might have `editor.marks.add` and then make some `MarkManager` class that defines all of the mark-related methods.

For my two cents, I was using Slate in a project (haven't worked on it in a while) where the majority of the codebase was in TypeScript. I tried using some of the community-supplied TypeScript definitions (that were already out of date when I tried) and ended up just settling on writing plain JavaScript for the slate-specific portion of the code and it worked out pretty well. It would be nice to see TypeScript support for Slate, but I'm personally worried that it will devolve into a not very friendly API to make the static typing work.

**Comment by ssalka** [comment]
> Plugins that can define their own methods that will live on the editor.

If users are changing the type of something exported from a library at runtime, then it should be their responsibility to also augment the types to match those changes. In this case, the plugins should have type definitions made available, such that by having them installed & referenced in a user's project, the `MyEditor` interface would automatically gain whatever is declared by the plugin's types.

Material UI does this with their [theme interface](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/src/defaultTheme/index.d.ts). As a consumer, you can amend it [like so](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/src/defaultTheme/defaultTheme.spec.ts#L4-L8) in your own source code:

```ts
declare module '@material-ui/styles' {
  interface DefaultTheme {
    myProperty: string;
  }
}
```

This is a lot simpler than trying to handle the plugin types generically, as @travigd suggests with the `Editor` type, though it requires some extra work to be done by the user, so I admit I do like the type inference approach - I've done similar things before, and it can work.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
