### ISSUE TITLE
Copying from Slate adds a newline after first character

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#562]
Copying this fragment:

![screen shot 2017-01-18 at 10 15 56](https://cloud.githubusercontent.com/assets/5644953/22057909/200b6790-dd67-11e6-919d-fc8d614b86f6.png)

...and pasting it here gives:

### From Firefox
```
r
endered block quote in the middle of the page, like this:

    A wise quote.
```

### From Chrome and Safari
```
r
endered block quote in the middle of the page, like this:
A wise quote.
```

You can see the unwanted newline after the first character in any case.

**Comment by Slapbox** [comment]
I've also seen this in every instance of copying out of Slate, but assumed it was something I had done to cause it.

**Comment by Slapbox** [comment]
I've also seen this in every instance of Slate I have played with, including in my own app.

**Comment by amaau** [comment]
it's because slate put's the first character of the selection in a span, (used to store the document fragment in the span's attribute, so could later paste exactly that.
simplest way around, if you don't need that functionality is to comment out 

`var wrapper = window.document.createElement('span');
var text = contents.childNodes[0];
var char = text.textContent.slice(0, 1);
var first = window.document.createTextNode(char);
var rest = text.textContent.slice(1);
text.textContent = rest;
wrapper.appendChild(first);
wrapper.setAttribute('data-slate-fragment', encoded);
contents.insertBefore(wrapper, text)`

from core.js plugin onCutOrCopy function, or make the span be around the whole selection

**Comment by Slapbox** [comment]
@ianstormtaylor Do you have something in mind to address this already? If not, do you plan to address this issue as a bug?

**Comment by wmertens** [comment]
why not put the data-slate-fragment on an empty span, or on the first childnode?

**Comment by ianstormtaylor** [comment]
Putting it on an empty span, or on the first child element node sounds great to me! I'd love a PR that implements that. Thanks!
