### ISSUE TITLE
typing END on multiline text moves selection to start of next line

### ISSUE THREAD

**Issue by amaau** [ianstormtaylor/slate#627]
In a word-wrapped multiline text, when typing END or clicking to the right of the line, the expected behavior is to select the last possible position on that line, slate moves the selection to the start of the next line.
I see the caret for a moment jumps to this invisible 'line-ending' character, then quickly corrects itself, but in the wrong direction.
Related issue -
If I click to the right of the line the second time (after it corrected the first), I actually select this impossible position, no correction takes place.
edit - just checked some more, the second time I click there slate doesn't notice the selection changed - no slate functions are called.

**Comment by skogsmaskin** [comment]
Something similar happens if a inline node is the last node in a block. It is because of the ``data-slate-zero-width`` spans I think. As for your word-wrapped example, it may be something else, because the ``data-slate-zero-width`` shouldn't be there.

**Comment by amaau** [comment]
yeah, mine's something else
in contenteditable it seems there's no difference between end of one line and beginning of next - offsets are the same. if selection has been saved+restored, there's no way to distinguish. slate re-applies selection on every onSelect, I imagine it is a lot of work to change

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
