### ISSUE TITLE
Inconsistency in setBlock/wrapBlock behavior

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#674]
I came across a case where `setBlock` followed by `wrapBlock` works differently when done at the beginning of the doc and when done someplace else. 

Here is a simple JSFiddle illustrating that - https://jsfiddle.net/u2r1e2wm/1/

I am not sure if I'm misunderstanding the behavior or missing some detail here, but wanted to bring it up since nothing else was apparent to me.

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!

**Comment by oyeanuj** [comment]
@ianstormtaylor This is still occurring in the latest version of Slate. Here is an updated JSFiddle - https://jsfiddle.net/u2r1e2wm/2/

My guess is that the problem is somewhere in the code for `wrapBlock` - maybe you have other insights into what might be going on?

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
