### ISSUE TITLE
Control over block/inline plain-text representation

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#691]
Hey, 
Is there currently any way to control how a block should be serialized by the plain serializer? Say we have some isVoid block (an image) and we'd like to have that represented in the serialized plain text (maybe in markdown syntax).

If not, would you consider adding such functionality? Maybe we could have an option for the serializer that we can give an object with keys for every block/inline type, that defines a function with the node (for data) as an argument and returns a string.

What do you think?

**Comment by ianstormtaylor** [comment]
Hey @bkniffler, interesting question.

What's your exact use case for this? My first thought is that I think the `Plain` serializer is simple enough, that it wouldn't be hard to create another serializer for this purpose. But curious about your use case, and if it merits having it handled by "core".

**Comment by bkniffler** [comment]
I thought about using the plain serializer as a base, but then I took a look at the html serializer which allows for custom rules. So I wondered if it might be more consistent to allow to customize each serializers behavior by custom serialization/deserialization rules.

In my case I got inline isVoid=true nodes that contain fixed text that is pulled from the nodes data. Think about a textblock block node, that should not be editable directly, but users may choose different texts that will appear in the block. When I export the document as plain text, it will ignore the text from the block, since it has isVoid=true. 
![marz-30-2017 13-54-10](https://cloud.githubusercontent.com/assets/4349324/24503039/a98a823c-1550-11e7-8297-c74db8211dcd.gif)

Having rules would also facilitate making a markdown serializer/deserializer, but maybe you might find this should not be inside the plain serializer's scope.

Under the bottom line, I think adding a custom serializer based on the easy-to-understand plain serializer is an absolutely valid solution, so if you don't see any benefit for the core and other users/use-cases, feel free to close! I'll leave it open in case you think that adding rules to plain serializer might be useful.

**Comment by abobwhite** [comment]
I have a use-case I'm struggling with badly that seems related to this. I've created an inline node that contains some dynamic piece of styled text that's read-only. When serializing HTML I can handle this perfectly. In plain text, this node doesn't show up because it's not a block and it's not actually a Text object within. Any thoughts? If I make it a Text, it would be editable I believe.

**Comment by ianstormtaylor** [comment]
Hey you two, thinking about this more, I think it's out of scope right now for the library to make the serializers more modular, since it seems hard to satisfy all cases.

That said, I would like to change void behavior to allow text in void nodes, which would then get serialized properly by the plain serializer—which sounds like it happens to solve @bkniffler's issue, although there's a chance that you'd still want custom logic for the void nodes, in which case you'd be back to defining a custom serializer.

**Comment by abobwhite** [comment]
Hey @ianstormtaylor I actually wrote my own Plain serializer which mimics what the Html serializer was doing by optionally taking rules and by having a default rule. It works really well. I was thinking about writing some tests and actually creating a PR against slate itself so others could use it and it's fully backwards-compatible. What are your thoughts?

**Comment by ianstormtaylor** [comment]
@abobwhite I'd love to check it out. I haven't thought super deeply about it so I'm not sure off the top of my head whether it would be a good fit for core, but I'd definitely be interested in reading the code and seeing examples to judge for sure! Thanks for asking!

**Comment by oyeanuj** [comment]
@abobwhite Did you post the plain serializer in the comment above as a PR or on Slack? Would love to take a look!
