### ISSUE TITLE
Embed does not work correctly when using special keyboard

### ISSUE THREAD

**Issue by pa-nam** [ianstormtaylor/slate#697]
When using a special keyboard on Mac (like Japanese or Vietnamese), the embed elements always rerender again and cause some flicker. Here is a test case on slate home page:

![slate-key-hook-bug](https://cloud.githubusercontent.com/assets/19988263/24538359/dcab8d74-1612-11e7-8eac-33307c219d59.gif)

Im working on embed right now, so I haven't test on other kind of elements yet.
I will report here if I found a similar flicker due to keyboard, maybe I will test on Windows too.

Thank you for this great editor.

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
