### ISSUE TITLE
Some enh

### ISSUE THREAD

**Issue by githubjeka** [ianstormtaylor/slate#724]
**1. Markdown**
[Correct Syntax Header](http://daringfireball.net/projects/markdown/syntax#header)
to string `#my-hash-tag`  generate header tag. It's wrong.
For example correct behavior you can see here on GitHub

`#my-hash-tag`

#my-hash-tag

`# my-hash-tag`

# my-hash-tag

**2. Paste images**
When I copy text & images from anyway and paste in your editor then text copied only
Is't possible to make automatic insertion of images with the original URL?
This behavior work on https://www.tinymce.com/ for example and very сonvenient to use

**Comment by ianstormtaylor** [comment]
Hey @githubjeka thanks for opening this!

For (1), I agree with you, but in this case the "Markdown Preview" example is just a simple example that uses Prism.js to parse where the markdown elements are. So it's kind of out of scope, but if it gets fixed in Prism.js's Markdown parsing I'm happy to upgrade that dependency.

For (2), this is actually be design with the most basic editor, check out this [question in the FAQ](https://github.com/ianstormtaylor/slate/blob/master/docs/general/faq.md#why-is-content-pasted-as-plain-text) for more information. It's possible, but it requires work in userland.
