### ISSUE TITLE
define `isVoid` behavior in the schema itself

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#735]
Hey @ianstormtaylor! While working on embeds, I noticed a particular pattern emerging within my code. That led me to a question/proposal around how blocks are declared in the schema. It is still fairly high level but wanted to put it out there to start discussion (and make sure I am not missing anything in my understanding). 

---

**1. Declaring isVoid in the schema instead of block properties**

I noticed that for certain blocks, especially for `void` ones, I kept adding that wherever I needed to insert or toggle a block.
```js
const embedContent = Block.create({
  type:	embedBlock.data.get('embedType'),
  isVoid: true
});
```

Now I know, that the above problem can be mitigated by having one function creating the block and calling that function everywhere, or by having a normalization rule that ensures that it is always `void`.

But it seems to me that `isVoid` information is something that is not likely to change in a schema, and hence should be defined there (alongside `render` or `decorate` in a `node`).

---

**2. Nested block structure in the schema**

Another pattern that has emerged in different cases (lists, embed) is that a block might need to **always** have a particular structure as its `children`. 
```yaml
Embed
  - EmbedContent
  - EmbedInfo
    -- EmbedTitle
    -- EmbedAuthor
```
Now it feels a little weird to enforce or insert this structure everytime one inserts or toggles to an embed block. It takes a few `insertBlock` and `wrapBlock` operations to do so. To be fair, this can again be abstracted into a function and reused, or be enforced through schema validation and normalization rules as you have in some examples. 

But again, it made me wonder if the more appropriate place might be the schema declaration (especially, when the structure shouldn't change). 

This one is more complicated than the previous one (especially around flexibility with nested structures), and I am aware that the schema declaration is also translated into rules, so this might be more about it being a more readable and shorthand for writing schema rules.

Thanks for your time, would love to hear your thoughts!

**Comment by Slapbox** [comment]
I think these are excellent ideas.

**Comment by ianstormtaylor** [comment]
Hey @oyeanuj thanks for opening this!

For (1), I'm definitely open to that. The one tricky thing is that it means that the `schema` becomes a required object to have around to be able to transform a `state`. Which probably means that we'd want to store it on the `state` itself. This might not be bad, I'm not completely sure. I think I'd like to wait to see how collaborative editing with OT works a bit more before committing to that, in case there are any issues there. But if it works fine with the `schema` being required to transform things, then I'm definitely down to make this change.

For (2), I'd be curious to see code samples for what you're thinking. I'm not sure there's an easy way to do it that's not also limiting to other use cases, but I haven't thought about it a ton right now. I think this does sound like something that could be made into a simple plugin that returns schema validators though.

**Comment by oyeanuj** [comment]
@ianstormtaylor Thanks for the response!

> For (1) ... The one tricky thing is that it means that the schema becomes a required object to have around to be able to transform a state.

Is the complication or trickiness that the code would have to look up `schema` or `editor.props.schema` in the transform operation? Or that `isVoid` data would not be represented anywhere in the document state? 

If the latter, then I imagine every `setBlock`, `insertBlock` or other `Block` operation, core code would need to consult the schema first to set that property before the operation..

> For (2), I'd be curious to see code samples for what you're thinking.

Maybe something along the lines of this (adding a `children` property to a node) -
```js
embed: {
  render: EmbedContainer,
  children: [
    embedContent,
    embedInfo, 
  ]
 }
...
embedInfo: {
  render: EmbedInfo,
  children: [
    embedTitle,
    embedAuthor
  ]
}
```

The advantage of something like this is that one could have complex nested components with ease, as each component will just declare its children and composition takes care of the rest.

> I'm not sure there's an easy way to do it that's not also limiting to other use cases

Initially, I thought that it would mainly take away some of the flexibility that Slate provides for the developer to specify children at the time of transform. But thinking more about it, we could still let the developer do that and if they do, it would override the children hierarchy mentioned in the schema.

> I think this does sound like something that could be made into a simple plugin that returns schema validators though.

True, although there is a case for having it in the core API if we think that generally nested components will follow a particular, singular structure. 

---

Finally, thinking more about this case and the above case, I think allowing some part of the schema to be stored in the document state will allow for more such cases, and for less brittle code and boilerplate. 

- Semantically, I could see an argument for having some terse representation of the schema in the state as well. If the document state is what one needs to understand everything about the document (except the rendering), then it would make sense to have certain top-level information or data about different type of nodes and marks in the document schema.

- Representing children in simple arrays/json/yaml allows for less boilerplate (than writing rules) while developing, easier unit testing and (maybe easier enforcement for core writing rules?).

---

I know this has become a longer comment than I anticipated, but tried to capture all the little pieces. Thanks for being open to the ideas! 😃

**Comment by ianstormtaylor** [comment]
@oyeanuj just to follow up here:

1. I think this is still a possibility, but I'm waiting to learn more about what our requirements will be. I'm unsure if there are any big downsides to including the schema inside the state itself.

2. I think this is something that should be handled by plugins, and shouldn't be part of core. The way the core schema rules are setup, they allow for complex schema definitions, and I agree that the one you point out is a common case, but I don't think I want to complicate core by adding support for that case over others, since there are going to be lots of individual opinions about how it should work.

**Comment by oyeanuj** [comment]
@ianstormtaylor appreciate the update. I want to clarify that for (2), it is not only about how achieve it functionally (plugin vs core, for example) but also about where nesting definitions feel intuitive and easy to reason. It seems to me that if one looks at the schema, they should be able to understand everything about the structure of document, or the kind of elements in the document. Part of that understanding is the nesting or hierarchy (which is enforced through rules or individual insert operations). Another way to think about it is that nesting might be a special kind of fundamental rule which warrants a place in the schema definition - since it has immense semantic meaning.

For other kind of rules, I can totally see a plugin being super helpful and the way to go rather than including it in schema definition.

Totally understand if this doesn't feel worth the effort right now, or if it adds unnecessary complexity but just wanted to make sure I was making the best case for why this might be an API direction to embrace.

**Comment by ianstormtaylor** [comment]
@oyeanuj thanks, yeah I don't mind you expanding at all. I think I get where you are coming from, and surely some sort of nesting will be the most common use case. I could _potentially_ see it making it into core, although it would be down the road since it's not a priority right now.

But part of me also thinks that allowing it in core is going to lead having to make potentially opinionated, and restricting, decisions that make some use cases harder to manage. I believe Prosemirror has a similar nesting syntax. But then people will argue over whether core should support ordering in addition to nesting, or whether nesting should be order independent. I think it all just makes more sense as a plugin that can define it easily, and convert it into simple schema rules.

Right now the way the schema is defined, pretty much anything is possible, but nothing is forced. And unless we have a very 90+% use case to account for, without obvious different solutions, I'd like to keep it that way.

If you look through the issue history, I think there were a few issues where the Gitbook team and I discussed schema rules. And they proposed a similar nesting solution, with an example API. I think that kind of API could make for a nice plugin.
