### ISSUE TITLE
Add information on weight of code + explore reducing

### ISSUE THREAD

**Issue by natew** [ianstormtaylor/slate#744]
Just did a webpack analyze on slate and saw it's 440Kb without immutablejs (another 120Kb).

I know this is unminified, but was definitely a surprise to see such a large size for slate outside of immutable.

Would be good incentive to minimize it by adding it to README.md somewhere visible!

**Comment by ianstormtaylor** [comment]
Hey @natew good point. I haven't done any true work on getting the size down yet, so there's probably low-hanging fruit everywhere. I'd be open to any pull requests that help! I'd also be open to a specific test-case (or system similar to `./benchmark`) that would make it easy to keep track of the true bundle size over time.

For now since Slate is in beta and things change fairly often, I'd rather not have to maintain it in the readme since it's going to get stale fast.

Also, I think comparing "unminified" results are going to be very skewed unless you remove comments first, because Slate is much more commented than the average library—which I find helpful when trying to keep track of all the inconsistencies it deals with, and is generally a reason that other libraries are hard to contribute to in the first place—so that's going to throw off super simple file size checks.

**Comment by conorcussell** [comment]
Would including a simple badge like this be worthwhile? 

![gzip size](http://img.badgesize.io/https://unpkg.com/slate@0.19.20/dist/slate.min.js?compression=gzip&label=gzip%20size)

`![gzip size](http://img.badgesize.io/https://unpkg.com/slate@0.19.20/dist/slate.min.js?compression=gzip&label=gzip%20size)`

**Comment by ianstormtaylor** [comment]
Woah @conorcussel, that's cool! I'm down if you PR it next to the other green badges!

**Comment by conorcussell** [comment]
Done, https://github.com/ianstormtaylor/slate/pull/748
