### ISSUE TITLE
Multiple bugs with tables

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#754]
http://slatejs.org/#/tables

1. Put cursor at the beginning of "Human" cell. Clicking right or left arrow keys doesn't work. (This seems to be the case for all but the empty cell.)
2. Triple click "Human" to select it and start typing. Note that the cells collapsed. Related to https://github.com/ianstormtaylor/slate/issues/752
3. Typing long text into a cell causes the table to become too wide.

**Comment by ianstormtaylor** [comment]
Hey @AlexeiAndreev, actually in this case I this is going to have to stay this way, since the tables example is really just a tiny example to show that table rendering is possible, but not to implement it fully, since doing so requires a lot of work. There's a `slate-edit-table` plugin I believe that tries to implement lots of the behavior you're talking about though!

I'll edit the table example text to make it slightly more clear though!
