### ISSUE TITLE
Toggling mark on a selection that only partly had it then undoing produces wrong results

### ISSUE THREAD

**Issue by mernen** [ianstormtaylor/slate#767]
1. Open the example at http://slatejs.org
2. Select the “editable **rich** text” passage
3. Press the Bold button. The “rich” word loses its bold formatting
4. Press Ctrl/Cmd-Z

Expected: “rich” should get its formatting back, the other words should remain unchanged.

Actual: the entire selection becomes bold.

**Comment by ianstormtaylor** [comment]
This is due to the current implementation of the [`add_mark`](https://github.com/ianstormtaylor/slate/blob/master/src/transforms/operations.js#L22-L41) and [`remove_mark`](https://github.com/ianstormtaylor/slate/blob/master/src/transforms/operations.js#L186-L205) operations. Right now they create an inverse that adds/removes completely. When really they should be creating many operations, for each range that doesn't currently have the mark attached.
