### ISSUE TITLE
"Weird" selection behaviour

### ISSUE THREAD

**Issue by alexeygolev** [ianstormtaylor/slate#780]
I stumbled upon some weird behaviour. The selection is not yet updated when I query it from `componentDidUpdate` in the component containing the Editor (in fact it's not yet updated in the Editor's `componentDidUpdate`. When I query the current window selection in Content's `updateSelection` it's correct but it happens after both `componentDidUpdate`)
It might be that I'm not understanding the `componentDidUpdate` timing though.
[Here](https://jsfiddle.net/2zokvrvt/7/) is a fiddle — open the console to see what I mean.

**Comment by ianstormtaylor** [comment]
Hey @alexeygolev it looks like the fiddle might not have been saved?

**Comment by alexeygolev** [comment]
@ianstormtaylor Sorry,  https://jsfiddle.net/2zokvrvt/95/

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
