### ISSUE TITLE
Backspace after isVoid block

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#781]
In an editor like Medium, when pressing backspace after a void block (image, video, etc), it always move the selection to the void node.

In Slate, it works like this only if the block is empty (see the [images example](http://slatejs.org/#/images)).  
If the paragraph after the void node is not empty, it deletes the void node.

I think we should match the medium behaviour, more natural and common to all use-cases.

**Comment by ianstormtaylor** [comment]
I'm down with that! Sounds much safer. I'd be open to a PR, thanks @SamyPesse!

**Comment by thepian** [comment]
Could the improvement include firing onSelect since the selection is changed?

**Comment by ianstormtaylor** [comment]
After thinking about this more, I think this should be something that's implemented in userland. Otherwise we're adding an edge casing to deleting logic that doesn't delete anything but just moves the selection, which seems like it'll leak upwards. Whereas in userland it's fairly easy to add this behavior for when the selection is collapsed before a void node.
