### ISSUE TITLE
add support for common deletion hotkeys (word-level / line-level)

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#80]
Steps:

1. Open an editor and type some text, and make sure the cursor is at the end of the line.
2. Hit option-delete.
  - Expected behavior: delete previous word.
  - Actual behavior: no effect.
3. Hit command-delete.
  - Expected behavior: delete the line.
  - Actual behavior: deletes only one letter at a time.

However, option-move (arrow keys) do work.

**Comment by ianstormtaylor** [comment]
Good catch. I want to get these working. Right now the reason the current word-level deletions don't work is because of this [temp/non-working code here](https://github.com/ianstormtaylor/slate/blob/master/lib/plugins/core.js#L156-L166) which was just a placeholder.

I was thinking that the `deleteForward` and `deleteBackward` transforms could also support being passed two hotkeys of `'word'` and `'line'` in addition to just a `n: Number`, and that they'd turn them into the proper offset.

**Comment by ianstormtaylor** [comment]
Added in `0.1.10`!

Chose to trigger the logic from the "core" plugin. Right now deleting a "line" clears from the cursor to the start of the block, similar to how Medium and Dropbox Paper do it. Although in the future, since its at the plugin level it could be made smarter to calculate the where the line boundaries are.

**Comment by markbao** [comment]
Thanks! Confirmed to be working. Deleting to the edge of the line is the expected behavior in normal text editors and ContentEditable but it's not really a big issue as you mention. Surprising that both Medium and Dropbox Paper do clear to beginning of block.

**Comment by ianstormtaylor** [comment]
Haha yeah I was surprised they both cheated that way too. I'm definitely +1 to making it properly do line-level deleting in the future though.
