### ISSUE TITLE
How to handle alignment of nodes?

### ISSUE THREAD

**Issue by jatins** [ianstormtaylor/slate#800]
I want to properly align some inline nodes.

For inline nodes, it seems slate renders a bunch of surrounding `span`s in DOM around the actual node component. And For block nodes, it renders surrpunding `div`s.

Due the elements surrounding components, I am not able to properly align elements. 

Here's a fiddle to illustrate the point: https://jsfiddle.net/2zokvrvt/100/

If you type 'h' in the fiddle, it renders the `right` node (pink color bg) node on a new line while I have `display: inline-block` set to the div of corresponding component.

So, how can I achieve proper alignment in such cases?

(asked this on Slack also)

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
