### ISSUE TITLE
Request: getting selection should work even when the editor is not in editable state

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#824]
Right now if you get editor's selection when it's not in editable state, the selection object is not correct. Would it be easy to fix that?

**Comment by AlexeiAndreev** [comment]
Another way to solve this problem would be a function that takes standard JS selection (window.getSelection()) and returns the corresponding slate.Selection object.

**Comment by AlexeiAndreev** [comment]
My workaround is to use 'slate/lib/utils/get-point' directly.

**Comment by ianstormtaylor** [comment]
Hey @AlexeiAndreev I'm not sure what you mean, but if you can include a JSFiddle that shows the behavior that would help a lot. Thanks!

**Comment by AlexeiAndreev** [comment]
Here you go: https://jsfiddle.net/zwomqyx5/
Take a look at the output. Then select a word. Notice that printed selection doesn't change.

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
