### ISSUE TITLE
wrapInline transformation in the beginning of a paragraph doesn't work as expected.

### ISSUE THREAD

**Issue by mtuchkov** [ianstormtaylor/slate#827]
It looks like a bug in updateSelection 

#### What's the current behavior?

Creating inline element in the beginning of the bock resets the selection and if I try to restore it it fails with exception.

If Inline element is inserted in the middle of the block it doesn't reset the selection and does not fail if I try to modify the selection.

[JSFiddle](https://jsfiddle.net/yLancvu9/)

Code that reproduce the error:

```js
state = state.transform()
            .wrapInline(
            {
                type: "link",
                data: {
                    href: hyperlink.href,
                    target: hyperlink.target
                }
            })
            .apply();
```
```
Error:
find-deepest-node.js:15 Uncaught (in promise) TypeError: Cannot read property 'firstChild' of null
    at findDeepestNode (find-deepest-node.js:15)
    at Content.444._initialiseProps.updateSelection (content.js:410)
    at Content.444._initialiseProps.componentDidUpdate (content.js:341)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponent.js:729
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:206)
    at ReactReconcileTransaction.perform (Transaction.js:153)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:140)
```

#### What's the expected behavior?
Selection should remain the same.

**Comment by pavelvolek** [comment]
Having same issue here. Running the following snippet ends up in text being deleted and nothing being inserted.
```
state
  .transform()
  .deleteBackward(textToReplace.length)
  .insertText(newText)
  .extend(0 - newText.length)
  .wrapInline({ type: "myInline" })
```

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
