### ISSUE TITLE
Make it possible for plugins to pass a function to 'schema' to alter it in any desired way

### ISSUE THREAD

**Issue by marschi** [ianstormtaylor/slate#837]
When writing a Plugin you can pass a 'schema' object into it like so 
```
{ schema: { nodes: {'randomnode': ... } } }
```
Wouldn't it be cool if you could also pass a function instead, that returns a new schema?
```
{ schema: (existingSchema) => alterSchema(existingSchema) }
```

**Comment by ianstormtaylor** [comment]
Hey @marschi, thanks for submitting the idea! What use case are you thinking about?

**Comment by marschi** [comment]
Hey @ianstormtaylor, I wanted to create a plugin that enables me to Drag and Drop Nodes around, and when I hover over another node it displays a "Insert here" message. For this case it would be handy to be able to wrap for example a "paragraph" Node inside a Hover Indicator component. To wrap the components I would like to "patch" the existing schema (and not override it as you can imagine)
Of course I could do that when defining my core schema, but It would be cool if one could do stuff like that with a Plugin.
I hope you understand my point

**Comment by ianstormtaylor** [comment]
@marschi ah that makes sense, and is a cool use case. I think it's something that definitely sounds reasonable to support. I'd like to delay for a bit in terms of implementing in the current architecture, because ideally I'd like to figure out how to make https://github.com/ianstormtaylor/slate/issues/835 work which would add support for this out of the box. Thanks for opening this!
