### ISSUE TITLE
Plugin onChange doesn't receive state or editor arguments

### ISSUE THREAD

**Issue by natew** [ianstormtaylor/slate#840]
Wondering why this is and if we can add that to be a little more consistent with the other events.

**Comment by ianstormtaylor** [comment]
Hey @natew can you explain what you mean more and what you'd prefer?

**Comment by natew** [comment]
I may revisit, but I just noticed that onKeydown and other events receive state/editor as arguments. Meanwhile onChange doesn't. For a use case I was looking at this was a bit weird, but I am also refactoring quite a bit at the moment so I'll have to update later if this is still an issue.

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice this is still needed, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
