### ISSUE TITLE
Github Page

### ISSUE THREAD

**Issue by kennetpostigo** [ianstormtaylor/slate#85]
It would be pretty sweet if you could make a github page to show examples of Slate and its plugins aside from just pointing to the code in the examples folder.

**Comment by ianstormtaylor** [comment]
Definitely! I want to do this somewhat soon. I'd like to get a few more things working in core first.

For the page, I was thinking we could have each of the examples listed with a little blurb explaining what they are designed to do. And maybe a "mega" example that combines everything that one would expect from a simple editor, so that people don't have a "it can't do X" reaction.

**Comment by ianstormtaylor** [comment]
Added :) 

I'll work on making it a better introduction to Slate, instead of just examples, later!
