### ISSUE TITLE
Auto-Markdown should support numbers

### ISSUE THREAD

**Issue by markbao** [ianstormtaylor/slate#86]
I was thinking about submitting a PR for this, but looking at the code, it might be best to figure out what the right approach is. An updated `NODES` for `auto-markdown/index.js` might be:

```js
const NODES = {
  'block-quote': props => <blockquote {...props.attributes}>{props.children}</blockquote>,
  'bulleted-list': props => <ul {...props.attributes}>{props.children}</ul>,
  'numbered-list': props => <ol {...props.attributes}>{props.children}</ol>,
  ...
  'list-item': props => <li {...props.attributes}>{props.children}</li>
}
```

and `getType()` to:

```js
  getType = (chars) => {
    switch (chars) {
      case '*':
      case '-':
      case '1.':
      case '+': return 'list-item'
  ...

```

Later on, it determines whether to wrap the element in a `bulleted-list`node if the type matches `list-item`:

```js
    if (type == 'list-item') transform = transform.wrapBlock('bulleted-list')
```

Now, should A) a redundant `list-item` be added to `NODES`, e.g.:

```js
const NODES = {
  ...
  'list-item': props => <li {...props.attributes}>{props.children}</li>,
  'numbered-list-item': props => <li {...props.attributes}>{props.children}</li>
}
```

so we can differentiate after using `getType()` in `onSpace()` e.g.:

```js
    if (type == 'list-item') transform = transform.wrapBlock('bulleted-list')
    if (type == 'numbered-list-item') transform = transform.wrapBlock('numbered-list')
```

or B) should there be a check on the wrap conditional like so:

```js
    if (type == 'list-item') {
      if (chars == '1.') {
        transform = transform.wrapBlock('numbered-list')
      } else {
        transform = transform.wrapBlock('bulleted-list')
      }
    }
```

A) seems cleaner and more DRY to me, but B) avoids the duplicate `number-list-item` HTML – but overall, that seems like less of a design issue than hard-coding in the chars into `onSpace()`.

**Comment by ianstormtaylor** [comment]
Hey, good questions!

It's definitely a question of what you want your structure to be. Slate leaves that kinda of schema-level decision up to you. 

I'd personally choose the `B` method, since it allows for a nesting that mimics what the DOM would be, and so nested lists are easier to reason about.

With `A` if you wanted to nesting you'd need to do some hacky things—associating the "depth" of the list item as an extra data property, instead of implied in the document. (This is how Draft.js does it actually.) However, `B` does have a tradeoff in the other direction, that you have to deal with nesting level logic instead of faking it—just a tradeoff.

That said, the `auto-markdown` example is mainly meant to showcase what's possible, and not to handle all of the markdown cases. I tried to keep it full enough that general Markdown features were shown, but not complex enough that it's hard to read through. 

For actually achieving Markdown parity, that's up to you (depends on how far you want to take it), but... 

Check out the [`slate-auto-replace-block` plugin](https://github.com/ianstormtaylor/slate-auto-replace-block) which can be used for achieving auto-markdown-like behavior. It's already smart enough to handle headers, block quotes, etc. Although to your point, I think it should be extended with an extra `wrap` option, which you could pass it to have it not only set new properties on the block, but also wrap it in a new block as well. (If you'd like to pull request that that would be awesome, otherwise I'll need to implement it soon myself regardless, since I plan on doing this exact same thing!)

Does that all make sense? Happy to clarify anything!

**Comment by markbao** [comment]
Thanks for taking the time to go through all this! Great stuff and I'll also take a look at the plugin for reference.

I was thinking that it might be a good idea to add this change to the repo, but if it's just an example of Markdown-like expansion, there's no need since the current state covers most of the examples. And if anyone needs to add the numbering in the future, they'll likely see this issue :)

If I get around to adding this, I'll go ahead and release it as a plugin forked from the example plugin. Thanks @ianstormtaylor!

**Comment by ianstormtaylor** [comment]
Awesome, sounds good!
