### ISSUE TITLE
Get selected text of first inline node in a block [Bug]

### ISSUE THREAD

**Issue by rholliger** [ianstormtaylor/slate#910]
#### Do you want to request a *feature* or report a *bug*?

A Bug.

#### What's the current behavior?

Hello folks.
I am currently adding a possibility to edit a link and his text, after it was added to the editor.
For this I need to get the text I just selected.

#551 told me, that I can get the selected text with `state.fragment.text`

Now I ran into a problem when selecting a link. The bug only occurs if the link is the first element in a new block and the selection starts from the first character (Shift + Right-Arrow).
Here's a recording of the bug:

![](http://g.recordit.co/BhqvTAMnlN.gif)

I assume that it has something to do with the zero-width character, which is wrapped around an inline node and the splitting of this node and the subsequent node.

![storybook](https://user-images.githubusercontent.com/6562926/27833145-c8360eb4-60d1-11e7-9d81-b1cb53640291.jpg)

Is this a known bug? Is there another way of selecting a text of an inline node?

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
