### ISSUE TITLE
state.marks returns incorrect value

### ISSUE THREAD

**Issue by jatins** [ianstormtaylor/slate#935]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?
I am trying to get `marks` in entire document, but it's returning 0, even though I have applied marks.

Fiddle: https://jsfiddle.net/2zokvrvt/170/

#### What's the expected behavior?
Correct value of marks should be returned.

**Comment by danburzo** [comment]
I might be mistaken, but I get the impressions marks added via decorators are purely for rendering purposes, and are not added as part of the state, and therefore cannot be retrieved via its APIs.

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
