### ISSUE TITLE
Multiline syntax highlighting

### ISSUE THREAD

**Issue by kvolkovich-sc** [ianstormtaylor/slate#945]
I write markdown highligthter for Slate using Prism and have troubles with code block.

This simple regex /(\`)[^]*\1/ matches:

\`\`\`
Code block
\`\`\`

Prism.highlight returns something like:

```
<span class="token codeBlock">Code block</span>
```

But Slate adds styles only for lines with backticks, not for content of code block.

[Whole code](https://github.com/OpusCapita/react-markdown/blob/bd3660d8e83c51defb53048b7eeb1380674f6fce/src/client/components/SlateEditor/plugins/slate-markdown-plugin/MarkdownPreviewSchema.js)

Is there any workarounds for solving it?

**Comment by ianstormtaylor** [comment]
Hey @kvolkovich-sc, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by latviancoder** [comment]
@ianstormtaylor I am struggling with the same problem currently and the slack channel wasn't much of a help unfortunately. Is there some related example so that I at least understand which direction I should move in?
