### ISSUE TITLE
Render html from saved json

### ISSUE THREAD

**Issue by hmontes** [ianstormtaylor/slate#955]
I have this schema.marks (for the rich-text example)

```
marks: {
    bold: {
      fontWeight: 'bold',
      color: '#000'
    },
    code: {
      fontFamily: 'monospace',
      backgroundColor: '#eee',
      padding: '3px',
      borderRadius: '4px'
    },
    italic: {
      fontStyle: 'italic'
    },
    underlined: {
      textDecoration: 'underline'
    }
  },
```

But, in your docs . The serialize (for save html) is:

```
 serialize(object, children) {
      if (object.kind != 'mark') return
      switch (object.type) {
        case 'bold': return <strong>{children}</strong>
        case 'italic': return <em>{children}</em>
        case 'underline': return <u>{children}</u>
      }
    }
```

How can i adapt the serialize to my (and docs/examples) mark?

Thanks

**Comment by hmontes** [comment]
Edited question (I changed the focus)

**Comment by talkingtab** [comment]
Is there a typo? 
`object.kind!='mark'`
and plural:
`marks: {}`

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by RobertDaleSmith** [comment]
Where can I find the Slack channel?

**Comment by ianstormtaylor** [comment]
@RobertDaleSmith https://slate-slack.herokuapp.com/
