### ISSUE TITLE
Questions about a blog

### ISSUE THREAD

**Issue by hmontes** [ianstormtaylor/slate#956]
Hi. I have some questions about Slate. I'm doing a Blog for learning purposes.

So. The Blog will have:

1. The Cards (https://semantic-ui.com/views/card.html ) in the index for show a picture, show the title an a little of the content for the post.

2. The Blog Post. The post

3. The comment system

So. For any stage.

1. I want to save the data generated in blog/post/create into json on the db, later show a few words (concate) for the content. I can do that with Plain. Covered.

2. I want to pass the json to HTML (When i try to do this i receive this error: TypeError: Cannot read property 'kind' of undefined) for inject the content in a div. NOT IN THE EDITOR !!!!!! (Because the post is created in another page with a custom div). How can i do that?

3. Then, i want to generate comments like github. When the owner of the comment click on "edit" the Editor activates and the user can modify the text. So, It's possible to render a multiple Editor instances for that?

Maybe i don't understand the approach of this package. Not all the blogs are like Medium. I only want to make a normal blog but i have a lot of issues with that. What is wrong? What is the best approach for this?

Thank you

**Comment by ianstormtaylor** [comment]
Hey @hmontes, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Comment by hmontes** [comment]
And I cannot pass from json to html outside the editor and that is an issue
